### ISSUE TITLE
ChatControl Pro error console.

### ISSUE THREAD

**Issue by andris155** [kangarko/ChatControl-Pro#1]
```
[17:06:58] [Server thread/INFO]: Marko3009 issued server command: /auc start 192 3000 500
[17:06:58] [Server thread/ERROR]: Could not pass event PlayerCommandPreprocessEvent to ChatControl v6.8.1
org.bukkit.event.EventException
	at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:46) ~[patched_1.9.jar:git-Paper-531]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.9.jar:git-Paper-531]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.9.jar:git-Paper-531]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [patched_1.9.jar:git-Paper-531]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [patched_1.9.jar:git-Paper-531]
	at net.minecraft.server.v1_9_R1.PlayerConnection.handleCommand(PlayerConnection.java:1373) [patched_1.9.jar:git-Paper-531]
	at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1193) [patched_1.9.jar:git-Paper-531]
	at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [patched_1.9.jar:git-Paper-531]
	at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) [patched_1.9.jar:git-Paper-531]
	at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [patched_1.9.jar:git-Paper-531]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_51]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_51]
	at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [patched_1.9.jar:git-Paper-531]
	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:775) [patched_1.9.jar:git-Paper-531]
	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:404) [patched_1.9.jar:git-Paper-531]
	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:714) [patched_1.9.jar:git-Paper-531]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:613) [patched_1.9.jar:git-Paper-531]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_51]
Caused by: me.kangarko.chatcontrol.cOM2
	at me.kangarko.chatcontrol.Com3.charAt(SourceFile:656) ~[?:?]
	at java.util.regex.Pattern$BmpCharProperty.match(Unknown Source) ~[?:1.8.0_51]
	at java.util.regex.Pattern$Branch.match(Unknown Source) ~[?:1.8.0_51]
	at java.util.regex.Pattern$Start.match(Unknown Source) ~[?:1.8.0_51]
	at java.util.regex.Matcher.search(Unknown Source) ~[?:1.8.0_51]
	at java.util.regex.Matcher.find(Unknown Source) ~[?:1.8.0_51]
	at java.util.regex.Matcher.replaceAll(Unknown Source) ~[?:1.8.0_51]
	at me.kangarko.chatcontrol.COM1.const(SourceFile:271) ~[?:?]
	at me.kangarko.chatcontrol.com1.const(SourceFile:271) ~[?:?]
	at me.kangarko.chatcontrol.com1.const(SourceFile:236) ~[?:?]
	at me.kangarko.chatcontrol.nuL.onPlayerCommand(SourceFile:211) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor117.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44) ~[patched_1.9.jar:git-Paper-531]
	... 17 more
```

**Comment by EvilOlaf** [comment]
Did you use the spigot patcher for plugins? If so, why? Chc is 1.9 compatible.

**Comment by EvilOlaf** [comment]
BTW your java installation is outdated

**Comment by andris155** [comment]
I use Paper 1.9 (build 531).

**Comment by andris155** [comment]
I don't have SSH permission. :/

**Comment by kangarko** [comment]
Is the error present on 6.8.2?

**Comment by andris155** [comment]
I don't tested 6.8.2.

**Comment by kangarko** [comment]
@andris155 does the error still occur on latest version?

**Comment by andris155** [comment]
No
