### ISSUE TITLE
Logon Error

### ISSUE THREAD

**Issue by TeeKay1** [kangarko/ChatControl-Pro#102]
Everytime some someone logs on. Im not sure what exactly what it means of why its doing this. Please Help.

[02:06:04 ERROR]: Could not pass event PlayerLoginEvent to ChatControl v7.0.11
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.10.jar:git-Spigot-c3e4052-1953f52]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.10.jar:git-Spigot-c3e4052-1953f52]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.10.jar:git-Spigot-c3e4052-1953f52]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.10.jar:git-Spigot-c3e4052-1953f52]
        at net.minecraft.server.v1_10_R1.PlayerList.attemptLogin(PlayerList.java:505) [spigot-1.10.jar:git-Spigot-c3e4052-1953f52]
        at net.minecraft.server.v1_10_R1.LoginListener.b(LoginListener.java:118) [spigot-1.10.jar:git-Spigot-c3e4052-1953f52]
        at net.minecraft.server.v1_10_R1.LoginListener.E_(LoginListener.java:54) [spigot-1.10.jar:git-Spigot-c3e4052-1953f52]
        at net.minecraft.server.v1_10_R1.NetworkManager.a(NetworkManager.java:233) [spigot-1.10.jar:git-Spigot-c3e4052-1953f52]
        at net.minecraft.server.v1_10_R1.ServerConnection.c(ServerConnection.java:140) [spigot-1.10.jar:git-Spigot-c3e4052-1953f52]
        at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:832) [spigot-1.10.jar:git-Spigot-c3e4052-1953f52]
        at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.10.jar:git-Spigot-c3e4052-1953f52]
        at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:672) [spigot-1.10.jar:git-Spigot-c3e4052-1953f52]
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:571) [spigot-1.10.jar:git-Spigot-c3e4052-1953f52]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]
Caused by: java.lang.NullPointerException: Cannot put TK1 to channel 'standard' on join as it doesn't exist!
        at java.util.Objects.requireNonNull(Unknown Source) ~[?:1.8.0_101]
        at me.kangarko.chatcontrol.Aux.native(SourceFile:97) ~[?:?]
        at me.kangarko.chatcontrol.Aux.const(SourceFile:60) ~[?:?]
        at me.kangarko.chatcontrol.ChatControl.const(SourceFile:372) ~[?:?]
        at nul.final...\\....if.com9.onPreLogin(SourceFile:50) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_101]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_101]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.10.jar:git-Spigot-c3e4052-1953f52]
        ... 13 more

**Comment by EvilOlaf** [comment]
Cannot put TK1 to channel 'standard' on join as it doesn't exist!


Check your config.

**Comment by kangarko** [comment]
If channels are enabled, by default the player will be put in the channel named 'standard'. If you removed it from chat.yml, an error will appear. Edit your settings.yml or create that channel.
