### ISSUE TITLE
SQLException: Before start of result set

### ISSUE THREAD

**Issue by mibby** [kangarko/ChatControl-Pro#1034]
ChatControlPro v7.11.3

```
[05:41:08] [Craft Scheduler Thread - 17/INFO]: [ChatControl] *-----------------------------------------------*
[05:41:08] [Craft Scheduler Thread - 17/INFO]: [ChatControl]  Failed to load Channels from MySQL
[05:41:08] [Craft Scheduler Thread - 17/INFO]: [ChatControl] *-----------------------------------------------*
[05:41:08] [Craft Scheduler Thread - 17/INFO]: [ChatControl] ChatControl 7.11.3 encountered a SQLException! Please check your error.log and report this issue with the information in that file.
[05:41:08] [Craft Scheduler Thread - 17/WARN]: java.sql.SQLException: Before start of result set
[05:41:08] [Craft Scheduler Thread - 17/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
[05:41:08] [Craft Scheduler Thread - 17/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
[05:41:08] [Craft Scheduler Thread - 17/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
[05:41:08] [Craft Scheduler Thread - 17/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
[05:41:08] [Craft Scheduler Thread - 17/WARN]: 	at com.mysql.jdbc.ResultSetImpl.checkRowPos(ResultSetImpl.java:790)
[05:41:08] [Craft Scheduler Thread - 17/WARN]: 	at com.mysql.jdbc.ResultSetImpl.getStringInternal(ResultSetImpl.java:5213)
[05:41:08] [Craft Scheduler Thread - 17/WARN]: 	at com.mysql.jdbc.ResultSetImpl.getString(ResultSetImpl.java:5136)
[05:41:08] [Craft Scheduler Thread - 17/WARN]: 	at com.mysql.jdbc.ResultSetImpl.getString(ResultSetImpl.java:5175)
[05:41:08] [Craft Scheduler Thread - 17/WARN]: 	at me.kangarko.chatcontrol.final. .bn.const(SourceFile:156)
[05:41:08] [Craft Scheduler Thread - 17/WARN]: 	at me.kangarko.chatcontrol.final. .bn.const(SourceFile:113)
[05:41:08] [Craft Scheduler Thread - 17/WARN]: 	at me.kangarko.chatcontrol.final. .bn.const(SourceFile:78)
[05:41:08] [Craft Scheduler Thread - 17/WARN]: 	at me.kangarko.chatcontrol.final. .bd.const(SourceFile:131)
[05:41:08] [Craft Scheduler Thread - 17/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:82)
[05:41:08] [Craft Scheduler Thread - 17/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[05:41:08] [Craft Scheduler Thread - 17/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[05:41:08] [Craft Scheduler Thread - 17/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[05:41:08] [Craft Scheduler Thread - 17/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[05:41:08] [Craft Scheduler Thread - 17/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by kangarko** [comment]
@jascotty2

**Comment by kangarko** [comment]
Should have been solved some updates ago. Comment below if still having issues.
