### ISSUE TITLE
Issue: Error in Console

### ISSUE THREAD

**Issue by farisjaclyn** [kangarko/ChatControl-Pro#1041]
**I updated to 7.11.3 last night and now I'm having an error message.**

[21:01:28] [ChatControl] Task #28 for ChatControl v7.11.3 generated an exception

[21:01:28] java.lang.NullPointerException: null

[21:01:28] at me.kangarko.chatcontrol.final. .bo$1.const(SourceFile:316) ~[?:?]

[21:01:28] at java.util.ArrayList.forEach(ArrayList.java:1249) ~[?:1.8.0_131]

[21:01:28] at me.kangarko.chatcontrol.final. .bo$1.run(SourceFile:315) ~[?:?]

[21:01:28] at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:82) ~[patched_1.13.2.jar:git-Paper-473]

[21:01:28] at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:448) ~[patched_1.13.2.jar:git-Paper-473]

[21:01:28] at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1008) ~[patched_1.13.2.jar:git-Paper-473]

[21:01:28] at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-473]

[21:01:28] at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943) ~[patched_1.13.2.jar:git-Paper-473]

[21:01:28] at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841) ~[patched_1.13.2.jar:git-Paper-473]

[21:01:28] at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]

**Comment by jascotty2** [comment]
Having some trouble working this one out - does the issue persist after stopping and starting the server again?

If this is still happening, could you zip your ChatControl folder in plugins and send it to me?
(You can send privately if you prefer here: https://www.spigotmc.org/members/jascotty2.3571/ )
