### ISSUE TITLE
Reloading ChatControl Error

### ISSUE THREAD

**Issue by PerkusMaximus** [kangarko/ChatControl-Pro#1066]
```
------------------------------------[ 23.01.2019 19:53:31 ]-----------------------------------
ChatControl 7.11.8 encountered a NullPointerException
Running CraftBukkit 1.13.2-R0.1-SNAPSHOT and Java 1.8.0_202
Plugins: LuckPerms v4.3.80, Vault v1.7.1-b91, PlaceholderAPI v2.9.2, ProtocolLib v4.4.0, ChatControl v7.11.8
----------------------------------------------------------------------------------------------

More Information: 
Error reloading ChatControl 7.11.8
NullPointerException (Unknown cause)
	 at me.kangarko.chatcontrol.final. .coM4.native(SourceFile:110)
	 at me.kangarko.chatcontrol.final. .com3.throw(SourceFile:533)
	 at me.kangarko.chatcontrol.final. .com3.abstract(SourceFile:499)
	 at me.kangarko.chatcontrol.final. .throw.const(SourceFile:558)
	 at me.kangarko.chatcontrol.final. .COM3.onCommand(SourceFile:61)
	 at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
	 at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:139)
	 at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:702)
	 at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchServerCommand(CraftServer.java:687)
----------------------------------------------------------------------------------------------
```

**Comment by x1p** [comment]
Confirmed. Can't find the source. At least there is nothing wrong with my rules.

**Comment by kangarko** [comment]
Will be fixed.
