### ISSUE TITLE
{simpleclans_in_clan} - PlaceholderAPI failed to replace variables!

### ISSUE THREAD

**Issue by FrozenBeard** [kangarko/ChatControl-Pro#1088]
Im trying to use the variable {simpleclans_in_clan}  but its erroring out `PlaceholderAPI failed to replace variables!` in the error.log, im checking if a user is in a clan to show them a different MOTD when they log in, There is both a {simpleclans_in_clan} built into Chatcontrol pro and there is a PlaceholderAPI which I am also using.
```
More Information: 
PlaceholderAPI failed to replace variables!
Player: CaptainKladian
Message: "{simpleclans_in_clan}" == "yes"
Error: %error
NullPointerException (Unknown cause)
	 at net.sacredlabyrinth.phaed.simpleclans.managers.ClanManager.getClanPlayer(ClanManager.java:230)
	 at net.sacredlabyrinth.phaed.simpleclans.managers.ClanManager.getClanPlayer(ClanManager.java:245)
	 at me.kangarko.chatcontrol.final. .cOM7.onPlaceholderRequest(SourceFile:1313)
	 at me.clip.placeholderapi.PlaceholderHook.onRequest(PlaceholderHook.java:40)
	 at me.kangarko.chatcontrol.final. .NuL.const(SourceFile:1224)
	 at me.kangarko.chatcontrol.final. .NuL.const(SourceFile:1192)
	 at me.kangarko.chatcontrol.final. .com9.native(SourceFile:530)
	 at me.kangarko.chatcontrol.final. .LpT6.const(SourceFile:187)
	 at me.kangarko.chatcontrol.final. .coM4.const(SourceFile:130)
	 at me.kangarko.chatcontrol.final. .coM4.const(SourceFile:126)
	 at me.kangarko.chatcontrol.final. .coM4.const(SourceFile:119)
	 at me.kangarko.chatcontrol.final. .bm.const(SourceFile:67)
	 at me.kangarko.chatcontrol.final. .bm.const(SourceFile:41)
	 at me.kangarko.chatcontrol.final. .bl.const(SourceFile:136)
	 at me.kangarko.chatcontrol.final. .bl.const(SourceFile:124)
	 at me.kangarko.chatcontrol.final. .bI.const(SourceFile:363)
	 at me.kangarko.chatcontrol.final. .bd.native(SourceFile:174)
	 at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:63)
	 at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423)
----------------------------------------------------------------------------------------------
```

**Comment by kangarko** [comment]
I am sorry, but this is a problem with "ClanManager" in SimpleClans. Contact the dev of SimpleClans instead.
