### ISSUE TITLE
Could not pass event AsyncPlayerChatEvent to ChatControl v7.11.16

### ISSUE THREAD

**Issue by x1p** [kangarko/ChatControl-Pro#1107]
Saw this error appear out of nowhere. No action was performed on that exact time, not right behind it. Cause unknown.
```
[11:41:36] [Async Chat Thread - #10/ERROR]: Could not pass event AsyncPlayerChatEvent to ChatControl v7.11.16
java.util.NoSuchElementException: null
	at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:721) ~[?:1.8.0_181]
	at java.util.LinkedHashMap$LinkedEntryIterator.next(LinkedHashMap.java:752) ~[?:1.8.0_181]
	at java.util.LinkedHashMap$LinkedEntryIterator.next(LinkedHashMap.java:750) ~[?:1.8.0_181]
	at me.kangarko.chatcontrol.final. .bU$transient$protected.const(SourceFile:384) ~[?:?]
	at me.kangarko.chatcontrol.final. .bU$transient$short.next(SourceFile:395) ~[?:?]
	at me.kangarko.chatcontrol.protected.getLastParrotMessage(SourceFile:62) ~[?:?]
	at me.kangarko.chatcontrol.final. .aZ.const(SourceFile:176) ~[?:?]
	at me.kangarko.chatcontrol.final. .aZ.const(SourceFile:57) ~[?:?]
	at me.kangarko.chatcontrol.final. .aZ.const(SourceFile:39) ~[?:?]
	at me.kangarko.chatcontrol.final. .lpt7.execute(SourceFile:26) ~[?:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[patched_1.13.2.jar:git-Paper-524]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.13.2.jar:git-Paper-524]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.13.2.jar:git-Paper-524]
	at net.minecraft.server.v1_13_R2.PlayerConnection.chat(PlayerConnection.java:1710) ~[patched_1.13.2.jar:git-Paper-524]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1625) ~[patched_1.13.2.jar:git-Paper-524]
	at net.minecraft.server.v1_13_R2.PacketPlayInChat$1.run(PacketPlayInChat.java:39) ~[patched_1.13.2.jar:git-Paper-524]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_181]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_181]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
```

**Comment by EmanuelSimard** [comment]
Is this a Towny server?

**Comment by x1p** [comment]
Close. It's a rare error on a creative server with plotsquared.

**Comment by kangarko** [comment]
Fixed anyways, thanks
