### ISSUE TITLE
chatcontrol crashes on load

### ISSUE THREAD

**Issue by mrcoffee1026** [kangarko/ChatControl-Pro#1116]
```
[13:45:02] [Server thread/INFO]: Rules loads now..
[13:45:02] [Server thread/INFO]: 42 global, 8 chat, 4 command, 2 packet and 1 book rule(s) found
[13:45:02] [Server thread/INFO]:  
[13:45:02] [Server thread/INFO]: Listening starts..
[13:45:02] [Server thread/INFO]: Rules & antispam listening at normal priority.
[13:45:02] [Server thread/INFO]: java.lang.NoSuchFieldError: BOOK_EDIT
[13:45:02] [Server thread/INFO]: 	at me.kangarko.chatcontrol.final. .prN.const(SourceFile:78)
[13:45:02] [Server thread/INFO]: 	at me.kangarko.chatcontrol.ChatControl.switch(SourceFile:259)
[13:45:02] [Server thread/INFO]: 	at me.kangarko.chatcontrol.ChatControl.native(SourceFile:180)
[13:45:02] [Server thread/INFO]: 	at me.kangarko.chatcontrol.final. .cOm8.super(SourceFile:341)
[13:45:02] [Server thread/INFO]: 	at me.kangarko.chatcontrol.final. .cOm8.a(SourceFile:330)
[13:45:02] [Server thread/INFO]: 	at me.kangarko.chatcontrol.final. .COm8.const(SourceFile:77)
[13:45:02] [Server thread/INFO]: 	at me.kangarko.chatcontrol.final. .COm8.const(SourceFile:73)
[13:45:02] [Server thread/INFO]: 	at me.kangarko.chatcontrol.final. .con$protected.const(SourceFile:118)
[13:45:02] [Server thread/INFO]: 	at me.kangarko.chatcontrol.final. .con.private(SourceFile:56)
[13:45:02] [Server thread/INFO]: 	at me.kangarko.chatcontrol.final. .con.native(SourceFile:52)
[13:45:02] [Server thread/INFO]: 	at me.kangarko.chatcontrol.final. .cOm8.onEnable(SourceFile:238)
[13:45:02] [Server thread/INFO]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[13:45:02] [Server thread/INFO]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
[13:45:02] [Server thread/INFO]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403)
[13:45:02] [Server thread/INFO]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381)
[13:45:02] [Server thread/INFO]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330)
[13:45:02] [Server thread/INFO]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422)
[13:45:02] [Server thread/INFO]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383)
[13:45:02] [Server thread/INFO]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338)
[13:45:02] [Server thread/INFO]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272)
[13:45:02] [Server thread/INFO]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545)
[13:45:02] [Server thread/INFO]: 	at java.base/java.lang.Thread.run(Thread.java:844)
[13:45:02] [Server thread/INFO]:   _   _                       _ 
[13:45:02] [Server thread/INFO]:   | | | | ___   ___  _ __  ___| |
[13:45:02] [Server thread/INFO]:   | |_| |/ _ \ / _ \| '_ \/ __| |
[13:45:02] [Server thread/INFO]:   |  _  | (_) | (_) | |_) \__ \_|
[13:45:02] [Server thread/INFO]:   |_| |_|\___/ \___/| .__/|___(_)
[13:45:02] [Server thread/INFO]:                     |_|          
[13:45:02] [Server thread/INFO]: !-----------------------------------------------------!
[13:45:02] [Server thread/INFO]:  Error loading ChatControl v7.13.3, plugin is disabled!
[13:45:02] [Server thread/INFO]:  Running on 1.12.2-R0.1-SNAPSHOT (v1_12_R1) & Java 10.0.2
[13:45:02] [Server thread/INFO]: !-----------------------------------------------------!
[13:45:02] [Server thread/INFO]:  Error: BOOK_EDIT
[13:45:02] [Server thread/INFO]: !-----------------------------------------------------!
[13:45:02] [Server thread/INFO]: [ChatControl] Disabling ChatControl v7.13.3
[13:45:02] [Server thread/INFO]: Saving player data to MySQL..

```

something in regards to the  book thing

**Comment by GeertBraakman** [comment]
I have the same error

**Comment by kangarko** [comment]
Thanks will be fixed.

For those of you who are on 1.13.2, make sure to have the latest dev build of ProtocolLib from http://ci.dmulloy2.net/job/ProtocolLib/
