### ISSUE TITLE
BungeeControlBridge ServerSwitchEvent error

### ISSUE THREAD

**Issue by andris155** [kangarko/ChatControl-Pro#1121]
```
[23:21:26] [Netty Worker IO Thread #0/WARN]: Error dispatching event ServerSwitchEvent(player=Dealer74) to listener me.kangarko.chatbungee.SwitchListener@2bc9a775
java.lang.NullPointerException: null
	at me.kangarko.chatbungee.SwitchListener.onConnect(SwitchListener.java:55) ~[?:?]
	at jdk.internal.reflect.GeneratedMethodAccessor23.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19) ~[waterfall-A.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d841657:261]
	at net.md_5.bungee.event.EventBus.post(EventBus.java:46) ~[waterfall-A.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d841657:261]
	at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:432) ~[waterfall-A.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d841657:261]
	at net.md_5.bungee.ServerConnector.handle(ServerConnector.java:336) ~[waterfall-A.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d841657:261]
	at net.md_5.bungee.protocol.packet.Login.handle(Login.java:72) ~[waterfall-A.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d841657:261]
	at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:104) ~[waterfall-A.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d841657:261]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[waterfall-A.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d841657:261]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[waterfall-A.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d841657:261]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[waterfall-A.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d841657:261]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) ~[waterfall-A.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d841657:261]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[waterfall-A.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d841657:261]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[waterfall-A.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d841657:261]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[waterfall-A.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d841657:261]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323) ~[waterfall-A.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d841657:261]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) ~[waterfall-A.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d841657:261]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:426) ~[waterfall-A.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d841657:261]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278) ~[waterfall-A.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d841657:261]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[waterfall-A.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d841657:261]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[waterfall-A.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d841657:261]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[waterfall-A.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d841657:261]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[waterfall-A.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d841657:261]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[waterfall-A.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d841657:261]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[waterfall-A.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d841657:261]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[waterfall-A.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d841657:261]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) ~[waterfall-A.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d841657:261]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[waterfall-A.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d841657:261]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[waterfall-A.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d841657:261]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) ~[waterfall-A.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d841657:261]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:799) ~[waterfall-A.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d841657:261]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:433) ~[waterfall-A.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d841657:261]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:330) ~[waterfall-A.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d841657:261]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:909) ~[waterfall-A.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d841657:261]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by kangarko** [comment]
Thanks, I will fix this
