### ISSUE TITLE
Chat Issue I think..?

### ISSUE THREAD

**Issue by BrettplayMC** [kangarko/ChatControl-Pro#1123]
Currently have a user trying to make a forceop book but that is besides the point.  I believe whenever they try to sign the book,  ChatControl errors and gives this:
`[22:20:57 ERROR]: Could not pass event PlayerEditBookEvent to ChatControl v7.13.7
org.bukkit.event.EventException
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[patched.jar:git-PaperSpigot-"4c7641d"]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched.jar:git-PaperSpigot-"4c7641d"]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched.jar:git-PaperSpigot-"4c7641d"]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [patched.jar:git-PaperSpigot-"4c7641d"]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [patched.jar:git-PaperSpigot-"4c7641d"]
at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.handleEditBookEvent(CraftEventFactory.java:860) [patched.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:2032) [patched.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.PacketPlayInCustomPayload.a(SourceFile:55) [patched.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.PacketPlayInCustomPayload.a(SourceFile:8) [patched.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [patched.jar:git-PaperSpigot-"4c7641d"]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_192]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_192]
at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [patched.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774) [patched.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [patched.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [patched.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [patched.jar:git-PaperSpigot-"4c7641d"]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_192]
Caused by: java.lang.NullPointerException: at index 42
at com.google.common.collect.ObjectArrays.checkElementNotNull(ObjectArrays.java:240) ~[patched.jar:git-PaperSpigot-"4c7641d"]
at com.google.common.collect.ObjectArrays.checkElementsNotNull(ObjectArrays.java:231) ~[patched.jar:git-PaperSpigot-"4c7641d"]
at com.google.common.collect.ObjectArrays.checkElementsNotNull(ObjectArrays.java:226) ~[patched.jar:git-PaperSpigot-"4c7641d"]
at com.google.common.collect.ImmutableList.construct(ImmutableList.java:303) ~[patched.jar:git-PaperSpigot-"4c7641d"]
at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:258) ~[patched.jar:git-PaperSpigot-"4c7641d"]
at org.bukkit.craftbukkit.v1_8_R3.inventory.CraftMetaBook.getPages(CraftMetaBook.java:243) ~[patched.jar:git-PaperSpigot-"4c7641d"]
at me.kangarko.chatcontrol.final. .aZ.onBookEdit(SourceFile:80) ~[ChatControl-7.13.7.jar:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_192]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_192]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_192]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_192]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[patched.jar:git-PaperSpigot-"4c7641d"]
... 17 more`
Hmm.
ChatControl: 7.13.7
Spigot: Paper 1.8.8

**Comment by kangarko** [comment]
Thanks, fixed
