### ISSUE TITLE
[ ERROR ] coM5 Report / ScriptEngine not found.

### ISSUE THREAD

**Issue by Linuxy-Lin** [kangarko/ChatControl-Pro#1133]
I am having a issue with ChatControl-Pro.

So far `/chc` and `/ch` is not working as commands.

Its giving me a error in the `error.log` file in the `plugins/chatcontorl` folder

```
------------------------------------[ 27.03.2019 08:01:16 ]-----------------------------------
ChatControl 7.14.1 encountered a coM5
Running Paper 1.13.2-R0.1-SNAPSHOT and Java 1.8.0_202
Plugins: CratesPlus v4.5.1, CoreProtect v2.16.3, LuckPerms v4.3.73, AntiBotDeluxe v9.3.2, BuildersUtilities v1.2.9, PlaceholderAPI v2.9.2, Shortify v1.7, ColorConsole v2.3.3, Votifier v2.5.0, EasyBackup v2.8.1, ProtocolLib v4.4.0, The Multiverse-Core Plugin, YoMama v4.2, Spartan vBuild 230, SkinsRestorer v13.6.1, MVdWPlaceholderAPI v2.5.1, FastAsyncWorldEdit v1.0, iDisguise v5.8.2, React v6.61, AlwaysOnline v6.1, Realistic_World v4.0.18, StaffChat v1.3.0, Vault v1.7.1-b91, ServerListPlus v3.4.8, Essentials v2.16.1.80, AnimatedNames v7.1.0, UltimateTimber v1.0.14, Parties v2.5.2, ChatControl v7.14.1, PerWorldInventory v2.2.2, LiteBans v2.3.15, EssentialsSpawn v2.16.1.80, WorldEdit vunspecified, WorldEditSelectionVisualizer v1.6.4, CrazyEnchantments v1.7.9.3.8, FastAsyncVoxelSniper v1.13.137, RedProtect v7.5.6, WorldGuard v7.0.0-SNAPSHOT;0dc5781, GadgetsMenu v4.3.9, uSkyBlock v2.7.6-RC3
----------------------------------------------------------------------------------------------

More Information: 
ScriptEngine not found. Detected: 
coM5 Report / ScriptEngine not found. Detected: 
	 at me.kangarko.chatcontrol.final. .LPt2.const(SourceFile:23)
	 at me.kangarko.chatcontrol.final. .COm8.<clinit>(SourceFile:32)
	 at me.kangarko.chatcontrol.final. .con$protected.const(SourceFile:118)
	 at me.kangarko.chatcontrol.final. .con.private(SourceFile:56)
	 at me.kangarko.chatcontrol.final. .con.native(SourceFile:52)
	 at me.kangarko.chatcontrol.final. .lpt6.onEnable(SourceFile:237)
	 at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265)
	 at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:334)
	 at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412)
	 at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:443)
	 at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:357)
----------------------------------------------------------------------------------------------

```

I don't believe any other plugin could interfere with the problem.

Any help is appreciated.

**Comment by kangarko** [comment]
Hey, no, no other plugin can interfere.

Seems your Java distribution does not contain the required library. 99% servers use this JDK https://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html by Oracle. If you use other distros such as OpenJDK this may be the case. At this time these are not supported as they lack these required libraries.

I recommend you consult with your hosting. Worst case I can send you a refund.

**Comment by kangarko** [comment]
Closing due to inactivity, comment below if you still need help
