### ISSUE TITLE
Huge HTTP spam

### ISSUE THREAD

**Issue by snimka** [kangarko/ChatControl-Pro#1153]
01:23:04 WARN]: java.net.NoRouteToHostException: No route to host (Host unreachable)
[01:23:04 WARN]: at java.net.PlainSocketImpl.socketConnect(Native Method)
[01:23:04 WARN]: at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
[01:23:04 WARN]: at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
[01:23:04 WARN]: at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
[01:23:04 WARN]: at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
[01:23:04 WARN]: at java.net.Socket.connect(Socket.java:589)
[01:23:04 WARN]: at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
[01:23:04 WARN]: at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
[01:23:04 WARN]: at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
[01:23:04 WARN]: at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
[01:23:04 WARN]: at sun.net.www.http.HttpClient.New(HttpClient.java:339)
[01:23:04 WARN]: at sun.net.www.http.HttpClient.New(HttpClient.java:357)
[01:23:04 WARN]: at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1220)
[01:23:04 WARN]: at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
[01:23:04 WARN]: at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
[01:23:04 WARN]: at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:984)
[01:23:04 WARN]: at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)
[01:23:04 WARN]: at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
[01:23:04 WARN]: at kangarko.chatcontrol.utils.GeoAPI.track(GeoAPI.java:35)
[01:23:04 WARN]: at kangarko.chatcontrol.ChatControl.getGeoFor(ChatControl.java:318)
[01:23:04 WARN]: at kangarko.chatcontrol.listener.PlayerListener.onPreLogin(PlayerListener.java:30)
[01:23:04 WARN]: at sun.reflect.GeneratedMethodAccessor41.invoke(Unknown Source)
[01:23:04 WARN]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[01:23:04 WARN]: at java.lang.reflect.Method.invoke(Method.java:498)
[01:23:04 WARN]: at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300)
[01:23:04 WARN]: at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74)
[01:23:04 WARN]: at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[01:23:04 WARN]: at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:505)
[01:23:04 WARN]: at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485)
[01:23:04 WARN]: at net.minecraft.server.v1_8_R3.LoginListener$LoginHandler.fireEvents(LoginListener.java:254)
[01:23:04 WARN]: at net.minecraft.server.v1_8_R3.LoginListener$3.run(LoginListener.java:214)

**Comment by kangarko** [comment]
Wrong issue channel, this is for the free version.

Still, I fixed that.
