### ISSUE TITLE
Question - First join message

### ISSUE THREAD

**Issue by Kbryst** [kangarko/ChatControl-Pro#1160]
Is there a way to do a cross bungee broadcast when someone joins the lobby for the first time?

Having a hard time finding if there's a way to do it.

**Comment by kangarko** [comment]
Hey,

sure, we have a feature for that however the key is not present in Join Messages to demonstrate this possibility. I added it as a default example, see staff_message at https://pastebin.com/VXu49mJt

**Comment by Kbryst** [comment]
I'm actually having an issue with it. I followed the example, and it is enabled in the settings.yml

`[09:31:58] [Server thread/INFO]: *-----------------------------------------------*
[09:31:58] [Server thread/INFO]:  Error loading configuration in messages.yml!
[09:31:58] [Server thread/INFO]:  Problematic section: Join_Message
[09:31:58] [Server thread/INFO]:  Problem: java.lang.NullPointerException: Invalid condition option: Bungee_Message
[09:31:58] [Server thread/INFO]:  Plugin is now disabled.
[09:31:58] [Server thread/INFO]: *-----------------------------------------------*
[09:31:58] [Server thread/INFO]: [ChatControl] Disabling ChatControl v8.0.8
[09:31:58] [Server thread/INFO]: java.lang.NullPointerException: Invalid condition option: Bungee_Message
[09:31:58] [Server thread/INFO]: 	at org.mineacademy.chatcontrol.final. .bx.const(SourceFile:359)
[09:31:58] [Server thread/INFO]: 	at org.mineacademy.chatcontrol.final. .bx.const(SourceFile:318)
[09:31:58] [Server thread/INFO]: 	at org.mineacademy.chatcontrol.final. .bx.super(SourceFile:252)
[09:31:58] [Server thread/INFO]: 	at org.mineacademy.chatcontrol.final. .bx.init(SourceFile:101)
[09:31:58] [Server thread/INFO]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[09:31:58] [Server thread/INFO]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[09:31:58] [Server thread/INFO]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[09:31:58] [Server thread/INFO]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[09:31:58] [Server thread/INFO]: 	at org.mineacademy.chatcontrol.final. .E.const(SourceFile:135)
[09:31:58] [Server thread/INFO]: 	at org.mineacademy.chatcontrol.final. .E.strictfp(SourceFile:98)
[09:31:58] [Server thread/INFO]: 	at org.mineacademy.chatcontrol.final. .E$1.const(SourceFile:37)
[09:31:58] [Server thread/INFO]: 	at org.mineacademy.chatcontrol.final. .D.native(SourceFile:129)
[09:31:58] [Server thread/INFO]: 	at org.mineacademy.chatcontrol.final. .E.native(SourceFile:166)
[09:31:58] [Server thread/INFO]: 	at org.mineacademy.chatcontrol.final. .bx.native(SourceFile:73)
[09:31:58] [Server thread/INFO]: 	at org.mineacademy.chatcontrol.final. .E.const(SourceFile:63)
[09:31:58] [Server thread/INFO]: 	at org.mineacademy.chatcontrol.final. .f.onEnable(SourceFile:226)
[09:31:58] [Server thread/INFO]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[09:31:58] [Server thread/INFO]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316)
[09:31:58] [Server thread/INFO]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[09:31:58] [Server thread/INFO]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395)
[09:31:58] [Server thread/INFO]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344)
[09:31:58] [Server thread/INFO]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442)
[09:31:58] [Server thread/INFO]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403)
[09:31:58] [Server thread/INFO]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341)
[09:31:58] [Server thread/INFO]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:289)
[09:31:58] [Server thread/INFO]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616)
[09:31:58] [Server thread/INFO]: 	at java.lang.Thread.run(Thread.java:748)`


Here's the latest way I tested it:

`    firstjoin_message:
      Condition: 'player.getStatistic(Java.type("org.bukkit.Statistic").LEAVE_GAME) == 0'
      Bungee_Message: '&6[&4+&6] &6Welcome &b{player} &6to &bAges&6of&aMC&6!'`

I also tested it like this:

`    firstjoin_message:
      Condition: 'player.getStatistic(Java.type("org.bukkit.Statistic").LEAVE_GAME) == 0'
      Bungee_Message: default
       - '&8[&2+&8] &7Welcome &b{player} &7to the server!'
        - '&8[&2+&8] &7Bless &9{player} &7for joining!'
        - '&8[&2+&8] &7All say hey to &e{player} &7for joining!'
        - '&8[&2+&8] &7Watch out for &c{player} &7joining!'`

**Comment by Kbryst** [comment]
I apologize, this is hard to read, I've reposted it in a pastebin.

https://pastebin.com/EjWDDRau

**Comment by Kbryst** [comment]
Follow up question,

So I have it set up, I can see it work correctly on the lobby. I'm seeing the word "default" just show up in my chat on another server connected to it. I'm also not seeing the message go cross bungee.

Is there anything else that needs to be done to the other servers on the bungee?

**Comment by Kbryst** [comment]
I'm not sure if I did this right. I got an error and the plugin disabled.

https://pastebin.com/EjWDDRau
First two sections are two ways I tried it, 3rd is the error.

I even put it at the top next to "  Delay_Ticks: 1" and "Message: default" but it just kept sending the word "default" to me on one of the other servers.

**Comment by kangarko** [comment]
Hi, I am very sorry, just checked the code and it actually splits features between join/leave and death messages. I wrote it down to our roadmap but with the current workload I am not sure when it'll be implemented.
