### ISSUE TITLE
Updated to 8.1.0 and it broke entirely in Paper 1.12.2

### ISSUE THREAD

**Issue by FrozenBeard** [kangarko/ChatControl-Pro#1186]
Updated chat plugin to 8.1.0 on latest paper 1.12.2 and it broke entirely.

```
[10:43:40] [DiscordSRV - Initialization/INFO]: [DiscordSRV] Console forwarding assigned to channel 296598050728706049
[10:43:40] [Server thread/INFO]: [ChatControl] Enabling ChatControl v8.1.0
[10:43:44] [Server thread/INFO]:   _____ _           _    _____            _             _  +
[10:43:44] [Server thread/INFO]:  / ____| |         | |  / ____|          | |           | |
[10:43:44] [Server thread/INFO]: | |    | |__   __ _| |_| |     ___  _ __ | |_ _ __ ___ | |
[10:43:44] [Server thread/INFO]: | |    | '_ \ / _` | __| |    / _ \| '_ \| __| '__/ _ \| |
[10:43:44] [Server thread/INFO]: | |____| | | | (_| | |_| |___| (_) | | | | |_| | | (_) | |
[10:43:44] [Server thread/INFO]:  \_____|_| |_|\__,_|\__|\_____\___/|_| |_|\__|_|  \___/|_|
[10:43:44] [Server thread/INFO]:  
[10:43:44] [Server thread/WARN]: java.lang.NoSuchMethodException: net.minecraft.server.v1_12_R1.PacketPlayOutChat.<init>(net.minecraft.server.v1_12_R1.IChatBaseComponent, byte)
[10:43:44] [Server thread/WARN]: 	at java.lang.Class.getConstructor0(Class.java:3082)
[10:43:44] [Server thread/WARN]: 	at java.lang.Class.getConstructor(Class.java:1825)
[10:43:44] [Server thread/WARN]: 	at org.mineacademy.chatcontrol.final. .aq.<clinit>(SourceFile:62)
[10:43:44] [Server thread/WARN]: 	at org.mineacademy.chatcontrol.final. .ao.<clinit>(SourceFile:221)
[10:43:44] [Server thread/WARN]: 	at org.mineacademy.chatcontrol.final. .COM2.const(SourceFile:46)
[10:43:44] [Server thread/WARN]: 	at org.mineacademy.chatcontrol.final. .v.onEnable(SourceFile:181)
[10:43:44] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[10:43:44] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316)
[10:43:44] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[10:43:44] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395)
[10:43:44] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344)
[10:43:44] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442)
[10:43:44] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403)
[10:43:44] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341)
[10:43:44] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:289)
[10:43:44] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616)
[10:43:44] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[10:43:44] [Server thread/INFO]: ** COMPATIBILITY TEST FAILED - THIS PLUGIN WILL NOT FUNCTION **
[10:43:44] [Server thread/INFO]: ** YOUR MINECRAFT VERSION APPEARS UNSUPPORTED: v1_12 **
[10:43:44] [Server thread/WARN]: java.lang.ExceptionInInitializerError
[10:43:44] [Server thread/WARN]: 	at org.mineacademy.chatcontrol.final. .ao.<clinit>(SourceFile:221)
[10:43:44] [Server thread/WARN]: 	at org.mineacademy.chatcontrol.final. .COM2.const(SourceFile:46)
[10:43:44] [Server thread/WARN]: 	at org.mineacademy.chatcontrol.final. .v.onEnable(SourceFile:181)
[10:43:44] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[10:43:44] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316)
[10:43:44] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[10:43:44] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395)
[10:43:44] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344)
[10:43:44] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442)
[10:43:44] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403)
[10:43:44] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341)
[10:43:44] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:289)
[10:43:44] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616)
[10:43:44] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[10:43:44] [Server thread/WARN]: Caused by: org.mineacademy.chatcontrol.final. .aX$short: Error initiating Chat/Title/ActionBAR API (incompatible Craftbukkit? - git-Paper-1613 (MC: 1.12.2) / 1.12.2-R0.1-SNAPSHOT / v1_12_R1)
[10:43:44] [Server thread/WARN]: 	at org.mineacademy.chatcontrol.final. .aq.<clinit>(SourceFile:83)
[10:43:44] [Server thread/WARN]: 	... 14 more
[10:43:44] [Server thread/WARN]: Caused by: java.lang.NoSuchMethodException: net.minecraft.server.v1_12_R1.PacketPlayOutChat.<init>(net.minecraft.server.v1_12_R1.IChatBaseComponent, byte)
[10:43:44] [Server thread/WARN]: 	at java.lang.Class.getConstructor0(Class.java:3082)
[10:43:44] [Server thread/WARN]: 	at java.lang.Class.getConstructor(Class.java:1825)
[10:43:44] [Server thread/WARN]: 	at org.mineacademy.chatcontrol.final. .aq.<clinit>(SourceFile:62)
[10:43:44] [Server thread/WARN]: 	... 14 more
[10:43:44] [Server thread/ERROR]: Error occurred while enabling ChatControl v8.1.0 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
	at org.mineacademy.chatcontrol.final. .COM2.const(SourceFile:46) ~[?:?]
	at org.mineacademy.chatcontrol.final. .v.onEnable(SourceFile:181) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.12.2.jar:git-Paper-1613]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) ~[patched_1.12.2.jar:git-Paper-1613]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[patched_1.12.2.jar:git-Paper-1613]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395) ~[patched_1.12.2.jar:git-Paper-1613]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344) ~[patched_1.12.2.jar:git-Paper-1613]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) ~[patched_1.12.2.jar:git-Paper-1613]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403) ~[patched_1.12.2.jar:git-Paper-1613]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) ~[patched_1.12.2.jar:git-Paper-1613]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:289) ~[patched_1.12.2.jar:git-Paper-1613]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) ~[patched_1.12.2.jar:git-Paper-1613]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
Caused by: java.lang.RuntimeException: (This is a proxy exception, look for errors above)
	at org.mineacademy.chatcontrol.final. .ao.<clinit>(SourceFile:238) ~[?:?]
	... 13 more
[10:43:44] [Server thread/INFO]: [ChatControl] Disabling ChatControl v8.1.0
[10:43:44] [Server thread/INFO]: Plugin might not shut down property. Got NullPointerException: null
[10:43:44] [Server thread/INFO]: Error closing menu inventories for players..
[10:43:44] [Server thread/WARN]: java.lang.NoClassDefFoundError: Could not initialize class org.mineacademy.chatcontrol.final. .ao
[10:43:44] [Server thread/WARN]: 	at org.mineacademy.chatcontrol.final. .v.onDisable(SourceFile:517)
[10:43:44] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266)
[10:43:44] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:350)
[10:43:44] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:437)
[10:43:44] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:320)
[10:43:44] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[10:43:44] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395)
[10:43:44] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344)
[10:43:44] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442)
[10:43:44] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403)
[10:43:44] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341)
[10:43:44] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:289)
[10:43:44] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616)
[10:43:44] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[10:43:44] [DiscordSRV - Initialization/INFO]: [DiscordSRV] No chat plugin hooks enabled
```

**Comment by kangarko** [comment]
Apology for this, this is our fault in the Remain library. I'll fix this immediately.

I guess the Remain did not make the plugin remain compatible after all :)

**Comment by FrozenBeard** [comment]
Thanks!
