### ISSUE TITLE
[Error] 1.14 - 1.14.1: Chat Filter Not Working (Event listener errors)

### ISSUE THREAD

**Issue by Yumry** [kangarko/ChatControl-Pro#1197]
Hi, I'm having an issue on 1.14 relating to filtering the chat. Players are able to send messages
containing words that should be filtered out. 

The plugin still adds periods and filters spam with normal messages, but the plugins breaks when players say anything that is supposed to be blocked (according to the files in the rules folder)

When this occurs no formatting is done to the message and it is not blocked. The plugin also prints error to the console, it looks to be related to some code in the event listener for AsyncPlayerChatEvent.

Operating systems tested: 
`Ubuntu Server 18.04.2 LTS`
`Ubuntu Server 18.10`
`Windows 10`

Java versions tested:
`Java(TM) SE Runtime Environment (build 12.0.1+12)`
`OpenJDK Runtime Environment (build 1.8.0_212-8u212-b03-0ubuntu1.18.10.1-b03)`
`Java(TM) SE Runtime Environment (build 1.8.0_201-b09)`

Server versions tested: 
`git-Spigot-c8d4cef-1fee35b (MC: 1.14) (Implementing API version 1.14-R0.1-SNAPSHOT)`
`git-Spigot-8043ebc-9bda413 (MC: 1.14.1) (Implementing API version 1.14.1-R0.1-SNAPSHOT)`

ChatControl versions tested:
`8.1.0`
`8.1.1`
`8.1.2`
`8.1.3`

Server error output:
```
[03:07:05] [Async Chat Thread - #1/ERROR]: Could not pass event AsyncPlayerChatEvent to ChatControl v8.1.3
java.lang.IllegalStateException: PreRuleMatchEvent cannot be triggered asynchronously from another thread.
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) ~[spigot.jar:git-Spigot-c8d4cef-1fee
        at org.mineacademy.chatcontrol.final. .LpT2.const(SourceFile:1338) ~[?:?]
        at org.mineacademy.chatcontrol.final. .by.const(SourceFile:327) ~[?:?]
        at org.mineacademy.chatcontrol.final. .by.const(SourceFile:283) ~[?:?]
        at org.mineacademy.chatcontrol.final. .bb.const(SourceFile:281) ~[?:?]
        at org.mineacademy.chatcontrol.final. .bb.const(SourceFile:52) ~[?:?]
        at org.mineacademy.chatcontrol.final. .bb.const(SourceFile:34) ~[?:?]
        at org.mineacademy.chatcontrol.final. .LpT4.execute(SourceFile:25) ~[?:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot.jar:git-Spigot-c8d4cef-1fee35b
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:520) [spigot.jar:git-Spigot-c8d4cef-1fee3
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:499) [spigot.jar:git-Spigot-c8d4cef-1fee3
        at net.minecraft.server.v1_14_R1.PlayerConnection.chat(PlayerConnection.java:1588) [spigot.jar:git-Spigot-c8d4cef-1fe
        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1526) [spigot.jar:git-Spigot-c8d4cef-1fee35
        at net.minecraft.server.v1_14_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:41) [spigot.jar:git-Spigot-c8d4cef-1fee
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_212]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_212]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```

During server load there are no errors from ChatControl as far as I can tell.
```
[20:36:53] [Server thread/INFO]: [ChatControl] Enabling ChatControl v8.1.3
[20:36:53] [Server thread/INFO]:   _____ _           _    _____            _             _  +
[20:36:53] [Server thread/INFO]:  / ____| |         | |  / ____|          | |           | |
[20:36:53] [Server thread/INFO]: | |    | |__   __ _| |_| |     ___  _ __ | |_ _ __ ___ | |
[20:36:53] [Server thread/INFO]: | |    | '_ \ / _` | __| |    / _ \| '_ \| __| '__/ _ \| |
[20:36:53] [Server thread/INFO]: | |____| | | | (_| | |_| |___| (_) | | | | |_| | | (_) | |
[20:36:53] [Server thread/INFO]:  \_____|_| |_|\__,_|\__|\_____\___/|_| |_|\__|_|  \___/|_|
[20:36:53] [Server thread/INFO]:
[20:36:55] [Server thread/INFO]: Toasts are enabled. This may degrade your performance somewhat because advancements (Toasts) must be handled on the main thread.
[20:36:55] [Server thread/WARN]: Warning: Nashorn engine is planned to be removed from a future JDK release
[20:36:56] [Server thread/INFO]:
[20:36:56] [Server thread/INFO]: Checking compatible plugins..
[20:36:56] [Server thread/INFO]: Found: Essentials, Multiverse-Core, ProtocolLib, Vault, WorldEdit, WorldGuard
[20:36:56] [Server thread/INFO]:
[20:36:56] [Server thread/INFO]: Rules loads now..
[20:36:56] [Server thread/INFO]: 43 global, 15 chat, 4 command, 2 packet and 1 book rule(s) found
[20:36:56] [Server thread/INFO]:
[20:36:56] [Server thread/INFO]: Listening starts..
[20:36:56] [Server thread/INFO]: Rules & antispam listening at normal priority.
[20:36:56] [Server thread/INFO]: Fallback chat listener started at normal priority
[20:36:56] [Server thread/INFO]:
[20:36:56] [Server thread/INFO]: Ready for action! (took 275 ms)
[20:36:56] [Server thread/INFO]: ______________________________________________________________
[20:36:56] [Server thread/INFO]:
```

The error does not come up when players send messages that don't contain words that are supposed to be filtered.

I tested on a test server as well, using the latest version of both ChatControl and ProtocolLib, with no other plugins installed.
The test server was set up with default configurations on both spigot and the plugins.

Hope this can be resolved!

**Comment by kangarko** [comment]
Hi,

that appears like a Spigot new feature for 1.14. I took a look and made some codebase changes. Can you please test the next version?

I appreciate your detailed report though!

Matej

**Comment by Yumry** [comment]
Thanks for responding and fixing it so quickly. I can confirm the update has fixed it, words are now being censored properly and the error is gone. 
Thank you very much!

**Comment by Yumry** [comment]
After some more testing I found another issue I believe is related to this one. When joining a chat channel players are unable to send messages. When sending a message in the chat channel, nothing is sent to the chat and the following error occurs.

```
[12:08:08] [Async Chat Thread - #16/INFO]: [Server] ChatControl 8.1.4 encountered a IllegalStateException! Please check your error.log and report this issue with the information in that file.
[12:08:08] [Async Chat Thread - #16/INFO]: java.lang.IllegalStateException: ChatChannelEvent cannot be triggered asynchronously from another thread.
[12:08:08] [Async Chat Thread - #16/INFO]:      at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502)
[12:08:08] [Async Chat Thread - #16/INFO]:      at org.mineacademy.chatcontrol.final. .LpT2.const(SourceFile:1338)
[12:08:08] [Async Chat Thread - #16/INFO]:      at org.mineacademy.chatcontrol.final. .bn.sendMessage(SourceFile:217)
[12:08:08] [Async Chat Thread - #16/INFO]:      at org.mineacademy.chatcontrol.final. .bn.sendMessage(SourceFile:182)
[12:08:08] [Async Chat Thread - #16/INFO]:      at org.mineacademy.chatcontrol.final. .bn.sendMessage(SourceFile:177)
[12:08:08] [Async Chat Thread - #16/INFO]:      at org.mineacademy.chatcontrol.final. .ba.const(SourceFile:70)
[12:08:08] [Async Chat Thread - #16/INFO]:      at org.mineacademy.chatcontrol.final. .ba.const(SourceFile:18)
[12:08:08] [Async Chat Thread - #16/INFO]:      at org.mineacademy.chatcontrol.final. .LpT4.execute(SourceFile:25)
[12:08:08] [Async Chat Thread - #16/INFO]:      at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[12:08:08] [Async Chat Thread - #16/INFO]:      at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:520)
[12:08:08] [Async Chat Thread - #16/INFO]:      at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:499)
[12:08:08] [Async Chat Thread - #16/INFO]: [Server] *-----------------------------------------------*
[12:08:08] [Async Chat Thread - #16/INFO]: [Server]  Error sending channel message for Yumry!
[12:08:08] [Async Chat Thread - #16/INFO]: [Server]  Channel: global
[12:08:08] [Async Chat Thread - #16/INFO]: [Server]  Message: Testing, 123, testing.
[12:08:08] [Async Chat Thread - #16/INFO]: [Server]  Error: IllegalStateException: ChatChannelEvent cannot be triggered asynchronously from another thread.
[12:08:08] [Async Chat Thread - #16/INFO]: [Server] *-----------------------------------------------*
[12:08:08] [Async Chat Thread - #16/INFO]: [global] Yumry: Testing, 123, testing.
```
The messages sent in chat channels do not show up in-game, only in the console.

**Comment by kangarko** [comment]
Please upgrade to Paperspigot: https://papermc.io/

**Comment by NerdyBirder** [comment]
@kangarko is ChatControl only going to be supporting Paperspigot for 1.14 in the future? Or are there plans to continue support for Spigot servers? Our server has been using Chatcontrol for years and we would like to continue using it on our Spigot server as we hope to update to 1.14 in the near future.

**Comment by kangarko** [comment]
We will continue to support Spigot however they've messed up with the event system in a pretty bad way recently and some of the features in ChatControl simply broke. Tbh I can't rewrite their system but luckily Paper reverted their changes so you can just use it.

I've been personally on Paper for years without issues, it's faster and more customizable than Spigot.

**Comment by NerdyBirder** [comment]
Ok, thank you for the reply and the info. We will continue to wait to see what the next release of spigot for 1.14 does, maybe they will fix their mistake.

**Comment by kangarko** [comment]
Hi, good news, I got help from the PaperSpigot team and all plugins should be working just fine as per their next release.
