### ISSUE TITLE
onPacketSending(PacketEvent) Problem

### ISSUE THREAD

**Issue by vikram901** [kangarko/ChatControl-Pro#1203]
SupremeCruncher issued server command: /gm
[18:49:23 INFO]: ºbSupremeCruncher º4was denied access to command.
[18:49:23 ERROR]: [ChatControl] Unhandled exception occured in onPacketSending(PacketEvent) for ChatControl
java.lang.IllegalStateException: PreRuleMatchEvent cannot be triggered asynchronously from primary server thread.
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:482) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.mineacademy.chatcontrol.final. .LpT2.const(SourceFile:1338) ~[ChatControl-8.1.5.jar:?]
        at org.mineacademy.chatcontrol.final. .by.const(SourceFile:327) ~[ChatControl-8.1.5.jar:?]
        at org.mineacademy.chatcontrol.final. .by.const(SourceFile:677) ~[ChatControl-8.1.5.jar:?]
        at org.mineacademy.chatcontrol.hook.super$4.onPacketSending(SourceFile:252) ~[ChatControl-8.1.5.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) [ProtocolLib.jar:4.4.0-b421]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) [ProtocolLib.jar:4.4.0-b421]
        at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:588) [ProtocolLib.jar:4.4.0-b421]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:564) [ProtocolLib.jar:4.4.0-b421]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:338) [ProtocolLib.jar:4.4.0-b421]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:298) [ProtocolLib.jar:4.4.0-b421]
        at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:367) [ProtocolLib.jar:4.4.0-b421]
        at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:66) [ProtocolLib.jar:4.4.0-b421]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:332) [ProtocolLib.jar:4.4.0-b421]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:302) [ProtocolLib.jar:4.4.0-b421]
        at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) [ProtocolLib.jar:4.4.0-b421]
        at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) [ProtocolLib.jar:4.4.0-b421]
        at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:192) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.NetworkManager.handle(NetworkManager.java:141) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PlayerConnection.sendPacket(PlayerConnection.java:907) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.sendRawMessage(CraftPlayer.java:146) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.sendMessage(CraftPlayer.java:153) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at com.earth2me.essentials.User.sendMessage(User.java:795) [EssentialsX-2.16.1.0.jar:?]
        at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:527) [EssentialsX-2.16.1.0.jar:?]
        at com.earth2me.essentials.Essentials.onCommand(Essentials.java:458) [EssentialsX-2.16.1.0.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at java.base/java.lang.Thread.run(Unknown Source) [?:?]
[18:49:23 ERROR]: Parameters:
  net.minecraft.server.v1_8_R3.PacketPlayOutChat@448d94d2[
    a=TextComponent{text='', siblings=[TextComponent{text='You do not have access to that command.', siblings=[], style=Style{hasParent=true, color=º4, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}
    components=<null>
    b=1
  ]

**Comment by kangarko** [comment]
Packet features for Minecraft 1.14 and newer require PaperSpigot instead of Spigot. Get it from: https://papermc.io

**Comment by giovstr** [comment]
> Packet features for Minecraft 1.14 and newer require PaperSpigot instead of Spigot. Get it from: https://papermc.io

same problem on 1.18.2 and i'm on paper

**Comment by kangarko** [comment]
Ensure you're on the most up-to-date version
