### ISSUE TITLE
 Could not pass event PlayerCommandPreprocessEvent Paper 1.14.2

### ISSUE THREAD

**Issue by andris155** [kangarko/ChatControl-Pro#1216]
```
[14:44:13] [Server thread/INFO]: HORner issued server command: /m Panda123234 nem leugrottam véletlenül a netherbe a lávába
[14:44:13] [Server thread/ERROR]: Could not pass event PlayerCommandPreprocessEvent to ChatControl v8.1.6
java.lang.IllegalStateException: PreRuleMatchEvent cannot be triggered asynchronously from primary server thread.
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:522) ~[patched_1.14.2.jar:git-Paper-58]
	at org.mineacademy.chatcontrol.final. .LpT2.const(SourceFile:1338) ~[?:?]
	at org.mineacademy.chatcontrol.final. .bz.const(SourceFile:327) ~[?:?]
	at org.mineacademy.chatcontrol.final. .bz.const(SourceFile:283) ~[?:?]
	at org.mineacademy.chatcontrol.final. .bd.const(SourceFile:236) ~[?:?]
	at org.mineacademy.chatcontrol.final. .bd.onPlayerCommand(SourceFile:39) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor593.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.2.jar:git-Paper-58]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.2.jar:git-Paper-58]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.2.jar:git-Paper-58]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:534) ~[patched_1.14.2.jar:git-Paper-58]
	at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1822) ~[patched_1.14.2.jar:git-Paper-58]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1638) ~[patched_1.14.2.jar:git-Paper-58]
	at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.14.2.jar:git-Paper-58]
	at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.14.2.jar:git-Paper-58]
	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:18) ~[patched_1.14.2.jar:git-Paper-58]
	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.2.jar:git-Paper-58]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:127) ~[patched_1.14.2.jar:git-Paper-58]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.2.jar:git-Paper-58]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:105) ~[patched_1.14.2.jar:git-Paper-58]
	at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:998) ~[patched_1.14.2.jar:git-Paper-58]
	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:991) ~[patched_1.14.2.jar:git-Paper-58]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:91) ~[patched_1.14.2.jar:git-Paper-58]
	at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:974) ~[patched_1.14.2.jar:git-Paper-58]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:908) ~[patched_1.14.2.jar:git-Paper-58]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by kangarko** [comment]
Hi, this will get solved in the next version
