### ISSUE TITLE
Startup error

### ISSUE THREAD

**Issue by LogGits** [kangarko/ChatControl-Pro#1243]
Error on startup
```
[ChatControl]: Enabling ChatControl v8.2.4
Update channels.yml at 'Send_Command_Require_Join' -> 'false'
Rules loads now..
17 global, 15 chat, 3 command, 1 book an rule(s) found
Listening starts..
Rules & antispam listening at normal priority.
java.lang.NullPointerException
at java.util.ArrayList.<init>(ArrayList.java:178)
at org.bukkit.command.Command.setAliases(Command.java:360)
at org.mineacademy.chatcontrol.final. .PRN.<init>(SourceFile:121)
at org.mineacademy.chatcontrol.final. .PRN.<init>(SourceFile:105)
at org.mineacademy.chatcontrol.final. .short.<init>(SourceFile:59)
at org.mineacademy.chatcontrol.ChatControl.long(SourceFile:306)
at org.mineacademy.chatcontrol.ChatControl.double(SourceFile:209)
at org.mineacademy.chatcontrol.ChatControl.private(SourceFile:173)
at org.mineacademy.chatcontrol.final. .b.short(SourceFile:128)
at org.mineacademy.chatcontrol.final. .b.a(SourceFile:118)
at org.mineacademy.chatcontrol.lib.fo.model.LpT1.const(SourceFile:114)
at org.mineacademy.chatcontrol.final. .PrN$protected.const(SourceFile:138)
at org.mineacademy.chatcontrol.final. .PrN.private(SourceFile:70)
at org.mineacademy.chatcontrol.final. .PrN.native(SourceFile:66)
at org.mineacademy.chatcontrol.final. .b.static(SourceFile:94)
at org.mineacademy.chatcontrol.final. .CoM4.onEnable(SourceFile:196)
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265)
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:334)
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412)
at java.lang.Thread.run(Thread.java:748)
_ _ _ 
| | | | ___ ___ _ __ ___| |
| |_| |/ _ \ / _ \| '_ \/ __| |
| _ | (_) | (_) | |_) \__ \_|
|_| |_|\___/ \___/| .__/|___(_)
|_| 
!-----------------------------------------------------!
Error loading ChatControl v8.2.4, plugin is disabled!
Running on 1.13.2-R0.1-SNAPSHOT (v1_13_R2) & Java 1.8.0_201
!-----------------------------------------------------!
Error: Unable to get the error message, search above.
!-----------------------------------------------------!
```

**Comment by kangarko** [comment]
Thanks, that'll be fixed.
