### ISSUE TITLE
NullPointerException: Nodes must be provided

### ISSUE THREAD

**Issue by mibby** [kangarko/ChatControl-Pro#1261]
Paper dev 122 (Spigot 1.14.3)
ChatControlPro v8.2.7

@kangarko Any idea what this error could be pertaining to?
https://paste.ubuntu.com/p/tPZjDd56Tw/

**Comment by kangarko** [comment]
Hi,

please wait for the next update tonight and retest. Error lines have been changed.

However, the last error says "No operations allowed after connection closed" for your MySQL connection. Seems like it is being closed before we can save some data. I recommend you ask your hosting about that or check if the connection is actually opened.

**Comment by mibby** [comment]
I actually have direct access to the server box. The SQL database is operational and up on the same local machine. What was going on when the error occurred was the server initializing and just finished. I proxy all connections and idle them during server updates/restarts so players automatically reconnect once the server is done (with late-bind: true in spigot).

I'm guessing ChatControl couldn't parse connections with 20+ people all joining at the same time immediately after server initialization finished? For reference, this didn't use to happen with 1.13, only after updating to 1.14 with the newest ChatControlPro.

**Comment by mibby** [comment]
@kangarko Since updating to ChatControlPro 8.2.9, I've ran into a couple more issues. 

1) /chc announce was showing [ChatControl] prefix for every line and empty linespace whereas wasn't before with 8.2.7.

2) Trying to remove the prefix in the settings to fix the issue and reloading ChatControl, everything broke. Error occured. 
```
More Information: 
Error updating mysql data for <player>
NullPointerException (Unknown cause)
	 at org.mineacademy.chatcontrol.final. .E.native(SourceFile:241)
	 at org.mineacademy.chatcontrol.ChatControl.double(SourceFile:298)
	 at org.mineacademy.chatcontrol.ChatControl.protected(SourceFile:200)
	 at org.mineacademy.chatcontrol.final. .coM5.break(SourceFile:653)
	 at org.mineacademy.chatcontrol.final. .short.const(SourceFile:560)
	 at org.mineacademy.chatcontrol.final. .com2.execute(SourceFile:266)
	 at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
	 at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:739)
```

Reloaded again to re-add the prefix since chat formatting broke.

```
More Information: 
Error updating mysql data for <player>
NullPointerException (Unknown cause)
	 at org.mineacademy.chatcontrol.final. .E.native(SourceFile:241)
	 at org.mineacademy.chatcontrol.ChatControl.double(SourceFile:298)
	 at org.mineacademy.chatcontrol.ChatControl.strictfp(SourceFile:187)
	 at org.mineacademy.chatcontrol.final. .coM5.onDisable(SourceFile:542)
	 at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265)
	 at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:373)
	 at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:452)
	 at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:438)
	 at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:431)
	 at org.bukkit.craftbukkit.v1_14_R1.CraftServer.disablePlugins(CraftServer.java:401)
```

3) Node must be positive still happening with v8.2.9 at server start-up initialization. :(
https://paste.ubuntu.com/p/3sH3nV6xvr/

**Comment by kangarko** [comment]
Thank you, the first two issues will be solved, that was a poorly tested release when it came to MySQL from my side and I apology.

As to our initial problem, there were changes to MySQL. Report if you got any more problems after the new update. I tested it well and it appears to work fine using an external database, the only thing now is that everything is sync so it will show up on timings in case there are delays, but it is safe.

Just curious does the Nodes problem stops when you remove me.clip.chatreaction.ChatReaction ? It appears in your error log.

**Comment by kangarko** [comment]
@mibby curious if you are still experiencing this on the most recent version?

**Comment by mibby** [comment]
Apologies for the delay. I'll update to the newest version and give everything another look over. :)

**Comment by mibby** [comment]
@kangarko My server is being deadlocked on start-up with ChatControlPro 8.3.0. Removing ChatControl, server is stable again, responds, and can check TPS.

**Comment by kangarko** [comment]
What is the deadlock? Please send me the full startup log.

Try setting the Clear_Data_If_Inactive to 0 in the next version. I judge that clearing the data.db fires many blocking net requests that cause it (even though we should stop the task after 5 seconds if that happens).

**Comment by mibby** [comment]
@kangarko The start-up log is fine. It's what happens after start-up initialization finishes and reaches a "done" state. The server completely locks up and freezes. Since the server is deadlocked and frozen, it cannot even generate a stacktrace dump. 

This still occurs with v8.3.1. However setting ``Clear_Data_If_Inactive: 0`` seems to have fixed the problem!

```
[08:30:51] [Server thread/INFO]:   _____ _           _    _____            _             _  +
[08:30:51] [Server thread/INFO]:  / ____| |         | |  / ____|          | |           | |
[08:30:51] [Server thread/INFO]: | |    | |__   __ _| |_| |     ___  _ __ | |_ _ __ ___ | |
[08:30:51] [Server thread/INFO]: | |    | '_ \ / _` | __| |    / _ \| '_ \| __| '__/ _ \| |
[08:30:51] [Server thread/INFO]: | |____| | | | (_| | |_| |___| (_) | | | | |_| | | (_) | |
[08:30:51] [Server thread/INFO]:  \_____|_| |_|\__,_|\__|\_____\___/|_| |_|\__|_|  \___/|_|
[08:30:51] [Server thread/INFO]:   
[08:30:51] [Server thread/INFO]: Connecting to MySQL database...
[08:30:51] [Server thread/INFO]:   
[08:30:51] [Server thread/INFO]: Update settings.yml. Move 'BungeeCords' (was 'MemorySection[path='BungeeCords', root='YamlConfiguration']') to 'BungeeCord'
[08:30:52] [Server thread/INFO]: Registering commands...
[08:30:52] [Server thread/INFO]:   
[08:30:52] [Server thread/INFO]: Hooked into: DiscordSRV
[08:30:52] [Server thread/INFO]:   
[08:30:52] [Server thread/INFO]: ChatControl loaded. Ready for action!
[08:30:52] [Server thread/INFO]: ______________________________________________________________
```

**Comment by kangarko** [comment]
Thanks, I completely abandoned asking Bukkit for play times, we now save Last_Active flag directly to the file. Less effective but prevents any deadlocks

**Comment by mibby** [comment]
@kangarko I'm still getting this error with v8.3.5 after restarting my server and auto-reconnecting players. :(

https://paste.ubuntu.com/p/TxF4XSMbxz/

**Comment by kangarko** [comment]
Hey,

sorry for the extra trouble. Seems like either ChatReaction or something else causes our data to load on a separate thread, which causes the issue. I have explicitly set the data to be loaded/saved on the main thread to the next version, please let me know if you will still get the issue.

**Comment by mibby** [comment]
Thanks! I'll update and monitor logs during scheduled restarts. I'll let you know if it has been fixed or not.
