### ISSUE TITLE
ChatControl 8.2.9 Error when a certain player leaves

### ISSUE THREAD

**Issue by x1p** [kangarko/ChatControl-Pro#1268]
This error happens every time only with this particular player
```
[18:12:33] [Server thread/INFO]: bryan_de_monkey lost connection: Disconnected
[18:12:33] [Server thread/INFO]: [ChatControl] !-----------------------------------------------------!
[18:12:33] [Server thread/INFO]: [ChatControl]  Error compiling mysql data for bryan_de_monkey
[18:12:33] [Server thread/INFO]: [ChatControl] !-----------------------------------------------------!
[18:12:33] [Server thread/INFO]: [ChatControl] ChatControl 8.2.9 encountered a NullPointerException! Please check your error.log and report this issue with the information in that file.
[18:12:33] [Server thread/ERROR]: Could not pass event PlayerQuitEvent to ChatControl v8.2.9
java.lang.NullPointerException: null
	at org.mineacademy.chatcontrol.final. .E.native(SourceFile:222) ~[?:?]
	at org.mineacademy.chatcontrol.final. .u.onQuit(SourceFile:258) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor417.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.13.2.jar:git-Paper-637]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.13.2.jar:git-Paper-637]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[patched_1.13.2.jar:git-Paper-637]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:520) ~[patched_1.13.2.jar:git-Paper-637]
	at net.minecraft.server.v1_13_R2.PlayerList.disconnect(PlayerList.java:429) ~[patched_1.13.2.jar:git-Paper-637]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1466) ~[patched_1.13.2.jar:git-Paper-637]
	at net.minecraft.server.v1_13_R2.NetworkManager.handleDisconnection(NetworkManager.java:367) ~[patched_1.13.2.jar:git-Paper-637]
	at net.minecraft.server.v1_13_R2.ServerConnection.c(ServerConnection.java:153) ~[patched_1.13.2.jar:git-Paper-637]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1132) ~[patched_1.13.2.jar:git-Paper-637]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-637]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940) ~[patched_1.13.2.jar:git-Paper-637]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837) ~[patched_1.13.2.jar:git-Paper-637]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```
the error.log:
```
------------------------------------[ 07.07.2019 18:12:33 ]-----------------------------------
ChatControl 8.2.9 encountered a NullPointerException
Running Paper 1.13.2-R0.1-SNAPSHOT and Java 1.8.0_212
Plugins: (hidden for some privacy)
----------------------------------------------------------------------------------------------

More Information: 
Error compiling mysql data for bryan_de_monkey
NullPointerException (Unknown cause)
	 at org.mineacademy.chatcontrol.final. .E.native(SourceFile:222)
	 at org.mineacademy.chatcontrol.final. .u.onQuit(SourceFile:258)
	 at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor417.execute(Unknown Source)
	 at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
	 at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
	 at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66)
	 at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:520)
----------------------------------------------------------------------------------------------
```

**Comment by x1p** [comment]
Edit: it happens with many more players, but not all

**Comment by kangarko** [comment]
Hey, please test using the most recent version, the MySQL logic and thus the error logs have been changed. Thank you and apology for a late reply.

**Comment by x1p** [comment]
I haven't seen it since 8.2.9.

**Comment by kangarko** [comment]
Awesome thanks, let me know if something comes up again!
