### ISSUE TITLE
1.13.2 - Could not pass event EntityDamageByEntityEvent to ChatControl v8.2.12

### ISSUE THREAD

**Issue by SmallSansSerif** [kangarko/ChatControl-Pro#1276]
Getting this error in logs on Paper version git-Paper-638 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

`
[13:28:06 ERROR]: Could not pass event EntityDamageByEntityEvent to ChatControl v8.2.12
java.lang.NullPointerException: null
        at org.mineacademy.chatcontrol.lib.fo.model.aUx.const(SourceFile:260) ~[?:?]
        at org.mineacademy.chatcontrol.lib.fo.model.LPT8.const(SourceFile:59) ~[?:?]
        at org.mineacademy.chatcontrol.lib.fo.model.LPT8.onEntityDamage(SourceFile:31) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor768.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.13.2.jar:git-Paper-638]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.13.2.jar:git-Paper-638]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[patched_1.13.2.jar:git-Paper-638]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:520) ~[patched_1.13.2.jar:git-Paper-638]
        at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callEvent(CraftEventFactory.java:104) ~[patched_1.13.2.jar:git-Paper-638]
        at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:834) ~[patched_1.13.2.jar:git-Paper-638]
        at net.minecraft.server.v1_13_R2.EntityLiving.damageEntity0(EntityLiving.java:1520) ~[patched_1.13.2.jar:git-Paper-638]
        at net.minecraft.server.v1_13_R2.EntityLiving.damageEntity(EntityLiving.java:993) ~[patched_1.13.2.jar:git-Paper-638]
        at de.Keyle.MyPet.compat.v1_13_R2.entity.EntityMyPet.attack(EntityMyPet.java:355) ~[?:?]
        at de.Keyle.MyPet.compat.v1_13_R2.entity.ai.attack.MeleeAttack.tick(MeleeAttack.java:137) ~[?:?]
        at de.Keyle.MyPet.api.entity.ai.AIGoalSelector.tick(AIGoalSelector.java:125) ~[?:?]
        at de.Keyle.MyPet.compat.v1_13_R2.entity.EntityMyPet.doMyPetTick(EntityMyPet.java:1090) ~[?:?]
        at de.Keyle.MyPet.compat.v1_13_R2.entity.EntityMyPet.movementTick(EntityMyPet.java:973) ~[?:?]
        at net.minecraft.server.v1_13_R2.EntityLiving.tick(EntityLiving.java:2135) ~[patched_1.13.2.jar:git-Paper-638]
        at net.minecraft.server.v1_13_R2.EntityInsentient.tick(EntityInsentient.java:261) ~[patched_1.13.2.jar:git-Paper-638]
        at de.Keyle.MyPet.compat.v1_13_R2.entity.EntityMyPet.tick(EntityMyPet.java:1281) ~[?:?]
        at net.minecraft.server.v1_13_R2.World.entityJoinedWorld(World.java:1561) ~[patched_1.13.2.jar:git-Paper-638]
        at net.minecraft.server.v1_13_R2.World.g(World.java:1528) ~[patched_1.13.2.jar:git-Paper-638]
        at net.minecraft.server.v1_13_R2.World.tickEntities(World.java:1339) ~[patched_1.13.2.jar:git-Paper-638]
        at net.minecraft.server.v1_13_R2.WorldServer.tickEntities(WorldServer.java:599) ~[patched_1.13.2.jar:git-Paper-638]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1107) ~[patched_1.13.2.jar:git-Paper-638]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-638]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940) ~[patched_1.13.2.jar:git-Paper-638]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837) ~[patched_1.13.2.jar:git-Paper-638]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
`

**Comment by kangarko** [comment]
Thanks, will be solved, please try the next version.
