### ISSUE TITLE
Plugin ChatControl v8.3.2 generated an exception whilst handling plugin message

### ISSUE THREAD

**Issue by x1p** [kangarko/ChatControl-Pro#1298]
```
[20:58:21 WARN]: [ChatControl] Plugin ChatControl v8.3.0 generated an exception whilst handling plugin message
java.lang.IllegalArgumentException: Name cannot be empty
at org.apache.commons.lang.Validate.notEmpty(Validate.java:321) ~[patched_1.13.2.jar:git-Paper-638]
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.getOfflinePlayer(CraftServer.java:1457) ~[patched_1.13.2.jar:git-Paper-638]
at org.bukkit.Bukkit.getOfflinePlayer(Bukkit.java:833) ~[patched_1.13.2.jar:git-Paper-638]
at org.mineacademy.chatcontrol.lib.fo.model.case.const(SourceFile:2463) ~[?:?]
at org.mineacademy.chatcontrol.lib.fo.model.Com2.const(SourceFile:580) ~[?:?]
at org.mineacademy.chatcontrol.protected.isIgnoring(SourceFile:458) ~[?:?]
at org.mineacademy.chatcontrol.hook.transient.const(SourceFile:77) ~[?:?]
at org.mineacademy.chatcontrol.final.nul. .cOM5.onPluginMessageReceived(SourceFile:35) ~[?:?]
at org.bukkit.plugin.messaging.StandardMessenger.dispatchIncomingMessage(StandardMessenger.java:436) ~[patched_1.13.2.jar:git-Paper-638]
at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:2625) ~[patched_1.13.2.jar:git-Paper-638]
at net.minecraft.server.v1_13_R2.PacketPlayInCustomPayload.a(SourceFile:45) ~[patched_1.13.2.jar:git-Paper-638]
at net.minecraft.server.v1_13_R2.PacketPlayInCustomPayload.a(SourceFile:9) ~[patched_1.13.2.jar:git-Paper-638]
at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15) ~[patched_1.13.2.jar:git-Paper-638]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_212]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_212]
at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[patched_1.13.2.jar:git-Paper-638]
at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1018) ~[patched_1.13.2.jar:git-Paper-638]
at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-638]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940) ~[patched_1.13.2.jar:git-Paper-638]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837) ~[patched_1.13.2.jar:git-Paper-638]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```
Paper 1.13.2
ChatControl 8.3.0
BungeeControl 2.2.0

**Comment by x1p** [comment]
This error spams all my servers about 20 times a day.

**Comment by x1p** [comment]
Changed the title because it still exist in 8.3.2.

**Comment by kangarko** [comment]
Apology for a late response.

Please repost me the error, code changed much since those two versions, I can't track it.

**Comment by x1p** [comment]
```
[22:05:28] [Server thread/WARN]: [ChatControl] Plugin ChatControl v8.3.2 generated an exception whilst handling plugin message
java.lang.IllegalArgumentException: Name cannot be empty
	at org.apache.commons.lang.Validate.notEmpty(Validate.java:321) ~[patched_1.13.2.jar:git-Paper-638]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.getOfflinePlayer(CraftServer.java:1457) ~[patched_1.13.2.jar:git-Paper-638]
	at org.bukkit.Bukkit.getOfflinePlayer(Bukkit.java:833) ~[patched_1.13.2.jar:git-Paper-638]
	at org.mineacademy.chatcontrol.lib.fo.model.case.const(SourceFile:2518) ~[?:?]
	at org.mineacademy.chatcontrol.lib.fo.model.CoM3.const(SourceFile:608) ~[?:?]
	at org.mineacademy.chatcontrol.protected.isIgnoring(SourceFile:463) ~[?:?]
	at org.mineacademy.chatcontrol.hook.transient.const(SourceFile:77) ~[?:?]
	at org.mineacademy.chatcontrol.final.nul. .cOM5.onPluginMessageReceived(SourceFile:35) ~[?:?]
	at org.bukkit.plugin.messaging.StandardMessenger.dispatchIncomingMessage(StandardMessenger.java:436) ~[patched_1.13.2.jar:git-Paper-638]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:2625) ~[patched_1.13.2.jar:git-Paper-638]
	at net.minecraft.server.v1_13_R2.PacketPlayInCustomPayload.a(SourceFile:45) ~[patched_1.13.2.jar:git-Paper-638]
	at net.minecraft.server.v1_13_R2.PacketPlayInCustomPayload.a(SourceFile:9) ~[patched_1.13.2.jar:git-Paper-638]
	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15) ~[patched_1.13.2.jar:git-Paper-638]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_212]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_212]
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[patched_1.13.2.jar:git-Paper-638]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1018) ~[patched_1.13.2.jar:git-Paper-638]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-638]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940) ~[patched_1.13.2.jar:git-Paper-638]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837) ~[patched_1.13.2.jar:git-Paper-638]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```

**Comment by kangarko** [comment]
Thanks, fixed!
