### ISSUE TITLE
[issue] Plugin don't load after /cc reload

### ISSUE THREAD

**Issue by arturek1666** [kangarko/ChatControl-Pro#1309]
Every time I want to change something I have to restart the server as after using /cc reload I am just getting error and plugin gets disabled:
```
------------------------------------[ 22.07.2019 21:19:55 ]-----------------------------------
ChatControl 8.3.2 encountered a COm1
Running Paper 1.14.4-R0.1-SNAPSHOT and Java 1.8.0_181
Plugins: CoreProtect v2.17.5, LuckPerms v4.4.26, WorldEdit v7.0.0;214af8a, OnlyProxyJoin v1.1.2, PlaceholderAPI v2.10.3, PlugMan v2.1.6, Elevator v3.7.0, WorldBorder v1.9.10 (beta), ProtocolLib v4.5.0-SNAPSHOT, SkinsRestorer v13.7.1, AsyncWorldEdit v3.6.7, MobFarmManager v1.5.2.2, ReWorld v1.1.8, DropEdit2 v1.1.22-SNAPSHOT, Vault v1.6.11, GlobalMarketChest v1.3.1, OreAnnouncer v2.2.0, ChatControl v8.3.2, HeadDatabase v4.9.2, RecipeControl v2.3.2, LiteBans v2.3.18, WorldGuard v7.0.1-beta-01;14e7525, JupiterCore v1.2.3, WorldGuardExtraFlags v4.1.2, Jobs v4.13.0, CMI v8.6.7.5, Residence v4.8.6.6, QuantumShop v2.4.1, AntiCommandSuggestions v1.3-SNAPSHOT, SpecializedCrates v2.8.9
----------------------------------------------------------------------------------------------

More Information: 
Cannot call Localization before it loads!
COm1 Report / Cannot call Localization before it loads!
	 at org.mineacademy.chatcontrol.final.nul. .lPt2.const(SourceFile:77)
	 at org.mineacademy.chatcontrol.ChatControl.finally(SourceFile:619)
	 at org.mineacademy.chatcontrol.ChatControl.void(SourceFile:556)
	 at org.mineacademy.chatcontrol.final.nul. .com4.package(SourceFile:735)
	 at org.mineacademy.chatcontrol.final.nul. .short.const(SourceFile:562)
	 at org.mineacademy.chatcontrol.final.nul. .LPt8.execute(SourceFile:305)
	 at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
	 at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:739)
	 at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchServerCommand(CraftServer.java:701)
----------------------------------------------------------------------------------------------
```

**Comment by kangarko** [comment]
There must be a different issue causing this. Please post me your entire startup log from server as well as the console log from when you run /chc rl, not the error.log this time. Thanks

**Comment by arturek1666** [comment]
I had resolved the issue, by setting up in config bungee server name.
