### ISSUE TITLE
Bungeecontrol 2.2.0 error Waterfall 1.14.4

### ISSUE THREAD

**Issue by andris155** [kangarko/ChatControl-Pro#1323]
```
13:37:51] [Netty Worker IO Thread #1/WARN]: Error dispatching event ServerSwitchEvent(player=AdamT) to listener org.mineacademy.bungeecontrol.listener.SwitchListener@2b556bb2
java.lang.NullPointerException: null
	at org.mineacademy.bungeecontrol.listener.SwitchListener.onConnect(SwitchListener.java:59) ~[?:?]
	at jdk.internal.reflect.GeneratedMethodAccessor29.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19) ~[waterfall-B.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
	at net.md_5.bungee.event.EventBus.post(EventBus.java:46) ~[waterfall-B.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
	at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:433) ~[waterfall-B.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
	at net.md_5.bungee.ServerConnector.handle(ServerConnector.java:346) ~[waterfall-B.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
	at net.md_5.bungee.protocol.packet.Login.handle(Login.java:87) ~[waterfall-B.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
	at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:104) ~[waterfall-B.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) ~[waterfall-B.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) ~[waterfall-B.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337) ~[waterfall-B.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) ~[waterfall-B.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) ~[waterfall-B.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) ~[waterfall-B.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337) ~[waterfall-B.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323) ~[waterfall-B.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297) ~[waterfall-B.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) ~[waterfall-B.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) ~[waterfall-B.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337) ~[waterfall-B.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[waterfall-B.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) ~[waterfall-B.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) ~[waterfall-B.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337) ~[waterfall-B.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408) ~[waterfall-B.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) ~[waterfall-B.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) ~[waterfall-B.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930) ~[waterfall-B.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:796) ~[waterfall-B.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:427) ~[waterfall-B.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:328) ~[waterfall-B.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905) ~[waterfall-B.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by kangarko** [comment]
Thanks, will be fixed
