### ISSUE TITLE
LuckPerms cancels /tell due to lookup being on main server thread

### ISSUE THREAD

**Issue by PsychoLynx** [kangarko/ChatControl-Pro#1357]
Hi! I recently updated ChatControl to 8.3.11 to fix the bug from earlier. Now when trying to send a /tell from one server to another, LuckPerms prints this message:

`[09:12:04 WARN]: [ChatControl] Plugin ChatControl v8.3.11 generated an exception whilst handling plugin message
java.lang.RuntimeException: The operation to lookup a UUID for 'PsychoLynx' was cancelled by LuckPerms. This is NOT a bug. 
The lookup request was made on the main server thread. It is not safe to execute a request to 
load username data from the database in this context. 
If you are a plugin author, please either make your request asynchronously, 
or provide an 'OfflinePlayer' object with the UUID already populated. 
Alternatively, server admins can disable this catch by setting 'vault-unsafe-lookups' to true 
in the LP config, but should consider the consequences (lag) before doing so.
	at me.lucko.luckperms.bukkit.vault.LuckPermsVaultPermission.lookupUuid(LuckPermsVaultPermission.java:112) ~[?:?]
	at me.lucko.luckperms.bukkit.vault.AbstractVaultPermission.has(AbstractVaultPermission.java:119) ~[?:?]
	at org.mineacademy.chatcontrol.lib.fo.model.LPT6.const(SourceFile:1730) ~[?:?]
	at org.mineacademy.chatcontrol.lib.fo.model.CoM3.native(SourceFile:879) ~[?:?]
	at org.mineacademy.chatcontrol.final.nul. .lpT1.const(SourceFile:275) ~[?:?]
	at org.mineacademy.chatcontrol.hook.transient.const(SourceFile:156) ~[?:?]
	at org.mineacademy.chatcontrol.final.nul. .cOM5.onPluginMessageReceived(SourceFile:35) ~[?:?]
	at org.bukkit.plugin.messaging.StandardMessenger.dispatchIncomingMessage(StandardMessenger.java:455) ~[patched_1.14.4.jar:git-Paper-172]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:2652) ~[patched_1.14.4.jar:git-Paper-172]
	at net.minecraft.server.v1_14_R1.PacketPlayInCustomPayload.a(SourceFile:45) ~[patched_1.14.4.jar:git-Paper-172]
	at net.minecraft.server.v1_14_R1.PacketPlayInCustomPayload.a(SourceFile:9) ~[patched_1.14.4.jar:git-Paper-172]
	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.14.4.jar:git-Paper-172]
	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.4.jar:git-Paper-172]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.14.4.jar:git-Paper-172]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.4.jar:git-Paper-172]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.14.4.jar:git-Paper-172]
	at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1012) ~[patched_1.14.4.jar:git-Paper-172]
	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1005) ~[patched_1.14.4.jar:git-Paper-172]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.14.4.jar:git-Paper-172]
	at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:989) ~[patched_1.14.4.jar:git-Paper-172]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:922) ~[patched_1.14.4.jar:git-Paper-172]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]`

**Comment by kangarko** [comment]
Fixed
