### ISSUE TITLE
Reload command error

### ISSUE THREAD

**Issue by TheC0ller** [kangarko/ChatControl-Pro#137]
Can you tell me where is problem ?

```
>[18:20:41 WARN]: [ChatControl] Task #1419 for ChatControl v7.0.32 generated an exception
java.lang.NoClassDefFoundError: Could not initialize class com.massivecraft.factions.entity.MPlayerColl
at com.massivecraft.factions.entity.MPlayer.get(MPlayer.java:43) ~[?:?]
at nul.final...\\.............if.COm4.const(SourceFile:689) ~[?:?]
at nul.final...\\.............if.coM4.for(SourceFile:253) ~[?:?]
at nul.final...\\.............if.COM3.const(SourceFile:161) ~[?:?]
at nul.final...\\.............if.COM3.const(SourceFile:130) ~[?:?]
at nul.final...\\.............if.COM3.const(SourceFile:111) ~[?:?]
at nul.final...\\.............if.COM3.const(SourceFile:107) ~[?:?]
at nul.final...\\.............if.COM3.const(SourceFile:100) ~[?:?]
at me.kangarko.chatcontrol.ChatControl$3.run(SourceFile:350) ~[?:?]
at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[minecraft_server.jar:git-Spigot-7d78b81-a867313]

at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [minecraft_server.jar:git-Spigot-7d78b81-a867313]

at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:730) [minecraft_server.jar:git-Spigot-7d78b81-a867313]

at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [minecraft_server.jar:git-Spigot-7d78b81-a867313]

at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [minecraft_server.jar:git-Spigot-7d78b81-a867313]

at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [minecraft_server.jar:git-Spigot-7d78b81-a867313]

at java.lang.Thread.run(Thread.java:745) [?:1.8.0_102]
```

**Comment by TheC0ller** [comment]
I'm not using MassiveCraft Factions...

**Comment by kangarko** [comment]
Do not use /reload command, it messes up. Also ensure you're on latest spigot as those new versions might be unstable.

**Comment by EvilOlaf** [comment]
As said above, do not use /reload. Never. If you have to reload the configuration of a individual plugin that does not offer an internal mechanism for this case the safest way is to perform a clean restart. 
Another, not as clean as, solution might be a plugin management plugin to reload the plugin. 

The /reload command is broken for years and was never safe to use.
