### ISSUE TITLE
Error when updating

### ISSUE THREAD

**Issue by DriedSponge** [kangarko/ChatControl-Pro#1378]
I got this error when updating the plugin 
[21:26:46 INFO]: !-----------------------------------------------------!
[21:26:46 INFO]: Error loading ChatControl v8.3.13, plugin is disabled!
[21:26:46 INFO]: Running on 1.13.2-R0.1-SNAPSHOT (v1_13_R2) & Java 1.8.0_221
[21:26:46 INFO]: !-----------------------------------------------------!
[21:26:46 INFO]: Error: Report / Global_Shortcut in formatting.yml cannot equal Bungee_Chat.Shortcut in settings.yml!

**Comment by DriedSponge** [comment]
Sorry this is the proper error 
```
[23:52:08 INFO]: org.mineacademy.chatcontrol.final.nul. .COm1: Report / Global_Shortcut in formatting.yml cannot equal Bungee_Chat.Shortcut in settings.yml!
[23:52:08 INFO]:        at org.mineacademy.chatcontrol.final.nul. .af$short.init(SourceFile:121)
[23:52:08 INFO]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[23:52:08 INFO]:        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[23:52:08 INFO]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[23:52:08 INFO]:        at java.lang.reflect.Method.invoke(Unknown Source)
[23:52:08 INFO]:        at org.mineacademy.chatcontrol.final.nul. .CoN.native(SourceFile:164)
[23:52:08 INFO]:        at org.mineacademy.chatcontrol.final.nul. .CoN.const(SourceFile:137)
[23:52:08 INFO]:        at org.mineacademy.chatcontrol.final.nul. .CoN.volatile(SourceFile:116)
[23:52:08 INFO]:        at org.mineacademy.chatcontrol.final.nul. .CoN$1.a_(SourceFile:55)
[23:52:08 INFO]:        at org.mineacademy.chatcontrol.final.nul. .CoM2.private(SourceFile:290)
[23:52:08 INFO]:        at org.mineacademy.chatcontrol.final.nul. .CoN.native(SourceFile:202)
[23:52:08 INFO]:        at org.mineacademy.chatcontrol.final.nul. .af.const(SourceFile:20)
[23:52:08 INFO]:        at org.mineacademy.chatcontrol.final.nul. .CoN.const(SourceFile:77)
[23:52:08 INFO]:        at org.mineacademy.chatcontrol.final.nul. .com4.onEnable(SourceFile:253)
[23:52:08 INFO]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254)
[23:52:08 INFO]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
[23:52:08 INFO]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403)
[23:52:08 INFO]:        at java.lang.Thread.run(Unknown Source)
```

**Comment by DriedSponge** [comment]
I updated my server version and new error
```
[14:42:36] [Server thread/INFO]: [ChatControl] Disabling ChatControl v8.3.13
[14:42:36] [Server thread/INFO]: org.mineacademy.chatcontrol.final.nul. .COm1: Report / Global_Shortcut in formatting.yml cannot equal Bungee_Chat.Shortcut in settings.yml!
[14:42:36] [Server thread/INFO]:        at org.mineacademy.chatcontrol.final.nul. .af$short.init(SourceFile:121)
[14:42:36] [Server thread/INFO]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[14:42:36] [Server thread/INFO]:        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[14:42:36] [Server thread/INFO]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[14:42:36] [Server thread/INFO]:        at java.lang.reflect.Method.invoke(Unknown Source)
[14:42:36] [Server thread/INFO]:        at org.mineacademy.chatcontrol.final.nul. .CoN.native(SourceFile:164)
[14:42:36] [Server thread/INFO]:        at org.mineacademy.chatcontrol.final.nul. .CoN.const(SourceFile:137)
[14:42:36] [Server thread/INFO]:        at org.mineacademy.chatcontrol.final.nul. .CoN.volatile(SourceFile:116)
[14:42:36] [Server thread/INFO]:        at org.mineacademy.chatcontrol.final.nul. .CoN$1.a_(SourceFile:55)
[14:42:36] [Server thread/INFO]:        at org.mineacademy.chatcontrol.final.nul. .CoM2.private(SourceFile:290)
[14:42:36] [Server thread/INFO]:        at org.mineacademy.chatcontrol.final.nul. .CoN.native(SourceFile:202)
[14:42:36] [Server thread/INFO]:        at org.mineacademy.chatcontrol.final.nul. .af.const(SourceFile:20)
[14:42:36] [Server thread/INFO]:        at org.mineacademy.chatcontrol.final.nul. .CoN.const(SourceFile:77)
[14:42:36] [Server thread/INFO]:        at org.mineacademy.chatcontrol.final.nul. .com4.onEnable(SourceFile:253)
[14:42:36] [Server thread/INFO]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[14:42:36] [Server thread/INFO]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352)
[14:42:36] [Server thread/INFO]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:417)
[14:42:36] [Server thread/INFO]:        at java.lang.Thread.run(Unknown Source)
[14:42:36] [Server thread/INFO]:   _   _                       _
[14:42:36] [Server thread/INFO]:   | | | | ___   ___  _ __  ___| |
[14:42:36] [Server thread/INFO]:   | |_| |/ _ \ / _ \| '_ \/ __| |
[14:42:36] [Server thread/INFO]:   |  _  | (_) | (_) | |_) \__ \_|
[14:42:36] [Server thread/INFO]:   |_| |_|\___/ \___/| .__/|___(_)
[14:42:36] [Server thread/INFO]:                     |_|
[14:42:36] [Server thread/INFO]: !-----------------------------------------------------!
[14:42:36] [Server thread/INFO]: Error loading ChatControl v8.3.13, plugin is disabled!
[14:42:36] [Server thread/INFO]: Running on 1.14.4-R0.1-SNAPSHOT (v1_14_R1) & Java 1.8.0_221
[14:42:36] [Server thread/INFO]: !-----------------------------------------------------!
[14:42:36] [Server thread/INFO]: Error: Report / Global_Shortcut in formatting.yml cannot equal Bungee_Chat.Shortcut in settings.yml!
```

**Comment by DriedSponge** [comment]
Got it fixed sorry to bother you
