### ISSUE TITLE
1.8: Doesn't start

### ISSUE THREAD

**Issue by Stremo** [kangarko/ChatControl-Pro#1404]
**The plugin does not start and says that it is not supported for my minecraft version.**
```
[06:33:02] [Server thread/INFO]: [ChatControl] Loading ChatControl v8.3.18
[06:33:02] [Server thread/WARN]: java.lang.ArrayIndexOutOfBoundsException: 0
[06:33:02] [Server thread/WARN]: 	at org.mineacademy.chatcontrol.final.nul. .Com9.<clinit>(SourceFile:55)
[06:33:02] [Server thread/WARN]: 	at org.mineacademy.chatcontrol.final.nul. .com6.<clinit>(SourceFile:210)
[06:33:02] [Server thread/WARN]: 	at org.mineacademy.chatcontrol.final.nul. .h.const(SourceFile:42)
[06:33:02] [Server thread/WARN]: 	at org.mineacademy.chatcontrol.final.nul. .i.const(SourceFile:88)
[06:33:02] [Server thread/WARN]: 	at org.mineacademy.chatcontrol.final.nul. .i.const(SourceFile:57)
[06:33:02] [Server thread/WARN]: 	at org.mineacademy.chatcontrol.final.nul. .p.byte(SourceFile:36)
[06:33:02] [Server thread/WARN]: 	at org.mineacademy.chatcontrol.final.nul. .cOn.onLoad(SourceFile:205)
[06:33:02] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugins(CraftServer.java:296)
[06:33:02] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.java:152)
[06:33:02] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:505)
[06:33:02] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[06:33:02] [Server thread/INFO]: ** COMPATIBILITY TEST FAILED - THIS PLUGIN WILL NOT FUNCTION **
[06:33:02] [Server thread/INFO]: ** YOUR MINECRAFT VERSION APPEARS UNSUPPORTED: v1_8 **
[06:33:02] [Server thread/WARN]: java.lang.ExceptionInInitializerError
[06:33:02] [Server thread/WARN]: 	at org.mineacademy.chatcontrol.final.nul. .com6.<clinit>(SourceFile:210)
[06:33:02] [Server thread/WARN]: 	at org.mineacademy.chatcontrol.final.nul. .h.const(SourceFile:42)
[06:33:02] [Server thread/WARN]: 	at org.mineacademy.chatcontrol.final.nul. .i.const(SourceFile:88)
[06:33:02] [Server thread/WARN]: 	at org.mineacademy.chatcontrol.final.nul. .i.const(SourceFile:57)
[06:33:02] [Server thread/WARN]: 	at org.mineacademy.chatcontrol.final.nul. .p.byte(SourceFile:36)
[06:33:02] [Server thread/WARN]: 	at org.mineacademy.chatcontrol.final.nul. .cOn.onLoad(SourceFile:205)
[06:33:02] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugins(CraftServer.java:296)
[06:33:02] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.java:152)
[06:33:02] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:505)
[06:33:02] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[06:33:02] [Server thread/WARN]: Caused by: org.mineacademy.chatcontrol.final.nul. .Nul$transient: Error initiating Chat/Title/ActionBAR API (incompatible Craftbukkit? - git-Spigot-550ebac-7019900 (MC: 1.8) / 1.8-R0.1-SNAPSHOT / v1_8_R1)
[06:33:02] [Server thread/WARN]: 	at org.mineacademy.chatcontrol.final.nul. .Com9.<clinit>(SourceFile:88)
[06:33:02] [Server thread/WARN]: 	... 10 more
[06:33:02] [Server thread/WARN]: Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
[06:33:02] [Server thread/WARN]: 	at org.mineacademy.chatcontrol.final.nul. .Com9.<clinit>(SourceFile:55)
[06:33:02] [Server thread/WARN]: 	... 10 more
[06:33:02] [Server thread/INFO]: ***************************************************************
[06:33:02] [Server thread/INFO]: [ChatControl] ChatControl 8.3.18 encountered a cOm2! Please check your error.log and report this issue with the information in that file.[m
[06:33:02] [Server thread/INFO]: [ChatControl] <0> An error occured: samF2YS5sYW5nLkV4Y2VwdGlvbkluSW5pdGlhbGl6ZXJFcnJvcg==[m
```

**Comment by kangarko** [comment]
ChatControl works on Spigot 1.8.8 only, not on 1.8.1 or any older version.

You can get PaperSpigot 1.8.8 here: https://papermc.io/ci/job/Paper/443/

**Comment by Stremo** [comment]
Clarify that on the plugin page so no one else makes this mistake.
![t](https://user-images.githubusercontent.com/31030769/65368544-d326d300-dc42-11e9-9870-a6a67b4b7cb1.png)

**Comment by kangarko** [comment]
Thanks, done

![a](https://i.imgur.com/uqpYzGn.png)

What is your paypal? I can send you a refund.

**Comment by Stremo** [comment]
Don't worry I really like the plugin and plan to upgrade the server to version 1.8.8. Thanks for everything
