### ISSUE TITLE
ch spy doesn't work right after u relog

### ISSUE THREAD

**Issue by Kbryst** [kangarko/ChatControl-Pro#1420]
So this has been an issue for a pretty long time. I honestly just haven't had the time to report it.

It has been tested on 8.4.0, our current live server is a few versions behind.

Paper spigot 1.14.4

So we use towny, and have town and nation chat through chatcontrol. 

What we are noticing is when we use "ch spy town" or "ch spy nation" it stays on after we relog... but it doesnt actually work.

We have to run the command again, twice (1st to turn it off, 2nd to turn it back on) and then it starts working again.

Being on bungee, when we switch servers and then switch back, we have to run the commands again. I run these commands at least 30 times a day.

**Comment by Kbryst** [comment]
Another note:

I'm OP and I have staff with the permissions, we both get the same issue. So I don't believe it to be a missing permission on our end.

**Comment by kangarko** [comment]
I apologies, I was not able to catch up the problem, seems to work fine with a primitive reproduction: https://i.imgur.com/HkKaxQv.gifv

Please ZIP me your entire ChatControl folder. If there is anything specific you do more than I did on the demo to get this issue, let me know. Thanks.

**Comment by Kbryst** [comment]
[ChatControlFiles.zip](https://github.com/kangarko/ChatControl-Pro/files/3722093/ChatControlFiles.zip)

Pretty much recreated it the same way you did on the demo.

**Comment by kangarko** [comment]
Thank you, I was still not able to fully reproduce the problem but I noticed that, when you have OP or * permissions, or the autojoin permissions, you are getting joined to appropriate channels automatically on login. This may interfere with the old channels.

While I apology that I don't have the time to solve this in the new few days and possibly a week (due to moving countries), I want you to gather as much data so that when I have time I deliver a fix asap.

Please set Debug to [channels-join] and report the messages after 1st login (when you have channel spy disabled), then after you enable it, and finally after the 2nd login when it should remain but it does not. Also report to me what ChatControl permissions you have.

Thank you.

**Comment by Kbryst** [comment]
`[18.10.2019 09:23:40] [channels-join]: Preparing channel join for -name removed-. Limits: write 1, read 3, bypass = true
[18.10.2019 09:23:40] [channels-join]: Maybe join admin channel:
[18.10.2019 09:23:40] [channels-join]: Mode read set (chatcontrol.channel.autojoin.admin.read)
[18.10.2019 09:23:40] [channels-join]: Maybe join global channel:
[18.10.2019 09:23:40] [channels-join]: Mode write set (chatcontrol.channel.autojoin.global.write)
[18.10.2019 09:23:40] [channels-join]: Maybe join nation channel:
[18.10.2019 09:23:40] [channels-join]: Mode read set (chatcontrol.channel.autojoin.nation.read)
[18.10.2019 09:23:40] [channels-join]: Maybe join town channel:
[18.10.2019 09:23:40] [channels-join]: Mode read set (chatcontrol.channel.autojoin.town.read)
[18.10.2019 09:23:40] [channels-join]: Preparing channel join for -name removed-. Limits: write 1, read 3, bypass = true
[18.10.2019 09:23:40] [channels-join]: Maybe join admin channel:
[18.10.2019 09:23:40] [channels-join]: Already in channel
[18.10.2019 09:23:40] [channels-join]: Maybe join global channel:
[18.10.2019 09:23:40] [channels-join]: Already in channel
[18.10.2019 09:23:40] [channels-join]: Maybe join nation channel:
[18.10.2019 09:23:40] [channels-join]: Already in channel
[18.10.2019 09:23:40] [channels-join]: Maybe join town channel:
[18.10.2019 09:23:40] [channels-join]: Already in channel`

**Comment by kangarko** [comment]
In the log it said you were joined to "town" and "nation" channels in so called read mode, that means the "chatcontrol.channel.autojoin.nation.read" permission was applied automatically.

I have edited ChatControl to load MySQL/data.db data first, then look up for these permissions. This change will solve this problem. Please use the next version :)

**Comment by Kbryst** [comment]
There's another error that said to set "bungee" to debug for this issue. Do
you want to see that error and log?

**Comment by kangarko** [comment]
I apology for a late response.

Yes please. What's the bug?

**Comment by Kbryst** [comment]
I am on a business trip until the 5th. I'll have to check on my
home computer

**Comment by kangarko** [comment]
Sure return back later just comment below and I see that!

**Comment by Kbryst** [comment]
`More Information: 
Head out of bounds! Max data size for SPY is 1! (Set Debug to [bungee] in settings.yml and report this issue along with the new console messages
cOm2 Report / Head out of bounds! Max data size for SPY is 1! (Set Debug to [bungee] in settings.yml and report this issue along with the new console messages
	 at org.mineacademy.chatcontrol.final.nul. .lPt2.const(SourceFile:78)
	 at org.mineacademy.chatcontrol.final.nul. .lPT4.const(SourceFile:206)
	 at org.mineacademy.chatcontrol.final.nul. .lPT4.const(SourceFile:108)
	 at org.mineacademy.chatcontrol.final.nul. .lPT4.const(SourceFile:47)
	 at org.mineacademy.chatcontrol.final.nul. .x.const(SourceFile:303)
	 at org.mineacademy.chatcontrol.final.nul. .x.const(SourceFile:270)
	 at org.mineacademy.chatcontrol.final.nul. .x.onPlayerCommand(SourceFile:46)
	 at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor855.execute(Unknown Source)
	 at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
	 at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
	 at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
	 at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545)`




I'm having a hard time finding anything in the debug log. Its huge and it all just looks the same.

**Comment by kangarko** [comment]
Are you on the latest ChatControl Pro and BungeeControl versions?
