### ISSUE TITLE
Error updating mysql data for [NAME]

### ISSUE THREAD

**Issue by PrymWorld** [kangarko/ChatControl-Pro#1430]
I always have this problem with my gameserver no matter how little or how many plugins I have.

```
 ------------------------------------[ 19.10.2019 20:13:14 ]-----------------------------------
ChatControl 8.4.3 encountered a SocketException
Running Paper 1.14.4-R0.1-SNAPSHOT and Java 1.8.0_222
Plugins: WorldEdit v7.0.1;61bc012, IPortal v1.13, PlaceholderAPI v2.10.4, PlugMan v2.1.6, NetworkManager v2.8.2-SNAPSHOT, GWarp v[2.10.1.0], WorldGuard v7.0.0;02b731f, ProtocolLib v4.5.0-SNAPSHOT, Vault v1.7.2-b107, BungeeTabListPlus v2.8.11, SuperLobby v4.0.9, MysqlEcoBridge v3.4.0, ChatControl v8.4.3
----------------------------------------------------------------------------------------------
More Information: 
Error updating mysql data for NAME
SocketException Connection reset
	 at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:115)
	 at java.net.SocketOutputStream.write(SocketOutputStream.java:155)
	 at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
	 at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
	 at com.mysql.jdbc.MysqlIO.send(MysqlIO.java:3733)
	 at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2512)
	 at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683)
	 at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2495)
	 at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1903)
	 at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2124)
	 at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2058)
	 at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5158)
	 at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2043)
	 at org.mineacademy.chatcontrol.final.nul. .L.native(SourceFile:233)
	 at org.mineacademy.chatcontrol.ChatControl.double(SourceFile:304)
	 at org.mineacademy.chatcontrol.ChatControl.strictfp(SourceFile:181)
	 at org.mineacademy.chatcontrol.final.nul. .cOn.onDisable(SourceFile:622)
	 at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265)
	 at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:373)
	 at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:453)
	 at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:439)
	 at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:432)
	 at org.bukkit.craftbukkit.v1_14_R1.CraftServer.disablePlugins(CraftServer.java:401)
----------------------------------------------------------------------------------------------
```

**Comment by PrymWorld** [comment]
I have the following options enabled in the config without success.
The error always comes back no matter what I try myself Without plugin only with ChatControl this error comes with each Joinen.

   Aggressive: true

What exactly does the MySQL error mean, what should I do?

**Comment by kangarko** [comment]
I recommend you use the next version, if the problem persists then please contact your hosting because I believe it may as well be an issue on their side, closing the connection.

**Comment by PrymWorld** [comment]
The new version does not help anything that should help synonymous was fixed no error.
My hoster does not terminate connections only ChatControl always wants to keep the connection permanently so was programmed incorrectly so the timout is reached.
Program it so that the MySQL request is also closed again ChatControl does not.
What should I do now, is not it my fault?

**Comment by PrymWorld** [comment]
Do you have discord?

**Comment by kangarko** [comment]
@PrymWorld I apology for a late reply!

Have you tried removing the highlighted part from MySQL of settings.yml?
![a](https://i.imgur.com/kRipE3w.png)

**Comment by PrymWorld** [comment]
Yes, I have always tried the same mistake.

**Comment by kangarko** [comment]
Let's continue in private messages where you sent me your error.
