### ISSUE TITLE
ClassNotFoundException: github.scarsz.discordsrv.dependencies.jda.core.entities.TextChannel

### ISSUE THREAD

**Issue by mibby** [kangarko/ChatControl-Pro#1445]
ChatControlPro dev 8.4.6
DiscordSRV 1.18.0-20191106.205127-15 (https://github.com/DiscordSRV/DiscordSRV/commits/develop)

```
[03:23:49] [Server thread/INFO]:   _____ _           _    _____            _             _  +
[03:23:49] [Server thread/INFO]:  / ____| |         | |  / ____|          | |           | |
[03:23:49] [Server thread/INFO]: | |    | |__   __ _| |_| |     ___  _ __ | |_ _ __ ___ | |
[03:23:49] [Server thread/INFO]: | |    | '_ \ / _` | __| |    / _ \| '_ \| __| '__/ _ \| |
[03:23:49] [Server thread/INFO]: | |____| | | | (_| | |_| |___| (_) | | | | |_| | | (_) | |
[03:23:49] [Server thread/INFO]:  \_____|_| |_|\__,_|\__|\_____\___/|_| |_|\__|_|  \___/|_|
[03:23:49] [Server thread/INFO]:   
[03:23:49] [Server thread/INFO]: Connecting to MySQL database...
[03:23:49] [Server thread/INFO]:   
[03:23:49] [Server thread/INFO]: !-----------------------------------------------------!
[03:23:49] [Server thread/INFO]: ChatControl could not integrate to DiscordSRV because the plugin is outdated!
[03:23:49] [Server thread/INFO]: !-----------------------------------------------------!
[03:23:49] [Server thread/INFO]: ChatControl 8.4.6 encountered a ClassNotFoundException! Please check your error.log and report this issue with the information in that file.
[03:23:49] [Server thread/INFO]: java.lang.ClassNotFoundException: github.scarsz.discordsrv.dependencies.jda.core.entities.TextChannel
[03:23:49] [Server thread/INFO]: at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
[03:23:49] [Server thread/INFO]: at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:139)
[03:23:49] [Server thread/INFO]: at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:85)
[03:23:49] [Server thread/INFO]: at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
[03:23:49] [Server thread/INFO]: at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
[03:23:49] [Server thread/INFO]: at java.lang.Class.forName0(Native Method)
[03:23:49] [Server thread/INFO]: at java.lang.Class.forName(Class.java:264)
[03:23:49] [Server thread/INFO]: at org.mineacademy.chatcontrol.lib.fo.model.CoM3.const(SourceFile:195)
[03:23:49] [Server thread/INFO]: at org.mineacademy.chatcontrol.final.nul. .cOn.onEnable(SourceFile:264)
[03:23:49] [Server thread/INFO]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[03:23:49] [Server thread/INFO]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338)
[03:23:49] [Server thread/INFO]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420)
[03:23:49] [Server thread/INFO]: at java.lang.Thread.run(Thread.java:748)
[03:23:49] [Server thread/INFO]:   _   _                       _
[03:23:49] [Server thread/INFO]:   | | | | ___   ___  _ __  ___| |
[03:23:49] [Server thread/INFO]:   | |_| |/ _ \ / _ \| '_ \/ __| |
[03:23:49] [Server thread/INFO]:   |  _  | (_) | (_) | |_) \__ \_|
[03:23:49] [Server thread/INFO]:   |_| |_|\___/ \___/| .__/|___(_)
[03:23:49] [Server thread/INFO]:                     |_|
[03:23:49] [Server thread/INFO]: !-----------------------------------------------------!
[03:23:49] [Server thread/INFO]: Error loading ChatControl v8.4.6, plugin is disabled!
[03:23:49] [Server thread/INFO]: Running on 1.14.4-R0.1-SNAPSHOT (v1_14_R1) & Java 1.8.0_232
[03:23:49] [Server thread/INFO]: !-----------------------------------------------------!
[03:23:49] [Server thread/INFO]: Error: github.scarsz.discordsrv.dependencies.jda.core.entities.TextChannel
[03:23:49] [Server thread/INFO]: !-----------------------------------------------------!
[03:23:49] [Server thread/INFO]: [ChatControl] Disabling ChatControl v8.4.6
```

**Comment by kangarko** [comment]
Thanks, I will update

**Comment by mibby** [comment]
@kangarko :(

```
[02:08:09] [Server thread/INFO]: [ChatControl] Enabling ChatControl v8.4.7
[02:08:09] [Server thread/INFO]:   _____ _           _    _____            _             _  +
[02:08:09] [Server thread/INFO]:  / ____| |         | |  / ____|          | |           | |
[02:08:09] [Server thread/INFO]: | |    | |__   __ _| |_| |     ___  _ __ | |_ _ __ ___ | |
[02:08:09] [Server thread/INFO]: | |    | '_ \ / _` | __| |    / _ \| '_ \| __| '__/ _ \| |
[02:08:09] [Server thread/INFO]: | |____| | | | (_| | |_| |___| (_) | | | | |_| | | (_) | |
[02:08:09] [Server thread/INFO]:  \_____|_| |_|\__,_|\__|\_____\___/|_| |_|\__|_|  \___/|_|
[02:08:09] [Server thread/INFO]:   
[02:08:09] [Server thread/INFO]: Connecting to MySQL database...
[02:08:09] [Server thread/INFO]:   
[02:08:09] [Server thread/INFO]: !-----------------------------------------------------!
[02:08:09] [Server thread/INFO]: ChatControl could not integrate to DiscordSRV because the plugin is outdated!
[02:08:09] [Server thread/INFO]: !-----------------------------------------------------!
[02:08:09] [Server thread/INFO]: ChatControl 8.4.7 encountered a ClassNotFoundException! Please check your error.log and report this issue with the information in that file.
[02:08:09] [Server thread/INFO]: java.lang.ClassNotFoundException: github.scarsz.discordsrv.dependencies.jda.core.entities.TextChannel
[02:08:09] [Server thread/INFO]: at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
[02:08:09] [Server thread/INFO]: at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:139)
[02:08:09] [Server thread/INFO]: at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:85)
[02:08:09] [Server thread/INFO]: at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
[02:08:09] [Server thread/INFO]: at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
[02:08:09] [Server thread/INFO]: at java.lang.Class.forName0(Native Method)
[02:08:09] [Server thread/INFO]: at java.lang.Class.forName(Class.java:264)
[02:08:09] [Server thread/INFO]: at org.mineacademy.chatcontrol.lib.fo.model.CoM3.const(SourceFile:195)
[02:08:09] [Server thread/INFO]: at org.mineacademy.chatcontrol.final.nul. .cOn.onEnable(SourceFile:264)
[02:08:09] [Server thread/INFO]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[02:08:09] [Server thread/INFO]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338)
[02:08:09] [Server thread/INFO]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420)
[02:08:09] [Server thread/INFO]: at java.lang.Thread.run(Thread.java:748)
[02:08:09] [Server thread/INFO]:   _   _                       _
[02:08:09] [Server thread/INFO]:   | | | | ___   ___  _ __  ___| |
[02:08:09] [Server thread/INFO]:   | |_| |/ _ \ / _ \| '_ \/ __| |
[02:08:09] [Server thread/INFO]:   |  _  | (_) | (_) | |_) \__ \_|
[02:08:09] [Server thread/INFO]:   |_| |_|\___/ \___/| .__/|___(_)
[02:08:09] [Server thread/INFO]:                     |_|
[02:08:09] [Server thread/INFO]: !-----------------------------------------------------!
[02:08:09] [Server thread/INFO]: Error loading ChatControl v8.4.7, plugin is disabled!
[02:08:09] [Server thread/INFO]: Running on 1.14.4-R0.1-SNAPSHOT (v1_14_R1) & Java 1.8.0_232
[02:08:09] [Server thread/INFO]: !-----------------------------------------------------!
[02:08:09] [Server thread/INFO]: Error: github.scarsz.discordsrv.dependencies.jda.core.entities.TextChannel
[02:08:09] [Server thread/INFO]: !-----------------------------------------------------!
[02:08:09] [Server thread/INFO]: [ChatControl] Disabling ChatControl v8.4.7
```

**Comment by kangarko** [comment]
I apology, please try the next version. We are still on the problem though.

**Comment by mibby** [comment]
@kangarko Thanks. It seems to start-up fine now. 

One thing I did notice is my console is now spamming this 802 times in 5 minute intervals. Did you happen to leave any leftover debug in ChatControlPro v8.4.8? I'm not really sure where it is coming from. :(

```
[18:04:41] [Craft Scheduler Thread - 673/INFO]: #6666CC
```

**Comment by kangarko** [comment]
No this is not coming from ChatControl as far as I am concerned, it looks like a hex code color, try removing DiscordSRV first or any recently updated plugin.
