### ISSUE TITLE
Discordsrv broken in latest version (both plugins updated)

### ISSUE THREAD

**Issue by espen96** [kangarko/ChatControl-Pro#1448]
------------------------------------[ 10.11.2019 14:47:17 ]-----------------------------------
ChatControl 8.4.7 encountered a ClassNotFoundException
Running Paper 1.14.4-R0.1-SNAPSHOT and Java 1.8.0_212
Plugins: CoreProtect v2.17.5, dynmap v3.0-beta-5-218, PsudoCommand v1.0.12, MerchantPriceSetter v1.0.0, BetterFarming v1.8.2.9, AdvancedReporter v4.2, ItemParticles v1.11, WorldEdit v7.0.1;61bc012, EntityTrackerFixer v1.1.1, OpenInv v4.0.6, PlaceholderAPI v2.10.4, Lands v4.1.3.4, WorldBorder v1.9.10 (beta), ChestProtect v3.0.2.4, WorldGuard v7.0.1-SNAPSHOT;556b638, ProtocolLib v4.4.0, Multiverse-Core v4.1.0-b775, Cartographer2 v2.11, ForceResourcepacks v1.8.7 (build #338), MobFarmManager v1.5.4.0, PermissionsEx v1.23.4, UpgradeableHoppers v1.2.5.0, EpicWorldGenerator v8.1.7, Multiverse-NetherPortals v4.1.0-b763, Vault v1.7.3-b${env.TRAVIS_BUILD_NUMBER}, WorldGuardExtraFlags v4.1.2, boosCooldowns v3.14.5, WorldEditSelectionVisualizer v2.0.4, AdvancedRegionMarket v2.1.1, Jobs v4.14.3, HeadDatabase v4.9.6, DeathChestPro v3.3.11, QuickShop vReremake 2.4.6.4, DecoHeads v1.5.0, Shopkeepers v2.8.1, DiscordSRV v1.18.0, ItemFrameShops v6.0.5, ChatControl v8.4.7, CMI v8.6.15.5
----------------------------------------------------------------------------------------------

More Information: 
&cChatControl could not integrate to DiscordSRV because the plugin is outdated!
ClassNotFoundException github.scarsz.discordsrv.dependencies.jda.core.entities.TextChannel
	 at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	 at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:139)
	 at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:85)
	 at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	 at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	 at java.lang.Class.forName0(Native Method)
	 at java.lang.Class.forName(Class.java:264)
	 at org.mineacademy.chatcontrol.lib.fo.model.CoM3.const(SourceFile:195)
	 at org.mineacademy.chatcontrol.final.nul. .cOn.onEnable(SourceFile:264)
	 at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
	 at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338)
	 at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420)
	 at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:467)
	 at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:381)
----------------------------------------------------------------------------------------------

**Comment by x1p** [comment]
This probably reads better
```
[04:57:21] [Server thread/INFO]: !-----------------------------------------------------!
[04:57:21] [Server thread/INFO]: ChatControl could not integrate to DiscordSRV because the plugin is outdated!
[04:57:21] [Server thread/INFO]: !-----------------------------------------------------!
[04:57:21] [Server thread/INFO]: ChatControl 8.4.7 encountered a ClassNotFoundException! Please check your error.log and report this issue with the information in that file.
[04:57:21] [Server thread/INFO]: java.lang.ClassNotFoundException: github.scarsz.discordsrv.dependencies.jda.core.entities.TextChannel
[04:57:21] [Server thread/INFO]: at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
[04:57:21] [Server thread/INFO]: at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:140)
[04:57:21] [Server thread/INFO]: at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86)
[04:57:21] [Server thread/INFO]: at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[04:57:21] [Server thread/INFO]: at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[04:57:21] [Server thread/INFO]: at java.lang.Class.forName0(Native Method)
[04:57:21] [Server thread/INFO]: at java.lang.Class.forName(Class.java:264)
[04:57:21] [Server thread/INFO]: at org.mineacademy.chatcontrol.lib.fo.model.CoM3.const(SourceFile:195)
[04:57:21] [Server thread/INFO]: at org.mineacademy.chatcontrol.final.nul. .cOn.onEnable(SourceFile:264)
[04:57:21] [Server thread/INFO]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265)
[04:57:21] [Server thread/INFO]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:334)
[04:57:21] [Server thread/INFO]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412)
[04:57:21] [Server thread/INFO]: at java.lang.Thread.run(Thread.java:748)
[04:57:21] [Server thread/INFO]:   _   _                       _
[04:57:21] [Server thread/INFO]:   | | | | ___   ___  _ __  ___| |
[04:57:21] [Server thread/INFO]:   | |_| |/ _ \ / _ \| '_ \/ __| |
[04:57:21] [Server thread/INFO]:   |  _  | (_) | (_) | |_) \__ \_|
[04:57:21] [Server thread/INFO]:   |_| |_|\___/ \___/| .__/|___(_)
[04:57:21] [Server thread/INFO]:                     |_|
[04:57:21] [Server thread/INFO]: !-----------------------------------------------------!
[04:57:21] [Server thread/INFO]: Error loading ChatControl v8.4.7, plugin is disabled!
[04:57:21] [Server thread/INFO]: Running on 1.13.2-R0.1-SNAPSHOT (v1_13_R2) & Java 1.8.0_212
[04:57:21] [Server thread/INFO]: !-----------------------------------------------------!
[04:57:21] [Server thread/INFO]: Error: github.scarsz.discordsrv.dependencies.jda.core.entities.TextChannel
[04:57:21] [Server thread/INFO]: !-----------------------------------------------------!
[04:57:21] [Server thread/INFO]: [ChatControl] Disabling ChatControl v8.4.7
```

**Comment by KarlOfDuty** [comment]
Same here.

**Comment by astirling** [comment]
I am also having this issue on my servers.
ChatControlPro v8.4.7
DiscordSRV v1.18.0

**Comment by key1313** [comment]
Same issue ^

**Comment by Neeonn** [comment]
Same issue.

**Comment by Vankka** [comment]
DiscordSRV updated JDA to major version 4, ChatControl needs to be updated for DiscordSRV 1.18.x. JDA4 mostly changed package names from `core` to `api` as well as some method name changes. @kangarko

**Comment by kangarko** [comment]
Sorry everyone for waiting, ever since I moved countries I find myself not having time for Spigot. 

I'm building a team with positions open for Java developers (paid), anyone feel free to apply [here](https://www.spigotmc.org/threads/403375/).

**This is now fixed.**
