### ISSUE TITLE
/msg broken

### ISSUE THREAD

**Issue by LogGits** [kangarko/ChatControl-Pro#1470]
After updating to version 8.4.9 I can nolonger /msg. it says `"Oups! The Command failed :( Check the console and report the error"`
Which says:
```
ChatControl 8.4.9 encountered a cOm2
Running Paper 1.14.4-R0.1-SNAPSHOT and Java 1.8.0_201
```
```
Data count != valid values count in PM_LOOKUP! Data: 4 vs 5
cOm2 Report / Data count != valid values count in PM_LOOKUP! Data: 4 vs 5
	 at org.mineacademy.chatcontrol.final.nul. .lPt2.const(SourceFile:78)
	 at org.mineacademy.chatcontrol.final.nul. .lPT4.const(SourceFile:65)
	 at org.mineacademy.chatcontrol.final.nul. .lPT4.const(SourceFile:47)
	 at org.mineacademy.chatcontrol.final.nul. .AUX.const(SourceFile:165)
	 at org.mineacademy.chatcontrol.final.nul. .LPt8.execute(SourceFile:320)
	 at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
	 at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:739)
```

command used `/msg {myusername} test`

**Comment by andris155** [comment]
Same problem.

**Comment by Sikatsu** [comment]
Same here.

**Comment by lackoSK** [comment]
Hello guys,

I am already resolving this issue, please, be patient ;)

**Comment by JavaFactoryDev** [comment]
Will be fixed asap.

**Comment by FrozenBeard** [comment]
#1467

**Comment by JavaFactoryDev** [comment]
Duplicate #1467
