### ISSUE TITLE
Chc pro cant send messages

### ISSUE THREAD

**Issue by Scorpionvssub** [kangarko/ChatControl-Pro#1471]
Getting this error.log

`------------------------------------[ 07.12.2019 10:08:24 ]-----------------------------------
ChatControl 8.4.9 encountered a cOm2
Running CraftBukkit 1.14.4-R0.1-SNAPSHOT and Java 1.8.0_212
Plugins: BCDiscord v1.0.0, LuckPerms v4.4.27, WorldEdit v1.14-37, PlaceholderAPI v2.10.3, ArmorStandEditor v1.13-21, AdvancedBan v2.1.5-RELEASE, WorldBorder v1.8.7, Votifier v1.9, WorldGuard v7.0.0-beta-03;e51a220, ProtocolLib v4.5.0-SNAPSHOT, ExtraPlot v1.0.0, FastAsyncWorldEdit v1.14, IPWhitelist v1.7, MaxClaimBlocks v1.0.0, Vault v1.7.1-b91, BungeeTabListPlus v2.8.11, AdvancedBCRanks v2.2.0, Essentials v2.16.1.219, HeadDatabase v4.9.1, HolographicDisplays v2.3.3-SNAPSHOT, PlotSquared v4.353, BuycraftX v12.0.2, The Multiverse-Core Plugin, EssentialsChat v2.16.1.219, GriefPrevention v16.12.0-d4d7ac4, ChatControl v8.4.9
----------------------------------------------------------------------------------------------

More Information: 
Data count != valid values count in PM_LOOKUP! Data: 4 vs 5
cOm2 Report / Data count != valid values count in PM_LOOKUP! Data: 4 vs 5
	 at org.mineacademy.chatcontrol.final.nul. .lPt2.const(SourceFile:78)
	 at org.mineacademy.chatcontrol.final.nul. .lPT4.const(SourceFile:65)
	 at org.mineacademy.chatcontrol.final.nul. .lPT4.const(SourceFile:47)
	 at org.mineacademy.chatcontrol.final.nul. .AUX.const(SourceFile:165)
	 at org.mineacademy.chatcontrol.final.nul. .LPt8.execute(SourceFile:320)
	 at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149)
	 at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:710)
----------------------------------------------------------------------------------------------`

**Comment by JavaFactoryDev** [comment]
Duplicate #1470.

**Comment by FrozenBeard** [comment]
@JavaFactoryDev My report was before that #1467
