### ISSUE TITLE
I have a little problem with the plugin

### ISSUE THREAD

**Issue by cool9535** [kangarko/ChatControl-Pro#149]
Hello kangarko, I've got a problem with the pro version of the plugin, It keeps getting disabled on my cauldron 1.7.10 server I don't know why, do you? Log:
[12:18:37] [Server thread/WARN]: java.lang.reflect.InvocationTargetException
[12:18:37] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[12:18:37] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[12:18:37] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[12:18:37] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[12:18:37] [Server thread/WARN]: 	at kangarko.chatcontrol.config.ConfHelper.invokeMethods(ConfHelper.java:84)
[12:18:37] [Server thread/WARN]: 	at kangarko.chatcontrol.config.ConfHelper.loadValues(ConfHelper.java:70)
[12:18:37] [Server thread/WARN]: 	at kangarko.chatcontrol.config.ConfHelper.createFileAndLoad(ConfHelper.java:123)
[12:18:37] [Server thread/WARN]: 	at kangarko.chatcontrol.config.Settings.load(Settings.java:24)
[12:18:37] [Server thread/WARN]: 	at kangarko.chatcontrol.config.ConfHelper.loadAll(ConfHelper.java:54)
[12:18:37] [Server thread/WARN]: 	at kangarko.chatcontrol.ChatControl.onEnable(ChatControl.java:79)
[12:18:37] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316)
[12:18:37] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368)
[12:18:37] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410)
[12:18:37] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:415)
[12:18:37] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:349)
[12:18:37] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.java:511)
[12:18:37] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:485)
[12:18:37] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:445)
[12:18:37] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:336)
[12:18:37] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:631)
[12:18:37] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[12:18:37] [Server thread/WARN]: Caused by: java.lang.IllegalArgumentException: Malformed config value, expected double at: Chat.Formatter.Range
[12:18:37] [Server thread/WARN]: 	at org.apache.commons.lang.Validate.isTrue(Validate.java:136)
[12:18:37] [Server thread/WARN]: 	at kangarko.chatcontrol.config.ConfHelper.getDouble(ConfHelper.java:164)
[12:18:37] [Server thread/WARN]: 	at kangarko.chatcontrol.config.Settings$Chat$Formatter.init(Settings.java:136)
[12:18:37] [Server thread/WARN]: 	... 21 more
[12:18:37] [Server thread/INFO]: !----------------------------------------------!
[12:18:37] [Server thread/INFO]:  Error loading ChatControl, plugin is disabled!
[12:18:37] [Server thread/INFO]:  Running on 1.7.10-R0.1-SNAPSHOT (v1_7_R4) and Java 1.8.0_121
[12:18:37] [Server thread/INFO]: !----------------------------------------------!
[12:18:37] [Server thread/INFO]:  Error: Unable to get the error message, search above.
[12:18:37] [Server thread/INFO]: !----------------------------------------------!
[12:18:37] [Server thread/INFO]: [ChatControl] Disabling ChatControl v5.4.1

**Comment by kangarko** [comment]
This is the free version, not the pro one.

You have an error on Chat.Formatter.Range. It's supposed to be a full number like 1,2,3, not a decimal: 2.56 etc..

**Comment by cool9535** [comment]
Wait what?? Free version? I downloaded the pro version from spigot and yes, I have bourght it

**Comment by kangarko** [comment]
The error above is from the free version. Make sure you have removed the free version from your server otherwise it might get loaded first.

**Comment by cool9535** [comment]
Okay thx :)
