### ISSUE TITLE
Latest version not working on 1.13.2

### ISSUE THREAD

**Issue by Nedjii** [kangarko/ChatControl-Pro#1490]
Hello, I had to update the plugin from multiple versions behind because the plugin wouldn't start with discordsrv, since the update nothing is working anymore :
More Information: 
REGISTRY_GET_INVERSE could not find method 'b' in 'class net.minecraft.server.v1_13_R2.RegistryMaterials'
NoSuchMethodException net.minecraft.server.v1_13_R2.RegistryMaterials.b(java.lang.Object)
	 at java.lang.Class.getMethod(Class.java:1786)
	 at org.mineacademy.chatcontrol.final.nul. .S.<init>(SourceFile:124)
	 at org.mineacademy.chatcontrol.final.nul. .S.<clinit>(SourceFile:98)
	 at org.mineacademy.chatcontrol.final.nul. .D.const(SourceFile:73)
	 at org.mineacademy.chatcontrol.final.nul. .w.const(SourceFile:61)
	 at org.mineacademy.chatcontrol.final.nul. .q.<clinit>(SourceFile:213)
	 at org.mineacademy.chatcontrol.final.nul. .X.private(SourceFile:281)
	 at org.mineacademy.chatcontrol.final.nul. .Z.dd(SourceFile:220)
	 at org.mineacademy.chatcontrol.final.nul. .W.const(SourceFile:39)
	 at org.mineacademy.chatcontrol.final.nul. .Z.const(SourceFile:80)
	 at org.mineacademy.chatcontrol.final.nul. .com1.onEnable(SourceFile:253)
	 at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265)
	 at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:334)
	 at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412)
	 at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:443)
	 at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:357)
----------------------------------------------------------------------------------------------

**Comment by Nedjii** [comment]
I tried the version before latest one and this one is working.

**Comment by lackoSK** [comment]
Hello,

Please use pastebin.com to send us the **whole** console log from the server's boot.

Also, have you tried updating DiscordSRV?

**Comment by kangarko** [comment]
Closing due to inactivity

@Nedjii what version were you using during the error log? When you get back to me please post me your full console startup log till that error appears **using the latest version**.
