### ISSUE TITLE
Error on ChatControl 8.5.2 - 1.13.2

### ISSUE THREAD

**Issue by XxCoolGamesxX** [kangarko/ChatControl-Pro#1514]
Hello,
Is error only show on 1.13.2 but is fine on 1.14.4 and 1.15.1.
Thank.

```log ------------------------------------[ 08.01.2020 21:37:31 ]-----------------------------------
ChatControl 8.5.2 encountered a NoSuchMethodException
Running Paper 1.13.2-R0.1-SNAPSHOT and Java 1.8.0_231
Plugins: LuckPerms v5.0.21, BuycraftX v12.0.6, Vault v1.7.2-b107, ProtocolSupport v4.29-dev, Essentials v2.17.1.26, EssentialsProtect v2.17.1.26, EssentialsChat v2.17.1.26, ViaVersion v3.0.0-SNAPSHOT, EssentialsSpawn v2.17.1.26, ViaBackwards v3.0.0-SNAPSHOT, ProtocolLib v4.5.0, ViaRewind v1.5.0-SNAPSHOT, ChatControl v8.5.2
----------------------------------------------------------------------------------------------

More Information: 
REGISTRY_GET_INVERSE could not find method 'b' in 'class net.minecraft.server.v1_13_R2.RegistryMaterials'
NoSuchMethodException net.minecraft.server.v1_13_R2.RegistryMaterials.b(java.lang.Object)
	 at java.lang.Class.getMethod(Unknown Source)
	 at org.mineacademy.chatcontrol.final.nul. .Com8.<init>(SourceFile:124)
	 at org.mineacademy.chatcontrol.final.nul. .Com8.<clinit>(SourceFile:98)
	 at org.mineacademy.chatcontrol.final.nul. .cOm6.const(SourceFile:73)
	 at org.mineacademy.chatcontrol.final.nul. .LPT7.const(SourceFile:61)
	 at org.mineacademy.chatcontrol.final.nul. .lPT1.<clinit>(SourceFile:213)
	 at org.mineacademy.chatcontrol.final.nul. .CoN.private(SourceFile:281)
	 at org.mineacademy.chatcontrol.final.nul. .a.native(SourceFile:220)
	 at org.mineacademy.chatcontrol.final.nul. .lpT2.const(SourceFile:39)
	 at org.mineacademy.chatcontrol.final.nul. .a.const(SourceFile:80)
	 at org.mineacademy.chatcontrol.final.nul. .Com1.onEnable(SourceFile:253)
	 at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265)
	 at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:334)
	 at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412)
	 at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:443)
	 at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:357)
----------------------------------------------------------------------------------------------```

**Comment by SeruhioX** [comment]
Same, https://github.com/kangarko/ChatControl-Pro/issues/1490

If you try to reload (/chc reload)

`[15:10:25] [Server thread/INFO]: ______________________________________________________________
[15:10:25] [Server thread/INFO]:   
[15:10:25] [Server thread/INFO]: Reloading plugin ChatControl v8.5.0
[15:10:25] [Server thread/INFO]:   
[15:10:25] [Server thread/INFO]: !-----------------------------------------------------!
[15:10:25] [Server thread/INFO]: Please change your Bungee_Server_Name in
[15:10:25] [Server thread/INFO]: settings.yml to the exact name of this server
[15:10:25] [Server thread/INFO]: as you have in config.yml of your BungeeCord.
[15:10:25] [Server thread/INFO]: Plugin is now disabled.
[15:10:25] [Server thread/INFO]: !-----------------------------------------------------!
[15:10:25] [Server thread/INFO]: [ChatControl] Disabling ChatControl v8.5.0
[15:10:25] [Server thread/INFO]: Registering commands...
[15:10:25] [Server thread/INFO]: Warning: ChatControl may have not registered all /tell command aliases due to Towny is installed to prevent /t from being unregistered in Towny.
[15:10:25] [Server thread/INFO]:   
[15:10:25] [Server thread/INFO]: Loaded 29 global, 7 chat, 4 command, 2 packet and 1 book rules
[15:10:25] [Server thread/INFO]: !-----------------------------------------------------!
[15:10:25] [Server thread/INFO]: Error reloading ChatControl 8.5.0
[15:10:25] [Server thread/INFO]: !-----------------------------------------------------!
[15:10:25] [Server thread/INFO]: ChatControl 8.5.0 encountered an IllegalPluginAccessException! Please check your error.log and report this issue with the information in that file.
[15:10:25] [Server thread/INFO]: ______________________________________________________________
[15:10:25] [Server thread/WARN]: org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register class org.bukkit.event.player.AsyncPlayerChatEvent while not enabled
[15:10:25] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.registerEvent(SimplePluginManager.java:580)
[15:10:25] [Server thread/WARN]: 	at org.mineacademy.chatcontrol.final.nul. .lPT6.native(SourceFile:172)
[15:10:25] [Server thread/WARN]: 	at org.mineacademy.chatcontrol.final.nul. .PrN.const(SourceFile:63)
[15:10:25] [Server thread/WARN]: 	at org.mineacademy.chatcontrol.final.nul. .com1.const(SourceFile:832)
[15:10:25] [Server thread/WARN]: 	at org.mineacademy.chatcontrol.ChatControl.protected(SourceFile:247)
[15:10:25] [Server thread/WARN]: 	at org.mineacademy.chatcontrol.final.nul. .com1.break(SourceFile:744)
[15:10:25] [Server thread/WARN]: 	at org.mineacademy.chatcontrol.final.nul. .short.const(SourceFile:562)
[15:10:25] [Server thread/WARN]: 	at org.mineacademy.chatcontrol.final.nul. .nUL.execute(SourceFile:322)
[15:10:25] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151)
[15:10:25] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:734)
[15:10:25] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1783)
[15:10:25] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1591)
[15:10:25] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45)
[15:10:25] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:5)
[15:10:25] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15)
[15:10:25] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[15:10:25] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[15:10:25] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108)
[15:10:25] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1018)
[15:10:25] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439)
[15:10:25] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940)
[15:10:25] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837)
[15:10:25] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)`

This only happens in version 1.13.2

**Comment by lackoSK** [comment]
When this error occurs?

**Comment by SeruhioX** [comment]
> When this error occurs?

When the server starts.

**Comment by XxCoolGamesxX** [comment]
> 
> 
> > When this error occurs?
> 
> When the server starts.

Some.

**Comment by JavaFactoryDev** [comment]
Hey XxCoolGamesxX,

thanks for using ChatControlPro & reporting this issue.
We already know about it.
This only happens in 1.13. It seems like this happens because some internal stuff in the 1.13 is different from all other MC-Versions.

However, we are working on this issue and we will be releasing a fixed version soon.

Until then you could try to use a different minecraft-version until then.

Regards,
Leonhard from MineAcademy

**Comment by lackoSK** [comment]
Hey,

It will be fixed in the next update of the plugin, which will be out SOON!

Thank you guys for reporting it!

**Comment by XxCoolGamesxX** [comment]
Error is back again in ChatControl 8.5.4 for 1.13.2.

```log
------------------------------------[ 12.01.2020 20:41:40 ]-----------------------------------
ChatControl 8.5.4 encountered a NoSuchMethodException
Running Paper 1.13.2-R0.1-SNAPSHOT and Java 1.8.0_231
Plugins: LuckPerms v5.0.21, BuycraftX v12.0.6, Vault v1.7.2-b107, ProtocolSupport v4.29-dev, Essentials v2.17.1.50, EssentialsProtect v2.17.1.50, EssentialsChat v2.17.1.50, ViaVersion v3.0.0-SNAPSHOT, EssentialsSpawn v2.17.1.50, ViaBackwards v3.0.0-SNAPSHOT, ProtocolLib v4.5.0, ViaRewind v1.5.0-SNAPSHOT, ChatControl v8.5.4
----------------------------------------------------------------------------------------------

More Information: 
REGISTRY_GET_INVERSE could not find method 'b' in 'class net.minecraft.server.v1_13_R2.RegistryMaterials'
NoSuchMethodException net.minecraft.server.v1_13_R2.RegistryMaterials.b(java.lang.Object)
	 at java.lang.Class.getMethod(Unknown Source)
	 at org.mineacademy.chatcontrol.final.nul. .Com8.<init>(SourceFile:123)
	 at org.mineacademy.chatcontrol.final.nul. .Com8.<clinit>(SourceFile:97)
	 at org.mineacademy.chatcontrol.final.nul. .cOm6.const(SourceFile:73)
	 at org.mineacademy.chatcontrol.final.nul. .LPT7.const(SourceFile:61)
	 at org.mineacademy.chatcontrol.final.nul. .lPT1.<clinit>(SourceFile:213)
	 at org.mineacademy.chatcontrol.final.nul. .CoN.private(SourceFile:281)
	 at org.mineacademy.chatcontrol.final.nul. .a.native(SourceFile:220)
	 at org.mineacademy.chatcontrol.final.nul. .lpT2.const(SourceFile:39)
	 at org.mineacademy.chatcontrol.final.nul. .a.const(SourceFile:80)
	 at org.mineacademy.chatcontrol.final.nul. .Com1.onEnable(SourceFile:253)
	 at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265)
	 at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:334)
	 at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412)
	 at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:443)
	 at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:357)
----------------------------------------------------------------------------------------------
```
