### ISSUE TITLE
Reload Error.

### ISSUE THREAD

**Issue by IsThrill** [kangarko/ChatControl-Pro#1516]
Hey there, so recently I've purchased this plugin not to long ago, but every time I modified the configuration file and try to reload the plugin it prompts me with this error. Any further information would be greatly appreciated.

> [14:40:30 INFO]: !-----------------------------------------------------!
> [14:40:30 INFO]: Error reloading ChatControl 8.5.2
> [14:40:30 INFO]: !-----------------------------------------------------!
> [14:40:30 INFO]: ChatControl 8.5.2 encountered an IllegalPluginAccessException! Please check your error.log and report this issue with the information in that file.
> [14:40:30 INFO]: ______________________________________________________________
> [14:40:30 WARN]: org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register class org.bukkit.event.player.AsyncPlayerChatEvent while not enabled
> [14:40:30 WARN]: at org.bukkit.plugin.SimplePluginManager.registerEvent(SimplePluginManager.java:577)
> [14:40:30 WARN]: at org.mineacademy.chatcontrol.final.nul. .LPt5.native(SourceFile:172)
> [14:40:30 WARN]: at org.mineacademy.chatcontrol.final.nul. .cOn.const(SourceFile:63)
> [14:40:30 WARN]: at org.mineacademy.chatcontrol.final.nul. .Com1.const(SourceFile:832)
> [14:40:30 WARN]: at org.mineacademy.chatcontrol.ChatControl.protected(SourceFile:273)
> [14:40:30 WARN]: at org.mineacademy.chatcontrol.final.nul. .Com1.break(SourceFile:744)
> [14:40:30 WARN]: at org.mineacademy.chatcontrol.final.nul. .short.const(SourceFile:554)
> [14:40:30 WARN]: at org.mineacademy.chatcontrol.final.nul. .LPt8.execute(SourceFile:322)
> [14:40:30 WARN]: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:146)
> [14:40:30 WARN]: at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:666)
> [14:40:30 WARN]: at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1189)
> [14:40:30 WARN]: at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1001)
> [14:40:30 WARN]: at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
> [14:40:30 WARN]: at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
> [14:40:30 WARN]: at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
> [14:40:30 WARN]: at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> [14:40:30 WARN]: at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> [14:40:30 WARN]: at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
> [14:40:30 WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774)
> [14:40:30 WARN]: at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378)
> [14:40:30 WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713)
> [14:40:30 WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616)
> [14:40:30 WARN]: at java.lang.Thread.run(Thread.java:748)

**Comment by IsThrill** [comment]
After looking further into the issue, I had realized how stupid I was due to the lack of sleep I've been getting and it had been further resolved.
