### ISSUE TITLE
Error tingy

### ISSUE THREAD

**Issue by LogGits** [kangarko/ChatControl-Pro#1527]
Error thingy majiggy ChatControl 8.5.4 paper 1.15.1 build 51
```
[09:17:02] [Async Chat Thread - #125/INFO]: ChatControl 8.5.4 encountered a cOm2! Please check your error.log and report this issue with the information in that file.
[09:17:02] [Async Chat Thread - #126/INFO]: ChatControl 8.5.4 encountered a cOm2! Please check your error.log and report this issue with the information in that file.
[09:17:02] [Async Chat Thread - #126/ERROR]: Could not pass event AsyncPlayerChatEvent to ChatControl v8.5.4
org.mineacademy.chatcontrol.final.nul. .cOm2: Report / Head out of bounds! Max data size for BROADCAST_JSON_WITH_PERMISSION_AS is 3! (Set Debug to [bungee] in settings.yml and report this issue along with the new console messages
	at org.mineacademy.chatcontrol.final.nul. .lPt2.const(SourceFile:78) ~[?:?]
	at org.mineacademy.chatcontrol.final.nul. .lPT4.const(SourceFile:206) ~[?:?]
	at org.mineacademy.chatcontrol.final.nul. .lPT4.const(SourceFile:108) ~[?:?]
	at org.mineacademy.chatcontrol.final.nul. .lPT4.const(SourceFile:47) ~[?:?]
	at org.mineacademy.chatcontrol.final.nul. .K.native(SourceFile:116) ~[?:?]
	at org.mineacademy.chatcontrol.final.nul. .K.const(SourceFile:41) ~[?:?]
	at org.mineacademy.chatcontrol.final.nul. .an.const(SourceFile:179) ~[?:?]
	at org.mineacademy.chatcontrol.final.nul. .x.const(SourceFile:85) ~[?:?]
	at org.mineacademy.chatcontrol.final.nul. .x.const(SourceFile:39) ~[?:?]
	at org.mineacademy.chatcontrol.final.nul. .LPt5.execute(SourceFile:77) ~[?:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.15.1.jar:git-Paper-51]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.1.jar:git-Paper-51]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.15.1.jar:git-Paper-51]
	at net.minecraft.server.v1_15_R1.PlayerConnection.chat(PlayerConnection.java:1733) ~[?:git-Paper-51]
	at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1648) ~[?:git-Paper-51]
	at net.minecraft.server.v1_15_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:41) ~[patched_1.15.1.jar:git-Paper-51]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_201]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_201]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_201]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_201]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
[09:17:02] [Async Chat Thread - #125/ERROR]: Could not pass event AsyncPlayerChatEvent to ChatControl v8.5.4
org.mineacademy.chatcontrol.final.nul. .cOm2: Report / Head out of bounds! Max data size for BROADCAST_JSON_WITH_PERMISSION_AS is 3! (Set Debug to [bungee] in settings.yml and report this issue along with the new console messages
	at org.mineacademy.chatcontrol.final.nul. .lPt2.const(SourceFile:78) ~[?:?]
	at org.mineacademy.chatcontrol.final.nul. .lPT4.const(SourceFile:206) ~[?:?]
	at org.mineacademy.chatcontrol.final.nul. .lPT4.const(SourceFile:108) ~[?:?]
	at org.mineacademy.chatcontrol.final.nul. .lPT4.const(SourceFile:47) ~[?:?]
	at org.mineacademy.chatcontrol.final.nul. .K.native(SourceFile:116) ~[?:?]
	at org.mineacademy.chatcontrol.final.nul. .K.const(SourceFile:41) ~[?:?]
	at org.mineacademy.chatcontrol.final.nul. .an.const(SourceFile:179) ~[?:?]
	at org.mineacademy.chatcontrol.final.nul. .x.const(SourceFile:85) ~[?:?]
	at org.mineacademy.chatcontrol.final.nul. .x.const(SourceFile:39) ~[?:?]
	at org.mineacademy.chatcontrol.final.nul. .LPt5.execute(SourceFile:77) ~[?:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.15.1.jar:git-Paper-51]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.1.jar:git-Paper-51]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.15.1.jar:git-Paper-51]
	at net.minecraft.server.v1_15_R1.PlayerConnection.chat(PlayerConnection.java:1733) ~[?:git-Paper-51]
	at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1648) ~[?:git-Paper-51]
	at net.minecraft.server.v1_15_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:41) ~[patched_1.15.1.jar:git-Paper-51]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_201]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_201]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_201]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_201]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
```

**Comment by lackoSK** [comment]
Hey,

Set Debug to [bungee] in settings.yml and report this issue along with the new console messages

Can you do it? 

Thanks!

**Comment by LogGits** [comment]
Please reopen this. I am getting this issue on 8.6.6:
```
ChatControl 8.6.6 encountered a bM! Please check your error.log and report this issue with the information in that file.
ERROR 14:28:21
Could not pass event AsyncPlayerChatEvent to ChatControl v8.6.6
Console 14:28:21
org.mineacademy.chatcontrol.final.nul. .bM: Report / Head out of bounds! Max data size for BROADCAST_JSON_WITH_PERMISSION_AS is 3! (Set Debug to [bungee] in settings.yml and report this issue along with the new console messages
at org.mineacademy.chatcontrol.final.nul. .aX.a(SourceFile:78) ~[?:?]
at org.mineacademy.chatcontrol.final.nul. .aA.a(SourceFile:206) ~[?:?]
at org.mineacademy.chatcontrol.final.nul. .aA.a(SourceFile:108) ~[?:?]
at org.mineacademy.chatcontrol.final.nul. .aA.a(SourceFile:47) ~[?:?]
at org.mineacademy.chatcontrol.final.nul. .V.b(SourceFile:116) ~[?:?]
at org.mineacademy.chatcontrol.final.nul. .V.a(SourceFile:41) ~[?:?]
at org.mineacademy.chatcontrol.final.nul. .ay.a(SourceFile:172) ~[?:?]
at org.mineacademy.chatcontrol.final.nul. .I.a(SourceFile:85) ~[?:?]
at org.mineacademy.chatcontrol.final.nul. .I.a(SourceFile:39) ~[?:?]
at org.mineacademy.chatcontrol.final.nul. .bJ.execute(SourceFile:77) ~[?:?]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.15.2.jar:git-Paper-132]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-132]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:559) ~[patched_1.15.2.jar:git-Paper-132]
at net.minecraft.server.v1_15_R1.PlayerConnection.chat(PlayerConnection.java:1738) ~[?:git-Paper-132]
at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1653) ~[?:git-Paper-132]
at net.minecraft.server.v1_15_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:41) ~[patched_1.15.2.jar:git-Paper-132]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_201]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_201]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_201]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_201]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
```
```
------------------------------------[ 04.04.2020 00:28:21 ]-----------------------------------
ChatControl 8.6.6 encountered a bM
Running Paper 1.15.2-R0.1-SNAPSHOT and Java 1.8.0_201
----------------------------------------------------------------------------------------------

More Information: 
Head out of bounds! Max data size for BROADCAST_JSON_WITH_PERMISSION_AS is 3! (Set Debug to [bungee] in settings.yml and report this issue along with the new console messages
bM Report / Head out of bounds! Max data size for BROADCAST_JSON_WITH_PERMISSION_AS is 3! (Set Debug to [bungee] in settings.yml and report this issue along with the new console messages
	 at org.mineacademy.chatcontrol.final.nul. .aX.a(SourceFile:78)
	 at org.mineacademy.chatcontrol.final.nul. .aA.a(SourceFile:206)
	 at org.mineacademy.chatcontrol.final.nul. .aA.a(SourceFile:108)
	 at org.mineacademy.chatcontrol.final.nul. .aA.a(SourceFile:47)
	 at org.mineacademy.chatcontrol.final.nul. .V.b(SourceFile:116)
	 at org.mineacademy.chatcontrol.final.nul. .V.a(SourceFile:41)
	 at org.mineacademy.chatcontrol.final.nul. .ay.a(SourceFile:172)
	 at org.mineacademy.chatcontrol.final.nul. .I.a(SourceFile:85)
	 at org.mineacademy.chatcontrol.final.nul. .I.a(SourceFile:39)
	 at org.mineacademy.chatcontrol.final.nul. .bJ.execute(SourceFile:77)
	 at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
	 at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
	 at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:559)
----------------------------------------------------------------------------------------------
```

**Comment by lackoSK** [comment]
Hey,

Set Debug to [bungee] in settings.yml and report this issue along with the new console messages

Can you do it?

Thanks!

**Comment by LogGits** [comment]
I cant that floods console and would make debugging even harder for me. Why is this even being called for a regular chat. Foundation suggests:
```java
/**
* Broadcast a json message to every player with permission as a sender.
*/
BROADCAST_JSON_WITH_PERMISSION_AS("sender", "permission", "message"),
```
This issue happens so randomly (maybe once every couple days)

**Comment by lackoSK** [comment]
Hmm, anyways, we need that
