### ISSUE TITLE
paper build 62 thinks java is the wrong version now -- all builds of 1.15.2

### ISSUE THREAD

**Issue by mrcoffee1026** [kangarko/ChatControl-Pro#1531]
I get this on startup in paper build 62:

```
[13:45:09] [Async Chat Thread - #0/INFO]: !-----------------------------------------------------!
[13:45:09] [Async Chat Thread - #0/INFO]: JavaScript placeholders will not function!
[13:45:09] [Async Chat Thread - #0/INFO]:   
[13:45:09] [Async Chat Thread - #0/INFO]: Your Java version/distribution lacks
[13:45:09] [Async Chat Thread - #0/INFO]: the Nashorn library for JavaScript
[13:45:09] [Async Chat Thread - #0/INFO]: placeholders. Unfortunately this plugin
[13:45:09] [Async Chat Thread - #0/INFO]: relies heavily on Nashorn and cannot
[13:45:09] [Async Chat Thread - #0/INFO]: continue. Please install Oracle Java 8.
[13:45:09] [Async Chat Thread - #0/INFO]: Plugin is now disabled.
[13:45:09] [Async Chat Thread - #0/INFO]: !-----------------------------------------------------!
[13:45:09] [Async Chat Thread - #0/INFO]: [ChatControl] Disabling ChatControl v8.5.4
[13:45:09] [Async Chat Thread - #0/INFO]: Saving player data to MySQL..
[13:45:09] [Async Chat Thread - #0/INFO]: !-----------------------------------------------------!
[13:45:09] [Async Chat Thread - #0/INFO]: Failed to replace a custom variable!
[13:45:09] [Async Chat Thread - #0/INFO]: Message: *-----* {player} *-----*
[13:45:09] [Async Chat Thread - #0/INFO]: Prefix: {pl_prefix}{javascript_hiddenrank}
[13:45:09] [Async Chat Thread - #0/INFO]: Jobs: {javascript_jobsprefix}
[13:45:09] [Async Chat Thread - #0/INFO]: Ping: {ping}
[13:45:09] [Async Chat Thread - #0/INFO]: Variable: {ping}
[13:45:09] [Async Chat Thread - #0/INFO]: NullPointerException
[13:45:09] [Async Chat Thread - #0/INFO]: !-----------------------------------------------------!
[13:45:09] [Async Chat Thread - #0/INFO]: ChatControl 8.5.4 encountered a NullPointerException! Please check your error.log and report this issue with the information in that file.
[13:45:09] [Async Chat Thread - #0/INFO]: ChatControl 8.5.4 encountered a NullPointerException! Please check your error.log and report this issue with the information in that file.
[13:45:09] [Async Chat Thread - #0/INFO]: java.lang.NullPointerException
[13:45:09] [Async Chat Thread - #0/INFO]: at org.mineacademy.chatcontrol.lib.fo.model.Lpt3.const(SourceFile:114)
[13:45:09] [Async Chat Thread - #0/INFO]: at org.mineacademy.chatcontrol.lib.fo.model.COM9.const(SourceFile:590)
[13:45:09] [Async Chat Thread - #0/INFO]: at org.mineacademy.chatcontrol.lib.fo.model.LPT6.native(SourceFile:300)
[13:45:09] [Async Chat Thread - #0/INFO]: at org.mineacademy.chatcontrol.lib.fo.model.LPT6.const(SourceFile:265)
[13:45:09] [Async Chat Thread - #0/INFO]: at org.mineacademy.chatcontrol.final.nul. .H.native(SourceFile:386)
[13:45:09] [Async Chat Thread - #0/INFO]: at org.mineacademy.chatcontrol.final.nul. .G.const(SourceFile:431)
[13:45:09] [Async Chat Thread - #0/INFO]: at org.mineacademy.chatcontrol.final.nul. .L.const(SourceFile:98)
[13:45:09] [Async Chat Thread - #0/INFO]: at org.mineacademy.chatcontrol.final.nul. .L.const(SourceFile:42)
[13:45:09] [Async Chat Thread - #0/INFO]: at org.mineacademy.chatcontrol.final.nul. .N.sendMessage(SourceFile:221)
[13:45:09] [Async Chat Thread - #0/INFO]: at org.mineacademy.chatcontrol.final.nul. .N.sendMessage(SourceFile:176)
[13:45:09] [Async Chat Thread - #0/INFO]: at org.mineacademy.chatcontrol.final.nul. .N.sendMessage(SourceFile:171)
[13:45:09] [Async Chat Thread - #0/INFO]: at org.mineacademy.chatcontrol.final.nul. .w.const(SourceFile:68)
[13:45:09] [Async Chat Thread - #0/INFO]: at org.mineacademy.chatcontrol.final.nul. .w.const(SourceFile:19)
[13:45:09] [Async Chat Thread - #0/INFO]: at org.mineacademy.chatcontrol.final.nul. .LPt5.execute(SourceFile:77)
[13:45:09] [Async Chat Thread - #0/INFO]: at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
[13:45:09] [Async Chat Thread - #0/INFO]: at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[13:45:09] [Async Chat Thread - #0/INFO]: at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545)
[13:45:09] [Async Chat Thread - #0/INFO]: at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[13:45:09] [Async Chat Thread - #0/INFO]: at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[13:45:09] [Async Chat Thread - #0/INFO]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[13:45:09] [Async Chat Thread - #0/INFO]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[13:45:09] [Async Chat Thread - #0/INFO]: at java.lang.Thread.run(Thread.java:748)
[13:45:09] [Async Chat Thread - #0/INFO]: !-----------------------------------------------------!

```

Issue is resolved by using build 60 instead for now.

**Comment by Busted11290** [comment]
Same issue, https://pastebin.com/J5hUrYSc

Same resolution for now, use build 60.

**Comment by mrcoffee1026** [comment]
I didn't do excessive testing but didn't see this error anymore when attempting build 65 (1.15.2), so I guess don't worry about it.

**Comment by espen96** [comment]
I do see it on 1.15.2 (build 65)  however

**Comment by mrcoffee1026** [comment]
actually attempting 1.15.2 and actually using the plugin, it fails to work properly, just errors and crashes if any messages are sent.

**Comment by mrcoffee1026** [comment]
first level console error in 1.15.2 when (I'm assuming anyone) tries to chat:
https://pastebin.com/BvEdvau1
just before they are disconnected.

What shows up in the log it suggests looking at:
https://pastebin.com/GYgcTcpe

**Comment by lackoSK** [comment]
Hey guys,

Apologies the late reply,

We will update our Foundation library to support 1.15.2 tomorrow. 

Thank you guys for being patient. 

Thanks! 

King Regards,
lackoSK

**Comment by TNTUP** [comment]
Current ChatControl 8.5.4 works fine on Paper 1.15.2 build 71. I must be lucky

**Comment by mrcoffee1026** [comment]
i think if you can somehow skip using all placeholders, it would still work.

**Comment by kangarko** [comment]
We are investigating this issue. In the meanwhile, we edited the next release to boot up and run and replace all placeholders except JavaScript ones until this is solved.

**Comment by lackoSK** [comment]
Hello,

Thank you for reporting the issue.

It is fixed in the newest version of ChatControl ^^

Regards,
lackoSK

**Comment by mrcoffee1026** [comment]
This is still broken:
https://pastebin.com/ucLbHuw7

**Comment by mrcoffee1026** [comment]
the error.log it refers to:
https://pastebin.com/DG2fb5Rm

**Comment by lackoSK** [comment]
Thanks,

We will try to fix it.

Regards,
lackoSK

**Comment by kangarko** [comment]
We are aware of this issue and you can find more info here https://github.com/walterhiggins/ScriptCraft/issues/423

@mrcoffee1026 I need the following information

- What is your Java distribution? Your error log says you have Java 8 but do you run the official from Oracle or another such as OpenJDK?
- Please send me your javascript.txt file

**Comment by kangarko** [comment]
I made a small plugin to list your system's properties. Please install and send me the data from LISTING ALL SYSTEM PROPERTIES till it says LISTING END. Since some of it may be sensitive you can send it over to matej@matejpacan.com

[PropertyLister.zip](https://github.com/kangarko/ChatControl-Pro/files/4176640/PropertyLister.zip)

**Comment by mrcoffee1026** [comment]
openjdk i can answer that immediately, 
but the propertylister thing i may need a moment on.  
[javascript.txt](https://github.com/kangarko/ChatControl-Pro/files/4177022/javascript.txt)

**Comment by mrcoffee1026** [comment]
You'll also need this the commented out lines are the ones being affected:
[formatting.zip](https://github.com/kangarko/ChatControl-Pro/files/4177034/formatting.zip)

**Comment by mrcoffee1026** [comment]
where does this plugin actually put the data?  it doesn't seem to have any commands and creates no plugin folder.  If it has put it somewhere, I don't know where it put it.

**Comment by mrcoffee1026** [comment]
nevermind

**Comment by lackoSK** [comment]
> where does this plugin actually put the data? it doesn't seem to have any commands and creates no plugin folder. If it has put it somewhere, I don't know where it put it.

/plugins/ChatControl/.. ?

**Comment by mrcoffee1026** [comment]
no it puts in the startup log

**Comment by lackoSK** [comment]
Ah, you meant that plugin. It just writes to console. So yah /logs/lastest.lag

**Comment by mrcoffee1026** [comment]
you undo the fix you provided me in build 8.6.2

**Comment by kangarko** [comment]
@mrcoffee1026 can you please clarify what exact problem are you facing right now? I remember you emailed me that you have now been able to boot the plugin up with the "Nashorn" javascript engine

**Comment by mrcoffee1026** [comment]
nothing changed on my end, the last build of 8.6.1 replaced the variables... the new 8.6.2 version no longer replaces the variables: instead errors to console and so all chat is disabled.

**Comment by lackoSK** [comment]
Okay, 

It seems like I've fixed it: 
![image](https://user-images.githubusercontent.com/53174757/74760987-8ab82380-527b-11ea-800f-119e9d35a81d.png)

Thank you for your patience. 

PS: Ping is 0 because of the localhost :-) 
PS2: Wait until 8.6.3 released 

Regards,
lackoSK

**Comment by mrcoffee1026** [comment]
Seems to be working for all but placeholder api variables.  Any way you can get those working too?

**Comment by lackoSK** [comment]
Have you downloaded PlaceholderAPI extension?

**Comment by mrcoffee1026** [comment]
i'm not sure what you're asking here.  I have the PlaceHolderAPI plugin, several expansions off the ecloud which provides additional variables... they were working in the custom version provided but are not now in the latest 8.6.3 that I attempted.  I'm not sure what else you could be referring to though.

**Comment by mrcoffee1026** [comment]
nevermind had something to do with getting the extensions enabled on my local version.  seems to be working.

**Comment by lackoSK** [comment]
Awesome!
