### ISSUE TITLE
Error on ChatControl 8.5.6 - 1.13.2

### ISSUE THREAD

**Issue by XxCoolGamesxX** [kangarko/ChatControl-Pro#1539]
Error is back again in ChatControl 8.5.6 for 1.13.2.

```
------------------------------------[ 26.01.2020 15:13:26 ]-----------------------------------
ChatControl 8.5.6 encountered a NoSuchMethodException
Running Paper 1.13.2-R0.1-SNAPSHOT and Java 1.8.0_241
Plugins: LuckPerms v5.0.21, WorldEdit v7.1.0-SNAPSHOT;4822-a27ade5, ViaVersion v3.0.0-SNAPSHOT, BuycraftX v12.0.6, Vault v1.7.2-b107, ViaBackwards v3.0.0-SNAPSHOT, ProtocolLib v4.5.1-SNAPSHOT-b445, ViaRewind v1.5.0-SNAPSHOT, Essentials v2.17.1.53, EssentialsProtect v2.17.1.53, EssentialsChat v2.17.1.53, ViaRewind-Legacy-Support v1.3.2, ChatControl v8.5.6, EssentialsSpawn v2.17.1.53
----------------------------------------------------------------------------------------------

More Information: 
REGISTRY_GET_INVERSE could not find method 'b' in 'class net.minecraft.server.v1_13_R2.RegistryMaterials'
NoSuchMethodException net.minecraft.server.v1_13_R2.RegistryMaterials.b(java.lang.Object)
	 at java.lang.Class.getMethod(Unknown Source)
	 at org.mineacademy.chatcontrol.final.nul. .T.<init>(SourceFile:121)
	 at org.mineacademy.chatcontrol.final.nul. .T.<clinit>(SourceFile:96)
	 at org.mineacademy.chatcontrol.final.nul. .E.const(SourceFile:73)
	 at org.mineacademy.chatcontrol.final.nul. .x.const(SourceFile:61)
	 at org.mineacademy.chatcontrol.final.nul. .r.<clinit>(SourceFile:213)
	 at org.mineacademy.chatcontrol.final.nul. .Y.private(SourceFile:281)
	 at org.mineacademy.chatcontrol.final.nul. .aa.dk(SourceFile:220)
	 at org.mineacademy.chatcontrol.final.nul. .X.const(SourceFile:39)
	 at org.mineacademy.chatcontrol.final.nul. .aa.const(SourceFile:80)
	 at org.mineacademy.chatcontrol.final.nul. .CoM2.onEnable(SourceFile:253)
	 at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265)
	 at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:334)
	 at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412)
	 at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:443)
	 at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:357)
----------------------------------------------------------------------------------------------
```

**Comment by lackoSK** [comment]
Hello,

Thank you for reporting it. 

I've fixed it, you will be able to download it **soon**.

Regards,
lackoSK

**Comment by Haveyougonemad** [comment]
KK
