### ISSUE TITLE
Chat control not showing up in /plugins

### ISSUE THREAD

**Issue by WheatLoaf** [kangarko/ChatControl-Pro#154]
Hi I started up my server and did /plugins to find chat control and it doesn't show. I'm currently using spigot 1.11.2.Here are some console messages of chat control.
[21:59:21] [Server thread/ERROR]: Could not load 'plugins/ChatControl.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: me/kangarko/chatcontrol/ChatControl : Unsupported major.minor version 52.0
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:133) ~[Spigot%201.11.2.jar:git-Spigot-6de2fbc-c1aa859]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[Spigot%201.11.2.jar:git-Spigot-6de2fbc-c1aa859]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [Spigot%201.11.2.jar:git-Spigot-6de2fbc-c1aa859]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.loadPlugins(CraftServer.java:301) [Spigot%201.11.2.jar:git-Spigot-6de2fbc-c1aa859]
	at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:204) [Spigot%201.11.2.jar:git-Spigot-6de2fbc-c1aa859]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:542) [Spigot%201.11.2.jar:git-Spigot-6de2fbc-c1aa859]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_121]
Caused by: java.lang.UnsupportedClassVersionError: me/kangarko/chatcontrol/ChatControl : Unsupported major.minor version 52.0

**Comment by kangarko** [comment]
Hey, you need to be running Java 8 to run the versions above 7.1.x. Either use 7.0.x or upgrade your java.
