### ISSUE TITLE
Not Looding HElp me

### ISSUE THREAD

**Issue by Haveyougonemad** [kangarko/ChatControl-Pro#1550]
[14:56:54 ERROR]: Could not load 'plugins/ChatControl.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.ClassFormatError: JVMCFRE068 class name is invalid; class=me/kangarko/chatcontrol/ChatControl, offset=0
at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:133) ~[server.jar:git-Spigot-dcd1643-e60fc34]
at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:327) ~[server.jar:git-Spigot-dcd1643-e60fc34]
at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:248) [server.jar:git-Spigot-dcd1643-e60fc34]
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:305) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:205) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [server.jar:git-Spigot-dcd1643-e60fc34]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_232]
Caused by: java.lang.ClassFormatError: JVMCFRE068 class name is invalid; class=me/kangarko/chatcontrol/ChatControl, offset=0
at java.lang.ClassLoader.defineClassImpl(Native Method) ~[?:1.8.0_232]
at java.lang.ClassLoader.defineClassInternal(Unknown Source) ~[?:1.8.0_232]
at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_232]
at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_232]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:148) ~[server.jar:git-Spigot-dcd1643-e60fc34]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[server.jar:git-Spigot-dcd1643-e60fc34]
at java.lang.ClassLoader.loadClassHelper(Unknown Source) ~[?:1.8.0_232]
at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_232]
at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_232]
at java.lang.Class.forNameImpl(Native Method) ~[?:1.8.0_232]
at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_232]
at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:78) ~[server.jar:git-Spigot-dcd1643-e60fc34]
at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[server.jar:git-Spigot-dcd1643-e60fc34]
... 6 more

**Comment by lackoSK** [comment]
#1551
