### ISSUE TITLE
This error has been happening many many versions now. Fix it please.

### ISSUE THREAD

**Issue by LucidAPs** [kangarko/ChatControl-Pro#1552]
>.... [15:19:50 ERROR]: Could not pass event AsyncPlayerChatEvent to ChatControl v8.6.0
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
at java.lang.String.substring(String.java:1967) ~[?:1.8.0_212]
at org.mineacademy.chatcontrol.final.nul. .prn.const(SourceFile:81) ~[?:?]
at org.mineacademy.chatcontrol.final.nul. .com8.const(SourceFile:33) ~[?:?]
at org.mineacademy.chatcontrol.final.nul. .com8.const(SourceFile:13) ~[?:?]
at org.mineacademy.chatcontrol.final.nul. .Lpt4.execute(SourceFile:77) ~[?:?]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.15.2.jar:git-Paper-90]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-90]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:559) ~[patched_1.15.2.jar:git-Paper-90]
at net.minecraft.server.v1_15_R1.PlayerConnection.chat(PlayerConnection.java:1733) ~[?:git-Paper-90]
at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1648) ~[?:git-Paper-90]
at net.minecraft.server.v1_15_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:41) ~[patched_1.15.2.jar:git-Paper-90]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_212]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_212]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

**Comment by lackoSK** [comment]
Hello,

Please send us your ChatControl's folder. 

Thanks 
lackoSK

**Comment by HexedHero** [comment]
Related to #1521

**Comment by lackoSK** [comment]
Hi,

Can you give me steps, how can I reproduce it? Also, give us your ChatControl's folder.

Thanks,
lackoSK

**Comment by lackoSK** [comment]
Can you do it, please?
