### ISSUE TITLE
Error on startup, Paper-MC 1.15.2 v75 and CC v8.6.1 and 8.6.2

### ISSUE THREAD

**Issue by sean-perryman** [kangarko/ChatControl-Pro#1573]
!-----------------------------------------------------!
[13:20:46 INFO]: JavaScript placeholders will not function!
[13:20:46 INFO]:   
[13:20:46 INFO]: Your Java version/distribution lacks
[13:20:46 INFO]: the Nashorn library for JavaScript
[13:20:46 INFO]: placeholders. Ensure you have Oracle
[13:20:46 INFO]: Java 8.
[13:20:46 INFO]: !-----------------------------------------------------!
[13:20:46 WARN]: [ChatControl] Task #391 for ChatControl v8.6.1 generated an exception
java.lang.NullPointerException: null
        at org.mineacademy.chatcontrol.final.nul. .lPt6.throw(SourceFile:155) ~[?:?]
        at org.mineacademy.chatcontrol.final.nul. .lPt6.const(SourceFile:75) ~[?:?]
        at org.mineacademy.chatcontrol.final.nul. .lPT5.protected(SourceFile:102) ~[?:?]
        at org.mineacademy.chatcontrol.final.nul. .lPT5.const(SourceFile:83) ~[?:?]
        at org.mineacademy.chatcontrol.final.nul. .lPT5.strictfp(SourceFile:69) ~[?:?]
        at org.mineacademy.chatcontrol.final.nul. .lpT1.const(SourceFile:223) ~[?:?]
        at org.mineacademy.chatcontrol.final.nul. .lpT1.const(SourceFile:210) ~[?:?]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-Paper-75]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.15.2.jar:git-Paper-75]
        at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1185) ~[patched_1.15.2.jar:git-Paper-75]
        at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:423) ~[patched_1.15.2.jar:git-Paper-75]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1112) ~[patched_1.15.2.jar:git-Paper-75]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934) ~[patched_1.15.2.jar:git-Paper-75]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]

Is this something to worry about?

**Comment by sean-perryman** [comment]
I also think this is contributing to my use of {pl_prefix+} not working currently. I removed OpenJDK and installed Oracle JRE as the file specified, but it is still telling me it isn't right. 

# java -version
java version "1.8.0_241"
Java(TM) SE Runtime Environment (build 1.8.0_241-b07)
Java HotSpot(TM) 64-Bit Server VM (build 25.241-b07, mixed mode)

**Comment by sean-perryman** [comment]
Just tried updating to Paper 105 (newest as of this writing) and CC 8.6.2 and the issue persists.

**Comment by lackoSK** [comment]
Hi, 

This is fixed in 8.6.3 you can download it.

Best,
lackoSK
