### ISSUE TITLE
If both Admin Chat and Bungee Chat shortcuts are set to '', ChatControl breaks.

### ISSUE THREAD

**Issue by mibby** [kangarko/ChatControl-Pro#1582]
Can't have both Admin Chat and Bungee Chat shortcuts be "unset" with ``''`` in the config. Setting it to ``none`` seems to work however. Setting any shortcut also fixes the error, such as ``'!'``, but I couldn't actually get the shortcut to work for admin chat.

```
Admin_Chat.Shortcut cannot equal Bungee_Chat.Shortcut in settings.yml!
COm6 Report / Admin_Chat.Shortcut cannot equal Bungee_Chat.Shortcut in settings.yml!
	 at org.mineacademy.chatcontrol.final.nul. .con$short.init(SourceFile:126)
	 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	 at java.lang.reflect.Method.invoke(Method.java:498)
	 at org.mineacademy.chatcontrol.final.nul. .ad.native(SourceFile:182)
	 at org.mineacademy.chatcontrol.final.nul. .ad.const(SourceFile:155)
	 at org.mineacademy.chatcontrol.final.nul. .ad.class(SourceFile:134)
	 at org.mineacademy.chatcontrol.final.nul. .ad$1.a_(SourceFile:56)
	 at org.mineacademy.chatcontrol.final.nul. .ab.private(SourceFile:295)
	 at org.mineacademy.chatcontrol.final.nul. .ad.dk(SourceFile:220)
	 at org.mineacademy.chatcontrol.final.nul. .con.const(SourceFile:20)
	 at org.mineacademy.chatcontrol.final.nul. .ad.const(SourceFile:80)
	 at org.mineacademy.chatcontrol.final.nul. .CoN.onEnable(SourceFile:253)
	 at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
	 at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
	 at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:435)
	 at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:470)
	 at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:384)
```

**Comment by lackoSK** [comment]
Your settings please

**Comment by mibby** [comment]
```
Admin_Chat:
  Bungee: true
  Log_To_Console: true
  Write_To_File: true
  Discord_Channel: ''
  Shortcut: ''
Bungee_Chat:
  Enabled_By_Default: true
  Log_To_Console: true
  Write_To_File: false
  Discord_Channel: 'global'
  Shortcut: ''
```

**Comment by lackoSK** [comment]
It seems like you have two same shortcuts for the same chats. I am going to add a function to disable the shortcut feature.

Will it be this ok for you? Do you need it to be done in some other way?

**Comment by mibby** [comment]
That would be fine, or make it so ``''`` registers as empty / disabled instead of as a valid shortcut, thus breaking.

**Comment by lackoSK** [comment]
Okay, we can do so.

**Comment by lackoSK** [comment]
We are recoding ChatControl-Pro (only formatting) so will be added - in some time
