### ISSUE TITLE
Turning on channels gives NullPointerException

### ISSUE THREAD

**Issue by FrozenBeard** [kangarko/ChatControl-Pro#1585]
I turned on the Channels setting in ChatControl and it gives me a NullPointerException when I try and write.
```
------------------------------------[ 04.03.2020 17:38:36 ]-----------------------------------
ChatControl 8.6.5 encountered a NullPointerException
Running Paper 1.12.2-R0.1-SNAPSHOT and Java 11.0.6
Plugins: Removed
----------------------------------------------------------------------------------------------

More Information: 
Error sending channel message for GodsDead!
Channel: help
Message: Testing 2
Error: %error
NullPointerException (Unknown cause)
	 at org.mineacademy.chatcontrol.final.nul. .dz.a(SourceFile:557)
	 at org.mineacademy.chatcontrol.final.nul. .dz.sendMessage(SourceFile:210)
	 at org.mineacademy.chatcontrol.final.nul. .dz.sendMessage(SourceFile:166)
	 at org.mineacademy.chatcontrol.final.nul. .dz.sendMessage(SourceFile:161)
	 at org.mineacademy.chatcontrol.final.nul. .di.a(SourceFile:79)
	 at org.mineacademy.chatcontrol.final.nul. .di.a(SourceFile:20)
	 at org.mineacademy.chatcontrol.final.nul. .aI.execute(SourceFile:77)
	 at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74)
	 at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
	 at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513)
----------------------------------------------------------------------------------------------
```

**Comment by lackoSK** [comment]
Hi,

Thank you for reporting.

Was fixed in the latest version.

Regards,
lackoSK
