### ISSUE TITLE
 AsyncPlayerChatEvent player lost prefix in chat

### ISSUE THREAD

**Issue by WolverStones** [kangarko/ChatControl-Pro#1596]
`[22:07:13 ERROR]: Could not pass event AsyncPlayerChatEvent to ChatControl v8.6.6
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
at java.lang.String.substring(String.java:1967) ~[?:1.8.0_191]
at org.mineacademy.chatcontrol.final.nul. .ay.a(SourceFile:74) ~[?:?]
at org.mineacademy.chatcontrol.final.nul. .M.a(SourceFile:140) ~[?:?]
at org.mineacademy.chatcontrol.final.nul. .M.a(SourceFile:94) ~[?:?]
at org.mineacademy.chatcontrol.final.nul. .M.a(SourceFile:36) ~[?:?]
at org.mineacademy.chatcontrol.final.nul. .bJ.execute(SourceFile:77) ~[?:?]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.15.2.jar:git-Paper-137]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-137]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:559) ~[patched_1.15.2.jar:git-Paper-137]
at net.minecraft.server.v1_15_R1.PlayerConnection.chat(PlayerConnection.java:1738) ~[patched_1.15.2.jar:git-Paper-137]
at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1653) ~[patched_1.15.2.jar:git-Paper-137]
at net.minecraft.server.v1_15_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:41) ~[patched_1.15.2.jar:git-Paper-137]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_191]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_191]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
[22:07:13 INFO]: <[NT NM] Danielakiller286> co zbynda ?`

Server: git-Paper-135 (MC: 1.15.2)
ChatcontrolPro: 8.6.6
LuckPerms-Bukkit-5.0.88.jar
Vault-1.7.3.jar
PlaceholderAPI-2.10.4.jar

**Comment by MrMorganCz** [comment]
[ChatControl.zip](https://github.com/kangarko/ChatControl-Pro/files/4345924/ChatControl.zip)

**Comment by lackoSK** [comment]
Ahoj,

Niejaky popis kedy sa to stalo?

**Comment by MrMorganCz** [comment]
Stává se to poměrně často, co tomu předchází nemám tušení, objevu se to random v chatu.

[07:58:20] [Server thread/INFO]: [Boy] Plechy: 4
[07:58:25] [Server thread/INFO]: [Banned] tatrankacz: 1
[07:58:26] [Server thread/INFO]: [Boy] Plechy: 6
[07:58:31] [Server thread/INFO]: Nixium24 issued server command: /home
[07:58:39] [Server thread/INFO]: Nixium24 lost connection: Disconnected
[07:58:39] [Server thread/INFO]:   
[07:58:43] [Async Chat Thread - #7/ERROR]: Could not pass event AsyncPlayerChatEvent to ChatControl v8.6.6
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1967) ~[?:1.8.0_191]
	at org.mineacademy.chatcontrol.final.nul. .ay.a(SourceFile:74) ~[?:?]
	at org.mineacademy.chatcontrol.final.nul. .M.a(SourceFile:140) ~[?:?]
	at org.mineacademy.chatcontrol.final.nul. .M.a(SourceFile:94) ~[?:?]
	at org.mineacademy.chatcontrol.final.nul. .M.a(SourceFile:36) ~[?:?]
	at org.mineacademy.chatcontrol.final.nul. .bJ.execute(SourceFile:77) ~[?:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.15.2.jar:git-Paper-143]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-143]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:559) ~[patched_1.15.2.jar:git-Paper-143]
	at net.minecraft.server.v1_15_R1.PlayerConnection.chat(PlayerConnection.java:1738) ~[patched_1.15.2.jar:git-Paper-143]
	at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1653) ~[patched_1.15.2.jar:git-Paper-143]
	at net.minecraft.server.v1_15_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:41) ~[patched_1.15.2.jar:git-Paper-143]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_191]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
[07:58:43] [Server thread/INFO]: <[NT NM NC] tatrankacz> plechy co delas??
[07:58:43] [Craft Scheduler Thread - 787/INFO]: [BuycraftX] Fetching all due players...
[07:58:43] [Craft Scheduler Thread - 787/INFO]: [BuycraftX] Fetched due players (0 found).
[07:58:48] [Server thread/INFO]: [Boy] Plechy: ?

[09:56:05] [Server thread/INFO]: [MVP+] [Boss] Kokis07: :D
[09:56:05] [Server thread/INFO]: [HELPER] [Rich$] samuelovski1: Našel jsem dalšího griefera spawnu
[09:56:09] [Server thread/INFO]: [HELPER] [Rich$] samuelovski1: super
[09:56:11] [Server thread/INFO]: [VIP+] [Frosty] jenilakoss: :O
[09:56:24] [Async Chat Thread - #26/ERROR]: Could not pass event AsyncPlayerChatEvent to ChatControl v8.6.6
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1967) ~[?:1.8.0_191]
	at org.mineacademy.chatcontrol.final.nul. .ay.a(SourceFile:74) ~[?:?]
	at org.mineacademy.chatcontrol.final.nul. .M.a(SourceFile:140) ~[?:?]
	at org.mineacademy.chatcontrol.final.nul. .M.a(SourceFile:94) ~[?:?]
	at org.mineacademy.chatcontrol.final.nul. .M.a(SourceFile:36) ~[?:?]
	at org.mineacademy.chatcontrol.final.nul. .bJ.execute(SourceFile:77) ~[?:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.15.2.jar:git-Paper-143]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-143]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:559) ~[patched_1.15.2.jar:git-Paper-143]
	at net.minecraft.server.v1_15_R1.PlayerConnection.chat(PlayerConnection.java:1738) ~[patched_1.15.2.jar:git-Paper-143]
	at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1653) ~[patched_1.15.2.jar:git-Paper-143]
	at net.minecraft.server.v1_15_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:41) ~[patched_1.15.2.jar:git-Paper-143]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_191]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
[09:56:24] [Server thread/INFO]: <[NT NH NM] Plechy> pojd sem vilky
[09:56:26] [Server thread/INFO]: jenilakoss issued server command: /ah
[09:56:32] [Server thread/INFO]: [MVP+] [Boss] Kokis07: ze ja to včera dělal .. s tim tnt
[09:56:39] [Server thread/INFO]: samuelovski1 issued server command: /ban Adam99cz 7d Grief spawnu, zneužití bugu.

**Comment by lackoSK** [comment]
pastebin.com prosím

**Comment by MrMorganCz** [comment]
https://pastebin.com/WCDmh74q

**Comment by lackoSK** [comment]
Sorry, neviem to tam nájsť, prosil som o ten error, nie celý log.

**Comment by MrMorganCz** [comment]
https://pastebin.com/nBEE2f4U

**Comment by lackoSK** [comment]
Ahoj,

Sorry, za neskorú odpoveď,

Čo tam máte za Java verziu? 

S pozdravom,
lackoSK

**Comment by MrMorganCz** [comment]
Nedávno jsme přecházeli se servery na https://github.com/Spottedleaf/Tuinity takže se musela dát verze java 11 a větší. (od té doby jsem tento problém nezaznamenal.)

Ale v době kdy jsem to posílal tak byla na serveru Java SE 8u241.

**Comment by MrMorganCz** [comment]
Tak změna, objevil jsem to znovu https://pastebin.com/pqaAtKjP

**Comment by lackoSK** [comment]
daj si tam javu 8

**Comment by HexedHero** [comment]
Same issue, paper java 8. Doesn't seem like this is ever going to get fixed at this point. Been reported like at least 4 times.

**Comment by kangarko** [comment]
I apology for delays, I personally had a look and we changed some code lines to mitigate this. We will continue to test it and the next release should have the fix contained.

**Comment by lackoSK** [comment]
Hello,

These issues should be fixed within the next release of ChatControl-Pro.

If not, please open the issue again. 

Sincerely,
Ladislav from MineAcademy.org
