### ISSUE TITLE
ChatControl PRO

### ISSUE THREAD

**Issue by IonutMc2** [kangarko/ChatControl-Pro#1617]
[22:40:22] [Server thread/INFO]:   _____ _           _    _____            _             _  +
[22:40:22] [Server thread/INFO]:  / ____| |         | |  / ____|          | |           | |
[22:40:22] [Server thread/INFO]: | |    | |__   __ _| |_| |     ___  _ __ | |_ _ __ ___ | |
[22:40:22] [Server thread/INFO]: | |    | '_ \ / _` | __| |    / _ \| '_ \| __| '__/ _ \| |
[22:40:22] [Server thread/INFO]: | |____| | | | (_| | |_| |___| (_) | | | | |_| | | (_) | |
[22:40:22] [Server thread/INFO]:  \_____|_| |_|\__,_|\__|\_____\___/|_| |_|\__|_|  \___/|_|
[22:40:22] [Server thread/INFO]:   
[22:40:22] [Server thread/INFO]: ChatControl 8.6.6 encountered a NoSuchMethodException! Please check your error.log and report this issue with the information in that file.
[22:40:22] [Server thread/INFO]: java.lang.NoSuchMethodException: net.minecraft.server.v1_12_R1.TileEntity.create(net.minecraft.server.v1_12_R1.World, net.minecraft.server.v1_12_R1.NBTTagCompound)
[22:40:22] [Server thread/INFO]: at java.lang.Class.getMethod(Class.java:1786)
[22:40:22] [Server thread/INFO]: at org.mineacademy.chatcontrol.final.nul. .dC.<init>(SourceFile:118)
[22:40:22] [Server thread/INFO]: at org.mineacademy.chatcontrol.final.nul. .dC.<clinit>(SourceFile:77)
[22:40:22] [Server thread/INFO]: at org.mineacademy.chatcontrol.final.nul. .dn.a(SourceFile:73)
[22:40:22] [Server thread/INFO]: at org.mineacademy.chatcontrol.final.nul. .dg.a(SourceFile:62)
[22:40:22] [Server thread/INFO]: at org.mineacademy.chatcontrol.final.nul. .da.<clinit>(SourceFile:211)
[22:40:22] [Server thread/INFO]: at org.mineacademy.chatcontrol.final.nul. .dH.c(SourceFile:280)
[22:40:22] [Server thread/INFO]: at org.mineacademy.chatcontrol.final.nul. .dJ.eg(SourceFile:220)
[22:40:22] [Server thread/INFO]: at org.mineacademy.chatcontrol.final.nul. .dG.a(SourceFile:39)
[22:40:22] [Server thread/INFO]: at org.mineacademy.chatcontrol.final.nul. .dJ.a(SourceFile:80)
[22:40:22] [Server thread/INFO]: at org.mineacademy.chatcontrol.final.nul. .cE.onEnable(SourceFile:262)
[22:40:22] [Server thread/INFO]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[22:40:22] [Server thread/INFO]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
[22:40:22] [Server thread/INFO]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402)
[22:40:22] [Server thread/INFO]: at java.lang.Thread.run(Thread.java:748)
[22:40:22] [Server thread/INFO]: !-----------------------------------------------------!
[22:40:22] [Server thread/INFO]: TILEENTITY_LOAD_LEGACY1121 could not find method 'create' in 'class net.minecraft.server.v1_12_R1.TileEntity'
[22:40:22] [Server thread/INFO]: !-----------------------------------------------------!
[22:40:22] [Server thread/INFO]: ChatControl 8.6.6 encountered a NoSuchMethodException! Please check your error.log and report this issue with the information in that file.
[22:40:22] [Server thread/INFO]: java.lang.NoSuchMethodException: net.minecraft.server.v1_12_R1.TileEntity.load(net.minecraft.server.v1_12_R1.NBTTagCompound)
[22:40:22] [Server thread/INFO]: at java.lang.Class.getMethod(Class.java:1786)
[22:40:22] [Server thread/INFO]: at org.mineacademy.chatcontrol.final.nul. .dC.<init>(SourceFile:118)
[22:40:22] [Server thread/INFO]: at org.mineacademy.chatcontrol.final.nul. .dC.<init>(SourceFile:137)
[22:40:22] [Server thread/INFO]: at org.mineacademy.chatcontrol.final.nul. .dC.<clinit>(SourceFile:81)
[22:40:22] [Server thread/INFO]: at org.mineacademy.chatcontrol.final.nul. .dn.a(SourceFile:73)
[22:40:22] [Server thread/INFO]: at org.mineacademy.chatcontrol.final.nul. .dg.a(SourceFile:62)
[22:40:22] [Server thread/INFO]: at org.mineacademy.chatcontrol.final.nul. .da.<clinit>(SourceFile:211)
[22:40:22] [Server thread/INFO]: at org.mineacademy.chatcontrol.final.nul. .dH.c(SourceFile:280)
[22:40:22] [Server thread/INFO]: at org.mineacademy.chatcontrol.final.nul. .dJ.eg(SourceFile:220)
[22:40:22] [Server thread/INFO]: at org.mineacademy.chatcontrol.final.nul. .dG.a(SourceFile:39)
[22:40:22] [Server thread/INFO]: at org.mineacademy.chatcontrol.final.nul. .dJ.a(SourceFile:80)
[22:40:22] [Server thread/INFO]: at org.mineacademy.chatcontrol.final.nul. .cE.onEnable(SourceFile:262)
[22:40:22] [Server thread/INFO]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[22:40:22] [Server thread/INFO]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
[22:40:22] [Server thread/INFO]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402)
[22:40:22] [Server thread/INFO]: at java.lang.Thread.run(Thread.java:748)
[22:40:22] [Server thread/INFO]: !-----------------------------------------------------!
[22:40:22] [Server thread/INFO]: TILEENTITY_SET_NBT could not find method 'load' in 'class net.minecraft.server.v1_12_R1.TileEntity'
[22:40:22] [Server thread/INFO]: !-----------------------------------------------------!
[22:40:22] [Server thread/INFO]: Toasts are enabled. This may degrade your performance somewhat because advancements (Toasts) must be handled on the main thread.
[22:40:22] [Server thread/INFO]: Registering commands...
[22:40:22] [Server thread/INFO]: Command /ignore already used by Essentials, we take it over...
[22:40:22] [Server thread/INFO]: Command /me already used by Essentials, we take it over...
[22:40:22] [Server thread/INFO]: Command /tell already used by Essentials, we take it over...
[22:40:22] [Server thread/INFO]: Command /reply already used by Essentials, we take it over...
[22:40:22] [Server thread/INFO]:   
[22:40:22] [Server thread/INFO]: Loaded 15 chat, 11 global rules
[22:40:22] [Server thread/INFO]: Hooked into: AuthMe
[22:40:22] [Server thread/INFO]: Hooked into: SimpleClans
[22:40:22] [Server thread/INFO]: Warning: ViaVersion detected. If you are getting kicked with weird messages, disable packet features in settings.yml -> Packets.

**Comment by lackoSK** [comment]
Hey there, 

Please send us your ChatControl folder.

Also, I'd like to note you use pastebin.com to upload the error.

Cheers,
lackoSK

**Comment by IonutMc2** [comment]
Possible Spam Detected

| 
| 
| 
|  |  |

 |

 |
| 
|  | 
Possible Spam Detected


 |

 |

 |





    Pe duminică, 5 aprilie 2020, 12:54:07 CEST, Ladislav Proc <notifications@github.com> a scris:  
 
 


Hey there,

Please send us your ChatControl folder.

Also, I'd like to note you use pastebin.com to upload the error.

Cheers,
lackoSK

**Comment by lackoSK** [comment]
I haven't received anything?
