### ISSUE TITLE
Paper 1.12.2 - DiscordSRV updated to 1.19.0 Hook broken.

### ISSUE THREAD

**Issue by FrozenBeard** [kangarko/ChatControl-Pro#1677]
```
[10:32:25] [Server thread/INFO]: ChatControl 8.6.6 encountered a ClassNotFoundException! Please check your error.log and report this issue with the information in that file.
[10:32:25] [Server thread/INFO]: java.lang.ClassNotFoundException: github.scarsz.discordsrv.dependencies.jda.api.entities.TextChannel
[10:32:25] [Server thread/INFO]: at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
[10:32:25] [Server thread/INFO]: at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:156)
[10:32:25] [Server thread/INFO]: at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:104)
[10:32:25] [Server thread/INFO]: at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
[10:32:25] [Server thread/INFO]: at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
[10:32:25] [Server thread/INFO]: at java.base/java.lang.Class.forName0(Native Method)
[10:32:25] [Server thread/INFO]: at java.base/java.lang.Class.forName(Class.java:315)
[10:32:25] [Server thread/INFO]: at org.mineacademy.chatcontrol.lib.fo.model.v.a(SourceFile:199)
[10:32:25] [Server thread/INFO]: at org.mineacademy.chatcontrol.final.nul. .cE.onEnable(SourceFile:273)
[10:32:25] [Server thread/INFO]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[10:32:25] [Server thread/INFO]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316)
[10:32:25] [Server thread/INFO]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[10:32:25] [Server thread/INFO]: at java.base/java.lang.Thread.run(Thread.java:834)
[10:32:25] [Server thread/INFO]: !-----------------------------------------------------!
[10:32:25] [Server thread/INFO]: ChatControl failed to hook DiscordSRV because the plugin is outdated (1.18.x is supported)!
[10:32:25] [Server thread/INFO]: !-----------------------------------------------------!
```

**Comment by lackoSK** [comment]
Hello,

Thank you! We supported a development build of DiscordSRV, but it seems like they've made some changes during that time. I've uploaded a new DiscordSRV build from the spigot to our repository so the compatibility should be fixed. 

Sincerely,
Ladislav from MineAcademy.org

**Comment by lackoSK** [comment]
Hello,

We've recently updated the version to 9.0.0. Can you please update and test it out here? Thank you. 

Sincerely,
Ladislav from MineAcademy.org
