### ISSUE TITLE
Issue with Sound Notify "AsyncPlayerChatEvent" index out of range (-1)

### ISSUE THREAD

**Issue by Phoetrix** [kangarko/ChatControl-Pro#1687]
### 1 - Write your Minecraft version in the title:
1.15.2

### 2 - Be clear: What is your current situation, the desired situation, and your problem?
Hey, I get an error when I write a player name (online player) in the chat because I have SoundNotify enabled in the settings.yml.
```
07.06 11:55:40 [Server] ERROR Could not pass event AsyncPlayerChatEvent to ChatControl v8.6.6
07.06 11:55:40 [Server] INFO java.lang.StringIndexOutOfBoundsException: String index out of range: -1
07.06 11:55:40 [Server] INFO at java.lang.String.substring(String.java:1967) ~[?:1.8.0_212]
07.06 11:55:40 [Server] INFO at org.mineacademy.chatcontrol.final.nul. .ay.a(SourceFile:74) ~[?:?]
07.06 11:55:40 [Server] INFO at org.mineacademy.chatcontrol.final.nul. .M.a(SourceFile:140) ~[?:?]
07.06 11:55:40 [Server] INFO at org.mineacademy.chatcontrol.final.nul. .M.a(SourceFile:94) ~[?:?]
07.06 11:55:40 [Server] INFO at org.mineacademy.chatcontrol.final.nul. .M.a(SourceFile:36) ~[?:?]
07.06 11:55:40 [Server] INFO at org.mineacademy.chatcontrol.final.nul. .bJ.execute(SourceFile:77) ~[?:?]
07.06 11:55:40 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.15.2.jar:git-Paper-332]
07.06 11:55:40 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-332]
07.06 11:55:40 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-332]
07.06 11:55:40 [Server] INFO at net.minecraft.server.v1_15_R1.PlayerConnection.chat(PlayerConnection.java:1773) ~[patched_1.15.2.jar:git-Paper-332]
07.06 11:55:40 [Server] INFO at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1688) ~[patched_1.15.2.jar:git-Paper-332]
07.06 11:55:40 [Server] INFO at net.minecraft.server.v1_15_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:41) ~[patched_1.15.2.jar:git-Paper-332]
07.06 11:55:40 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_212]
07.06 11:55:40 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_212]
07.06 11:55:40 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
07.06 11:55:40 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
07.06 11:55:40 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```
### 3 - Upload your plugin's folder.
This the only part of the config (settings.yml) who cause the bug. When "Sound Notify" is set to "false" everything works.
```
Sound_Notify:
  Enabled: true

  Cooldown: 0 seconds

  Require_Afk: false

  Require_Prefix: 'none'

  Sound: ENTITY_EXPERIENCE_ORB_PICKUP, 2F, 1.0F

  Color: '&6&l'

  Use_Sender_Group_Color: false
```

Thank you.

**Comment by lackoSK** [comment]
Hello,

We've released 9.0.0. We will be working on recode of Sound Notify very soon [within a few preview versions]. 

Sincerely,
Ladislav from MineAcademy.org
