### ISSUE TITLE
ChatControl 9.0.0 Preview 1 breaks EpicSpawners

### ISSUE THREAD

**Issue by Alejandro-Sosa** [kangarko/ChatControl-Pro#1696]
Hello, ChatControl 9.0.0 Preview 1, latest from spigot breaks the plugin EpicSpawners.

Which is really weird since both aren't even related but the issue doesn't persist when going back to 8.6.6. Which would imply that this problem is coming from ChatControl.

Here is the warning spammed in console:

```
[11:17:59] [Server thread/WARN]: java.lang.NullPointerException
[11:17:59] [Server thread/WARN]: 	at com.songoda.epicspawners.spawners.spawner.option.SpawnOptionEntity_1_13.spawn(SpawnOptionEntity_1_13.java:161)
[11:17:59] [Server thread/WARN]: 	at com.songoda.epicspawners.spawners.spawner.SpawnerData.spawn(SpawnerData.java:110)
[11:17:59] [Server thread/WARN]: 	at com.songoda.epicspawners.spawners.spawner.Spawner.spawn(Spawner.java:74)
[11:17:59] [Server thread/WARN]: 	at com.songoda.epicspawners.tasks.SpawnerSpawnTask.lambda$run$0(SpawnerSpawnTask.java:59)
[11:17:59] [Server thread/WARN]: 	at com.songoda.epicspawners.tasks.SpawnerSpawnTask$$Lambda$4884.00000000B0E23240.accept(Unknown Source)
[11:17:59] [Server thread/WARN]: 	at java.util.ArrayList.forEach(ArrayList.java:1257)
[11:17:59] [Server thread/WARN]: 	at com.songoda.epicspawners.tasks.SpawnerSpawnTask.run(SpawnerSpawnTask.java:36)
[11:17:59] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84)
[11:17:59] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:461)
[11:17:59] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1321)
[11:17:59] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:431)
[11:17:59] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1236)
[11:17:59] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:967)
[11:17:59] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:813)

```

Hope to get this sorted soon, the next generation of ChatControl looks really nice and can't wait to make use of it.

**Comment by lackoSK** [comment]
Hello,

You will need to disable Variables in settings.yml 
![image](https://user-images.githubusercontent.com/53174757/84425212-7aa8c300-ac21-11ea-849b-bf82a84fb39a.png)

PS: Will be available in a next update.

Sincerely,
Ladislav from MineAcademy.org

**Comment by lackoSK** [comment]
Hello,

I've reported this issue to the Songoda development team. 

Sincerely,
Ladislav from MineAcademy.org

**Comment by Alejandro-Sosa** [comment]
Thank you, their support is awful tho lets hope they will actually listen.

**Comment by lackoSK** [comment]
It will be handled with the Songoda team.
