### ISSUE TITLE
Paper-1.8.8: German Language File lacks a String at 'Cannot.Newcomer_Chat'

### ISSUE THREAD

**Issue by EmkaeyJr** [kangarko/ChatControl-Pro#1733]
I have an error when i am trying to load the server with the german version of the language file: 
More Information: 

Default 'messages_de.yml' lacks a String at 'Cannot.Newcomer_Chat'
bK Report / Default 'messages_de.yml' lacks a String at 'Cannot.Newcomer_Chat'
	 at org.mineacademy.chatcontrol.final.nul. .bb.a(SourceFile:56)
	 at org.mineacademy.chatcontrol.final.nul. .dD.i(SourceFile:1503)
	 at org.mineacademy.chatcontrol.final.nul. .dD.h(SourceFile:508)
	 at org.mineacademy.chatcontrol.final.nul. .dD.q(SourceFile:671)
	 at org.mineacademy.chatcontrol.final.nul. .dF.dl(SourceFile:335)
	 at org.mineacademy.chatcontrol.final.nul. .ay.init(SourceFile:773)
	 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	 at java.lang.reflect.Method.invoke(Method.java:498)
	 at org.mineacademy.chatcontrol.final.nul. .dF.b(SourceFile:197)
	 at org.mineacademy.chatcontrol.final.nul. .dF.a(SourceFile:166)
	 at org.mineacademy.chatcontrol.final.nul. .dF.d(SourceFile:148)
	 at org.mineacademy.chatcontrol.final.nul. .dF.a(SourceFile:40)
	 at org.mineacademy.chatcontrol.final.nul. .dF$1.a(SourceFile:60)
	 at org.mineacademy.chatcontrol.final.nul. .dD.m(SourceFile:224)
	 at org.mineacademy.chatcontrol.final.nul. .dF.cX(SourceFile:231)
	 at org.mineacademy.chatcontrol.final.nul. .dB.a_(SourceFile:39)
	 at org.mineacademy.chatcontrol.final.nul. .dF.a(SourceFile:84)
	 at org.mineacademy.chatcontrol.final.nul. .cA.onEnable(SourceFile:251)
	 at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
	 at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
	 at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407)
	 at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359)
	 at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318)

[ChatControl.zip](https://github.com/kangarko/ChatControl-Pro/files/4821285/ChatControl.zip)

MFG und schönen Abend
EmkaeyJr

**Comment by lackoSK** [comment]
Hello,

These issues should be fixed within the next release of ChatControl-Pro.

Sincerely,
Ladislav from MineAcademy.org
