### ISSUE TITLE
1.16.1: "NullPointerException"

### ISSUE THREAD

**Issue by Zakkry** [kangarko/ChatControl-Pro#1737]
###  25.06 19:56:04 [Server] Server thread/INFO ChatControl 9.0.2-BETA encountered a NullPointerException! Please check your error.log and report this issue with the information in that file.

[error.zip](https://github.com/kangarko/ChatControl-Pro/files/4833672/error.zip)

**Comment by lackoSK** [comment]
Hello,

I'm just reviewing this issue and I do not have enough information. Can you add a little more detail to this ticket? 

Please include the ChatControl folder. 

Sincerely,
Ladislav from MineAcademy.org

**Comment by Zakkry** [comment]
I honestly have no clue what the problem was or is. My console told me to report the issue.

[ChatControl.zip](https://github.com/kangarko/ChatControl-Pro/files/4839260/ChatControl.zip)

**Comment by lackoSK** [comment]
Hello,

Can you please send me the whole console error? 

Sincerely,
Ladislav from MineAcademy.org

**Comment by martijnpu** [comment]
I think I have the same error here. Was running BungeeControl 3.0.0 and newest version of CHC pro (9.0.2 BETA) on a paper 1.15.2 server. None errors on startup. Chat formatting was as default minecraft. To solve it I downgraded back to 8.x chc and 2.x bungeecontrol

```
[16:55:29] [Async Chat Thread - #0/ERROR]: Could not pass event AsyncPlayerChatEvent to ChatControl v9.0.2-BETA
java.lang.NullPointerException: null
	at org.mineacademy.chatcontrol.final.nul. .af.d(SourceFile:285) ~[?:?]
	at org.mineacademy.chatcontrol.final.nul. .af.a(SourceFile:160) ~[?:?]
	at org.mineacademy.chatcontrol.final.nul. .af.a(SourceFile:142) ~[?:?]
	at org.mineacademy.chatcontrol.final.nul. .aC.a(SourceFile:183) ~[?:?]
	at org.mineacademy.chatcontrol.final.nul. .X.a(SourceFile:198) ~[?:?]
	at org.mineacademy.chatcontrol.final.nul. .X.a(SourceFile:79) ~[?:?]
	at org.mineacademy.chatcontrol.final.nul. .X.a(SourceFile:32) ~[?:?]
	at org.mineacademy.chatcontrol.final.nul. .bH.execute(SourceFile:77) ~[?:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.15.2.jar:git-Paper-350]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-350]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-350]
	at net.minecraft.server.v1_15_R1.PlayerConnection.chat(PlayerConnection.java:1774) ~[patched_1.15.2.jar:git-Paper-350]
	at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1689) ~[patched_1.15.2.jar:git-Paper-350]
	at net.minecraft.server.v1_15_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:41) ~[patched_1.15.2.jar:git-Paper-350]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_252]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_252]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_252]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_252]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
[16:55:29] [Async Chat Thread - #0/INFO]: <martijnpu> ...```

**Comment by lackoSK** [comment]
Hello,

Can you tell me when this happens? How do I simulate it?

PS: Attach a screenshot of /pl

Sincerely,
Ladislav from MineAcademy.org

**Comment by martijnpu** [comment]
Hi,

It happened while updating a server from 8.6.6 to 9.0.2 BETA, rest of the server still used 8.6.6. And bungeecontrol 2.2.6 to 3.0.0.
Old systems were running fine. Added 9.0.2 BETA, did the formatting and restarted a 1.5.2 server. After this I restarted the bungee to enable bungeecord 3.0.0. Even after restarting the 1.5.2 server with 9.0.2 BETA the chat didn't work.

Console showed an exception for every chat send as above. Besides the bungee-chat didn't work.

Plugins: ![image](https://user-images.githubusercontent.com/38832167/86228841-301ac680-bb8f-11ea-9c47-47d3aad6ff16.png)

**Comment by JavaFactoryDev** [comment]
Hey, 

we tried to reproduce this, but it was not possible for us.
Does it still happen in the latest version?

Regards,
Leonhard from MineAcademy

**Comment by JavaFactoryDev** [comment]
Please respond.

**Comment by martijnpu** [comment]
Please calm down, some people have jobs to do.

Yesterday I tried it again and it worked this time.

**Comment by JavaFactoryDev** [comment]
Awesome, thank you!
I am sorry for my haste.

Regards,
Leonhard from MineAcademy
