### ISSUE TITLE
Paper 1.12.2 Beta does not load with latest SimpleClans

### ISSUE THREAD

**Issue by FrozenBeard** [kangarko/ChatControl-Pro#1742]
Using Paper 1.12.2 ChatControl pro  v9.0.2-BETA does not load at all, as it breaks when using the latest SimpleClans:

https://www.spigotmc.org/resources/simpleclans.71242/
https://github.com/marcelo-mason/SimpleClans/releases

```
[14:35:18] [Server thread/INFO]: [ChatControl] Enabling ChatControl v9.0.2-BETA
[14:35:18] [Server thread/INFO]:   _____ _           _    _____            _             _  +
[14:35:18] [Server thread/INFO]:  / ____| |         | |  / ____|          | |           | |
[14:35:18] [Server thread/INFO]: | |    | |__   __ _| |_| |     ___  _ __ | |_ _ __ ___ | |
[14:35:18] [Server thread/INFO]: | |    | '_ \ / _` | __| |    / _ \| '_ \| __| '__/ _ \| |
[14:35:18] [Server thread/INFO]: | |____| | | | (_| | |_| |___| (_) | | | | |_| | | (_) | |
[14:35:18] [Server thread/INFO]:  \_____|_| |_|\__,_|\__|\_____\___/|_| |_|\__|_|  \___/|_|
[14:35:18] [Server thread/INFO]:   
[14:35:18] [Server thread/INFO]: !-----------------------------------------------------!
[14:35:18] [Server thread/INFO]:   
[14:35:18] [Server thread/INFO]: IMPORTANT NOTICE ABOUT YOUR FOLDER
[14:35:18] [Server thread/INFO]: Since 9.0.0, ChatControl has undergone a major
[14:35:18] [Server thread/INFO]: upgrade and most of your configuration has been
[14:35:18] [Server thread/INFO]: upgraded and changed. Due to extensive
[14:35:18] [Server thread/INFO]: changes, automatic update is not possible.
[14:35:18] [Server thread/INFO]:   
[14:35:18] [Server thread/INFO]: Your old ChatControl folder has been safely
[14:35:18] [Server thread/INFO]: moved to archive/ folder. You can view it to
[14:35:18] [Server thread/INFO]: set up your brand new files quickly.
[14:35:18] [Server thread/INFO]:   
[14:35:18] [Server thread/INFO]: !-----------------------------------------------------!
[14:35:18] [Server thread/INFO]: Command /ignore already used by Essentials, we take it over...
[14:35:18] [Server thread/INFO]: Command /me already used by Essentials, we take it over...
[14:35:18] [Server thread/INFO]: Command /tell already used by Essentials, we take it over...
[14:35:18] [Server thread/INFO]: Command /reply already used by Essentials, we take it over...
[14:35:18] [Server thread/INFO]: [+] Loaded format pm_sender
[14:35:18] [Server thread/INFO]: [+] Loaded format ranged
[14:35:18] [Server thread/INFO]: [+] Loaded format chat
[14:35:18] [Server thread/INFO]: [+] Loaded format motd
[14:35:18] [Server thread/INFO]: [+] Loaded format ad_info
[14:35:18] [Server thread/INFO]: [+] Loaded format admin_chat
[14:35:18] [Server thread/INFO]: [+] Loaded format me
[14:35:18] [Server thread/INFO]: [+] Loaded format pm_recipient
[14:35:18] [Server thread/INFO]: [+] Loaded format bungee_chat
[14:35:18] [Server thread/INFO]: [+] Loaded format discord
[14:35:18] [Server thread/INFO]: [+] Loaded format spy_chat
[14:35:18] [Server thread/INFO]:   
[14:35:18] [Server thread/INFO]: [+] Loaded variable item
[14:35:18] [Server thread/INFO]: [+] Loaded variable ping
[14:35:18] [Server thread/INFO]: [+] Loaded variable difficulty_color
[14:35:18] [Server thread/INFO]:   
[14:35:18] [Server thread/INFO]: Loaded 43 global, 15 chat, 4 command, 2 packet and 1 book rules
[14:35:18] [Server thread/INFO]: Hooked into: SimpleClans
[14:35:18] [Server thread/INFO]: org.bukkit.plugin.IllegalPluginAccessException: Unable to find handler list for event net.sacredlabyrinth.phaed.simpleclans.events.ChatEvent. Static getHandlerList method required!
[14:35:18] [Server thread/INFO]: at org.bukkit.plugin.SimplePluginManager.getRegistrationClass(SimplePluginManager.java:604)
[14:35:18] [Server thread/INFO]: at org.bukkit.plugin.SimplePluginManager.registerEvents(SimplePluginManager.java:545)
[14:35:18] [Server thread/INFO]: at org.mineacademy.chatcontrol.final.nul. .aG.a(SourceFile:2207)
[14:35:18] [Server thread/INFO]: at org.mineacademy.chatcontrol.final.nul. .cz.a(SourceFile:51)
[14:35:18] [Server thread/INFO]: at org.mineacademy.chatcontrol.final.nul. .cA.a(SourceFile:810)
[14:35:18] [Server thread/INFO]: at org.mineacademy.chatcontrol.ChatControl.f(SourceFile:230)
[14:35:18] [Server thread/INFO]: at org.mineacademy.chatcontrol.final.nul. .cA.onEnable(SourceFile:282)
[14:35:18] [Server thread/INFO]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[14:35:18] [Server thread/INFO]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316)
[14:35:18] [Server thread/INFO]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[14:35:18] [Server thread/INFO]: at java.base/java.lang.Thread.run(Thread.java:834)
[14:35:18] [Server thread/INFO]:   _   _                       _
[14:35:18] [Server thread/INFO]:   | | | | ___   ___  _ __  ___| |
[14:35:18] [Server thread/INFO]:   | |_| |/ _ \ / _ \| '_ \/ __| |
[14:35:18] [Server thread/INFO]:   |  _  | (_) | (_) | |_) \__ \_|
[14:35:18] [Server thread/INFO]:   |_| |_|\___/ \___/| .__/|___(_)
[14:35:18] [Server thread/INFO]:                     |_|
[14:35:18] [Server thread/INFO]: !-----------------------------------------------------!
[14:35:18] [Server thread/INFO]: Error loading ChatControl v9.0.2-BETA, plugin is disabled!
[14:35:18] [Server thread/INFO]: Running on 1.12.2-R0.1-SNAPSHOT (v1_12_R1) & Java 11.0.7
[14:35:18] [Server thread/INFO]: !-----------------------------------------------------!
[14:35:18] [Server thread/INFO]: Error: Unable to find handler list for event net.sacredlabyrinth.phaed.simpleclans.events.ChatEvent. Static getHandlerList method required!
[14:35:18] [Server thread/INFO]: !-----------------------------------------------------!
[14:35:18] [Server thread/INFO]: [ChatControl] Disabling ChatControl v9.0.2-BETA
```

**Comment by lackoSK** [comment]
Hello,

Thank you for reporting this issue! (Apologies for the late reply, we had repository problem)

https://github.com/marcelo-mason/SimpleClans/issues/634

Sincerely,
Ladislav from MineAcademy.org

**Comment by JavaFactoryDev** [comment]
Fixed with the latest version of SimpleClans.
