### ISSUE TITLE
Minecraft Version: 1.16.1 Plugin not working with latest Paper Build #90

### ISSUE THREAD

**Issue by antoningfors** [kangarko/ChatControl-Pro#1766]
ChatControl-Pro Version 9.04-Beta does not work with the latest paper build. After upgrading from Build 89 to Build 90 the plugin breaks whenever you type a message in chat. You can replicate this issue by just setting up a server with Build 90 of paper and version 9.04-Beta of ChatControl-Pro. Then just join and type anything in chat with the default config generated by the plugin. I am not sure if Spigot works.

Build 89 (Working) - https://github.com/PaperMC/Paper/commit/12b2b263a0cbd0e8e71f437a81fe168c269161ca
Build 90 (Broken) - https://github.com/PaperMC/Paper/commit/e594a58695583d971ada21c3efd7cbe03e9e3498

**Stack Trace**
java.lang.NoSuchMethodError: 'net.md_5.bungee.api.chat.BaseComponent[] net.md_5.bungee.api.chat.HoverEvent.getValue()'
at org.mineacademy.chatcontrol.final.nul. .dm.a(SourceFile:486) ~[?:?]
at org.mineacademy.chatcontrol.final.nul. .dm.a(SourceFile:177) ~[?:?]
at org.mineacademy.chatcontrol.final.nul. .dm.a(SourceFile:126) ~[?:?]
at org.mineacademy.chatcontrol.final.nul. .fq.a(SourceFile:178) ~[?:?]
at org.mineacademy.chatcontrol.final.nul. .de.a(SourceFile:237) ~[?:?]
at org.mineacademy.chatcontrol.final.nul. .de.a(SourceFile:80) ~[?:?]
at org.mineacademy.chatcontrol.final.nul. .de.a(SourceFile:33) ~[?:?]
at org.mineacademy.chatcontrol.final.nul. .aZ.execute(SourceFile:77) ~[?:?]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.16.1.jar:git-Paper-90]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.1.jar:git-Paper-90]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.1.jar:git-Paper-90]
at net.minecraft.server.v1_16_R1.PlayerConnection.chat(PlayerConnection.java:1821) ~[patched_1.16.1.jar:git-Paper-90]
at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1736) ~[patched_1.16.1.jar:git-Paper-90]
at net.minecraft.server.v1_16_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:41) ~[patched_1.16.1.jar:git-Paper-90]
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:?]
at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
at java.lang.Thread.run(Unknown Source) [?:?]

**Comment by TNTUP** [comment]
They're phasing out Github, sadly so I don't know if they will take account of your issue but I can confirm on my side aswell

**Comment by broken1arrow** [comment]
Same error here. 

Error: %error
NoSuchMethodError 'net.md_5.bungee.api.chat.BaseComponent[] net.md_5.bungee.api.chat.HoverEvent.getValue()'
	 at org.mineacademy.chatcontrol.final.nul. .Z.a(SourceFile:573)
	 at org.mineacademy.chatcontrol.final.nul. .Z.a(SourceFile:222)
	 at org.mineacademy.chatcontrol.final.nul. .f.sendMessage(SourceFile:262)
	 at org.mineacademy.chatcontrol.final.nul. .dK.a(SourceFile:161)
	 at org.mineacademy.chatcontrol.final.nul. .dK.a(SourceFile:34)
	 at org.mineacademy.chatcontrol.final.nul. .bq.execute(SourceFile:77)
	 at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
	 at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
	 at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
----------------------------------------------------------------------------------------------

**Comment by JavaFactoryDev** [comment]
Please only use support.mineacademy.org to report issues.
