### ISSUE TITLE
1.16.1: Exception on Bungee Channels

### ISSUE THREAD

**Issue by james-d-elliott** [kangarko/ChatControl-Pro#1782]
Under the following circumstances the following exception occurs:

* On a Bungee Network
* Bungee Plugin Versions:
  * BungeeControl 2.2.6
  * LuckPerms 5.1.86 (bungee)
  * PunishControl 1.2.9
* Bukkit Plugin Versions:
  * ChatControlPro 8.6.9
  * Vault 1.7.3
  * PlaceholderAPI 2.10.8
  * LuckPerms 5.1.86
  * ProtocolLib 4.5.1
* Channels are enabled.
* UserA is on ServerA and UserB is on ServerB
* UserA on ServerA messages the global channel which is Bungee enabled.
* Exception occurs.

```

svra              | [11:57:26 WARN]: [ChatControl] Plugin ChatControl v8.6.9 generated an exception whilst handling plugin message
svra              | org.mineacademy.chatcontrol.final.nul. .aF: Report / Unexpected data type class java.lang.String, expected class java.lang.Boolean for CHANNEL
svra              |     at org.mineacademy.chatcontrol.final.nul. .W.a(SourceFile:76) ~[?:?]
svra              |     at org.mineacademy.chatcontrol.final.nul. .ac.a(SourceFile:100) ~[?:?]
svra              |     at org.mineacademy.chatcontrol.final.nul. .ab.a(SourceFile:62) ~[?:?]
svra              |     at org.mineacademy.chatcontrol.hook.b.a(SourceFile:120) ~[?:?]
svra              |     at org.mineacademy.chatcontrol.final.nul. .Y.onPluginMessageReceived(SourceFile:35) ~[?:?]
svra              |     at org.bukkit.plugin.messaging.StandardMessenger.dispatchIncomingMessage(StandardMessenger.java:455) ~[patched_1.16.1.jar:git-Paper-131]
svra              |     at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:2769) ~[patched_1.16.1.jar:git-Paper-131]
svra              |     at net.minecraft.server.v1_16_R1.PacketPlayInCustomPayload.a(SourceFile:44) ~[patched_1.16.1.jar:git-Paper-131]
svra              |     at net.minecraft.server.v1_16_R1.PacketPlayInCustomPayload.a(SourceFile:9) ~[patched_1.16.1.jar:git-Paper-131]
svra              |     at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.1.jar:git-Paper-                                                                                      131]
svra              |     at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18) ~[patched_1.16.1.jar:git-Paper-131]
svra              |     at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.1.jar:git-Paper-131]
svra              |     at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.1.jar:git-Paper-131]
svra              |     at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.1.jar:git-Paper-131]
svra              |     at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:1137) ~[patched_1.16.1.jar:git-Paper-131]
svra              |     at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:1130) ~[patched_1.16.1.jar:git-Paper-131]
svra              |     at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.1.jar:git-Paper-131]
svra              |     at net.minecraft.server.v1_16_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1091) ~[patched_1.16.1.jar:git-Paper-131]
svra              |     at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1005) ~[patched_1.16.1.jar:git-Paper-131]
svra              |     at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-131]
svra              |     at java.lang.Thread.run(Unknown Source) [?:?]

```

**Comment by JavaFactoryDev** [comment]
Hi,
thanks for reporting this!
We will have a look at it asap.

Regards,
Leonhard

**Comment by JavaFactoryDev** [comment]
Can you please make sure you are using BungeeControl 2.2.6 & all your sub-servers are on the latest ChatControl version?
I can't reproduce this issue so far.

**Comment by james-d-elliott** [comment]
I have verified and re-downloaded the latest version of ChatControlPro 8.6.9 and BungeeControl 2.2.6 from SpigotMC. 

The following settings have been changed from the default. Sending a message via `/channel send global test` results in the exception and players not on the same server as the player who sent it not receiving the message.

BungeeControl Config:

messages.enabled = true
global-join.enabled = true

ChatControl Main Config:
Private_Messages.Enabled = true
Private_Messages.Bungee = true
BungeeCord.Enabled = true
MySQL.Enabled = true
MySQL.Connection.Host = mariadb
MySQL.Connection.Database = minecraft
MySQL.Connection.User = chatcontrol
MySQL.Connection.Password = ****************
Bungee_Server_Name = svra

ChatControl Channels Config:

Enabled = true

**Comment by kangarko** [comment]
Thanks, I fixed it. It was an internal mistake in our packet that does the sending to BungeeControl.
