### ISSUE TITLE
1.16.1 CHC won't load on an empty server

### ISSUE THREAD

**Issue by x1p** [kangarko/ChatControl-Pro#1794]
Trying to load the default jar on a blanc test server
```
[21:35:09 INFO]: [ChatControl] Enabling ChatControl v8.7.1
[21:35:09 INFO]: _____ _ _ _____ _ _ +
[21:35:09 INFO]: / ____| | | | / ____| | | | |
[21:35:09 INFO]: | | | |__ __ _| |_| | ___ _ __ | |_ _ __ ___ | |
[21:35:09 INFO]: | | | '_ \ / _` | __| | / _ \| '_ \| __| '__/ _ \| |
[21:35:09 INFO]: | |____| | | | (_| | |_| |___| (_) | | | | |_| | | (_) | |
[21:35:09 INFO]: \_____|_| |_|\__,_|\__|\_____\___/|_| |_|\__|_| \___/|_|
[21:35:09 INFO]:
[21:35:09 INFO]: !-----------------------------------------------------!
[21:35:09 INFO]: Failed to copy /variables to variables
[21:35:09 INFO]: !-----------------------------------------------------!
[21:35:09 INFO]: ChatControl 8.7.1 encountered a NullPointerException! Please check your error.log and report this issue with the information in that file.
[21:35:09 INFO]: java.lang.NullPointerException
[21:35:09 INFO]: at org.mineacademy.chatcontrol.final.nul. .F.d(SourceFile:518)
[21:35:09 INFO]: at org.mineacademy.chatcontrol.lib.fo.model.h.a(SourceFile:94)
[21:35:09 INFO]: at org.mineacademy.chatcontrol.lib.fo.model.X.i(SourceFile:286)
[21:35:09 INFO]: at org.mineacademy.chatcontrol.final.nul. .dI.p(SourceFile:71)
[21:35:09 INFO]: at org.mineacademy.chatcontrol.final.nul. .dI.g(SourceFile:51)
[21:35:09 INFO]: at org.mineacademy.chatcontrol.final.nul. .cN$1.<init>(SourceFile:53)
[21:35:09 INFO]: at org.mineacademy.chatcontrol.final.nul. .cN.<init>(SourceFile:50)
[21:35:09 INFO]: at org.mineacademy.chatcontrol.final.nul. .cK.<init>(SourceFile:23)
[21:35:09 INFO]: at org.mineacademy.chatcontrol.final.nul. .dI.<init>(SourceFile:40)
[21:35:09 INFO]: at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[21:35:09 INFO]: at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[21:35:09 INFO]: at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[21:35:09 INFO]: at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
[21:35:09 INFO]: at java.base/java.lang.Class.newInstance(Class.java:584)
[21:35:09 INFO]: at org.mineacademy.chatcontrol.final.nul. .cN.a(SourceFile:80)
[21:35:09 INFO]: at org.mineacademy.chatcontrol.final.nul. .bv.onEnable(SourceFile:251)
[21:35:09 INFO]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[21:35:09 INFO]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380)
[21:35:09 INFO]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
[21:35:09 INFO]: at java.base/java.lang.Thread.run(Thread.java:834)
[21:35:09 INFO]: _ _ _
[21:35:09 INFO]: | | | | ___ ___ _ __ ___| |
[21:35:09 INFO]: | |_| |/ _ \ / _ \| '_ \/ __| |
[21:35:09 INFO]: | _ | (_) | (_) | |_) \__ \_|
[21:35:09 INFO]: |_| |_|\___/ \___/| .__/|___(_)
[21:35:09 INFO]: |_|
[21:35:09 INFO]: !-----------------------------------------------------!
[21:35:09 INFO]: Error loading ChatControl v8.7.1, plugin is disabled!
[21:35:09 INFO]: Running on 1.16.1-R0.1-SNAPSHOT (v1_16_R1) & Java 11.0.6
[21:35:09 INFO]: !-----------------------------------------------------!
[21:35:09 INFO]: Error: Unable to get the error message, search above.
[21:35:09 INFO]: !-----------------------------------------------------!
[21:35:09 INFO]: [ChatControl] Disabling ChatControl v8.7.1
[21:35:09 INFO]: Plugin might not shut down property. Got NullPointerException: null
```
Manually extracting the needed files from the jar solves it but it's not very conveniant.

Paper 1.16.1
CHC 8.7.1 released as of today

**Comment by NikKing97** [comment]
Got the exact same issue, on Paper 1.15.2.
[21:45:08] [Server thread/INFO]: !-----------------------------------------------------!
[21:45:08] [Server thread/INFO]: Error loading ChatControl v8.7.1, plugin is disabled!
[21:45:08] [Server thread/INFO]: Running on 1.15.2-R0.1-SNAPSHOT (v1_15_R1) & Java 11.0.7
[21:45:08] [Server thread/INFO]: !-----------------------------------------------------!

**Comment by kangarko** [comment]
Thank you, I missed that. Testing it I found the defect but could not fix it right away, I'll be investigating this. You can follow the progress here: https://www.spigotmc.org/threads/proguard-breaks-calling-class-getresource.456393/

**Comment by kangarko** [comment]
Thanks, I identified and fixed the problem. A new release will be available tonight.
