### ISSUE TITLE
1.16.1: 8.7.1 private messages broken?

### ISSUE THREAD

**Issue by james-d-elliott** [kangarko/ChatControl-Pro#1797]
This occurs with default formatting config on 8.7.1:

```
svrb              | [00:45:13 INFO]: usera issued server command: /tell usera test
svrb              | [00:45:13 INFO]: ChatControl 8.7.1 encountered a RuntimeException! Please check your error.log and report this issue with the information in that file.
svrb              | [00:45:13 INFO]: java.lang.RuntimeException: Failed to invoke public net.md_5.bungee.api.chat.BaseComponent() with no args
svrb              | [00:45:13 INFO]: at com.google.gson.internal.ConstructorConstructor$3.construct(ConstructorConstructor.java:111)
svrb              | [00:45:13 INFO]: at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:210)
svrb              | [00:45:13 INFO]: at com.google.gson.Gson.fromJson(Gson.java:887)
svrb              | [00:45:13 INFO]: at com.google.gson.Gson.fromJson(Gson.java:952)
svrb              | [00:45:13 INFO]: at com.google.gson.Gson.fromJson(Gson.java:925)
svrb              | [00:45:13 INFO]: at net.md_5.bungee.chat.ComponentSerializer.parse(ComponentSerializer.java:57)
svrb              | [00:45:13 INFO]: at org.mineacademy.chatcontrol.final.nul. .bQ.a(SourceFile:742)
svrb              | [00:45:13 INFO]: at org.mineacademy.chatcontrol.hook.b.a(SourceFile:174)
svrb              | [00:45:13 INFO]: at org.mineacademy.chatcontrol.final.nul. .Y.onPluginMessageReceived(SourceFile:35)
svrb              | [00:45:13 INFO]: at org.bukkit.plugin.messaging.StandardMessenger.dispatchIncomingMessage(StandardMessenger.java:455)
svrb              | [00:45:13 INFO]: at java.base/java.lang.Thread.run(Unknown Source)
svrb              | [00:45:13 INFO]: java.lang.InstantiationException
svrb              | [00:45:13 INFO]: at java.base/jdk.internal.reflect.InstantiationExceptionConstructorAccessorImpl.newInstance(Unknown Source)
svrb              | [00:45:13 INFO]: at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
svrb              | [00:45:13 INFO]: at com.google.gson.internal.ConstructorConstructor$3.construct(ConstructorConstructor.java:108)
svrb              | [00:45:13 INFO]: at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:210)
svrb              | [00:45:13 INFO]: at com.google.gson.Gson.fromJson(Gson.java:887)
svrb              | [00:45:13 INFO]: at com.google.gson.Gson.fromJson(Gson.java:952)
svrb              | [00:45:13 INFO]: at com.google.gson.Gson.fromJson(Gson.java:925)
svrb              | [00:45:13 INFO]: at net.md_5.bungee.chat.ComponentSerializer.parse(ComponentSerializer.java:57)
svrb              | [00:45:13 INFO]: at org.mineacademy.chatcontrol.final.nul. .bQ.a(SourceFile:742)
svrb              | [00:45:13 INFO]: at org.mineacademy.chatcontrol.hook.b.a(SourceFile:174)
svrb              | [00:45:13 INFO]: at org.mineacademy.chatcontrol.final.nul. .Y.onPluginMessageReceived(SourceFile:35)
svrb              | [00:45:13 INFO]: at org.bukkit.plugin.messaging.StandardMessenger.dispatchIncomingMessage(StandardMessenger.java:455)
svrb              | [00:45:13 INFO]: at java.base/java.lang.Thread.run(Unknown Source)
svrb              | [00:45:13 INFO]: !-----------------------------------------------------!
svrb              | [00:45:13 INFO]: Malformed JSON when sending message to usera with JSON: {"text":"","extra":[{"text":"","extra":[{"text":"✉ ","color":"gray"},{"text":"from usera: ","color":"gold"},{"text":"test","color":"white"}],"clickEvent":{"action":"suggest_command","value":"/r "},"hoverEvent":{"action":"show_text","value":{"value":[{"text":"","extra":[{"text":"     "},{"text":"~ ","color":"dark_gray"},{"text":"Private Message ","color":"dark_aqua"},{"text":"~     \n","color":"dark_gray"},{"text":"Received 05.08.2020 00:45:13\n","color":"dark_gray","italic":true},{"text":"Sender: ","color":"dark_aqua"},{"text":"usera\n\n","color":"white"},{"text":"Click for a reply.","color":"gray"}]}]}}}]}
svrb              | [00:45:13 INFO]: !-----------------------------------------------------!
svrb              | [00:45:13 INFO]: ChatControl 8.7.1 encountered a RuntimeException! Please check your error.log and report this issue with the information in that file.
svrb              | [00:45:13 INFO]: java.lang.RuntimeException: Failed to invoke public net.md_5.bungee.api.chat.BaseComponent() with no args
svrb              | [00:45:13 INFO]: at com.google.gson.internal.ConstructorConstructor$3.construct(ConstructorConstructor.java:111)
svrb              | [00:45:13 INFO]: at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:210)
svrb              | [00:45:13 INFO]: at com.google.gson.Gson.fromJson(Gson.java:887)
svrb              | [00:45:13 INFO]: at com.google.gson.Gson.fromJson(Gson.java:952)
svrb              | [00:45:13 INFO]: at com.google.gson.Gson.fromJson(Gson.java:925)
svrb              | [00:45:13 INFO]: at net.md_5.bungee.chat.ComponentSerializer.parse(ComponentSerializer.java:57)
svrb              | [00:45:13 INFO]: at org.mineacademy.chatcontrol.final.nul. .bQ.a(SourceFile:742)
svrb              | [00:45:13 INFO]: at org.mineacademy.chatcontrol.hook.b.a(SourceFile:195)
svrb              | [00:45:13 INFO]: at org.mineacademy.chatcontrol.final.nul. .Y.onPluginMessageReceived(SourceFile:35)
svrb              | [00:45:13 INFO]: at org.bukkit.plugin.messaging.StandardMessenger.dispatchIncomingMessage(StandardMessenger.java:455)
svrb              | [00:45:13 INFO]: at java.base/java.lang.Thread.run(Unknown Source)
svrb              | [00:45:13 INFO]: java.lang.InstantiationException
svrb              | [00:45:13 INFO]: at java.base/jdk.internal.reflect.InstantiationExceptionConstructorAccessorImpl.newInstance(Unknown Source)
svrb              | [00:45:13 INFO]: at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
svrb              | [00:45:13 INFO]: at com.google.gson.internal.ConstructorConstructor$3.construct(ConstructorConstructor.java:108)
svrb              | [00:45:13 INFO]: at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:210)
svrb              | [00:45:13 INFO]: at com.google.gson.Gson.fromJson(Gson.java:887)
svrb              | [00:45:13 INFO]: at com.google.gson.Gson.fromJson(Gson.java:952)
svrb              | [00:45:13 INFO]: at com.google.gson.Gson.fromJson(Gson.java:925)
svrb              | [00:45:13 INFO]: at net.md_5.bungee.chat.ComponentSerializer.parse(ComponentSerializer.java:57)
svrb              | [00:45:13 INFO]: at org.mineacademy.chatcontrol.final.nul. .bQ.a(SourceFile:742)
svrb              | [00:45:13 INFO]: at org.mineacademy.chatcontrol.hook.b.a(SourceFile:195)
svrb              | [00:45:13 INFO]: at org.mineacademy.chatcontrol.final.nul. .Y.onPluginMessageReceived(SourceFile:35)
svrb              | [00:45:13 INFO]: at org.bukkit.plugin.messaging.StandardMessenger.dispatchIncomingMessage(StandardMessenger.java:455)
svrb              | [00:45:13 INFO]: at java.base/java.lang.Thread.run(Unknown Source)
svrb              | [00:45:13 INFO]: !-----------------------------------------------------!
svrb              | [00:45:13 INFO]: Malformed JSON when sending message to usera with JSON: {"text":"","extra":[{"text":"","extra":[{"text":"✉ ","color":"gray"},{"text":"has been sent!","color":"dark_green"}],"clickEvent":{"action":"suggest_command","value":"/tell usera "},"hoverEvent":{"action":"show_text","value":{"value":[{"text":"","extra":[{"text":"     "},{"text":"~ ","color":"dark_gray"},{"text":"Private Message ","color":"dark_aqua"},{"text":"~     \n","color":"dark_gray"},{"text":"Sent 05.08.2020 00:45:13\n","color":"dark_gray","italic":true},{"text":"Receiver: ","color":"dark_aqua"},{"text":"usera\n","color":"white"},{"text":"Body: ","color":"dark_aqua"},{"text":"test","color":"white"}]}]}}}]}
svrb              | [00:45:13 INFO]: !-----------------------------------------------------!

```

**Comment by AngellitoX** [comment]
Hey James, happy to read you once again!

Have you tested this with a clean folder? If so, I'll ask Matej to take a look to it tomorrow once the workload gets relaxed.

Also, what is your setup? Paper version, bungeecord version, etc.

Angel from MineAcademy.org

**Comment by james-d-elliott** [comment]
Bungee Plugin Versions:
* BungeeControl 2.2.6
* LuckPerms 5.1.86 (bungee)

Bukkit Plugin Versions:
* ChatControlPro 8.6.9
* Vault 1.7.3
* PlaceholderAPI 2.10.9
* LuckPerms 5.1.86
* ProtocolLib 4.5.1

Attempting to do it from a completely blank folder gives this: https://github.com/kangarko/ChatControl-Pro/issues/1796

**Comment by james-d-elliott** [comment]
Paper 131, Waterfall 366 (forgot to mention).

**Comment by kangarko** [comment]
Thanks, seems that I fixed it by editing some other code. Tested using Paper 131 and BungeeCord without issues, /tell worked within 1 server or via Bungee.

Matej
