### ISSUE TITLE
Error starting Chatcontrol Pro 7.2.6 at a Cauldron 1.7.10 server (Security seal for Path)

### ISSUE THREAD

**Issue by cool9535** [kangarko/ChatControl-Pro#180]
My cauldron server is at another Hard Drive at my computer
LOG:
[11:29:31] [Server thread/ERROR]: The jar file D:\Forge_Server\mods\ChatControl.jar has a security seal for path nul.final...\\............aux, but that path is defined and not secure
[11:29:31] [Server thread/ERROR]: The jar file D:\Forge_Server\mods\ChatControl.jar has a security seal for path nul.final...\\............aux, but that path is defined and not secure
[11:29:31] [Server thread/ERROR]: Could not load 'plugins\ChatControl.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.IllegalStateException: JavaPlugin requires org.bukkit.plugin.java.PluginClassLoader
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:149) ~[JavaPluginLoader.class:1.7.10-R0.1-SNAPSHOT]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:334) ~[SimplePluginManager.class:1.7.10-R0.1-SNAPSHOT]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:256) [SimplePluginManager.class:1.7.10-R0.1-SNAPSHOT]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugins(CraftServer.java:320) [CraftServer.class:1.7.10-R0.1-SNAPSHOT]
	at net.minecraft.world.storage.SaveHandler.initBukkitData(SaveHandler.java:461) [ayq.class:?]
	at net.minecraft.world.storage.SaveHandler.func_75757_d(SaveHandler.java:137) [ayq.class:?]
	at net.minecraft.world.World.<init>(World.java:360) [ahb.class:?]
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:160) [mt.class:?]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:367) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:336) [lt.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:631) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
Caused by: java.lang.IllegalStateException: JavaPlugin requires org.bukkit.plugin.java.PluginClassLoader
	at org.bukkit.plugin.java.JavaPlugin.<init>(JavaPlugin.java:64) ~[JavaPlugin.class:1.7.10-R0.1-SNAPSHOT]
	at nul.final...\\............aux.e.<init>(SourceFile:26) ~[e.class:?]
	at me.kangarko.chatcontrol.ChatControl.<init>(SourceFile:59) ~[ChatControl.class:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_121]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_121]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_121]
	at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_121]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:201) ~[PluginClassLoader.class:1.7.10-R0.1-SNAPSHOT]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:145) ~[JavaPluginLoader.class:1.7.10-R0.1-SNAPSHOT]
	... 11 more

**Comment by kangarko** [comment]
Interesting error, it look like pain in the ass to fix haha , but I will look as soon as I have the capabilities

**Comment by cool9535** [comment]
Thanks

**Comment by kangarko** [comment]
Hey,

I was able to setup a debug environment and got the 7.3.2 version running with BungeeChatAPI along:
 https://www.spigotmc.org/resources/bungeechatapi.38379/

I am closing this, feel free to post below if there are any issues.
