### ISSUE TITLE
problem with chat

### ISSUE THREAD

**Issue by iProMC** [kangarko/ChatControl-Pro#1822]
Hello,

I have this problem when types in the chat and I use placeholderapi 2.10.6 should that make a problem?

------------------------------------[ 09.08.2020 14:35:33 ]-----------------------------------
ChatControl 8.7.4 encountered an aF
Running CraftBukkit 1.8.8-R0.1-SNAPSHOT and Java 1.8.0_252
----------------------------------------------------------------------------------------------

More Information: 
Method cannot be null for null
aF Report / Method cannot be null for null
	 at org.mineacademy.chatcontrol.final.nul. .W.a(SourceFile:56)
	 at org.mineacademy.chatcontrol.final.nul. .R.a(SourceFile:398)
	 at org.mineacademy.chatcontrol.lib.fo.model.B.a(SourceFile:1964)
	 at org.mineacademy.chatcontrol.lib.fo.model.u.b(SourceFile:941)
	 at org.mineacademy.chatcontrol.lib.fo.model.Y.a(SourceFile:263)
	 at org.mineacademy.chatcontrol.lib.fo.model.Y.a(SourceFile:227)
	 at org.mineacademy.chatcontrol.lib.fo.model.Y.a(SourceFile:186)
	 at org.mineacademy.chatcontrol.lib.fo.model.Y.a(SourceFile:212)
	 at org.mineacademy.chatcontrol.final.nul. .df.b(SourceFile:377)
	 at org.mineacademy.chatcontrol.final.nul. .dj.a(SourceFile:86)
	 at org.mineacademy.chatcontrol.final.nul. .dj.a(SourceFile:42)
	 at org.mineacademy.chatcontrol.final.nul. .cZ.a(SourceFile:135)
	 at org.mineacademy.chatcontrol.final.nul. .cZ.a(SourceFile:93)
	 at org.mineacademy.chatcontrol.final.nul. .cZ.a(SourceFile:38)
	 at org.mineacademy.chatcontrol.final.nul. .aC.execute(SourceFile:77)
	 at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74)
	 at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
	 at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517)
	 at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:499)
----------------------------------------------------------------------------------------------

**Comment by AngellitoX** [comment]
Hello there.

Update to latest PAPI and latest ChatControl and see if this solves your issue. And please use pastebin instead to provide console errors and paste the full message.

Closing for now. Thank you!

**Comment by iProMC** [comment]
I can't use the lastest papi because all of the plugins doesn't update to the last version

**Comment by AngellitoX** [comment]
Then you will also need to stay in a previous version of ChatControl.

**Comment by iProMC** [comment]
but kangarko says to me that he will support both of them

**Comment by kangarko** [comment]
Use this version of PAPI, the developer should have fixed the problems: https://www.spigotmc.org/resources/placeholderapi.6245/update?update=352711

And use ChatControl 8.7.6. Please comment below if still having issues and repost me the new error from that CHC version.
