### ISSUE TITLE
1.16.1: Users sometimes cannot join local chat channel.

### ISSUE THREAD

**Issue by bartymc** [kangarko/ChatControl-Pro#1830]
Users on my server are automatically put in the local chat channel and are unable to leave. However, a user on my server (and has happened in the past) is unable to switch to writing in local chat. They get this error when they do "/ch join local" (the error also happens when I try to set them to the channel using "/ch set [player] local":

`Player AntiDepressant_ is not in local channel!
aF Report / Player AntiDepressant_ is not in local channel!
	 at org.mineacademy.chatcontrol.final.nul. .W.a(SourceFile:56)
	 at org.mineacademy.chatcontrol.lib.fo.collection.d.a(SourceFile:49)
	 at org.mineacademy.chatcontrol.final.nul. .dl.removePlayer(SourceFile:163)
	 at org.mineacademy.chatcontrol.final.nul. .b.a(SourceFile:322)
	 at org.mineacademy.chatcontrol.final.nul. .al.execute(SourceFile:343)
	 at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172)
	 at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchCommand(CraftServer.java:794)`

**Comment by kangarko** [comment]
Please upload your ZIP folder of the plugin with steps to reproduce this issue. Could not get it on my server with default settings by doing /ch

**Comment by kangarko** [comment]
Nevermind, I just reviewed the current code. I will completely rewrite this on 9.1.0.
