### ISSUE TITLE
1.16.2 - ChatControl not supporting 1.16.2

### ISSUE THREAD

**Issue by malonnnn** [kangarko/ChatControl-Pro#1836]
https://pastebin.com/kUmzb1SP

v8.7.6
Java 1.8.0_251
ubuntu 20.04

BungeeCord build #1530

Chatcontrol fails to load on Spigot 1.16.2, works fine on 1.16.1

**Comment by AngellitoX** [comment]
Hello,

1.16.2 has not been added yet to ChatControl. It should be ready this week.

Also, it's important to mention that Spigot 1.16.2 contains many bugs for now which can corrupt your world/data, so I would definitely encourage you to wait on 1.16.1 until it gets stable and use plugins like ViaVersion if you want new version support.

Greetings!

**Comment by malonnnn** [comment]
ChatControl Pro says it supports 1.16.2 - right there in the title

https://www.spigotmc.org/resources/%E2%99%A3-chatcontrol-pro%E2%84%A2-format-and-filter-your-chat-1-7-10-1-16-2.10258/history

**Comment by AngellitoX** [comment]
Hello!

You are absolutely right. I apologize, I didnt notice that because it wasn't on the latest changelog. Let's hope Matej can take a look to this soon.

Thank you!

**Comment by james-d-elliott** [comment]
Related logs (Paper SNAPSHOT):

```
[12:25:06 INFO]: [ChatControl] Enabling ChatControl v8.7.6
[12:25:06 INFO]:   _____ _           _    _____            _             _  +
[12:25:06 INFO]:  / ____| |         | |  / ____|          | |           | |
[12:25:06 INFO]: | |    | |__   __ _| |_| |     ___  _ __ | |_ _ __ ___ | |
[12:25:06 INFO]: | |    | '_ \ / _` | __| |    / _ \| '_ \| __| '__/ _ \| |
[12:25:06 INFO]: | |____| | | | (_| | |_| |___| (_) | | | | |_| | | (_) | |
[12:25:06 INFO]:  \_____|_| |_|\__,_|\__|\_____\___/|_| |_|\__|_|  \___/|_|
[12:25:06 INFO]:
[12:25:07 WARN]: [NBTAPI] [NBTAPI] Wasn't able to find NMS Support! Some functions may not work!
[12:25:07 INFO]: ** COMPATIBILITY TEST FAILED - THIS PLUGIN WILL NOT FUNCTION **
[12:25:07 INFO]: ** YOUR MINECRAFT VERSION APPEARS UNSUPPORTED: v1_16 **
[12:25:07 WARN]: org.mineacademy.chatcontrol.final.nul. .cu: Method 'null' not loaded! 'ITEMSTACK_NMSCOPY'
[12:25:07 WARN]:      at org.mineacademy.chatcontrol.final.nul. .cD.a(SourceFile:149)
[12:25:07 WARN]:      at org.mineacademy.chatcontrol.final.nul. .cm.e(SourceFile:33)
[12:25:07 WARN]:      at org.mineacademy.chatcontrol.final.nul. .cq.a(SourceFile:517)
[12:25:07 WARN]:      at org.mineacademy.chatcontrol.final.nul. .cd.a(SourceFile:98)
[12:25:07 WARN]:      at org.mineacademy.chatcontrol.final.nul. .bW.a(SourceFile:62)
[12:25:07 WARN]:      at org.mineacademy.chatcontrol.final.nul. .bQ.<clinit>(SourceFile:223)
[12:25:07 WARN]:      at org.mineacademy.chatcontrol.final.nul. .cL.c(SourceFile:287)
[12:25:07 WARN]:      at org.mineacademy.chatcontrol.final.nul. .cN.b(SourceFile:230)
[12:25:07 WARN]:      at org.mineacademy.chatcontrol.final.nul. .cK.a(SourceFile:39)
[12:25:07 WARN]:      at org.mineacademy.chatcontrol.final.nul. .cN.a(SourceFile:82)
[12:25:07 WARN]:      at org.mineacademy.chatcontrol.final.nul. .bv.onEnable(SourceFile:251)
[12:25:07 WARN]:      at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[12:25:07 WARN]:      at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380)
[12:25:07 WARN]:      at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
[12:25:07 WARN]:      at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:499)
[12:25:07 WARN]:      at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:413)
[12:25:07 WARN]:      at net.minecraft.server.v1_16_R2.MinecraftServer.loadWorld(MinecraftServer.java:468)
[12:25:07 WARN]:      at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:241)
[12:25:07 WARN]:      at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:939)
[12:25:07 WARN]:      at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[12:25:07 WARN]:      at java.base/java.lang.Thread.run(Unknown Source)
[12:25:07 INFO]: ***************************************************************
[12:25:07 INFO]: ChatControl 8.7.6 encountered an aF! Please check your error.log and report this issue with the information in that file.
[12:25:07 INFO]: java.lang.ExceptionInInitializerError
[12:25:07 INFO]: at org.mineacademy.chatcontrol.final.nul. .cL.c(SourceFile:287)
[12:25:07 INFO]: at org.mineacademy.chatcontrol.final.nul. .cN.b(SourceFile:230)
[12:25:07 INFO]: at org.mineacademy.chatcontrol.final.nul. .cK.a(SourceFile:39)
[12:25:07 INFO]: at org.mineacademy.chatcontrol.final.nul. .cN.a(SourceFile:82)
[12:25:07 INFO]: at org.mineacademy.chatcontrol.final.nul. .bv.onEnable(SourceFile:251)
[12:25:07 INFO]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[12:25:07 INFO]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380)
[12:25:07 INFO]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
[12:25:07 INFO]: at java.base/java.lang.Thread.run(Unknown Source)
[12:25:07 INFO]: org.mineacademy.chatcontrol.final.nul. .aF: Report / (This is a proxy exception, look for errors above)
[12:25:07 INFO]: at org.mineacademy.chatcontrol.final.nul. .bQ.<clinit>(SourceFile:241)
[12:25:07 INFO]: at org.mineacademy.chatcontrol.final.nul. .cL.c(SourceFile:287)
[12:25:07 INFO]: at org.mineacademy.chatcontrol.final.nul. .cN.b(SourceFile:230)
[12:25:07 INFO]: at org.mineacademy.chatcontrol.final.nul. .cK.a(SourceFile:39)
[12:25:07 INFO]: at org.mineacademy.chatcontrol.final.nul. .cN.a(SourceFile:82)
[12:25:07 INFO]: at org.mineacademy.chatcontrol.final.nul. .bv.onEnable(SourceFile:251)
[12:25:07 INFO]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[12:25:07 INFO]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380)
[12:25:07 INFO]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
[12:25:07 INFO]: at java.base/java.lang.Thread.run(Unknown Source)
[12:25:07 INFO]:   _   _                       _
[12:25:07 INFO]:   | | | | ___   ___  _ __  ___| |
[12:25:07 INFO]:   | |_| |/ _ \ / _ \| '_ \/ __| |
[12:25:07 INFO]:   |  _  | (_) | (_) | |_) \__ \_|
[12:25:07 INFO]:   |_| |_|\___/ \___/| .__/|___(_)
[12:25:07 INFO]:                     |_|
[12:25:07 INFO]: !-----------------------------------------------------!
[12:25:07 INFO]: Error loading ChatControl v8.7.6, plugin is disabled!
[12:25:07 INFO]: Running on 1.16.2-R0.1-SNAPSHOT (v1_16_R2) & Java 11.0.8
[12:25:07 INFO]: !-----------------------------------------------------!
[12:25:07 INFO]: Error: Report / (This is a proxy exception, look for errors above)
[12:25:07 INFO]: !-----------------------------------------------------!
[12:25:07 INFO]: [ChatControl] Disabling ChatControl v8.7.6
[12:25:07 INFO]: Plugin might not shut down property. Got NullPointerException: null
[12:25:07 INFO]: Error clearing scoreboards for players..
[12:25:07 WARN]: java.lang.NoClassDefFoundError: Could not initialize class org.mineacademy.chatcontrol.final.nul. .bQ
[12:25:07 WARN]:      at org.mineacademy.chatcontrol.final.nul. .bv.onDisable(SourceFile:639)
[12:25:07 WARN]:      at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265)
[12:25:07 WARN]:      at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:415)
[12:25:07 WARN]:      at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:398)
[12:25:07 WARN]:      at org.mineacademy.chatcontrol.final.nul. .bv.a(SourceFile:616)
[12:25:07 WARN]:      at org.mineacademy.chatcontrol.final.nul. .bv.onEnable(SourceFile:330)
[12:25:07 WARN]:      at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[12:25:07 WARN]:      at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380)
[12:25:07 WARN]:      at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
[12:25:07 WARN]:      at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:499)
[12:25:07 WARN]:      at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:413)
[12:25:07 WARN]:      at net.minecraft.server.v1_16_R2.MinecraftServer.loadWorld(MinecraftServer.java:468)
[12:25:07 WARN]:      at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:241)
[12:25:07 WARN]:      at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:939)
[12:25:07 WARN]:      at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[12:25:07 WARN]:      at java.base/java.lang.Thread.run(Unknown Source)
[12:25:07 INFO]: Error closing menu inventories for players..
[12:25:07 WARN]: java.lang.NoClassDefFoundError: Could not initialize class org.mineacademy.chatcontrol.final.nul. .bQ
[12:25:07 WARN]:      at org.mineacademy.chatcontrol.final.nul. .bv.onDisable(SourceFile:649)
[12:25:07 WARN]:      at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265)
[12:25:07 WARN]:      at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:415)
[12:25:07 WARN]:      at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:398)
[12:25:07 WARN]:      at org.mineacademy.chatcontrol.final.nul. .bv.a(SourceFile:616)
[12:25:07 WARN]:      at org.mineacademy.chatcontrol.final.nul. .bv.onEnable(SourceFile:330)
[12:25:07 WARN]:      at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[12:25:07 WARN]:      at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380)
[12:25:07 WARN]:      at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
[12:25:07 WARN]:      at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:499)
[12:25:07 WARN]:      at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:413)
[12:25:07 WARN]:      at net.minecraft.server.v1_16_R2.MinecraftServer.loadWorld(MinecraftServer.java:468)
[12:25:07 WARN]:      at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:241)
[12:25:07 WARN]:      at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:939)
[12:25:07 WARN]:      at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[12:25:07 WARN]:      at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by kangarko** [comment]
@AngellitoX I did not say it will be ready this week

However yes I will do my best to get it done by Sunday. The error lays in the NBTAPI lib we are using, will try to update it.

**Comment by AngellitoX** [comment]
I know bro, hence the "should" and the strong belief that you're being a beast updating and improving! :P

**Comment by kangarko** [comment]
Ok so just to publicly state - I explained this in private too - do not misrepresent the brand by claims that are not mine. Your intentions are great but let's not do this please.

Regarding the incompatibility, got it working :)

![a](https://i.imgur.com/7SOTGWo.png)

**Comment by james-d-elliott** [comment]
Still an issue with the paper version linked. It's still beta though.

**Comment by kangarko** [comment]
ChatControl current public version does not support 1.16.2 yet. A new version with 1.16.2 support will be available tonight.

**Comment by james-d-elliott** [comment]
Ah makes sense!
