### ISSUE TITLE
1.16.1: Chat Control Encountered an aF.

### ISSUE THREAD

**Issue by TEighteen** [kangarko/ChatControl-Pro#1844]
Some players on my server have been able to explicit words despite them actually being blocked words. Every time they do say a blocked word, Chat Control does not attempt to block it but rather throws the ChatControl encountered an aF with the message: Key 'cZ listening to AsyncPlayerChatEvent at HIGH priority' is already in the map --> '12227359846474894'

I have also encountered similar aF errors with the message: 'Method cannot be null for null'

I have tried looking for the source of the issue but unable to find what is causing it. I have also reset the the config files several times along with reinstalling the plugin entirely.

https://pastebin.com/m0QNTQvE

[mftp_zip_2020_08_14_13_14_25.zip](https://github.com/kangarko/ChatControl-Pro/files/5074727/mftp_zip_2020_08_14_13_14_25.zip)

**Comment by Volgeop** [comment]
```
[16:48:51 ERROR]: Could not pass event AsyncPlayerChatEvent to ChatControl v8.7.7
org.mineacademy.chatcontrol.final.nul. .aF: Report / Key 'creating component [Chat]' is already in the map --> '84476509070194'
at org.mineacademy.chatcontrol.final.nul. .W.a(SourceFile:77) ~[?:?]
at org.mineacademy.chatcontrol.lib.fo.collection.d.a(SourceFile:86) ~[?:?]
at org.mineacademy.chatcontrol.final.nul. .ax.a(SourceFile:43) ~[?:?]
at org.mineacademy.chatcontrol.final.nul. .dj.a(SourceFile:46) ~[?:?]
at org.mineacademy.chatcontrol.final.nul. .dj.a(SourceFile:42) ~[?:?]
at org.mineacademy.chatcontrol.final.nul. .cZ.a(SourceFile:135) ~[?:?]
at org.mineacademy.chatcontrol.final.nul. .cZ.a(SourceFile:93) ~[?:?]
at org.mineacademy.chatcontrol.final.nul. .cZ.a(SourceFile:38) ~[?:?]
at org.mineacademy.chatcontrol.final.nul. .aC.execute(SourceFile:77) ~[?:?]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.15.2.jar:git-Paper-385]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-385]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-385]
at net.minecraft.server.v1_15_R1.PlayerConnection.chat(PlayerConnection.java:1782) ~[patched_1.15.2.jar:git-Paper-385]
at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1697) ~[patched_1.15.2.jar:git-Paper-385]
at net.minecraft.server.v1_15_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:41) ~[patched_1.15.2.jar:git-Paper-385]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
at java.lang.Thread.run(Thread.java:832) [?:?]
```

Same for me

**Comment by martijnpu** [comment]
Do you use the latest version 8.7.7? I had this problem in a earlier version but it's fixed in 8.7.7

**Comment by Volgeop** [comment]
It's another one.... It's not the same as it was. And yeah, when I downgraded to 8.7.6 it works....

**Comment by kangarko** [comment]
Thanks this will get fixed in a few hours.

**Comment by Volgeop** [comment]
Wasn't solved...
```
[20:48:11 WARN]: java.lang.NullPointerException
[20:48:11 WARN]: at org.mineacademy.chatcontrol.final.nul. .dc.a(SourceFile:111)
[20:48:11 WARN]: at org.mineacademy.chatcontrol.a.a(SourceFile:304)
[20:48:11 WARN]: at org.mineacademy.chatcontrol.a.b(SourceFile:213)
[20:48:11 WARN]: at org.mineacademy.chatcontrol.ChatControl.a(SourceFile:514)
[20:48:11 WARN]: at org.mineacademy.chatcontrol.ChatControl.a(SourceFile:505)
[20:48:11 WARN]: at org.mineacademy.chatcontrol.final.nul. .cS.onJoin(SourceFile:118)
[20:48:11 WARN]: at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor579.execute(Unknown Source)
[20:48:11 WARN]: at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[20:48:11 WARN]: at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[20:48:11 WARN]: at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[20:48:11 WARN]: at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
[20:48:11 WARN]: at net.minecraft.server.v1_15_R1.PlayerList.postChunkLoadJoin(PlayerList.java:240)
[20:48:11 WARN]: at net.minecraft.server.v1_15_R1.PlayerList.lambda$null$1(PlayerList.java:187)
[20:48:11 WARN]: at net.minecraft.server.v1_15_R1.PlayerConnection.tick(PlayerConnection.java:150)
[20:48:11 WARN]: at net.minecraft.server.v1_15_R1.NetworkManager.a(NetworkManager.java:373)
[20:48:11 WARN]: at net.minecraft.server.v1_15_R1.ServerConnection.c(ServerConnection.java:142)
[20:48:11 WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1354)
[20:48:11 WARN]: at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:431)
[20:48:11 WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1182)
[20:48:11 WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:971)
[20:48:11 WARN]: at java.base/java.lang.Thread.run(Thread.java:832)
```

When player join server

**Comment by WolverStones** [comment]
You have changed the placeholders in the lang file? 

Chatcontrol update: https://www.spigotmc.org/resources/♣-chatcontrol-pro™-format-and-filter-your-chat-1-7-10-1-16-1.10258/updates
Improve | Changed localization placeholders, basically we now use _ instead of "." everywhere so it is extremely consistent over all of our software:
{plugin.name} to {plugin_name}
{plugin.version} to {plugin_version}
{resourceId} to {resource_id}
{curr} to {current}

**Comment by Volgeop** [comment]
There weren't almost any of them °_°

**Comment by kangarko** [comment]
> Wasn't solved...
> 
> ```
> [20:48:11 WARN]: java.lang.NullPointerException
> [20:48:11 WARN]: at org.mineacademy.chatcontrol.final.nul. .dc.a(SourceFile:111)
> [20:48:11 WARN]: at org.mineacademy.chatcontrol.a.a(SourceFile:304)
> [20:48:11 WARN]: at org.mineacademy.chatcontrol.a.b(SourceFile:213)
> [20:48:11 WARN]: at org.mineacademy.chatcontrol.ChatControl.a(SourceFile:514)
> [20:48:11 WARN]: at org.mineacademy.chatcontrol.ChatControl.a(SourceFile:505)
> [20:48:11 WARN]: at org.mineacademy.chatcontrol.final.nul. .cS.onJoin(SourceFile:118)
> [20:48:11 WARN]: at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor579.execute(Unknown Source)
> [20:48:11 WARN]: at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
> [20:48:11 WARN]: at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
> [20:48:11 WARN]: at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
> [20:48:11 WARN]: at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
> [20:48:11 WARN]: at net.minecraft.server.v1_15_R1.PlayerList.postChunkLoadJoin(PlayerList.java:240)
> [20:48:11 WARN]: at net.minecraft.server.v1_15_R1.PlayerList.lambda$null$1(PlayerList.java:187)
> [20:48:11 WARN]: at net.minecraft.server.v1_15_R1.PlayerConnection.tick(PlayerConnection.java:150)
> [20:48:11 WARN]: at net.minecraft.server.v1_15_R1.NetworkManager.a(NetworkManager.java:373)
> [20:48:11 WARN]: at net.minecraft.server.v1_15_R1.ServerConnection.c(ServerConnection.java:142)
> [20:48:11 WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1354)
> [20:48:11 WARN]: at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:431)
> [20:48:11 WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1182)
> [20:48:11 WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:971)
> [20:48:11 WARN]: at java.base/java.lang.Thread.run(Thread.java:832)
> ```
> 
> When player join server

That is another problem, happens because of how MySQL database structure changed and it lacks the "Ignore_Timed_Messages" column. I will patch it tonight.



> You have changed the placeholders in the lang file? @Volgeop
> 
> Chatcontrol update: [https://www.spigotmc.org/resources/♣-chatcontrol-pro™-format-and-filter-your-chat-1-7-10-1-16-1.10258/updates](https://www.spigotmc.org/resources/%E2%99%A3-chatcontrol-pro%E2%84%A2-format-and-filter-your-chat-1-7-10-1-16-1.10258/updates)
> Improve | Changed localization placeholders, basically we now use _ instead of "." everywhere so it is extremely consistent over all of our software:
> {plugin.name} to {plugin_name}
> {plugin.version} to {plugin_version}
> {resourceId} to {resource_id}
> {curr} to {current}

The default files got updated, but we cannot update your existing files because your custom changes would get erased. You can simply do the update yourself, takes 3 minutes.
