### ISSUE TITLE
Could not pass event PlayerCommandPreprocessEvent to ChatControl v8.8.5

### ISSUE THREAD

**Issue by Sythindo** [kangarko/ChatControl-Pro#1951]
[19:07:19 ERROR]: Could not pass event PlayerCommandPreprocessEvent to ChatControl v8.8.5
java.lang.NullPointerException: sender is marked non-null but is null
at org.mineacademy.chatcontrol.i.L.a(SourceFile:254) ~[?:?]
at org.mineacademy.chatcontrol.i.dd.b(SourceFile:132) ~[?:?]
at org.mineacademy.chatcontrol.i.dd.a(SourceFile:44) ~[?:?]
at org.mineacademy.chatcontrol.i.dd.a(SourceFile:37) ~[?:?]
at org.mineacademy.chatcontrol.i.dm.a(SourceFile:541) ~[?:?]
at org.mineacademy.chatcontrol.i.dm.a(SourceFile:445) ~[?:?]
at org.mineacademy.chatcontrol.i.dm.a(SourceFile:287) ~[?:?]
at org.mineacademy.chatcontrol.i.cR.a(SourceFile:247) ~[?:?]
at org.mineacademy.chatcontrol.i.cR.onPlayerCommand(SourceFile:45) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor894.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.3.jar:git-Purpur-753]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.3.jar:git-Purpur-753]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.3.jar:git-Purpur-753]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.3.jar:git-Purpur-753]
at net.minecraft.server.v1_16_R2.PlayerConnection.handleCommand(PlayerConnection.java:1966) ~[patched_1.16.3.jar:git-Purpur-753]
at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:1777) ~[patched_1.16.3.jar:git-Purpur-753]
at net.minecraft.server.v1_16_R2.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.16.3.jar:git-Purpur-753]
at net.minecraft.server.v1_16_R2.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.16.3.jar:git-Purpur-753]
at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:43) ~[patched_1.16.3.jar:git-Purpur-753]
at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18) ~[patched_1.16.3.jar:git-Purpur-753]
at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.3.jar:git-Purpur-753]
at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.3.jar:git-Purpur-753]
at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.3.jar:git-Purpur-753]
at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:1203) ~[patched_1.16.3.jar:git-Purpur-753]
at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:1196) ~[patched_1.16.3.jar:git-Purpur-753]
at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.3.jar:git-Purpur-753]
at net.minecraft.server.v1_16_R2.MinecraftServer.sleepForTick(MinecraftServer.java:1172) ~[patched_1.16.3.jar:git-Purpur-753]
at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:1016) ~[patched_1.16.3.jar:git-Purpur-753]
at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:178) ~[patched_1.16.3.jar:git-Purpur-753]
at java.lang.Thread.run(Thread.java:830) [?:?]

**Comment by kangarko** [comment]
Thanks, please update to the next release available later today and comment below if it happens again, should be fixed.
