### ISSUE TITLE
1.15.2: Data.db yaml error

### ISSUE THREAD

**Issue by zeronerve** [kangarko/ChatControl-Pro#1975]
Using 8.8.8: Getting this yaml parsing error on startup. I've tried renaming/moving data.db. I couldn't find the strings mentioned in the error log in any config file. This is after updating from 8.6.6. I've also moved/renamed the plugins/ChatControl directory and allowed CC to rebuild the folder, but still get the same error.

https://pastebin.com/Sif30NDd

**Comment by AngellitoX** [comment]
Hello, this issue has been reported already. Please port back to ChatControl 8.8.7 while the issue gets resolved.

I deeply apologize for the inconvenience.

Angel from MineAcademy.org

**Comment by kangarko** [comment]
Can you show us your data.db please?

**Comment by kangarko** [comment]
Also remove it and test using the next version to see if it happens again.

**Comment by kangarko** [comment]
Closing in good faith next release will resolve this, if not comment below

**Comment by zeronerve** [comment]
Still getting this in 8.8.9...

`------------------------------------[ 26.09.2020 22:34:52 ]-----------------------------------
ChatControl 8.8.9 encountered an InvalidConfigurationException
Running Paper 1.15.2-R0.1-SNAPSHOT and Java 11.0.7
Plugins: CleanroomGenerator v1.1.0, LuckPerms v5.1.93, Essentials v2.17.2.131, Modifyworld v${project.version}, ProtocolLib v4.5.1, FastAsyncWorldEdit v1.16-376;3b66075, BungeeGuard v1.0-SNAPSHOT, EssentialsChat v2.17.2.131, goPaint v2.3.0-dev, ProtocolSupport v4.29-dev, WizeCraft-Build v1.0, BKCommonLib v1.15.2-v4, goBrush v3.5.1, LightCleaner v1.15.2-v2, HolographicDisplays v2.4.3, PlotSquared v5.13.0-Premium, Multiverse-Core v4.1.1-SNAPSHOT-b777, DiscordSRV v1.19.1, ProtocolSupportStuff v2.0.0, Multiverse-Portals v4.1.1-SNAPSHOT-b808, BungeeTabListPlus v3.2.2, TouchscreenHolograms v1.4.2, CommandSigns v2.2.0, BanManager v7.2.1, ProtocolSupportLegacyChest v1.3, ChatControl v8.8.9
----------------------------------------------------------------------------------------------

More Information: 
Error loading configuration in data.db!
Problematic section: ''
Problem: org.mineacademy.chatcontrol.i.aL: Report: Malformed YAML file d7ef8607-6085-4e07-a181-c6915afeb793.yml.broken.1512968622230 (see below for more)
InvalidConfigurationException while parsing a block mapping
 in 'string', line 1, column 1:
    lastAccountName: zeronerve
    ^
expected <block end>, but found '<block mapping start>'
 in 'string', line 27, column 3:
      x: -15.396535088159442
      ^

	 at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:56)
	 at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160)
	 at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:128)
	 at org.mineacademy.chatcontrol.i.E.d(SourceFile:248)
	 at org.mineacademy.chatcontrol.i.s.a(SourceFile:79)
	 at org.mineacademy.chatcontrol.i.s.f(SourceFile:48)
	 at org.mineacademy.chatcontrol.i.cL.a(SourceFile:362)
	 at org.mineacademy.chatcontrol.i.s.<init>(SourceFile:36)
	 at org.mineacademy.chatcontrol.i.s.<clinit>(SourceFile:29)
	 at org.mineacademy.chatcontrol.ChatControl.c(SourceFile:122)
	 at org.mineacademy.chatcontrol.i.bA.onEnable(SourceFile:294)
	 at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
	 at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380)
	 at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
	 at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:472)
	 at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:386)
ParserException while parsing a block mapping
 in 'string', line 1, column 1:
    lastAccountName: zeronerve
    ^
expected <block end>, but found '<block mapping start>'
 in 'string', line 27, column 3:
      x: -15.396535088159442
      ^

	 at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:572)
	 at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158)
	 at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:148)
	 at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:217)
	 at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:144)
	 at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:85)
	 at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:108)
	 at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:141)
	 at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:525)
	 at org.yaml.snakeyaml.Yaml.load(Yaml.java:438)
	 at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:54)
	 at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160)
	 at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:128)
	 at org.mineacademy.chatcontrol.i.E.d(SourceFile:248)
	 at org.mineacademy.chatcontrol.i.s.a(SourceFile:79)
	 at org.mineacademy.chatcontrol.i.s.f(SourceFile:48)
	 at org.mineacademy.chatcontrol.i.cL.a(SourceFile:362)
	 at org.mineacademy.chatcontrol.i.s.<init>(SourceFile:36)
	 at org.mineacademy.chatcontrol.i.s.<clinit>(SourceFile:29)
	 at org.mineacademy.chatcontrol.ChatControl.c(SourceFile:122)
	 at org.mineacademy.chatcontrol.i.bA.onEnable(SourceFile:294)
	 at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
	 at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380)
	 at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
	 at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:472)
	 at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:386)
----------------------------------------------------------------------------------------------`

**Comment by zeronerve** [comment]
[09:14:22 INFO]:     ___                  _
[09:14:22 INFO]:    / _ \  ___  _ __  ___| |
[09:14:22 INFO]:   | | | |/ _ \| '_ \/ __| |
[09:14:22 INFO]:   | |_| | (_) | |_) \__ \_|
[09:14:22 INFO]:    \___/ \___/| .__/|___(_)
[09:14:22 INFO]:              |_|
[09:14:22 INFO]: !-----------------------------------------------------!
[09:14:22 INFO]: Error loading ChatControl v8.8.9, plugin is disabled!
[09:14:22 INFO]: Running on 1.16.3-R0.1-SNAPSHOT (v1_16_R2) & Java 1.8.0_201
[09:14:22 INFO]: !-----------------------------------------------------!
[09:14:22 INFO]: Error: while parsing a block mapping
[09:14:22 INFO]: in 'string', line 1, column 1:
[09:14:22 INFO]: lastAccountName: zeronerve
[09:14:22 INFO]: ^
[09:14:22 INFO]: expected <block end>, but found '<block mapping start>'
[09:14:22 INFO]: in 'string', line 27, column 3:
[09:14:22 INFO]: x: -15.396535088159442
[09:14:22 INFO]: ^
[09:14:22 INFO]: !-----------------------------------------------------!

**Comment by zeronerve** [comment]
My data.db...
https://pastebin.com/XQhA3B0F

**Comment by zeronerve** [comment]
@kangarko please reopen this.

**Comment by zeronerve** [comment]
I'm counting on your EXISTING *premium* software to work correctly, not your future vision with fancy new features. 8.6.6 met my needs from a functionality standpoint, but we're forced to support a 1.16+ player base. Please prioritize stabilizing the basics. Or release a ChatControl "Lite" or "Core" version that addresses only the most important benefit, which in my opinion is *keeping chat clean*. All else is bloat. I didn't pay for bloat. I'd pay 10x for a simple, efficient "keep chat clean" plugin. But fix 8.8.9 first please.

So until this is fixed, we have to choose between "clean chat" or support for 1.16. If you're sensing my frustration, it's because of the apparent neglect over the past year or so, and lack of commitment to a solid direction. Frankly, based on our history, we have been afraid to move to ANY new release of ChatControlPro, because every time we do, there's downtime, bugs and a long hunt for a solution. I believe the success is found in getting the *Core* right for everyone, instead of *Everything* right for only a few.

You've helped me in numerous ways, through MineAcademy, and I appreciate you greatly! But keeping ChatControl running smoothly has been a struggle for us. You and I know this is likely a 10-minute fix.

**Comment by kangarko** [comment]
Hey,

Apology for the continuous issues. I feel your pain as a developer looking at the backend. I am committed to supporting 8th generation even after the 9th is released to give people time.

I am not ignoring you, simply I was not presently monitoring GitHub. Strangely enough your data.db loaded fine on my end. Can you please ZIP me your full CHC folder and send via a private message on SpigotMC? Mention this ticket and I will prioritize you. If I can't get this fixed that way we can have a call where you'll screenshare how to reproduce this and I'll have a look.

You're right, you can't please everyone and building a monster will kill us. Next generation of will keep things simple and stable, focusing on core features instead of adding flash. I'm rewriting the core from the ground up.

**Comment by kangarko** [comment]
I've noticed something looking at your report again:

`d7ef8607-6085-4e07-a181-c6915afeb793.yml.broken.1512968622230`

This is definitely not ChatControl. The file looks like from the Essentials/userdata folder or such, and has the .broken.timestamp prefix appended. Try looking in your plugins/ folder where that file is located and remove it.

**Comment by zeronerve** [comment]
Nice. That fixed it. Thanks for the quick response!

**Comment by kangarko** [comment]
Oh that was quick! Happy to hear that :) If there's anything I can help you with besides doing the obvious please let me know!
