### ISSUE TITLE
1.8.8:Getting error on /r

### ISSUE THREAD

**Issue by Kedarin** [kangarko/ChatControl-Pro#2036]
Hey I have a problem with ChatControlPro when user use /r command I have this error on log: https://pastebin.com/dmSqX3mL
( No problem in the game ), formatting.yml is set to false

And other problem: 
I use the join message by ChatControlPro and only the join message ( [+] %player% ) are duplicated ( two times )
not the leave message I don't understand why, this is my config : https://pastebin.com/11MSRYL8

Thank's

**Comment by BobbyMere** [comment]
I have the same issue

**Comment by kangarko** [comment]
Thanks, was fixed yesterday.

**Comment by Kedarin** [comment]
Already a problem with players message join (display two times)

And:
ChatControl 8.8.18 encountered an aM! Please check your error.log and report this issue with the information in that file.

Error.log:

More Information: 
Method cannot be null for com.earth2me.essentials.User@8d4b10d0
aM Report: Method cannot be null for com.earth2me.essentials.User@8d4b10d0
	 at org.mineacademy.chatcontrol.i.V.a(SourceFile:60)
	 at org.mineacademy.chatcontrol.i.Q.a(SourceFile:514)
	 at org.mineacademy.chatcontrol.lib.fo.model.q.d(SourceFile:1484)
	 at org.mineacademy.chatcontrol.lib.fo.model.v.e(SourceFile:795)
	 at org.mineacademy.chatcontrol.i.dM.a(SourceFile:117)
	 at org.mineacademy.chatcontrol.i.cY.a(SourceFile:268)
	 at org.mineacademy.chatcontrol.i.cY.onPlayerCommand(SourceFile:45)
	 at spg.lgdev.events.executor.asm.generated.GeneratedEventExecutor859.execute(Unknown Source)
	 at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:68)
	 at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78)
	 at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
	 at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:570)
	 at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:549)
---------------------------------------------------------------------------------------------

**Comment by kangarko** [comment]
I apology for this and will release a fix shortly.
