### ISSUE TITLE
Plugin Disabled?

### ISSUE THREAD

**Issue by Darien5** [kangarko/ChatControl-Pro#2048]
Server Verison: 1.16.3

I've installed Chat Control and all the other requirements to have it operable. I restarted the server and whenever I type a command in chat, I always get the message, "Cannot use this command while the plugin is disabled". Is there a way to fix this issue?

**Comment by malonnnn** [comment]
You should check the console for errors in regards to startup

**Comment by Darien5** [comment]
<img width="817" alt="Screen Shot 2020-10-22 at 8 29 42 AM" src="https://user-images.githubusercontent.com/73259036/96895235-0f79c380-1441-11eb-9415-574bda9edc40.png">

This is what I got in the console...

**Comment by JHiroshige** [comment]
Hey, I also got that problem so I changed back to an older version till this gets fixxed

**Comment by james-d-elliott** [comment]
If you're staying on 8.8.17, there are two versions of this release. Make sure you have the latest one. It apparently has this issue fixed. Otherwise you probably want to supply more logs than just "Error loading". There should be more information above.

**Comment by LeehamElectronics** [comment]
@Darien5 Please upload your entire latest.log file onto paste showing the entire server load console output so we can diagnose the issue.
Thanks

**Comment by Darien5** [comment]
------------------------------------[ 23.10.2020 21:51:45 ]-----------------------------------
ChatControl 8.8.17 encountered a NullPointerException
Running CraftBukkit 1.16.3-R0.1-SNAPSHOT and Java 1.8.0_211
Plugins: PluginConstructorAPI v1.0.52, NoCollisionPlugin v2.3, PlaceholderAPI v2.10.6, BungeeChatAPI v1.0.1, Elections v2.6, AntiAFKPlus v3.02, PlayTime v2.2-1.8, AutoRestart v4.2.1, NoteBlockAPI v1.6.1-SNAPSHOT, EpicPluginLib v1.6, CraftingStore v2.4.2, PlayMoreSounds v3.1.1, StopPushing v1.2, LightAPI v3.2.9, LuckPerms v5.1.82, Skript v2.5-beta2, AntiAdvertiser v1.2.3, PwnPlantGrowth v2.5.7, ClearLag v3.1.6, ArmorStandEditor v1.16-24, TAB-BukkitBridge v1.1, AutoMessage v1.4, SkQuery v3.6.5, ore-control v2020.09.19, VoidAvoid v1.2, Votifier v2.7.1, SilkSpawners v1.6, ProtocolLib v4.5.1, Multiverse-Core v4.1.0-b775, DeathMessagesPrime v1.16.5, ImageOnMap v4.0, CS-CoreLib vDEV - 90 (git 9dd4a1cf), Vault v1.7.2-b107, Matrix v5.2.1, HolographicDisplays v2.4.4, PlayerVaults v4.1.15, Multiverse-NetherPortals v4.1.0-b763, MyCommand v5.6.7, EZRanksPro v1.3.2, dynmap v3.1-beta4-421, WorldEdit v7.2.0-beta-05+e575ffe, GUIPlus v2.7, Essentials v2.17.2.0, BountyHunters v2.2.6, HeadDatabase v4.12.6, Citizens v2.0.27-SNAPSHOT (build 2113), VotingPlugin v5.24.1, DiscordSRV v1.20.0, TradeSystem v1.2.1, EssentialsChat v2.17.2.0, HolographicPlaceholders v2.1.2 Stable, TAB v2.8.7, Lottery v1.4.3, BlockParticles v1.11.1-RELEASE, LeaderHeadsRevamped v4.0.6, WorldGuard v7.0.3;5407315, CitizensCMD v2.5.1, AuctionHouse v2.1.8, EssentialsXMPP v2.17.2.0, EssentialsProtect v2.17.2.0, EssentialsGeoIP v2.17.2.0, EssentialsAntiBuild v2.17.2.0, CombatLogX v10.3.0.0, EssentialsSpawn v2.17.2.0, CoreProtect v19.2, McDuels v2.1.6, TitleManager v2.3.0, Denizen v1.1.6-SNAPSHOT (build 1716-REL), ChatControl v8.8.17, Jobs v4.16.2, ActionHealth v3.5.1, Kingdoms v1.8.19, Plan v5.1 build 770, FogusCore v1.9.9, ProCosmetics v11.9.1, Botany v10, QuickShop v4.0.4.14, FactionsTop v5.0.55.4, GoldenCrates v3.9.6, FactionsTopGuiV5-2.0 v2.0.6, FactionsTopv5NPCs v1.0.13
----------------------------------------------------------------------------------------------

More Information: 
Failed to load variable item from variables
NullPointerException (DO NOT REPORT, PLEASE FIX YOURSELF) Please set 'Type' as variable type (available: FORMAT, MESSAGE) in plugins/ChatControl/variables/item.yml
	 at java.util.Objects.requireNonNull(Objects.java:228)
	 at org.mineacademy.chatcontrol.lib.fo.model.ac.f(SourceFile:129)
	 at org.mineacademy.chatcontrol.i.cO.a(SourceFile:336)
	 at org.mineacademy.chatcontrol.lib.fo.model.ac.<init>(SourceFile:113)
	 at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	 at org.mineacademy.chatcontrol.lib.fo.model.i.c(SourceFile:161)
	 at org.mineacademy.chatcontrol.lib.fo.model.i.a(SourceFile:128)
	 at org.mineacademy.chatcontrol.lib.fo.model.ac.a(SourceFile:274)
	 at org.mineacademy.chatcontrol.ChatControl.f(SourceFile:190)
	 at org.mineacademy.chatcontrol.i.bB.onEnable(SourceFile:284)
	 at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
	 at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351)
	 at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
	 at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:494)
	 at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:408)
----------------------------------------------------------------------------------------------

**Comment by Darien5** [comment]
------------------------------------[ 23.10.2020 21:51:45 ]-----------------------------------
ChatControl 8.8.17 encountered a NullPointerException
Running CraftBukkit 1.16.3-R0.1-SNAPSHOT and Java 1.8.0_211
Plugins: PluginConstructorAPI v1.0.52, NoCollisionPlugin v2.3, PlaceholderAPI v2.10.6, BungeeChatAPI v1.0.1, Elections v2.6, AntiAFKPlus v3.02, PlayTime v2.2-1.8, AutoRestart v4.2.1, NoteBlockAPI v1.6.1-SNAPSHOT, EpicPluginLib v1.6, CraftingStore v2.4.2, PlayMoreSounds v3.1.1, StopPushing v1.2, LightAPI v3.2.9, LuckPerms v5.1.82, Skript v2.5-beta2, AntiAdvertiser v1.2.3, PwnPlantGrowth v2.5.7, ClearLag v3.1.6, ArmorStandEditor v1.16-24, TAB-BukkitBridge v1.1, AutoMessage v1.4, SkQuery v3.6.5, ore-control v2020.09.19, VoidAvoid v1.2, Votifier v2.7.1, SilkSpawners v1.6, ProtocolLib v4.5.1, Multiverse-Core v4.1.0-b775, DeathMessagesPrime v1.16.5, ImageOnMap v4.0, CS-CoreLib vDEV - 90 (git 9dd4a1cf), Vault v1.7.2-b107, Matrix v5.2.1, HolographicDisplays v2.4.4, PlayerVaults v4.1.15, Multiverse-NetherPortals v4.1.0-b763, MyCommand v5.6.7, EZRanksPro v1.3.2, dynmap v3.1-beta4-421, WorldEdit v7.2.0-beta-05+e575ffe, GUIPlus v2.7, Essentials v2.17.2.0, BountyHunters v2.2.6, HeadDatabase v4.12.6, Citizens v2.0.27-SNAPSHOT (build 2113), VotingPlugin v5.24.1, DiscordSRV v1.20.0, TradeSystem v1.2.1, EssentialsChat v2.17.2.0, HolographicPlaceholders v2.1.2 Stable, TAB v2.8.7, Lottery v1.4.3, BlockParticles v1.11.1-RELEASE, LeaderHeadsRevamped v4.0.6, WorldGuard v7.0.3;5407315, CitizensCMD v2.5.1, AuctionHouse v2.1.8, EssentialsXMPP v2.17.2.0, EssentialsProtect v2.17.2.0, EssentialsGeoIP v2.17.2.0, EssentialsAntiBuild v2.17.2.0, CombatLogX v10.3.0.0, EssentialsSpawn v2.17.2.0, CoreProtect v19.2, McDuels v2.1.6, TitleManager v2.3.0, Denizen v1.1.6-SNAPSHOT (build 1716-REL), ChatControl v8.8.17, Jobs v4.16.2, ActionHealth v3.5.1, Kingdoms v1.8.19, Plan v5.1 build 770, FogusCore v1.9.9, ProCosmetics v11.9.1, Botany v10, QuickShop v4.0.4.14, FactionsTop v5.0.55.4, GoldenCrates v3.9.6, FactionsTopGuiV5-2.0 v2.0.6, FactionsTopv5NPCs v1.0.13
----------------------------------------------------------------------------------------------

More Information: 
Failed to load variable item from variables
NullPointerException (DO NOT REPORT, PLEASE FIX YOURSELF) Please set 'Type' as variable type (available: FORMAT, MESSAGE) in plugins/ChatControl/variables/item.yml
	 at java.util.Objects.requireNonNull(Objects.java:228)
	 at org.mineacademy.chatcontrol.lib.fo.model.ac.f(SourceFile:129)
	 at org.mineacademy.chatcontrol.i.cO.a(SourceFile:336)
	 at org.mineacademy.chatcontrol.lib.fo.model.ac.<init>(SourceFile:113)
	 at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	 at org.mineacademy.chatcontrol.lib.fo.model.i.c(SourceFile:161)
	 at org.mineacademy.chatcontrol.lib.fo.model.i.a(SourceFile:128)
	 at org.mineacademy.chatcontrol.lib.fo.model.ac.a(SourceFile:274)
	 at org.mineacademy.chatcontrol.ChatControl.f(SourceFile:190)
	 at org.mineacademy.chatcontrol.i.bB.onEnable(SourceFile:284)
	 at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
	 at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351)
	 at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
	 at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:494)
	 at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:408)
----------------------------------------------------------------------------------------------

**Comment by Darien5** [comment]
------------------------------------[ 23.10.2020 21:51:45 ]-----------------------------------
ChatControl 8.8.17 encountered a NullPointerException
Running CraftBukkit 1.16.3-R0.1-SNAPSHOT and Java 1.8.0_211
Plugins: ChatControl v8.8.17, 
----------------------------------------------------------------------------------------------

More Information: 
Failed to load variable item from variables
NullPointerException (DO NOT REPORT, PLEASE FIX YOURSELF) Please set 'Type' as variable type (available: FORMAT, MESSAGE) in plugins/ChatControl/variables/item.yml
	 at java.util.Objects.requireNonNull(Objects.java:228)
	 at org.mineacademy.chatcontrol.lib.fo.model.ac.f(SourceFile:129)
	 at org.mineacademy.chatcontrol.i.cO.a(SourceFile:336)
	 at org.mineacademy.chatcontrol.lib.fo.model.ac.<init>(SourceFile:113)
	 at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	 at org.mineacademy.chatcontrol.lib.fo.model.i.c(SourceFile:161)
	 at org.mineacademy.chatcontrol.lib.fo.model.i.a(SourceFile:128)
	 at org.mineacademy.chatcontrol.lib.fo.model.ac.a(SourceFile:274)
	 at org.mineacademy.chatcontrol.ChatControl.f(SourceFile:190)
	 at org.mineacademy.chatcontrol.i.bB.onEnable(SourceFile:284)
	 at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
	 at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351)
	 at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
	 at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:494)
	 at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:408)
----------------------------------------------------------------------------------------------

**Comment by Darien5** [comment]
There is more plugins other than chat control-pro too

**Comment by LeehamElectronics** [comment]
Can you please upload your entire console log using the pastebin website and just put the link here.
I can not read your comment on my mobile phone app.

**Comment by Darien5** [comment]
https://pastebin.pl/view/287e00e2 for the error logs (All the errors are the same) and then the picture above is what it showed in the console. I looked into other logs and it doesn't show anything.

**Comment by NerdyBirder** [comment]
What I have to do to get the latest version to work is to insert this line "Type: MESSAGE" into all three files in the variables section, then remove the "s and the { } s from the first line in the configs. I just followed the directions the error kept giving and eventually it worked.

**Comment by LeehamElectronics** [comment]
I just deleted my entire folder and let it regenerate and it was all good afterwards.

**Comment by Darien5** [comment]
I fixed it by getting the latest .jar file
