### ISSUE TITLE
ChatControl 7.3.6 Failed to load on Spigot 1.8.8

### ISSUE THREAD

**Issue by Porama6400** [kangarko/ChatControl-Pro#210]
[20:37:05] [Server thread/INFO]: [ChatControl] Enabling ChatControl v7.3.6
[20:37:06] [Server thread/INFO]: [0;36;1m _____ _           _    _____            _             _  [0;35;1m+[m
[20:37:06] [Server thread/INFO]: [0;36;1m / ____| |         | |  / ____|          | |           | |[m
[20:37:06] [Server thread/INFO]: [0;36;1m| |    | |__   __ _| |_| |     ___  _ __ | |_ _ __ ___ | |[m
[20:37:06] [Server thread/INFO]: [0;36;1m| |    | '_ \ / _` | __| |    / _ \| '_ \| __| '__/ _ \| |[m
[20:37:06] [Server thread/INFO]: [0;36;22m| |____| | | | (_| | |_| |___| (_) | | | | |_| | | (_) | |[m
[20:37:06] [Server thread/INFO]: [0;36;22m \_____|_| |_|\__,_|\__|\_____\___/|_| |_|\__|_|  \___/|_|[m
[20:37:06] [Server thread/INFO]:  [m
[20:37:06] [Server thread/INFO]: [0;36;22mConfiguration loads[0;30;1m..[m
[20:37:06] [Server thread/INFO]: [0;37;22mUpdate settings.yml at [0;36;1m'[0;37;1mMySQL.Connection.Connector_Advanced[0;36;1m' [0;37;22m-> [0;36;1m'[0;37;1mjdbc:mysql://{host}:{port}/{database}?autoReconnect=true[0;36;1m'[m[m
[20:37:06] [Server thread/INFO]: Connecting to MySQL database...[m
[20:37:06] [Server thread/INFO]: [0;33;1mSaved updated file: settings.yml (# Comments removed)[m
[20:37:06] [Server thread/INFO]: [0;37;22m*-----------------------------------------------*[m
[20:37:06] [Server thread/INFO]:  [0;31;1mError making condition at Death_Messages.Entity_Attack[m
[20:37:06] [Server thread/INFO]:  [0;31;1mError: super: The enum 'EntityType' does not contain 'DRAGON_FIREBALL'! Available values: DROPPED_ITEM, EXPERIENCE_ORB, LEASH_HITCH, PAINTING, ARROW, SNOWBALL, FIREBALL, SMALL_FIREBALL, ENDER_PEARL, ENDER_SIGNAL, THROWN_EXP_BOTTLE, ITEM_FRAME, WITHER_SKULL, PRIMED_TNT, FALLING_BLOCK, FIREWORK, ARMOR_STAND, MINECART_COMMAND, BOAT, MINECART, MINECART_CHEST, MINECART_FURNACE, MINECART_TNT, MINECART_HOPPER, MINECART_MOB_SPAWNER, CREEPER, SKELETON, SPIDER, GIANT, ZOMBIE, SLIME, GHAST, PIG_ZOMBIE, ENDERMAN, CAVE_SPIDER, SILVERFISH, BLAZE, MAGMA_CUBE, ENDER_DRAGON, WITHER, BAT, WITCH, ENDERMITE, GUARDIAN, PIG, SHEEP, COW, CHICKEN, SQUID, WOLF, MUSHROOM_COW, SNOWMAN, OCELOT, IRON_GOLEM, HORSE, RABBIT, VILLAGER, ENDER_CRYSTAL, SPLASH_POTION, EGG, FISHING_HOOK, LIGHTNING, WEATHER, PLAYER, COMPLEX_PART, UNKNOWN[m
[20:37:06] [Server thread/INFO]: [0;37;22m*-----------------------------------------------*[m
[20:37:06] [Server thread/WARN]: java.lang.reflect.InvocationTargetException
[20:37:06] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20:37:06] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[20:37:06] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[20:37:06] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[20:37:06] [Server thread/WARN]: 	at me.kangarko.chatcontrol.  .....com8.protected(SourceFile:128)
[20:37:06] [Server thread/WARN]: 	at me.kangarko.chatcontrol.  .....com8.super(SourceFile:112)
[20:37:06] [Server thread/WARN]: 	at me.kangarko.chatcontrol.  .....com8.lPT3(SourceFile:93)
[20:37:06] [Server thread/WARN]: 	at me.kangarko.chatcontrol.  .....LpT8.protected(SourceFile:48)
[20:37:06] [Server thread/WARN]: 	at me.kangarko.chatcontrol.  .....com8.protected(SourceFile:56)
[20:37:06] [Server thread/WARN]: 	at me.kangarko.chatcontrol.  .....con.onEnable(SourceFile:65)
[20:37:06] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[20:37:06] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
[20:37:06] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[20:37:06] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357)
[20:37:06] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317)
[20:37:06] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414)
[20:37:06] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378)
[20:37:06] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333)
[20:37:06] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263)
[20:37:06] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525)
[20:37:06] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[20:37:06] [Server thread/WARN]: Caused by: me.kangarko.chatcontrol.  .....lpT7$super: The enum 'EntityType' does not contain 'DRAGON_FIREBALL'! Available values: DROPPED_ITEM, EXPERIENCE_ORB, LEASH_HITCH, PAINTING, ARROW, SNOWBALL, FIREBALL, SMALL_FIREBALL, ENDER_PEARL, ENDER_SIGNAL, THROWN_EXP_BOTTLE, ITEM_FRAME, WITHER_SKULL, PRIMED_TNT, FALLING_BLOCK, FIREWORK, ARMOR_STAND, MINECART_COMMAND, BOAT, MINECART, MINECART_CHEST, MINECART_FURNACE, MINECART_TNT, MINECART_HOPPER, MINECART_MOB_SPAWNER, CREEPER, SKELETON, SPIDER, GIANT, ZOMBIE, SLIME, GHAST, PIG_ZOMBIE, ENDERMAN, CAVE_SPIDER, SILVERFISH, BLAZE, MAGMA_CUBE, ENDER_DRAGON, WITHER, BAT, WITCH, ENDERMITE, GUARDIAN, PIG, SHEEP, COW, CHICKEN, SQUID, WOLF, MUSHROOM_COW, SNOWMAN, OCELOT, IRON_GOLEM, HORSE, RABBIT, VILLAGER, ENDER_CRYSTAL, SPLASH_POTION, EGG, FISHING_HOOK, LIGHTNING, WEATHER, PLAYER, COMPLEX_PART, UNKNOWN
[20:37:06] [Server thread/WARN]: 	at me.kangarko.chatcontrol.  .....lpT7.protected(SourceFile:134)
[20:37:06] [Server thread/WARN]: 	at me.kangarko.chatcontrol.  .....lpT7.protected(SourceFile:103)
[20:37:06] [Server thread/WARN]: 	at me.kangarko.chatcontrol.  .....lpt8.super(SourceFile:25)
[20:37:06] [Server thread/WARN]: 	at me.kangarko.chatcontrol.  .....LpT8$2.protected(SourceFile:224)
[20:37:06] [Server thread/WARN]: 	at me.kangarko.chatcontrol.  .....LpT8$2.protected(SourceFile:219)
[20:37:06] [Server thread/WARN]: 	at me.kangarko.chatcontrol.  .....LpT8.protected(SourceFile:308)
[20:37:06] [Server thread/WARN]: 	at me.kangarko.chatcontrol.  .....LpT8.protected(SourceFile:259)
[20:37:06] [Server thread/WARN]: 	at me.kangarko.chatcontrol.  .....LpT8.transient(SourceFile:239)
[20:37:06] [Server thread/WARN]: 	at me.kangarko.chatcontrol.  .....LpT8.init(SourceFile:101)
[20:37:06] [Server thread/WARN]: 	... 21 more
[20:37:06] [Server thread/INFO]: [0;31;1m  _   _                       _ [m
[20:37:06] [Server thread/INFO]: [0;31;1m  | | | | ___   ___  _ __  ___| |[m
[20:37:06] [Server thread/INFO]: [0;31;1m  | |_| |/ _ \ / _ \| '_ \/ __| |[m
[20:37:06] [Server thread/INFO]: [0;31;1m  |  _  | (_) | (_) | |_) \__ \_|[m
[20:37:06] [Server thread/INFO]: [0;31;22m  |_| |_|\___/ \___/| .__/|___(_)[m
[20:37:06] [Server thread/INFO]: [0;31;22m                    |_|          [m
[20:37:06] [Server thread/INFO]: [0;31;22m!-----------------------------------------------------![m
[20:37:06] [Server thread/INFO]:  [0;31;1mError loading ChatControl v7.3.6, plugin is disabled![m
[20:37:06] [Server thread/INFO]:  [0;31;1mRunning on 1.8.8-R0.1-SNAPSHOT (v1_8_R3) & Java 1.8.0_112[m
[20:37:06] [Server thread/INFO]: [0;31;22m!-----------------------------------------------------![m
[20:37:06] [Server thread/INFO]:  [0;31;1mError: The enum 'EntityType' does not contain 'DRAGON_FIREBALL'! Available values: DROPPED_ITEM, EXPERIENCE_ORB, LEASH_HITCH, PAINTING, ARROW, SNOWBALL, FIREBALL, SMALL_FIREBALL, ENDER_PEARL, ENDER_SIGNAL, THROWN_EXP_BOTTLE, ITEM_FRAME, WITHER_SKULL, PRIMED_TNT, FALLING_BLOCK, FIREWORK, ARMOR_STAND, MINECART_COMMAND, BOAT, MINECART, MINECART_CHEST, MINECART_FURNACE, MINECART_TNT, MINECART_HOPPER, MINECART_MOB_SPAWNER, CREEPER, SKELETON, SPIDER, GIANT, ZOMBIE, SLIME, GHAST, PIG_ZOMBIE, ENDERMAN, CAVE_SPIDER, SILVERFISH, BLAZE, MAGMA_CUBE, ENDER_DRAGON, WITHER, BAT, WITCH, ENDERMITE, GUARDIAN, PIG, SHEEP, COW, CHICKEN, SQUID, WOLF, MUSHROOM_COW, SNOWMAN, OCELOT, IRON_GOLEM, HORSE, RABBIT, VILLAGER, ENDER_CRYSTAL, SPLASH_POTION, EGG, FISHING_HOOK, LIGHTNING, WEATHER, PLAYER, COMPLEX_PART, UNKNOWN[m
[20:37:06] [Server thread/INFO]: [0;31;22m!-----------------------------------------------------![m
[20:37:06] [Server thread/INFO]: [ChatControl] Disabling ChatControl v7.3.6

ChatControl v7.3.6
BungeeControlBridge v1.4
BungeeCord latest
Server: Spigot 1.11.2 + ProtocolSupport and Spigot 1.8 + ViaVersion

After update from CC 7.3.5 to 7.3.6 This error appear

**Comment by kangarko** [comment]
Open messages.yml and remove the key at **Death_Messages.Entity_Attack.dragon_fireball**
