### ISSUE TITLE
1.16.4: MCMMO party chat related error

### ISSUE THREAD

**Issue by LogGits** [kangarko/ChatControl-Pro#2102]
```
Console 23:12:33
at org.mineacademy.chatcontrol.hook.c.onChat(SourceFile:33) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1025.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.4.jar:git-Paper-262]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.4.jar:git-Paper-262]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.4.jar:git-Paper-262]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.4.jar:git-Paper-262]
at com.gmail.nossr50.chat.mailer.PartyChatMailer.processChatMessage(PartyChatMailer.java:29) ~[?:?]
at com.gmail.nossr50.chat.ChatManager.processPlayerMessage(ChatManager.java:76) ~[?:?]
at com.gmail.nossr50.chat.ChatManager.processPlayerMessage(ChatManager.java:60) ~[?:?]
at com.gmail.nossr50.commands.chat.PartyChatCommand.processCommandArgsPlayer(PartyChatCommand.java:66) ~[?:?]
at com.gmail.nossr50.commands.chat.PartyChatCommand.processCommand(PartyChatCommand.java:49) ~[?:?]
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
at com.gmail.nossr50.mcmmo.acf.RegisteredCommand.invoke(RegisteredCommand.java:152) ~[?:?]
at com.gmail.nossr50.mcmmo.acf.BaseCommand.executeCommand(BaseCommand.java:577) ~[?:?]
at com.gmail.nossr50.mcmmo.acf.BaseCommand.execute(BaseCommand.java:513) ~[?:?]
at com.gmail.nossr50.mcmmo.acf.RootCommand.execute(RootCommand.java:99) ~[?:?]
at com.gmail.nossr50.mcmmo.acf.BukkitRootCommand.execute(BukkitRootCommand.java:81) ~[?:?]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.4.jar:git-Paper-262]
at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:802) ~[patched_1.16.4.jar:git-Paper-262]
at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2007) ~[?:git-Paper-262]
at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:1818) ~[?:git-Paper-262]
at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1771) ~[?:git-Paper-262]
at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.16.4.jar:git-Paper-262]
at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.16.4.jar:git-Paper-262]
at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.4.jar:git-Paper-262]
at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.4.jar:git-Paper-262]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.4.jar:git-Paper-262]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.4.jar:git-Paper-262]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.4.jar:git-Paper-262]
at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1136) ~[patched_1.16.4.jar:git-Paper-262]
at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1129) ~[patched_1.16.4.jar:git-Paper-262]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.4.jar:git-Paper-262]
at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1090) ~[patched_1.16.4.jar:git-Paper-262]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1004) ~[patched_1.16.4.jar:git-Paper-262]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.4.jar:git-Paper-262]
at java.lang.Thread.run(Thread.java:834) [?:?]
```
paper 1.16.4 build 262
chatcontrol pro build 8.9.0-BETA
Latest mcmmo

**Comment by kangarko** [comment]
Thanks, will update mcmmo hook tonight
