### ISSUE TITLE
1.16.4: Error

### ISSUE THREAD

**Issue by LogGits** [kangarko/ChatControl-Pro#2130]
Error typing after startup:
```
01:54:15
Can't keep up! Is the server overloaded? Running 5012ms or 100 ticks behind
INFO 01:54:17
ChatControl 8.9.2 encountered a FoException! Please check your error.log and report this issue with the information in that file.
org.mineacademy.chatcontrol.lib.fo.exception.FoException: Report: Async file plugins/ChatControl/data.db saving was temporarily disabled - report this error!
at org.mineacademy.chatcontrol.lib.fo.Valid.checkBoolean(Valid.java:81)
at org.mineacademy.chatcontrol.lib.fo.Valid.checkSync(Valid.java:142)
at org.mineacademy.chatcontrol.lib.fo.settings.ConfigInstance.save(YamlConfig.java:2056)
at org.mineacademy.chatcontrol.lib.fo.settings.YamlConfig.save(YamlConfig.java:452)
at org.mineacademy.chatcontrol.SimplePlayerCache.save(SimplePlayerCache.java:287)
at org.mineacademy.chatcontrol.SimplePlayerCache.setChatMode(SimplePlayerCache.java:519)
at org.mineacademy.chatcontrol.listener.ListenerChecker.execute(ListenerChecker.java:97)
at org.mineacademy.chatcontrol.listener.ListenerChecker.execute(ListenerChecker.java:41)
at org.mineacademy.chatcontrol.lib.fo.event.SimpleListener.execute(SimpleListener.java:85)
!-----------------------------------------------------!
Unhandled exception listening to AsyncPlayerChatEvent
!-----------------------------------------------------!
```
paper 1.16.4 build 275
chc 8.9.2
**EDIT: Seems to happen quite often.**

**Comment by kangarko** [comment]
Thanks, will fix asap.
