### ISSUE TITLE
Paper-253 1.16.3: Error loading database data for <playername> (NullPointerException)

### ISSUE THREAD

**Issue by BakiDance** [kangarko/ChatControl-Pro#2137]
Since updating to ChatControlPro 8.9.3 and re-configuring the plugin, every time a player joins the console displays an error.

```
[21:16:44 INFO]: Silica_wife[/184.170.245.103:46248] logged in with entity id 62633 at ([survival]141.43285538262998, 72.0, 69.78770237456831)
[21:16:44 INFO]: !-----------------------------------------------------!
[21:16:44 INFO]: Failed to parse JSON from null
[21:16:44 INFO]: !-----------------------------------------------------!
[21:16:44 INFO]: ChatControl 8.9.3 encountered a NullPointerException! Please check your error.log and report this issue with the information in that file.
[21:16:44 INFO]: ChatControl 8.9.3 encountered a NullPointerException! Please check your error.log and report this issue with the information in that file.
[21:16:44 INFO]: java.lang.NullPointerException
[21:16:44 INFO]: at org.mineacademy.chatcontrol.lib.fo.collection.StrictMap.putAll(StrictMap.java:121)
[21:16:44 INFO]: at org.mineacademy.chatcontrol.lib.fo.collection.SerializedMap.fromJson(SerializedMap.java:1089)
[21:16:44 INFO]: at org.mineacademy.chatcontrol.model.MySQLManager.lambda$loadAsync$6(MySQLManager.java:166)
[21:16:44 INFO]: at org.mineacademy.chatcontrol.lib.fo.remain.CompRunnable$SafeRunnable.run(CompRunnable.java:35)
[21:16:44 INFO]: !-----------------------------------------------------!
[21:16:44 INFO]: Error loading database data for Silica_wife
[21:16:44 INFO]: !-----------------------------------------------------!
[21:16:44 INFO]: [+] Silica_wife


```
Error log: [error.log](https://github.com/kangarko/ChatControl-Pro/files/5549868/error.log)
Config ZIP: [ChatControl.zip](https://github.com/kangarko/ChatControl-Pro/files/5549888/ChatControl.zip)

**Comment by x1p** [comment]
Exact same issue here for some random player.
I checked that particular player. His data does not exist in the mysql database.

**Comment by kangarko** [comment]
I apology for missing out on this and will ship a fix quickly!
