### ISSUE TITLE
plugin doesn't launch correctly

### ISSUE THREAD

**Issue by juju78660** [kangarko/ChatControl-Pro#214]
Hi, I'm having an issue launching the plugin on my server, it don't work, i don't know why...
`[ChatControl] Enabling ChatControl v7.3.9
[20:08:43] [Server thread/INFO]:  _____ _           _    _____            _             _  +
[20:08:43] [Server thread/INFO]:  / ____| |         | |  / ____|          | |           | |
[20:08:43] [Server thread/INFO]: | |    | |__   __ _| |_| |     ___  _ __ | |_ _ __ ___ | |
[20:08:43] [Server thread/INFO]: | |    | '_ \ / _` | __| |    / _ \| '_ \| __| '__/ _ \| |
[20:08:43] [Server thread/INFO]: | |____| | | | (_| | |_| |___| (_) | | | | |_| | | (_) | |
[20:08:43] [Server thread/INFO]:  \_____|_| |_|\__,_|\__|\_____\___/|_| |_|\__|_|  \___/|_|
[20:08:43] [Server thread/INFO]:  
[20:08:43] [Server thread/INFO]: Configuration loads..
[20:08:43] [Server thread/INFO]: Update settings.yml at 'Version' -> '17'
[20:08:43] [Server thread/WARN]: java.lang.reflect.InvocationTargetException
[20:08:43] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20:08:43] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[20:08:43] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[20:08:43] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[20:08:43] [Server thread/WARN]: 	at me.kangarko.chatcontrol.  .....lPT1.protected(SourceFile:128)
[20:08:43] [Server thread/WARN]: 	at me.kangarko.chatcontrol.  .....lPT1.super(SourceFile:104)
[20:08:43] [Server thread/WARN]: 	at me.kangarko.chatcontrol.  .....lPT1.PRN(SourceFile:93)
[20:08:43] [Server thread/WARN]: 	at me.kangarko.chatcontrol.  .....COM5.protected(SourceFile:55)
[20:08:43] [Server thread/WARN]: 	at me.kangarko.chatcontrol.  .....lPT1.protected(SourceFile:56)
[20:08:43] [Server thread/WARN]: 	at me.kangarko.chatcontrol.  .....lPt4.onEnable(SourceFile:65)
[20:08:43] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271)
[20:08:43] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
[20:08:43] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[20:08:43] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:376)
[20:08:43] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:326)
[20:08:43] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.reload(CraftServer.java:750)
[20:08:43] [Server thread/WARN]: 	at org.bukkit.Bukkit.reload(Bukkit.java:540)
[20:08:43] [Server thread/WARN]: 	at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:25)
[20:08:43] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[20:08:43] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:650)
[20:08:43] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1344)
[20:08:43] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1179)
[20:08:43] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[20:08:43] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
[20:08:43] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[20:08:43] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[20:08:43] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[20:08:43] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46)
[20:08:43] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:747)
[20:08:43] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399)
[20:08:43] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678)
[20:08:43] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576)
[20:08:43] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[20:08:43] [Server thread/WARN]: Caused by: java.lang.NullPointerException: Defaults don't contain List at Debugger.Sections
[20:08:43] [Server thread/WARN]: 	at java.util.Objects.requireNonNull(Objects.java:228)
[20:08:43] [Server thread/WARN]: 	at me.kangarko.chatcontrol.  .....lPT1.protected(SourceFile:317)
[20:08:43] [Server thread/WARN]: 	at me.kangarko.chatcontrol.  .....lPT1.protected(SourceFile:173)
[20:08:43] [Server thread/WARN]: 	at me.kangarko.chatcontrol.  .....lPT1.protected(SourceFile:186)
[20:08:43] [Server thread/WARN]: 	at me.kangarko.chatcontrol.  .....lPT1.cOM3(SourceFile:190)
[20:08:43] [Server thread/WARN]: 	at me.kangarko.chatcontrol.  .....COM5.CoM3(SourceFile:29)
[20:08:43] [Server thread/WARN]: 	at me.kangarko.chatcontrol.  .....COM5$lPt9.init(SourceFile:907)
[20:08:43] [Server thread/WARN]: 	... 33 more
[20:08:43] [Server thread/INFO]:   _   _                       _ 
[20:08:43] [Server thread/INFO]:   | | | | ___   ___  _ __  ___| |
[20:08:43] [Server thread/INFO]:   | |_| |/ _ \ / _ \| '_ \/ __| |
[20:08:43] [Server thread/INFO]:   |  _  | (_) | (_) | |_) \__ \_|
[20:08:43] [Server thread/INFO]:   |_| |_|\___/ \___/| .__/|___(_)
[20:08:43] [Server thread/INFO]:                     |_|          
[20:08:43] [Server thread/INFO]: !-----------------------------------------------------!
[20:08:43] [Server thread/INFO]:  Error loading ChatControl v7.3.9, plugin is disabled!
[20:08:43] [Server thread/INFO]:  Running on 1.11.2-R0.1-SNAPSHOT (v1_11_R1) & Java 1.8.0_72
[20:08:43] [Server thread/INFO]: !-----------------------------------------------------!
[20:08:43] [Server thread/INFO]:  Error: Defaults don't contain List at Debugger.Sections
[20:08:43] [Server thread/INFO]: !-----------------------------------------------------!
[20:08:43] [Server thread/INFO]: [ChatControl] Disabling ChatControl v7.3.9
[20:08:43] [Server thread/INFO]: Plugin might not shut down property. Got NullPointerException: null`

Can someone help me please?
(I'm french, sorry for my english :)  )

**Comment by kangarko** [comment]
Do not reload. Restart the server instead.

**Comment by juju78660** [comment]
My mistake, i didn't checked it before :) thanks
I have another question, is it possible to make for exemple: it shows up a text when you over the name of a player depending on your group, for exemple, if i'm an administrator, i can click on his name and it write in the chat /ban {player} ?

**Comment by kangarko** [comment]
Totally possible, please see chat.yml file for examples (you'll also need to enable chat formatter in settings.yml in Chat.Formatter.Enabled).

**Comment by juju78660** [comment]
Did your plugin enter in conflict with DeluxeChat ? Cause i have it too, so i wonder if it will works with both of them.

**Comment by kangarko** [comment]
Yes it'll work. But you must only use chat formatter from one plugin, either from ChatControl or DeluxeChat. Rules are not chat formatter, so they will work anyway.

I am closing, feel free to comment below if anything.
