### ISSUE TITLE
Error when typing /ch

### ISSUE THREAD

**Issue by MrRobotMann** [kangarko/ChatControl-Pro#215]
When I'm typing /ch it shows up this error

[12:52:47 INFO]: An unhandled error occured during executing the command.
[12:52:47 WARN]: java.lang.NullPointerException
[12:52:47 WARN]: at me.kangarko.chatcontrol. .....this.protected(SourceFile:40)
[12:52:47 WARN]: at me.kangarko.chatcontrol. .....Lpt3.onCommand(SourceFile:50)
[12:52:47 WARN]: at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[12:52:47 WARN]: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[12:52:47 WARN]: at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641)
[12:52:47 WARN]: at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchServerCommand(CraftServer.java:627)
[12:52:47 WARN]: at net.minecraft.server.v1_8_R3.DedicatedServer.aO(DedicatedServer.java:412)
[12:52:47 WARN]: at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:375)
[12:52:47 WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[12:52:47 WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[12:52:47 WARN]: at java.lang.Thread.run(Unknown Source)

Server Version 1.8.8 Spigot

**Comment by kangarko** [comment]
Hey,

thank you for reporting. This bug has been resolved an a new release will be available shortly.
