### ISSUE TITLE
1.16.3 wtf 

### ISSUE THREAD

**Issue by dinobossytnew** [kangarko/ChatControl-Pro#2160]
27.11 03:49:33 [Server] INFO [Discord->ChatControl] Ignoring Discord message from channel 'dev_consola'. Available ChatControl channels: [admin, global, ranged, standard]

Can you help me you have 24h spam this msg I don't know why? I have discord and others but I don't know why I did something wrong or I don't know.

**Comment by dinobossytnew** [comment]
More Information: 
Format 'AdminChat' doesn't exist in formatting.yml! Available: Private_Message_Receiver, Discord_Chat, Spy_Party_Chat, Admin_Chat, Chat, Me, Bungee_Chat, Private_Message_Sender, Spy_Chat, Ad_Info, Global_Chat
FoException Report: Format 'AdminChat' doesn't exist in formatting.yml! Available: Private_Message_Receiver, Discord_Chat, Spy_Party_Chat, Admin_Chat, Chat, Me, Bungee_Chat, Private_Message_Sender, Spy_Chat, Ad_Info, Global_Chat
	 at org.mineacademy.chatcontrol.lib.fo.Valid.checkNotNull(Valid.java:60)
	 at org.mineacademy.chatcontrol.model.InteractiveChat$FormatLoader.getFormat(InteractiveChat.java:165)
	 at org.mineacademy.chatcontrol.model.InteractiveChat.createComponent(InteractiveChat.java:54)
	 at org.mineacademy.chatcontrol.model.InteractiveChat.createComponent(InteractiveChat.java:40)
	 at org.mineacademy.chatcontrol.model.SimpleChannel.sendMessage(SimpleChannel.java:400)
	 at org.mineacademy.chatcontrol.model.SimpleChannel.sendMessage(SimpleChannel.java:336)
	 at org.mineacademy.chatcontrol.listener.ListenerChannels.execute(ListenerChannels.java:70)
	 at org.mineacademy.chatcontrol.listener.ListenerChannels.execute(ListenerChannels.java:20)
	 at org.mineacademy.chatcontrol.lib.fo.event.SimpleListener.execute(SimpleListener.java:85)
	 at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
	 at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
	 at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
----------------------------------------------------------------------------------------------

**Comment by kangarko** [comment]
Regarding the spam, ensure your Debug option in settings.yml is set to []

Regarding the error, change AdminChat to Admin_Chat somewhere in the plugin (search using CTRL+F)

**Comment by dinobossytnew** [comment]
https://pastebin.com/fGNXjVzS

https://pastebin.com/Fb59mr5R

https://pastebin.com/YSZKxfx6 



bro doesn't work, it keeps giving that spam and it even has me fossils xd.

**Comment by dinobossytnew** [comment]
and please stop closing github ... first wait.

**Comment by dinobossytnew** [comment]
I have seen the wiki and did everything evenly but the spam still appears.

**Comment by kangarko** [comment]
It's okay to comment below a ticket, we'll see this and answer it as soon as I can.

**Comment by kangarko** [comment]
I made the message not show by default, you will no longer get the spam in the next version. You can go ahead and change your review if you want :)

**Comment by kangarko** [comment]
Closing since it has been fixed
