### ISSUE TITLE
1.16.4: Hide_Join_Quit_Kick_Messages true cause plugin kick errors

### ISSUE THREAD

**Issue by andris155** [kangarko/ChatControl-Pro#2166]
ChatControl version 8.9.7

When I enabled Hide_Join_Quit_Kick_Messages option plugins writes error when kick players.

```
[22:29:25] [Server thread/WARN]: [AuthMe] Task #488 for AuthMe v5.6.0-SNAPSHOT-b2432 generated an exception
java.lang.NullPointerException: null
	at net.minecraft.server.v1_16_R3.PlayerConnection.disconnect(PlayerConnection.java:323) ~[patched_1.16.4.jar:git-Yatopia-"23b9e93"]
	at org.bukkit.craftbukkit.v1_16_R3.entity.CraftPlayer.kickPlayer(CraftPlayer.java:467) ~[patched_1.16.4.jar:git-Yatopia-"23b9e93"]
	at fr.xephi.authme.task.TimeoutTask.run(TimeoutTask.java:31) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.4.jar:git-Yatopia-"23b9e93"]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.4.jar:git-Yatopia-"23b9e93"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1372) ~[patched_1.16.4.jar:git-Yatopia-"23b9e93"]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:397) ~[patched_1.16.4.jar:git-Yatopia-"23b9e93"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1282) ~[patched_1.16.4.jar:git-Yatopia-"23b9e93"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1013) ~[patched_1.16.4.jar:git-Yatopia-"23b9e93"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:179) ~[patched_1.16.4.jar:git-Yatopia-"23b9e93"]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[22:29:25] [Server thread/INFO]: andris155 lost connection: Login timeout exceeded, you have been kicked from the server, please try again!
```

**Comment by AngellitoX** [comment]
Hello there... Your issue is mostly cause by using the fork of the fork of the fork of the fork... I was searching around and Yatopia looks like a weird combination of many forks of Spigot in the martket which just by reading the GitHub intro, it looks like a really bad idea.

My first suggestion is to try to reproduce this issue using something official like Paper and see how it goes. If the issue remains, please let us know. Thank you!

**Comment by andris155** [comment]
Paper server file does not have this error.
I reported to Yatopia.
Thanks, and sorry.

**Comment by andris155** [comment]
https://github.com/YatopiaMC/Yatopia/issues/299
