### ISSUE TITLE
1.8.8: data.db problem

### ISSUE THREAD

**Issue by Lunatik934** [kangarko/ChatControl-Pro#2169]
Hey, I have this error on my error.log file; 

`More Information: 
Async file plugins/ChatControl/data.db saving was temporarily disabled - report this error!
FoException Report: Async file plugins/ChatControl/data.db saving was temporarily disabled - report this error!
	 at org.mineacademy.chatcontrol.lib.fo.Valid.checkBoolean(Valid.java:81)
	 at org.mineacademy.chatcontrol.lib.fo.Valid.checkSync(Valid.java:142)
	 at org.mineacademy.chatcontrol.lib.fo.settings.ConfigInstance.save(YamlConfig.java:2043)
	 at org.mineacademy.chatcontrol.lib.fo.settings.YamlConfig.save(YamlConfig.java:439)
	 at org.mineacademy.chatcontrol.ChatControl.onPluginStop(ChatControl.java:181)
	 at org.mineacademy.chatcontrol.lib.fo.plugin.SimplePlugin.onDisable(SimplePlugin.java:649)
	 at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:326)
	 at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:404)
	 at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:470)
	 at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:463)
	 at org.bukkit.craftbukkit.v1_8_R3.CraftServer.disablePlugins(SourceFile:337)`

**Comment by kangarko** [comment]
Ensure you are using Spigot or Paper, if you are using some weird fork then they broke the plugin disable mechanism by making it async.

**Comment by kangarko** [comment]
Closing due to inactivity, comment below when you come back.
