### ISSUE TITLE
1.16.4: Malformed JSON and Kick issue

### ISSUE THREAD

**Issue by Skizzles** [kangarko/ChatControl-Pro#2230]
```
------------------------------------[ 26.12.2020 10:11:19 ]-----------------------------------
ChatControl 8.9.9 encountered a JsonParseException
Running Yatopia 1.16.4-R0.1-SNAPSHOT and Java 1.8.0_275
Plugins: BlockLocker v1.9.1, PlaceholderAPI v2.10.10-DEV-111, PlugMan v2.1.7, DeluxeTags v1.8.1, CraftEnhance v2.4.2, ViaVersion v3.2.2-SNAPSHOT, ViaBackwards v3.2.1-SNAPSHOT, LuckPerms v5.2.32, ElementalGems v1.4.8, BuycraftX v12.0.6, Votifier v2.7.1, ProtocolLib v4.6.0-SNAPSHOT-b480, MVdWPlaceholderAPI v3.1.1, FastLeafDecay v1.0, VoidGenerator v1.7.0, FeatherBoard v4.29.0, CS-CoreLib vDEV - 90 (git 9dd4a1cf), Vault v1.7.3-b131, ViaRewind v1.5.3, HolographicDisplays v2.4.5, VoteParty v2.22, BungeeGuard v1.2-SNAPSHOT, WildChests v2.1.0, WorldEdit v7.3.0-SNAPSHOT+5491-5ae691a, MarriageMaster v2.2.11-Release, AnimatedNames v8.0.0a, spark v1.4.3, LiteBans v2.6, Citizens v2.0.27-SNAPSHOT (build 2191), AsyncWorldEdit v3.8.0, Toaster v1.6.6, CrazyCrates v1.10.1-SNAPSHOT-Build#95, StreakRewards v1.6.1, WorldGuard v7.0.5-SNAPSHOT+2084-035a645, TradePlus v3.79, Shop v1.8.2.3, CoreProtect v19.3, WorldGuardExtraFlags v4.1.5-SNAPSHOT, GadgetsMenu v4.6.3, SuperiorSkyblock2 v1.5.1, Slimefun vDEV - 769 (git d048f7f8), EcoPower vDEV - 2 (git b0c0c875), IslandWipe v1.0.0, TranscEndence v-bStatsFix, Multiverse-Core v4.2.3-SNAPSHOT-b818, HotbarPets vDEV - 33 (git ed485955), Tinkers v3.1.23, SlimefunLuckyBlocks vDEV - 30 (git 26824119), ExtraTools vDEV - 23 (git 9299a65c), SlimefunOreChunks vDEV - 10 (git 91df3b8e), SlimyTreeTaps vDEV - 16 (git 46272e92), FluffyMachines vDEV - 56 (git dcefabe9), Karma v1.1, Multiverse-NetherPortals v4.2.2-SNAPSHOT-b788, LiquidTanks v2.6.0, ExoticGarden vNCBPFluffyBear, LiteXpansion vDEV - 111 (git 64895074), CMI v8.7.12.3, CMIEInjector v1.0.2.3, PremiumVanish v2.6.0, DiscordSRV v1.21.0, Plan v5.1 build 813, AuctionHouse v2.1.12, BungeeTabListPlus v3.4.2, ChatControl v8.9.9, ShowItem v1.6.8 (build #397), WildStacker v3.4.3, WildTools v2.10.4, JetsMinions v6.6.14, AdvancedEnchantments v8.0.0-Pre17.1, BossShopPro v2.0.9, ItemShops v1.1.0, CMIPaperLib v1.0.0

More Information: 
Malformed JSON when sending message to FoxWarBr with JSON: {"text":"","extra":[{"text":"","extra":[{"text":"MSG ","color":"green"},{"text":"Secretary_Sami ","color":"gray"},{"text":"► ","color":"green"},{"text":"FoxWarBr ","color":"gray"},{"text":"»","color":"dark_gray"},{"text":" foxxxxy","color":"white"}],"clickEvent":{"action":"suggest_command","value":"/r "},"hoverEvent":{"action":"show_text","value":{"value":[{"text":"","extra":[{"text":"     "},{"text":"~ ","color":"dark_gray"},{"text":"Private Message ","color":"green"},{"text":"~     \n","color":"dark_gray"},{"text":"Received 26.12.2020 10:11:19\n","color":"dark_gray","italic":true},{"text":"Sender: ","color":"green"},{"text":"Secretary_Sami\n\n","color":"white"},{"text":"Click for a reply.","color":"gray"}]}]}}}]}
JsonParseException Could not parse JSON: missing 'text' property
	 at net.md_5.bungee.chat.TextComponentSerializer.deserialize(TextComponentSerializer.java:25)
	 at net.md_5.bungee.chat.TextComponentSerializer.deserialize(TextComponentSerializer.java:15)
	 at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
	 at com.google.gson.Gson.fromJson(Gson.java:887)
	 at com.google.gson.Gson.fromJson(Gson.java:952)
	 at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162)
	 at net.md_5.bungee.chat.ComponentSerializer.deserialize(ComponentSerializer.java:107)
	 at net.md_5.bungee.chat.ComponentSerializer.deserialize(ComponentSerializer.java:27)
	 at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
	 at com.google.gson.Gson.fromJson(Gson.java:887)
	 at com.google.gson.Gson.fromJson(Gson.java:952)
	 at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162)
	 at net.md_5.bungee.api.chat.hover.content.TextSerializer.deserialize(TextSerializer.java:28)
	 at net.md_5.bungee.api.chat.hover.content.TextSerializer.deserialize(TextSerializer.java:12)
	 at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
	 at com.google.gson.Gson.fromJson(Gson.java:887)
	 at com.google.gson.Gson.fromJson(Gson.java:952)
	 at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162)
	 at net.md_5.bungee.chat.BaseComponentSerializer.deserialize(BaseComponentSerializer.java:110)
	 at net.md_5.bungee.chat.TextComponentSerializer.deserialize(TextComponentSerializer.java:28)
	 at net.md_5.bungee.chat.TextComponentSerializer.deserialize(TextComponentSerializer.java:15)
	 at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
	 at com.google.gson.Gson.fromJson(Gson.java:887)
	 at com.google.gson.Gson.fromJson(Gson.java:952)
	 at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162)
	 at net.md_5.bungee.chat.ComponentSerializer.deserialize(ComponentSerializer.java:107)
	 at net.md_5.bungee.chat.ComponentSerializer.deserialize(ComponentSerializer.java:27)
	 at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
	 at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
	 at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72)
	 at com.google.gson.Gson.fromJson(Gson.java:887)
	 at com.google.gson.Gson.fromJson(Gson.java:952)
	 at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162)
	 at net.md_5.bungee.chat.BaseComponentSerializer.deserialize(BaseComponentSerializer.java:59)
	 at net.md_5.bungee.chat.TextComponentSerializer.deserialize(TextComponentSerializer.java:28)
	 at net.md_5.bungee.chat.TextComponentSerializer.deserialize(TextComponentSerializer.java:15)
	 at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
	 at com.google.gson.Gson.fromJson(Gson.java:887)
	 at com.google.gson.Gson.fromJson(Gson.java:952)
	 at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162)
	 at net.md_5.bungee.chat.ComponentSerializer.deserialize(ComponentSerializer.java:107)
	 at net.md_5.bungee.chat.ComponentSerializer.deserialize(ComponentSerializer.java:27)
	 at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
	 at com.google.gson.Gson.fromJson(Gson.java:887)
	 at com.google.gson.Gson.fromJson(Gson.java:952)
	 at com.google.gson.Gson.fromJson(Gson.java:925)
	 at net.md_5.bungee.chat.ComponentSerializer.parse(ComponentSerializer.java:57)
	 at org.mineacademy.chatcontrol.lib.fo.remain.Remain.sendJson(Remain.java:906)
	 at org.mineacademy.chatcontrol.hook.BungeeHookListener.onMessageReceived(BungeeHookListener.java:176)
	 at org.mineacademy.chatcontrol.lib.fo.bungee.BungeeListener.onPluginMessageReceived(BungeeListener.java:35)
	 at org.bukkit.plugin.messaging.StandardMessenger.dispatchIncomingMessage(StandardMessenger.java:455)
```
Minecraft Version: 1.16.4
MySQL: true
BungeeCord: true

When messaging users across servers this error is given, causes players to be kicked.

**Comment by kangarko** [comment]
Try using Paper, probably caused by Yatopia fork.

**Comment by Skizzles** [comment]
@kangarko I switched over to paper and this issue still occurs.

**Comment by MrIvanPlays** [comment]
@kangarko its not yatopia, neither your code. This bug has been well known for months now, it's an issue with bungee's chat component api, also shaded in bungee's sister, spigot.

**Comment by kangarko** [comment]
Michael Dardis (md_5) haven't fixed this in 3 months, I just patched that error on our end — we'll simply ignore such JSON's.
