### ISSUE TITLE
java 15

### ISSUE THREAD

**Issue by Envel-Nikita-Gutsenkov** [kangarko/ChatControl-Pro#2246]
sorry, but your plugin is the only one that doesn't support java 15

`[14:49:57 INFO]: [ChatControl] Disabling ChatControl v8.9.11
[14:49:57 INFO]: java.lang.RuntimeException: Script execution failed for ''
[14:49:57 INFO]:        at org.mineacademy.chatcontrol.lib.fo.model.JavaScriptExecutor.run(JavaScriptExecutor.java:139)
[14:49:57 INFO]:        at org.mineacademy.chatcontrol.lib.fo.model.JavaScriptExecutor.run(JavaScriptExecutor.java:75)
[14:49:57 INFO]:        at org.mineacademy.chatcontrol.lib.fo.plugin.SimplePlugin.onEnable(SimplePlugin.java:351)
[14:49:57 INFO]: java.lang.NullPointerException: Cannot invoke "javax.script.ScriptEngine.getBindings(int)" because "org.mineacademy.chatcontrol.lib.fo.model.JavaScriptExecutor.engine" is null
[14:49:57 INFO]:        at org.mineacademy.chatcontrol.lib.fo.model.JavaScriptExecutor.run(JavaScriptExecutor.java:112)
[14:49:57 INFO]:        at org.mineacademy.chatcontrol.lib.fo.model.JavaScriptExecutor.run(JavaScriptExecutor.java:75)
[14:49:57 INFO]:        at org.mineacademy.chatcontrol.lib.fo.plugin.SimplePlugin.onEnable(SimplePlugin.java:351)
[14:49:57 INFO]:     ___                  _
[14:49:57 INFO]:    / _ \  ___  _ __  ___| |
[14:49:57 INFO]:   | | | |/ _ \| '_ \/ __| |
[14:49:57 INFO]:   | |_| | (_) | |_) \__ \_|
[14:49:57 INFO]:    \___/ \___/| .__/|___(_)
[14:49:57 INFO]:              |_|
[14:49:57 INFO]: !-----------------------------------------------------!
[14:49:57 INFO]: Error loading ChatControl v8.9.11, plugin is disabled!
[14:49:57 INFO]: Running on 1.16.5-R0.1-SNAPSHOT (v1_16_R3) & Java 15
[14:49:57 INFO]: !-----------------------------------------------------!
[14:49:57 INFO]: Error: Cannot invoke "javax.script.ScriptEngine.getBindings(int)" because "org.mineacademy.chatcontrol.lib.fo.model.JavaScriptExecutor.engine" is null
[14:49:57 INFO]: !-----------------------------------------------------!`

**Comment by kangarko** [comment]
There's no support for J15 at the moment, we plan to make that happen after MC 1.17 is out
