### ISSUE TITLE
/msg not working

### ISSUE THREAD

**Issue by Shargann** [kangarko/ChatControl-Pro#225]
When trying to send /msg to any player following message appears in chat: 
`An unhandled error occured during executing the command.`
Console log:
`[20:46:03 INFO]: Shargann issued server command: /msg Shargann dsada
[20:46:03 INFO]: [ChatControl debug] Lag of creating component [Private_Message_Receiver] already being measured!
[20:46:03 INFO]: [ChatControl debug] Lag of loading component part [Private_Message_Receiver.Everything] already being measured!
[20:46:03 WARN]: java.lang.NoSuchMethodError: com.google.common.cache.CacheBuilder.maximumSize(J)Lcom/google/common/cache/CacheBuilder;
[20:46:03 WARN]:        at me.kangarko.chatcontrol.  ......lpt9.protected(SourceFile:136)
[20:46:03 WARN]:        at me.kangarko.chatcontrol.  ......lpt9.protected(SourceFile:211)
[20:46:03 WARN]:        at me.kangarko.chatcontrol.  ......lpt9.protected(SourceFile:160)
[20:46:03 WARN]:        at me.kangarko.chatcontrol.  ......lpt3.protected(SourceFile:123)
[20:46:03 WARN]:        at me.kangarko.chatcontrol.  ......lpt3.protected(SourceFile:119)
[20:46:03 WARN]:        at me.kangarko.chatcontrol.  ......lpt3.protected(SourceFile:112)
[20:46:03 WARN]:        at me.kangarko.chatcontrol.  ......AuX.protected(SourceFile:342)
[20:46:03 WARN]:        at me.kangarko.chatcontrol.  ......lPt6.protected(SourceFile:50)
[20:46:03 WARN]:        at me.kangarko.chatcontrol.  ......Com5.protected(SourceFile:76)
[20:46:03 WARN]:        at me.kangarko.chatcontrol.  ......cOm9.protected(SourceFile:52)
[20:46:03 WARN]:        at me.kangarko.chatcontrol.  ......LpT4.onCommand(SourceFile:50)
[20:46:03 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[20:46:03 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181)
[20:46:03 WARN]:        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:767)
[20:46:03 WARN]:        at net.minecraft.server.v1_7_R4.PlayerConnection.handleCommand(PlayerConnection.java:1043)
[20:46:03 WARN]:        at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:880)
[20:46:03 WARN]:        at net.minecraft.server.v1_7_R4.PacketPlayInChat.a(PacketPlayInChat.java:28)
[20:46:03 WARN]:        at net.minecraft.server.v1_7_R4.PacketPlayInChat.handle(PacketPlayInChat.java:65)
[20:46:03 WARN]:        at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:186)
[20:46:03 WARN]:        at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81)
[20:46:03 WARN]:        at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:734)
[20:46:03 WARN]:        at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289)
[20:46:03 WARN]:        at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584)
[20:46:03 WARN]:        at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490)
[20:46:03 WARN]:        at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628)`
ChatControl settings:
`Listener_Priority:
  Formatter: NORMAL
  Checker: NORMAL
Translate_Diacritical_Marks: true
Regex_Timeout_Milis: 100
Locale: pl
Log_Lag_Over_Milis: 100
Verbose_Rules: true
Silent_Startup: false
Regex_Strip_Colors: true
Reset_Cache_On_Quit: false
Enforce_New_Line: false
Server_Name: Survival
Check_Updates: true
Debug: true
Version: 17
Debugger:
  Sections: []
  Log: false
  Save: true`
Spigot 1.7-1.8 so really 1.7.10
Occuring on ChatControl from 7.3.6(?) to current version. Everything worked fine with 7.3.5

**Comment by kangarko** [comment]
Thank you for reporting, will be fixed tonight.

**Comment by BrinDeNuage** [comment]
Still not working for me, can't you do something about it?

**Comment by kangarko** [comment]
Please re-post a new stack trace to pastebin.com

**Comment by kangarko** [comment]
Please also reopen a new issue, this is over one year old.
