### ISSUE TITLE
Minecraft Version: Issue Title

### ISSUE THREAD

**Issue by masterhacka** [kangarko/ChatControl-Pro#2272]
[21:39:39] [Netty Server IO #1/INFO]: UUID of player .dounat113 is 00000000-0000-0000-0009-01fd74597829
[21:39:40] [Server thread/INFO]: [Matrix] (Via) Player .dounat113 joined with (1.16.x/754) client
[21:39:40] [Server thread/INFO]: ChatControl 8.10.2 encountered a FoException! Please check your error.log and report this issue with the information in that file.
[21:39:40] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to ChatControl v8.10.2
org.mineacademy.chatcontrol.lib.fo.exception.FoException: Report: Path must not contain '..' or more: Players..dounat113.Ignored_Players
	at org.mineacademy.chatcontrol.lib.fo.Valid.checkBoolean(Valid.java:81) ~[?:?]
	at org.mineacademy.chatcontrol.lib.fo.settings.YamlConfig.getT(YamlConfig.java:553) ~[?:?]
	at org.mineacademy.chatcontrol.lib.fo.settings.YamlConfig.getList(YamlConfig.java:1042) ~[?:?]
	at org.mineacademy.chatcontrol.lib.fo.settings.YamlConfig.getList(YamlConfig.java:1118) ~[?:?]
	at org.mineacademy.chatcontrol.lib.fo.settings.YamlConfig.getList(YamlConfig.java:1099) ~[?:?]
	at org.mineacademy.chatcontrol.lib.fo.settings.YamlConfig.getSet(YamlConfig.java:1080) ~[?:?]
	at org.mineacademy.chatcontrol.SimplePlayerCache.onLoadFinish(SimplePlayerCache.java:228) ~[?:?]
	at org.mineacademy.chatcontrol.lib.fo.settings.YamlConfig.loadConfiguration(YamlConfig.java:345) ~[?:?]
	at org.mineacademy.chatcontrol.SimplePlayerCache.<init>(SimplePlayerCache.java:218) ~[?:?]
	at org.mineacademy.chatcontrol.SimplePlayerCache.getFor(SimplePlayerCache.java:568) ~[?:?]
	at org.mineacademy.chatcontrol.SimplePlayerCache.getFor(SimplePlayerCache.java:555) ~[?:?]
	at org.mineacademy.chatcontrol.listener.ListenerPlayer.onJoin(ListenerPlayer.java:115) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1349.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Purpur-1060]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Purpur-1060]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Purpur-1060]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Purpur-1060]
	at net.minecraft.server.v1_16_R3.PlayerList.postChunkLoadJoin(PlayerList.java:357) ~[patched_1.16.5.jar:git-Purpur-1060]
	at net.minecraft.server.v1_16_R3.PlayerList.lambda$a$1(PlayerList.java:304) ~[patched_1.16.5.jar:git-Purpur-1060]
	at net.minecraft.server.v1_16_R3.PlayerConnection.tick(PlayerConnection.java:315) ~[?:git-Purpur-1060]
	at net.minecraft.server.v1_16_R3.NetworkManager.a(NetworkManager.java:592) ~[patched_1.16.5.jar:git-Purpur-1060]
	at net.minecraft.server.v1_16_R3.ServerConnection.c(ServerConnection.java:163) ~[patched_1.16.5.jar:git-Purpur-1060]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1593) ~[patched_1.16.5.jar:git-Purpur-1060]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:432) ~[patched_1.16.5.jar:git-Purpur-1060]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1412) ~[patched_1.16.5.jar:git-Purpur-1060]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1138) ~[patched_1.16.5.jar:git-Purpur-1060]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Purpur-1060]
	at java.lang.Thread.run(Thread.java:834) [?:?]

Using floodgate with "." prefix.

error.log:
------------------------------------[ 19.04.2021 21:40:07 ]-----------------------------------
ChatControl 8.10.2 encountered a FoException
Running Purpur 1.16.5-R0.1-SNAPSHOT and Java 11.0.10
Plugins: InventoryRollbackPlus v1.6.0, OSZOAntiWDL v1.3-SNAPSHOT, PlaceholderAPI v2.10.9, PlugMan v2.1.7, EasySetSpawn v3.3, ConsoleSpamFix v1.8.6, NoPlugins v7.3.3, OldCombatMechanics v1.9.0, ViaVersion v3.2.2-SNAPSHOT, ViaBackwards v3.2.1-SNAPSHOT, LuckPerms v5.3.21, CMILib v1.0.0.2, spark v1.5.2, ConditionalEvents v3.2.1, BuycraftX v12.0.6, MessageAnnouncer v1.12.2, EasyBackup v3.3.4, Votifier v2.7.2, BannerBoard v1.11.5, ProtocolLib v4.6.0, PrefixSystem v2.12, HamsterAPI v0.1.7, LibsDisguises v10.0.24, floodgate-bukkit v1.0-SNAPSHOT, TrollPlus v3.3.8, ServerListPlus v3.4.8, Vault v1.7.3-b${env.TRAVIS_BUILD_NUMBER}, UltimateHomes v2.1, ViaRewind v1.5.3, GMusic v[2.5.4.1], CrazyCrates v1.10.1-RELEASE, BedrockPlayerManager v1.3, Matrix v6.1.0, MyCommand v5.7.0, TigerReports v4.12.6, Essentials v2.18.2.0, FastAsyncWorldEdit v1.16-639;e40d3e3, DeluxeMenus v1.13.3-Release, SuperbVote v0.5.5, TAB v2.8.10, ChatEx v2.7.1, JumpPads v1.25.4, PlotSquared v5.13.11-Premium, TigerReportsSupports v1.5.6, WorldGuard v7.0.4+f7ff984, Perks v2.6.0, PlotBorder v1.7.3, WorldGuardExtraFlags v4.1.5-SNAPSHOT, WorldEditSUI v1.7.1, GadgetsMenu v4.6.9, Jobs v4.17.1, Citizens v2.0.27-SNAPSHOT (build 2296), LeaderHeadsRevamped v4.0.6, BossShopPro v2.0.9, CitizensIntergration v1, WarpSystem v5.0.1, LWC v2.2.7-ad0f824, CMI v8.8.3.4, AuctionHouse v2.1.12, TreeFeller v1.14.1, CoreProtect v19.5, TitleManager v2.3.3, CustomCobbleGen v1.5.0-BETA, PremiumVanish v2.6.11, ChatControl v8.10.2, WorldBorder v2.1.1, Multiverse-Core v4.2.2-b812, Multiverse-Inventories v4.2.2-b500, DiscordSRV v1.22.0, ItemJoin v5.2.1-RELEASE-b678, Multiverse-NetherPortals v4.2.1-b786, VoidSpawn v1.19.2, BentoBox v1.16.1, Plan v5.2 build 1174, Multiverse-Portals v4.2.1-b834
----------------------------------------------------------------------------------------------

More Information: 
Path must not contain '..' or more: Players..dounat113.Ignored_Players
FoException Report: Path must not contain '..' or more: Players..dounat113.Ignored_Players
	 at org.mineacademy.chatcontrol.lib.fo.Valid.checkBoolean(Valid.java:81)
	 at org.mineacademy.chatcontrol.lib.fo.settings.YamlConfig.getT(YamlConfig.java:553)
	 at org.mineacademy.chatcontrol.lib.fo.settings.YamlConfig.getList(YamlConfig.java:1042)
	 at org.mineacademy.chatcontrol.lib.fo.settings.YamlConfig.getList(YamlConfig.java:1118)
	 at org.mineacademy.chatcontrol.lib.fo.settings.YamlConfig.getList(YamlConfig.java:1099)
	 at org.mineacademy.chatcontrol.lib.fo.settings.YamlConfig.getSet(YamlConfig.java:1080)
	 at org.mineacademy.chatcontrol.SimplePlayerCache.onLoadFinish(SimplePlayerCache.java:228)
	 at org.mineacademy.chatcontrol.lib.fo.settings.YamlConfig.loadConfiguration(YamlConfig.java:345)
	 at org.mineacademy.chatcontrol.SimplePlayerCache.<init>(SimplePlayerCache.java:218)
	 at org.mineacademy.chatcontrol.SimplePlayerCache.getFor(SimplePlayerCache.java:568)
	 at org.mineacademy.chatcontrol.SimplePlayerCache.getFor(SimplePlayerCache.java:555)
	 at org.mineacademy.chatcontrol.listener.ListenerCommand.handleCommandEvent(ListenerCommand.java:87)
	 at org.mineacademy.chatcontrol.listener.ListenerCommand.onPlayerCommand(ListenerCommand.java:45)
	 at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1357.execute(Unknown Source)
	 at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
	 at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
	 at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
	 at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
	 at world.bentobox.bentobox.api.user.User.performCommand(User.java:541)
	 at world.bentobox.bentobox.api.commands.island.DefaultPlayerCommand.execute(DefaultPlayerCommand.java:105)
	 at world.bentobox.bentobox.api.commands.CompositeCommand.call(CompositeCommand.java:266)
	 at world.bentobox.bentobox.api.commands.CompositeCommand.execute(CompositeCommand.java:239)
	 at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172)
	 at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:810)
----------------------------------------------------------------------------------------------

**Comment by kangarko** [comment]
That's a wontfix kind of issue unfortunately, players with "." in front of their names will trigger yaml incompatible errors. I have silenced that error in the next version, lemme know below if you'll experience anything.
