### ISSUE TITLE
Announce isn't working on empty Servers..

### ISSUE THREAD

**Issue by Rurdo** [kangarko/ChatControl-Pro#23]
Hi!
We just set up Buycraft to use CHC announce if someone purchased something. 
Buycraft tells CHC on Server A to broadcast the Message over all Servers (which it normally does)
BUT, if there is no Player on this Server, the Announce throws an error and doesn't broadcast it anywhere.
The Error shown in latest.log:

> [18:15:22] [Server thread/INFO]: [BuycraftX] Dispatching command 'chc a rurdo hat was für den Server springen lassen. HipHip ...' for player 'rurdo'.
[18:15:22] [Server thread/INFO]: [ChatControl] [0;37;1m[Announcement by [0;36;1mCONSOLE[0;37;1m]: [0;37;22mrurdo hat was für den Server springen lassen. HipHip ...[m
[18:15:22] [Server thread/INFO]: [0;31;1mAn unhandled error occured during executing the command.[m
[18:15:22] [Server thread/WARN]: java.lang.IllegalArgumentException: Cannot send message to bungee from an empty server
[18:15:22] [Server thread/WARN]: 	at org.apache.commons.lang.Validate.isTrue(Validate.java:136)
[18:15:22] [Server thread/WARN]: 	at me.kangarko.chatcontrol.CoM2.native(SourceFile:611)
[18:15:22] [Server thread/WARN]: 	at me.kangarko.chatcontrol.com4.const(SourceFile:23)
[18:15:22] [Server thread/WARN]: 	at me.kangarko.chatcontrol.con.const(SourceFile:234)
[18:15:22] [Server thread/WARN]: 	at me.kangarko.chatcontrol.cOm4.onCommand(SourceFile:28)
[18:15:22] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[18:15:22] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[18:15:22] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCommand(CraftServer.java:645)
[18:15:22] [Server thread/WARN]: 	at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:580)
[18:15:22] [Server thread/WARN]: 	at net.buycraft.plugin.bukkit.BukkitBuycraftPlatform.dispatchCommand(BukkitBuycraftPlatform.java:38)
[18:15:22] [Server thread/WARN]: 	at net.buycraft.plugin.execution.strategy.QueuedCommandExecutor.run(QueuedCommandExecutor.java:49)
[18:15:22] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:71)
[18:15:22] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
[18:15:22] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:729)
[18:15:22] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400)
[18:15:22] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660)
[18:15:22] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559)
[18:15:22] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)

**Comment by kangarko** [comment]
Due to current technical limitations, the implementation requires at least one online player.

I'll take a look if this can be fixed.

**Comment by kangarko** [comment]
Fixed. A new release will be released soon.
