### ISSUE TITLE
/msg not working, one more time

### ISSUE THREAD

**Issue by Shargann** [kangarko/ChatControl-Pro#230]
Basically similar problem like it was in #225 
Log from console: `[23:04:35 INFO]: Shargann issued server command: /msg shargann test
[23:04:35 INFO]: [ChatControl debug] Lag of creating component [Private_Message_Receiver] already being measured!
[23:04:35 INFO]: [ChatControl debug] Lag of loading component part [Private_Message_Receiver.Everything] already being measured!
[23:04:35 WARN]: java.lang.NoSuchMethodError: com.google.common.cache.CacheBuilder.build(Lcom/google/common/cache/CacheLoader;)Lcom/google/common/cache/LoadingCache;
[23:04:35 WARN]:        at me.kangarko.chatcontrol.  ......lpt3.protected(SourceFile:146)
[23:04:35 WARN]:        at me.kangarko.chatcontrol.  ......lpt3.protected(SourceFile:225)
[23:04:35 WARN]:        at me.kangarko.chatcontrol.  ......lpt3.protected(SourceFile:174)
[23:04:35 WARN]:        at me.kangarko.chatcontrol.  ......cOM7.protected(SourceFile:123)
[23:04:35 WARN]:        at me.kangarko.chatcontrol.  ......cOM7.protected(SourceFile:119)
[23:04:35 WARN]:        at me.kangarko.chatcontrol.  ......cOM7.protected(SourceFile:112)
[23:04:35 WARN]:        at me.kangarko.chatcontrol.  ......Com5.protected(SourceFile:342)
[23:04:35 WARN]:        at me.kangarko.chatcontrol.  ......Com7.protected(SourceFile:50)
[23:04:35 WARN]:        at me.kangarko.chatcontrol.  ......coM8.protected(SourceFile:76)
[23:04:35 WARN]:        at me.kangarko.chatcontrol.  ......cOm9.protected(SourceFile:52)
[23:04:35 WARN]:        at me.kangarko.chatcontrol.  ......lPT8.onCommand(SourceFile:50)
[23:04:35 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[23:04:35 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181)
[23:04:35 WARN]:        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:767)
[23:04:35 WARN]:        at net.minecraft.server.v1_7_R4.PlayerConnection.handleCommand(PlayerConnection.java:1043)
[23:04:35 WARN]:        at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:880)
[23:04:35 WARN]:        at net.minecraft.server.v1_7_R4.PacketPlayInChat.a(PacketPlayInChat.java:28)
[23:04:35 WARN]:        at net.minecraft.server.v1_7_R4.PacketPlayInChat.handle(PacketPlayInChat.java:65)
[23:04:35 WARN]:        at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:186)
[23:04:35 WARN]:        at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81)
[23:04:35 WARN]:        at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:734)
[23:04:35 WARN]:        at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289)
[23:04:35 WARN]:        at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584)
[23:04:35 WARN]:        at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490)
[23:04:35 WARN]:        at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628)`

Version - [23:09:38 INFO]: ◈ ChatControl ◈ Running 7.3.15
Server - [23:10:07 INFO]: This server is running CraftBukkit version git-Spigot-1.7.9-R0.2-207-g03373bb (MC: 1.7.10) (Implementing API version 1.7.10-R0.1-SNAPSHOT)

**Comment by Porama6400** [comment]
Did you tried to update to latest 1.7.10?

**Comment by kangarko** [comment]
It doesn't help, because 1.7.10 lack required libraries. I will pack them with the plugin itself in the next release.
