### ISSUE TITLE
when they will update the plugin.

### ISSUE THREAD

**Issue by akillamrck** [kangarko/ChatControl-Pro#2300]
[06:42:16 INFO]: ______________________________________________________________
[06:42:16 INFO]: !-----------------------------------------------------!
[06:42:16 INFO]: JavaScript placeholders will not function!
[06:42:16 INFO]:
[06:42:16 INFO]: Your Java version/distribution lacks the
[06:42:16 INFO]: Nashorn library for JavaScript placeholders.
[06:42:16 INFO]: Please install Oracle Java 8 JDK.
[06:42:16 INFO]: Plugin is now disabled.
[06:42:16 INFO]: !-----------------------------------------------------!
[06:42:16 INFO]: [ChatControl] Disabling ChatControl v8.9.10
[06:42:16 INFO]: Saving player data to wMySQL..
[06:42:16 INFO]: java.lang.RuntimeException: Script execution failed for ''
[06:42:16 INFO]:        at org.mineacademy.chatcontrol.lib.fo.model.JavaScriptExecutor.run(JavaScriptExecutor.java:139)
[06:42:16 INFO]:        at org.mineacademy.chatcontrol.lib.fo.model.JavaScriptExecutor.run(JavaScriptExecutor.java:75)
[06:42:16 INFO]:        at org.mineacademy.chatcontrol.lib.fo.plugin.SimplePlugin.onEnable(SimplePlugin.java:348)
[06:42:16 INFO]: java.lang.NullPointerException: Cannot invoke "javax.script.ScriptEngine.getBindings(int)" because "org.mineacademy.chatcontrol.lib.fo.model.JavaScriptExecutor.engine" is null
[06:42:16 INFO]:        at org.mineacademy.chatcontrol.lib.fo.model.JavaScriptExecutor.run(JavaScriptExecutor.java:112)
[06:42:16 INFO]:        at org.mineacademy.chatcontrol.lib.fo.model.JavaScriptExecutor.run(JavaScriptExecutor.java:75)
[06:42:16 INFO]:        at org.mineacademy.chatcontrol.lib.fo.plugin.SimplePlugin.onEnable(SimplePlugin.java:348)
[06:42:16 INFO]:     ___                  _
[06:42:16 INFO]:    / _ \  ___  _ __  ___| |
[06:42:16 INFO]:   | | | |/ _ \| '_ \/ __| |
[06:42:16 INFO]:   | |_| | (_) | |_) \__ \_|
[06:42:16 INFO]:    \___/ \___/| .__/|___(_)
[06:42:16 INFO]:              |_|
[06:42:16 INFO]: !-----------------------------------------------------!
[06:42:16 INFO]: Error loading ChatControl v8.9.10, plugin is disabled!
[06:42:16 INFO]: Running on 1.16.5-R0.1-SNAPSHOT (v1_16_R3) & Java 16.0.1
[06:42:16 INFO]: !-----------------------------------------------------!
[06:42:16 INFO]: Error: Cannot invoke "javax.script.ScriptEngine.getBindings(int)" because "org.mineacademy.chatcontrol.lib.fo.model.JavaScriptExecutor.engine" is null
[06:42:16 INFO]: !-----------------------------------------------------!

**Comment by Malachiel87** [comment]
Waiting for the support 1.17 too

**Comment by kangarko** [comment]
When it's ready
