### ISSUE TITLE
1.17: ChatControl-Pro doesn't work.

### ISSUE THREAD

**Issue by TheIntelloBox** [kangarko/ChatControl-Pro#2306]
[00:45:17] [Server thread/INFO]: [ChatControl] Enabling ChatControl v8.9.10
[00:45:17] [Server thread/INFO]: [ChatControl] ChatControl 8.9.10 encountered a FoException! Please check your error.log and report this issue with the information in that file.
[00:45:17] [Server thread/ERROR]: Error occurred while enabling ChatControl v8.9.10 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
	at org.mineacademy.chatcontrol.lib.fo.Common.stripColors(Common.java:665) ~[?:?]
	at org.mineacademy.chatcontrol.lib.fo.Common.log(Common.java:1211) ~[?:?]
	at org.mineacademy.chatcontrol.lib.fo.Common.log(Common.java:1186) ~[?:?]
	at org.mineacademy.chatcontrol.lib.fo.Common.logFramed(Common.java:1259) ~[?:?]
	at org.mineacademy.chatcontrol.lib.fo.Common.logFramed(Common.java:1246) ~[?:?]
	at org.mineacademy.chatcontrol.lib.fo.plugin.SimplePlugin.checkServerVersions0(SimplePlugin.java:552) ~[?:?]
	at org.mineacademy.chatcontrol.lib.fo.plugin.SimplePlugin.onEnable(SimplePlugin.java:228) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.17.jar:git-Paper-74]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.jar:git-Paper-74]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.jar:git-Paper-74]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.17.jar:git-Paper-74]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.17.jar:git-Paper-74]
	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:643) ~[patched_1.17.jar:git-Paper-74]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:304) ~[patched_1.17.jar:git-Paper-74]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1118) ~[patched_1.17.jar:git-Paper-74]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[patched_1.17.jar:git-Paper-74]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: org.mineacademy.chatcontrol.lib.fo.exception.FoException: Report: Your Minecraft version 1.17 is unsupported by ChatControl
	at org.mineacademy.chatcontrol.lib.fo.Valid.checkBoolean(Valid.java:81) ~[?:?]
	at org.mineacademy.chatcontrol.lib.fo.remain.Remain.<clinit>(Remain.java:240) ~[?:?]
	... 17 more
[00:45:17] [Server thread/INFO]: [ChatControl] Disabling ChatControl v8.9.10
[00:45:17] [Server thread/ERROR]: Error occurred while disabling ChatControl v8.9.10 (Is it up to date?)
java.lang.NoClassDefFoundError: Could not initialize class org.mineacademy.chatcontrol.lib.fo.remain.Remain
	at org.mineacademy.chatcontrol.lib.fo.Common.stripColors(Common.java:665) ~[?:?]
	at org.mineacademy.chatcontrol.lib.fo.Common.log(Common.java:1211) ~[?:?]
	at org.mineacademy.chatcontrol.lib.fo.Common.log(Common.java:1186) ~[?:?]
	at org.mineacademy.chatcontrol.lib.fo.plugin.SimplePlugin.onDisable(SimplePlugin.java:651) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.17.jar:git-Paper-74]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:405) ~[patched_1.17.jar:git-Paper-74]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:533) ~[patched_1.17.jar:git-Paper-74]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:374) ~[patched_1.17.jar:git-Paper-74]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.jar:git-Paper-74]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.17.jar:git-Paper-74]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.17.jar:git-Paper-74]
	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:643) ~[patched_1.17.jar:git-Paper-74]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:304) ~[patched_1.17.jar:git-Paper-74]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1118) ~[patched_1.17.jar:git-Paper-74]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[patched_1.17.jar:git-Paper-74]
	at java.lang.Thread.run(Thread.java:831) [?:?]

**Comment by kangarko** [comment]
It says why, please wait for an update which is coming in the next few days thank you.

**Comment by kangarko** [comment]
Use this version: https://github.com/kangarko/ChatControl-Pro/releases/tag/8.10.6
