### ISSUE TITLE
Exception encountered when loading plugin: BungeeControl-Red

### ISSUE THREAD

**Issue by dwebeklint** [kangarko/ChatControl-Pro#2307]
Hello. 

I got a problem loading BungeeControll-Red on my proxy.

I have waterfall-1.17-443.jar
Bungeecontroll-red : 3.4.9

see the logs below: 
[18:46:01] [main/WARN]: Exception encountered when loading plugin: BungeeControl-Red
java.lang.NullPointerException: Cannot invoke "net.md_5.bungee.api.CommandSender.getName()" because "sender" is null
	at org.mineacademy.bungeecontrol.lib.bfo.model.JavaScriptExecutor.run(JavaScriptExecutor.java:142) ~[?:?]
	at org.mineacademy.bungeecontrol.lib.bfo.model.JavaScriptExecutor.run(JavaScriptExecutor.java:105) ~[?:?]
	at org.mineacademy.bungeecontrol.lib.bfo.plugin.SimplePlugin.onEnable(SimplePlugin.java:190) ~[?:?]
	at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:315) ~[waterfall-1.17-443.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:34188b3:443]
	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:290) ~[waterfall-1.17-443.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:34188b3:443]
	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:80) ~[waterfall-1.17-443.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:34188b3:443]
	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[waterfall-1.17-443.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:34188b3:443]

Thnx for a great plugin.

**Comment by dwebeklint** [comment]
Nevermind. You can close this. 
Found out I needed NashornPlus on the proxy as well.
Thnx
