### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Envel-Nikita-Gutsenkov** [kangarko/ChatControl-Pro#2313]
`[19:55:21 INFO]: ChatControl 8.10.7 encountered a FoException! Please check your error.log and report this issue with the information in that file.
[19:55:21 WARN]: [ChatControl] Task #3005 for ChatControl v8.10.7 generated an exception
org.mineacademy.chatcontrol.lib.fo.exception.FoException: Report: Condition must return a boolean, not null or anything else. Got: null
        at org.mineacademy.chatcontrol.lib.fo.Valid.checkBoolean(Valid.java:81) ~[ChatControl-8.10.7.jar:?]
        at org.mineacademy.chatcontrol.condition.Condition.isConditioned(Condition.java:155) ~[ChatControl-8.10.7.jar:?]
        at org.mineacademy.chatcontrol.condition.Condition.evaluate(Condition.java:75) ~[ChatControl-8.10.7.jar:?]
        at org.mineacademy.chatcontrol.condition.ConditionMessage.getCondition(ConditionMessage.java:102) ~[ChatControl-8.10.7.jar:?]
        at org.mineacademy.chatcontrol.condition.ConditionMessage.get(ConditionMessage.java:83) ~[ChatControl-8.10.7.jar:?]
        at org.mineacademy.chatcontrol.condition.ConditionMessage.getMessage(ConditionMessage.java:69) ~[ChatControl-8.10.7.jar:?]
        at org.mineacademy.chatcontrol.listener.ListenerPlayer.handlePlayerMessage(ListenerPlayer.java:233) ~[ChatControl-8.10.7.jar:?]
        at org.mineacademy.chatcontrol.listener.ListenerPlayer.lambda$onJoin$2(ListenerPlayer.java:227) ~[ChatControl-8.10.7.jar:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Purpur-1310]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[patched_1.17.1.jar:git-Purpur-1310]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1565) ~[patched_1.17.1.jar:git-Purpur-1310]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:492) ~[patched_1.17.1.jar:git-Purpur-1310]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1480) ~[patched_1.17.1.jar:git-Purpur-1310]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1270) ~[patched_1.17.1.jar:git-Purpur-1310]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Purpur-1310]
        at java.lang.Thread.run(Thread.java:831) [?:?]`
Minecraft Version: 1.17.1
MySQL: false
BungeeCord: false

ChatControl-8.10.7

**Comment by kangarko** [comment]
Please post me your debug zip file.

**Comment by Envel-Nikita-Gutsenkov** [comment]
fixed (use NashornPlus-1.1.0)
