### ISSUE TITLE
Minecraft Version: Issue Title

### ISSUE THREAD

**Issue by Kenyy11** [kangarko/ChatControl-Pro#2323]
[13:49:08 INFO]: [ChatControl] Enabling ChatControl v8.10.7
[13:49:08 INFO]: _____ _ _ _____ _ _ +
[13:49:08 INFO]: / ____| | | | / ____| | | | |
[13:49:08 INFO]: | | | |__ __ _| |_| | ___ _ __ | |_ _ __ ___ | |
[13:49:08 INFO]: | | | '_ \ / _` | __| | / _ \| '_ \| __| '__/ _ \| |
[13:49:08 INFO]: | |____| | | | (_| | |_| |___| (_) | | | | |_| | | (_) | |
[13:49:08 INFO]: \_____|_| |_|\__,_|\__|\_____\___/|_| |_|\__|_| \___/|_|
[13:49:08 INFO]:
[13:49:08 INFO]: Warning: Admin_Chat feature is deprecated. You can create an admin channel in channels.yml. If using Discord, you can put 'Discord: true' key there to connect it with Discord channel by the same name.
[13:49:08 INFO]: java.lang.IllegalArgumentException: Malformed YAML file formatting.yml - use services like yaml-online-parser.appspot.com to check and fix it
[13:49:08 INFO]: at ChatControl-8.10.7.jar//org.mineacademy.chatcontrol.lib.fo.FileUtil.loadConfigurationStrict(FileUtil.java:255)
[13:49:08 INFO]: at ChatControl-8.10.7.jar//org.mineacademy.chatcontrol.lib.fo.settings.YamlConfig.loadConfiguration(YamlConfig.java:324)
[13:49:08 INFO]: at ChatControl-8.10.7.jar//org.mineacademy.chatcontrol.lib.fo.settings.YamlStaticConfig.createFileAndLoad(YamlStaticConfig.java:254)
[13:49:08 INFO]: at ChatControl-8.10.7.jar//org.mineacademy.chatcontrol.settings.FormatSettings.load(FormatSettings.java:21)
[13:49:08 INFO]: at ChatControl-8.10.7.jar//org.mineacademy.chatcontrol.lib.fo.settings.YamlStaticConfig.load(YamlStaticConfig.java:92)
[13:49:08 INFO]: at ChatControl-8.10.7.jar//org.mineacademy.chatcontrol.lib.fo.plugin.SimplePlugin.onEnable(SimplePlugin.java:276)
[13:49:08 INFO]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[13:49:08 INFO]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[13:49:08 INFO]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[13:49:08 INFO]: at java.base/java.lang.Thread.run(Thread.java:831)
[13:49:08 INFO]: unacceptable code point '�' (0x9C) special characters are not allowed
[13:49:08 INFO]: in "'string'", position 691
[13:49:08 INFO]: at ChatControl-8.10.7.jar//org.mineacademy.chatcontrol.lib.fo.settings.SimpleYaml.loadFromString(SimpleYaml.java:94)
[13:49:08 INFO]: at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160)
[13:49:08 INFO]: at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:128)
[13:49:08 INFO]: at ChatControl-8.10.7.jar//org.mineacademy.chatcontrol.lib.fo.FileUtil.loadConfigurationStrict(FileUtil.java:246)
[13:49:08 INFO]: at ChatControl-8.10.7.jar//org.mineacademy.chatcontrol.lib.fo.settings.YamlConfig.loadConfiguration(YamlConfig.java:324)
[13:49:08 INFO]: at ChatControl-8.10.7.jar//org.mineacademy.chatcontrol.lib.fo.settings.YamlStaticConfig.createFileAndLoad(YamlStaticConfig.java:254)
[13:49:08 INFO]: at ChatControl-8.10.7.jar//org.mineacademy.chatcontrol.settings.FormatSettings.load(FormatSettings.java:21)
[13:49:08 INFO]: at ChatControl-8.10.7.jar//org.mineacademy.chatcontrol.lib.fo.settings.YamlStaticConfig.load(YamlStaticConfig.java:92)
[13:49:08 INFO]: at ChatControl-8.10.7.jar//org.mineacademy.chatcontrol.lib.fo.plugin.SimplePlugin.onEnable(SimplePlugin.java:276)
[13:49:08 INFO]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[13:49:08 INFO]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[13:49:08 INFO]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[13:49:08 INFO]: at java.base/java.lang.Thread.run(Thread.java:831)
[13:49:08 INFO]: ___ _
[13:49:08 INFO]: / _ \ ___ _ __ ___| |
[13:49:08 INFO]: | | | |/ _ \| '_ \/ __| |
[13:49:08 INFO]: | |_| | (_) | |_) \__ \_|
[13:49:08 INFO]: \___/ \___/| .__/|___(_)
[13:49:08 INFO]: |_|
[13:49:08 INFO]: !-----------------------------------------------------!
[13:49:08 INFO]: Error loading ChatControl v8.10.7, plugin is disabled!
[13:49:08 INFO]: Running on 1.17.1-R0.1-SNAPSHOT (v1_17_R1) & Java 16.0.2
[13:49:08 INFO]: !-----------------------------------------------------!
[13:49:08 INFO]: Error: special characters are not allowed
[13:49:08 INFO]: !-----------------------------------------------------!
[13:49:08 INFO]: [ChatControl] Disabling ChatControl v8.10.7

This bug occurs also with latest version of chatcontrol pro>

Tuinity 1.17.1
Bungee true

New config i didnt changed anything

**Comment by spannerman79** [comment]
> [13:49:08 INFO]: [ChatControl] Enabling ChatControl v8.10.7

https://github.com/kangarko/ChatControl-Pro/releases/latest

> New config i didnt changed anything

>[13:49:08 INFO]: java.lang.IllegalArgumentException: Malformed YAML file formatting.yml - use services like yaml-online-parser.appspot.com to check and fix it

I doubt it - default config gets copied from within the jar itself.  And that file, `formatting.yml` within that particular version **is** valid yaml format

**Comment by kangarko** [comment]
Remove your formatting.yml and let it regenerate again, also check our Wiki about encoding and use the right program to open/save your files such as Notepad++ or Sublime Text.
