### ISSUE TITLE
ERROR: Volanie nastaveni pred ich nacitanim!

### ISSUE THREAD

**Issue by Porama6400** [kangarko/ChatControl-Pro#234]
`7] [Server thread/INFO]: [0;36;22m \_____|_| |_|\__,_|\__|\_____\___/|_| |_|\__|_|  \___/|_|[m
[16:20:27] [Server thread/INFO]:  [m
[16:20:27] [Server thread/WARN]: java.lang.IllegalArgumentException: [FATAL/REPORT ME] Volanie nastaveni pred ich nacitanim!
[16:20:27] [Server thread/WARN]: 	at org.apache.commons.lang.Validate.isTrue(Validate.java:136)
[16:20:27] [Server thread/WARN]: 	at me.kangarko.chatcontrol.ChatControl.void(SourceFile:528)
[16:20:27] [Server thread/WARN]: 	at me.kangarko.chatcontrol.ChatControl.super(SourceFile:487)
[16:20:27] [Server thread/WARN]: 	at me.kangarko.chatcontrol.  ......cOm6.onEnable(SourceFile:77)
[16:20:27] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271)
[16:20:27] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
[16:20:27] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[16:20:27] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:376)
[16:20:27] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:326)
[16:20:27] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.t(MinecraftServer.java:421)
[16:20:27] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.l(MinecraftServer.java:382)
[16:20:27] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.a(MinecraftServer.java:337)
[16:20:27] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:272)
[16:20:27] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:544)
[16:20:27] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)`

ChatControl Pro: Latest
Server Version: 1.8.8 and 1.11.2 (Crash at the same time somehow :P)

**Comment by kangarko** [comment]
Are you using PlugMan or /reload command? Those may raise such issues.

**Comment by Porama6400** [comment]
No, It's fresh started server

But I make my server to start with windows, is that the problem?

**Comment by kangarko** [comment]
Please redownload the latest version. I have never had an issue of this kind actually. Just in case, try to backup your ChatControl/ folder and rename it, so you can see if the problem persist with the default configuration.

Operating system is not an issue.

**Comment by kangarko** [comment]
Closing, please comment below if still having issues.
