### ISSUE TITLE
1.16.5 I have a bug

### ISSUE THREAD

**Issue by raylux92** [kangarko/ChatControl-Pro#2340]
Minecraft Version: 1.16.5
MySQL: false
BungeeCord: false

Hi there.
Every time a user enters or leaves the server I get these types of errors. How can it be solved? Thanks.

[08:59:43 ERROR]: Could not pass event PlayerKickEvent to ChatControl v5.9.1
java.lang.NullPointerException: Cannot invoke "String.length()" because "input" is null
        at net.kyori.adventure.text.serializer.legacy.LegacyComponentSerializerImpl.deserialize(LegacyComponentSerializerImpl.java:242) ~[patched_1.16.5.jar:git-Purpur-1171]
        at org.bukkit.event.player.PlayerKickEvent.setLeaveMessage(PlayerKickEvent.java:134) ~[patched_1.16.5.jar:git-Purpur-1171]
        at org.mineacademy.chatcontrol.listener.PlayerListener.onKick(PlayerListener.java:148) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor846.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Purpur-1171]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Purpur-1171]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Purpur-1171]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.PlayerConnection.disconnect(PlayerConnection.java:476) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.PlayerConnection.disconnect(PlayerConnection.java:454) ~[patched_1.16.5.jar:git-Purpur-1171]
        at org.bukkit.craftbukkit.v1_16_R3.entity.CraftPlayer.kickPlayer(CraftPlayer.java:503) ~[patched_1.16.5.jar:git-Purpur-1171]
        at fr.xephi.authme.task.TimeoutTask.run(TimeoutTask.java:31) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Purpur-1171]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1503) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:449) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1416) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1142) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:293) ~[patched_1.16.5.jar:git-Purpur-1171]
        at java.lang.Thread.run(Thread.java:831) [?:?]

**Comment by Rawxdealz** [comment]
Do you have the error if you disable join/leave messages in the chatcontrol config?

**Comment by raylux92** [comment]
> ¿Tiene el error si deshabilita los mensajes de unirse / dejar en la configuración de chatcontrol?

I do not have them enabled

Messages:
  # Use 'default' to not modify, 'hide' to not display or write a custom message
  # Variables: {player} {pl_suffix} {pl_prefix} (when Vault is installed)
  # {countrycode} and {countryname} when AuthMe is installed
  Join: hide
  Quit: hide
  Kick: hide

**Comment by kangarko** [comment]
You have ChatControl Free, this issues channel is for the Pro edition.

Update your build to https://github.com/kangarko/ChatControl-Free/releases/tag/5.9.2
