### ISSUE TITLE
Using TAB-Complete features for allowed commands on specific version of server/client

### ISSUE THREAD

**Issue by TheJoshue** [kangarko/ChatControl-Pro#2359]
This happens when player that is playing on **1.12.2 AND LOWER** tries to tab-complete through allowed command (for example if he has permission to use `/msg` command, he can tab complete like: `/msg [TAB-BUTTON]` <- this is where this console error occurs).
When the error happens (every time someone on 1.12.2 or lower tries and succeeds to TAB-Complete), there is no actual problem in-game, it only prints error in the console.

**(( I know plugin has reached it's end, but just to note so you fix this in CHCRed and be kind back because you made this free for everyone and i wasn't buyer of CHCPro 😄))**

Specific options:
- Spigot setting for tab-completer isn't disabled (value is 0, i think -1 means disabled)
- ViaVersion has `disable-1_13-auto-complete` config option set to **false** (i tested with **true** too, same issue)
- ChatControl `settings.yml` config file has `Packets.Enabled` setting to **true**, and `Packets.Tab_Complete.Enabled` setting to **true** too.

Resource version:
- `VIA plugins versions`: **latest from SpigotMC**
- `ProtocolLib version`: **latest from Jenkins recommended for 1.8 to 1.17**
- `ChatControlPRO version`: **latest from github (8.11.5)**
- `Paper version`: **latest legacy build for 1.16.5**
![image](https://user-images.githubusercontent.com/56804505/149630867-8e6944e7-2f89-4089-bcfa-da53d20f16a4.png)

Error Log:
```
[18:05:58 ERROR]: [ChatControl] Unhandled exception occured in onPacketSending(PacketEvent) for ChatControl
com.comphenix.protocol.reflect.FieldAccessException: No field with type [Ljava.lang.String; exists in class PacketPlayOutTabComplete.
        at com.comphenix.protocol.reflect.StructureModifier.readInternal(StructureModifier.java:218) ~[?:?]
        at com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:197) ~[?:?]
        at org.mineacademy.chatcontrol.hook.ProtocolLibHook$3.onPacketSending(ProtocolLibHook.java:184) ~[?:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[?:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:535) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:516) ~[?:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:346) ~[?:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:308) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:433) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:70) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:373) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:343) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) ~[?:?]
        at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) ~[?:?]
        at net.minecraft.server.v1_16_R3.NetworkManager.b(NetworkManager.java:311) ~[paper-1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.NetworkManager.dispatchPacket(NetworkManager.java:267) ~[paper-1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.NetworkManager.sendPacket(NetworkManager.java:243) ~[paper-1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.NetworkManager.sendPacket(NetworkManager.java:229) ~[paper-1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.PlayerConnection.lambda$a$6(PlayerConnection.java:799) ~[paper-1.16.5.jar:git-Paper-794]
        at java.util.concurrent.CompletableFuture.uniAcceptNow(CompletableFuture.java:757) ~[?:?]
        at java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:735) ~[?:?]
        at java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2182) ~[?:?]
        at net.minecraft.server.v1_16_R3.PlayerConnection.lambda$a$7(PlayerConnection.java:794) ~[paper-1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[paper-1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[paper-1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[paper-1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[paper-1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1271) ~[paper-1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1264) ~[paper-1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[paper-1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1225) ~[paper-1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1139) ~[paper-1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[paper-1.16.5.jar:git-Paper-794]
        at java.lang.Thread.run(Thread.java:833) [?:?]
[18:05:58 ERROR]: Parameters:
  net.minecraft.server.v1_16_R3.PacketPlayOutTabComplete@9c1061f[
    a=-1060190951
    b=Suggestions{range=StringRange{start=5, end=5}, suggestions=[Suggestion{range=StringRange{start=5, end=5}, text='Shadowmortal', tooltip='null'}, Suggestion{range=StringRange{start=5, end=5}, text='TheJoshua', tooltip='null'}]}
```
**(( I know plugin has reached it's end, but just to note so you fix this in CHCRed and be kind back because you made this free for everyone and i wasn't buyer of CHCPro 😄))**

**Comment by kangarko** [comment]
Thanks, I do think this is patched in Red. You can get it now for 50% off which is cheaper than what we sold Pro for.
