### ISSUE TITLE
Error on console

### ISSUE THREAD

**Issue by x1p** [kangarko/ChatControl-Pro#237]
13:16:19] [Async Chat Thread - #4/WARN]: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet successfully received from the server was 29,748,105 milliseconds ago.  The last packet sent successfully to the server was 0 milliseconds ago.
[13:16:19] [Async Chat Thread - #4/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[13:16:19] [Async Chat Thread - #4/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[13:16:19] [Async Chat Thread - #4/WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[13:16:19] [Async Chat Thread - #4/WARN]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[13:16:19] [Async Chat Thread - #4/WARN]: 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
[13:16:19] [Async Chat Thread - #4/WARN]: 	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:989)
[13:16:19] [Async Chat Thread - #4/WARN]: 	at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3556)
[13:16:19] [Async Chat Thread - #4/WARN]: 	at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3456)
[13:16:19] [Async Chat Thread - #4/WARN]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3897)
[13:16:19] [Async Chat Thread - #4/WARN]: 	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2524)
[13:16:19] [Async Chat Thread - #4/WARN]: 	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2677)
[13:16:19] [Async Chat Thread - #4/WARN]: 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2545)
[13:16:19] [Async Chat Thread - #4/WARN]: 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2503)
[13:16:19] [Async Chat Thread - #4/WARN]: 	at com.mysql.jdbc.StatementImpl.executeQuery(StatementImpl.java:1369)
[13:16:19] [Async Chat Thread - #4/WARN]: 	at me.kangarko.chatcontrol.  ......Com2.protected(SourceFile:62)
[13:16:19] [Async Chat Thread - #4/WARN]: 	at me.kangarko.chatcontrol.  ......lPT3.protected(SourceFile:139)
[13:16:19] [Async Chat Thread - #4/WARN]: 	at me.kangarko.chatcontrol.  ......lPT3.protected(SourceFile:47)
[13:16:19] [Async Chat Thread - #4/WARN]: 	at me.kangarko.chatcontrol.  ......LpT7.protected(SourceFile:116)
[13:16:19] [Async Chat Thread - #4/WARN]: 	at me.kangarko.chatcontrol.  ......LpT7.protected(SourceFile:99)
[13:16:19] [Async Chat Thread - #4/WARN]: 	at me.kangarko.chatcontrol.  ......Lpt1.protected(SourceFile:526)
[13:16:19] [Async Chat Thread - #4/WARN]: 	at me.kangarko.chatcontrol.  ......Lpt1.protected(SourceFile:420)
[13:16:19] [Async Chat Thread - #4/WARN]: 	at me.kangarko.chatcontrol.  ......Lpt1.protected(SourceFile:273)
[13:16:19] [Async Chat Thread - #4/WARN]: 	at me.kangarko.chatcontrol.  ......Com8.protected(SourceFile:173)
[13:16:19] [Async Chat Thread - #4/WARN]: 	at me.kangarko.chatcontrol.  ......Com8.execute(SourceFile:43)
[13:16:19] [Async Chat Thread - #4/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[13:16:19] [Async Chat Thread - #4/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
[13:16:19] [Async Chat Thread - #4/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484)
[13:16:19] [Async Chat Thread - #4/WARN]: 	at net.minecraft.server.v1_11_R1.PlayerConnection.chat(PlayerConnection.java:1276)
[13:16:19] [Async Chat Thread - #4/WARN]: 	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1214)
[13:16:19] [Async Chat Thread - #4/WARN]: 	at net.minecraft.server.v1_11_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:39)
[13:16:19] [Async Chat Thread - #4/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[13:16:19] [Async Chat Thread - #4/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[13:16:19] [Async Chat Thread - #4/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[13:16:19] [Async Chat Thread - #4/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[13:16:19] [Async Chat Thread - #4/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[13:16:19] [Async Chat Thread - #4/WARN]: Caused by: java.io.EOFException: Can not read response from server. Expected to read 4 bytes, read 0 bytes before connection was unexpectedly lost.
[13:16:19] [Async Chat Thread - #4/WARN]: 	at com.mysql.jdbc.MysqlIO.readFully(MysqlIO.java:3008)
[13:16:19] [Async Chat Thread - #4/WARN]: 	at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3466)
[13:16:19] [Async Chat Thread - #4/WARN]: 	... 28 more
[13:16:19] [Async Chat Thread - #4/ERROR]: Could not pass event AsyncPlayerChatEvent to ChatControl v7.3.15
java.lang.NullPointerException
	at me.kangarko.chatcontrol.  ......lPT3.protected(SourceFile:141) ~[?:?]
	at me.kangarko.chatcontrol.  ......lPT3.protected(SourceFile:47) ~[?:?]
	at me.kangarko.chatcontrol.  ......LpT7.protected(SourceFile:116) ~[?:?]
	at me.kangarko.chatcontrol.  ......LpT7.protected(SourceFile:99) ~[?:?]
	at me.kangarko.chatcontrol.  ......Lpt1.protected(SourceFile:526) ~[?:?]
	at me.kangarko.chatcontrol.  ......Lpt1.protected(SourceFile:420) ~[?:?]
	at me.kangarko.chatcontrol.  ......Lpt1.protected(SourceFile:273) ~[?:?]
	at me.kangarko.chatcontrol.  ......Com8.protected(SourceFile:173) ~[?:?]
	at me.kangarko.chatcontrol.  ......Com8.execute(SourceFile:43) ~[?:?]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[custom.jar:git-Spigot-38ddb34-c19c293]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [custom.jar:git-Spigot-38ddb34-c19c293]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [custom.jar:git-Spigot-38ddb34-c19c293]
	at net.minecraft.server.v1_11_R1.PlayerConnection.chat(PlayerConnection.java:1276) [custom.jar:git-Spigot-38ddb34-c19c293]
	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1214) [custom.jar:git-Spigot-38ddb34-c19c293]
	at net.minecraft.server.v1_11_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:39) [custom.jar:git-Spigot-38ddb34-c19c293]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]

MC v 1.11.2 / ChatControl v 7.3.15

**Comment by kangarko** [comment]
Fixed in 7.3.17
