### ISSUE TITLE
Error in enabling Bungeecord : true

### ISSUE THREAD

**Issue by Gilthunderx** [kangarko/ChatControl-Pro#2375]
------------------------------------[ 03.07.2022 07:13:11 ]-----------------------------------
ChatControl 8.11.7 encountered an IllegalArgumentException
Running Paper 1.19-R0.1-SNAPSHOT and Java 17.0.2
Plugins: InventoryRollbackPlus v1.6.7, Chunky v1.2.217, PlaceholderAPI v2.11.1, PvPToggle v1.7, ChatReaction v1.8.0, ChatTags v1.0.2, ViaVersion v4.3.1, ViaBackwards v4.3.1, LuckPerms v5.4.9, BroadcastXS v3.4.3, spark v1.8.14, Votifier v2.7.3, ProtocolLib v5.0.0-SNAPSHOT-b569, LibsDisguises v10.0.28-SNAPSHOT, Vouchers v1.8-1.19-1.9.2, Vault v1.7.3-b131, ViaRewind v2.0.2, ChatColor2 v1.12.3, ResourceWorld v1.9.8, EpicRename v3.10.2, BungeeGuard v1.2-SNAPSHOT, PlayerVaults v4.2.9, NexEngine v2.2.0 build-18/06/2022, MyCommand v5.7.2, DecentHolograms v2.4.2, Essentials v2.19.4, LiteBans v2.9.5, SilkSpawners v2.1.5, Multiverse-Core v4.3.2-SNAPSHOT-b870, VotingPlugin v6.9, FastAsyncWorldEdit v2.4.0, TradeSystem v2.1.2, ajLeaderboards v2.4.5, CrazyAuctions v1.2.17-SNAPSHOT-Dev-Build-#9, DeluxeMenus v1.13.6-DEV-null, TAB v3.1.2, WorldGuard v7.0.7+216b061, EssentialsProtect v2.19.4, ChatFeelings v4.9.3, GSit v1.1.0, EssentialsSpawn v2.19.4, CoreProtect v21.2, WorldGuardExtraFlags v4.1.5-SNAPSHOT, AreaShop v2.6.3#CUSTOM, Guilds v3.5.6.3, ChatControl v8.11.7, Citizens v2.0.30-SNAPSHOT (build 2577), ExcellentCrates v4.0.5, mcMMO v2.1.212, GriefPrevention v16.18, PlayerParticles v8.2, ArtMap v3.9.5, MiniaturePets v2.7.4, StreakRewards v2.2.5, BlockLocker v1.10.4, Rankup v3.13.3, Boss v4.4.1, more-fish v3.0.3-SNAPSHOT, eGlow v3.1.6, Vulcan v2.6.7-HOTFIX, BetterRTP v3.4.2-2, AdvancedEnchantments v8.11.6, PlayerWarps v6.17.3, CMILib v1.2.0.3, Jobs v5.0.3.0, DeluxeChat v1.16.2, BottledExp v3.1.0.0, ChestShop v3.12.2 (build 353), MobFarmManager v2.0.3.0, InteractiveChat v4.2.2.0, Shopkeepers v2.15.1, Brewery v3.1, ClueScrolls v4.8.4
----------------------------------------------------------------------------------------------

More Information: 
Error reloading ChatControl 8.11.7
IllegalArgumentException This registration already exists
	 at org.bukkit.plugin.messaging.StandardMessenger.addToIncoming(StandardMessenger.java:94)
	 at org.bukkit.plugin.messaging.StandardMessenger.registerIncomingPluginChannel(StandardMessenger.java:226)
	 at ChatControl-8.11.7.jar//org.mineacademy.chatcontrol.lib.fo.plugin.SimplePlugin.registerBungeeCord(SimplePlugin.java:504)
	 at ChatControl-8.11.7.jar//org.mineacademy.chatcontrol.ChatControl.onReloadablesStart(ChatControl.java:286)
	 at ChatControl-8.11.7.jar//org.mineacademy.chatcontrol.lib.fo.plugin.SimplePlugin.reload(SimplePlugin.java:828)
	 at ChatControl-8.11.7.jar//org.mineacademy.chatcontrol.command.ChatControlCommand.onCommand(ChatControlCommand.java:553)
	 at ChatControl-8.11.7.jar//org.mineacademy.chatcontrol.lib.fo.command.SimpleCommand.execute(SimpleCommand.java:399)
	 at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)
	 at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:907)
	 at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchServerCommand(CraftServer.java:870)
----------------------------------------------------------------------------------------------

Minecraft Version: 1.19
MySQL: false
BungeeCord: true

**Comment by kangarko** [comment]
Do not reload, it is known to cause issues especially with these registrations.
