### ISSUE TITLE
Error when using /chc reload

### ISSUE THREAD

**Issue by AndGK** [kangarko/ChatControl-Pro#242]
Hey. I get this error whenever I reload the plugin using /chc reload
```
>chc reload
[16:01:44 INFO]: *-----------------------------------------------*
[16:01:44 INFO]: Reloading plugin ChatControl v7.3.17
[16:01:44 INFO]: *-----------------------------------------------*
[16:01:44 INFO]: Configuration loads..
[16:01:44 INFO]: *-----------------------------------------------*
[16:01:44 INFO]:  Failed to reload configuration
[16:01:44 INFO]: *-----------------------------------------------*
[16:01:44 WARN]: java.lang.reflect.InvocationTargetException
[16:01:44 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[16:01:44 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[16:01:44 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[16:01:44 WARN]:        at java.lang.reflect.Method.invoke(Method.java:498)
[16:01:44 WARN]:        at me.kangarko.chatcontrol.  .....lpt6.const(SourceFile:133)
[16:01:44 WARN]:        at me.kangarko.chatcontrol.  .....lpt6.volatile(SourceFile:109)
[16:01:44 WARN]:        at me.kangarko.chatcontrol.  .....lpt6.g(SourceFile:94)
[16:01:44 WARN]:        at me.kangarko.chatcontrol.  .....COM5.const(SourceFile:55)
[16:01:44 WARN]:        at me.kangarko.chatcontrol.  .....lpt6.const(SourceFile:56)
[16:01:44 WARN]:        at me.kangarko.chatcontrol.  .....cOm6.strictfp(SourceFile:151)
[16:01:44 WARN]:        at me.kangarko.chatcontrol.  .....nul.const(SourceFile:423)
[16:01:44 WARN]:        at me.kangarko.chatcontrol.  .....lPT8.onCommand(SourceFile:50)
[16:01:44 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[16:01:44 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[16:01:44 WARN]:        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:650)
[16:01:44 WARN]:        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchServerCommand(CraftServer.java:636)
[16:01:44 WARN]:        at net.minecraft.server.v1_11_R1.DedicatedServer.aM(DedicatedServer.java:437)
[16:01:44 WARN]:        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:400)
[16:01:44 WARN]:        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678)
[16:01:44 WARN]:        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576)
[16:01:44 WARN]:        at java.lang.Thread.run(Thread.java:748)
[16:01:44 WARN]: Caused by: java.lang.IllegalArgumentException: Warning set 'global' already exists! (TIP: Use /chc reload, not plugin managers!)
[16:01:44 WARN]:        at org.apache.commons.lang.Validate.isTrue(Validate.java:136)
[16:01:44 WARN]:        at me.kangarko.chatcontrol.  .....LpT7.const(SourceFile:81)
[16:01:44 WARN]:        at me.kangarko.chatcontrol.  .....COM5$CoM5.init(SourceFile:742)
[16:01:44 WARN]:        ... 21 more
[16:01:44 INFO]: An unhandled error occured during executing the command.
[16:01:44 WARN]: java.lang.NullPointerException
[16:01:44 WARN]:        at java.lang.String.replace(String.java:2240)
[16:01:44 WARN]:        at me.kangarko.chatcontrol.  .....nul.const(SourceFile:427)
[16:01:44 WARN]:        at me.kangarko.chatcontrol.  .....lPT8.onCommand(SourceFile:50)
[16:01:44 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[16:01:44 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[16:01:44 WARN]:        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:650)
[16:01:44 WARN]:        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchServerCommand(CraftServer.java:636)
[16:01:44 WARN]:        at net.minecraft.server.v1_11_R1.DedicatedServer.aM(DedicatedServer.java:437)
[16:01:44 WARN]:        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:400)
[16:01:44 WARN]:        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678)
[16:01:44 WARN]:        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576)
[16:01:44 WARN]:        at java.lang.Thread.run(Thread.java:748)

```

**Comment by kangarko** [comment]
Thank you for reporting.

The bug was confirmed and will be fixed shortly.
