### ISSUE TITLE
ChatControl won't work with 1.12

### ISSUE THREAD

**Issue by StandbyGamer** [kangarko/ChatControl-Pro#256]
I updated my server up to 1.12 and installed ChatControl but it shows me the error in the console and disabled ChatControl.

```
[21:59:48] [Server thread/INFO]: [ChatControl] Enabling ChatControl v5.5.1
[21:59:48] [Server thread/INFO]: Hooked into: AuthMe (Country Variables)
[21:59:48] [Server thread/INFO]: Hooked into: Essentials
[21:59:48] [Server thread/INFO]: Hooked into: Multiverse-Core (World Alias)
[21:59:48] [Server thread/INFO]: Hooked into: ProtocolLib (Packet Features)
[21:59:48] [Server thread/INFO]: Hooked into: Vault
[21:59:48] [Server thread/INFO]: Hooked into: PlaceholderAPI
[21:59:48] [Server thread/INFO]: Updating settings.yml with 'Minimum_Players_To_Enable_Checks' -> '0'
[21:59:48] [Server thread/INFO]: Updating settings.yml with 'Version' -> ''
[21:59:48] [Server thread/INFO]: Updating settings.yml with 'Anti_Bot.Rejoin_Delay_Seconds' -> ''
[21:59:48] [Server thread/INFO]: Updating settings.yml with 'Anti_Bot.Block_Actions_Until_Moved.Chat' -> 'true'
[21:59:48] [Server thread/INFO]: Updating settings.yml with 'Anti_Caps.Warn_Player' -> 'true'
[21:59:48] [Server thread/INFO]: Updating settings.yml with 'Anti_Spam.Chat.Regex_In_Whitelist' -> 'false'
[21:59:48] [Server thread/INFO]: Updating settings.yml with 'Chat.Formatter.Message_Format' -> '%pl_prefix%player:%pl_suffix %message'
[21:59:48] [Server thread/INFO]: Updating settings.yml with 'Chat.Formatter.Global_Message_Format' -> '[GLOBAL]%pl_prefix%player:%pl_suffix%message'
[21:59:48] [Server thread/INFO]: Updating settings.yml with 'Chat.Formatter.Spy_Message_Format' -> 'SPY: [%world%pl_prefix%player:%pl_suffix%message]'
[21:59:48] [Server thread/INFO]: Updating settings.yml with 'Chat.Formatter.Ranged_Mode' -> 'false'
[21:59:48] [Server thread/WARN]: java.lang.reflect.InvocationTargetException
[21:59:48] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[21:59:48] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[21:59:48] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[21:59:48] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[21:59:48] [Server thread/WARN]: 	at kangarko.chatcontrol.config.ConfHelper.invokeMethods(ConfHelper.java:84)
[21:59:48] [Server thread/WARN]: 	at kangarko.chatcontrol.config.ConfHelper.loadValues(ConfHelper.java:70)
[21:59:48] [Server thread/WARN]: 	at kangarko.chatcontrol.config.ConfHelper.createFileAndLoad(ConfHelper.java:123)
[21:59:48] [Server thread/WARN]: 	at kangarko.chatcontrol.config.Settings.load(Settings.java:26)
[21:59:48] [Server thread/WARN]: 	at kangarko.chatcontrol.config.ConfHelper.loadAll(ConfHelper.java:54)
[21:59:48] [Server thread/WARN]: 	at kangarko.chatcontrol.ChatControl.onEnable(ChatControl.java:90)
[21:59:48] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[21:59:48] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
[21:59:48] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402)
[21:59:48] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:377)
[21:59:48] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:327)
[21:59:48] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:421)
[21:59:48] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:382)
[21:59:48] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:337)
[21:59:48] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272)
[21:59:48] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:544)
[21:59:48] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[21:59:48] [Server thread/WARN]: Caused by: java.lang.IllegalArgumentException: Malformed config value, expected double at: Chat.Formatter.Range
[21:59:48] [Server thread/WARN]: 	at org.apache.commons.lang.Validate.isTrue(Validate.java:136)
[21:59:48] [Server thread/WARN]: 	at kangarko.chatcontrol.config.ConfHelper.getDouble(ConfHelper.java:164)
[21:59:48] [Server thread/WARN]: 	at kangarko.chatcontrol.config.Settings$Chat$Formatter.init(Settings.java:138)
[21:59:48] [Server thread/WARN]: 	... 21 more
[21:59:48] [Server thread/INFO]: !----------------------------------------------!
[21:59:48] [Server thread/INFO]:  Error loading ChatControl, plugin is disabled!
[21:59:48] [Server thread/INFO]:  Running on 1.12-R0.1-SNAPSHOT (v1_12_R1) and Java 1.8.0_101
[21:59:48] [Server thread/INFO]: !----------------------------------------------!
[21:59:48] [Server thread/INFO]:  Error: Unable to get the error message, search above.
[21:59:48] [Server thread/INFO]: !----------------------------------------------!
[21:59:48] [Server thread/INFO]: [ChatControl] Disabling ChatControl v5.5.1
```

**Comment by EvilOlaf** [comment]
You are obviously using CHC free, not Pro.
Therefore please post your issue in the proper repository which you can find here: https://github.com/kangarko/ChatControl


Invalid

**Comment by kangarko** [comment]
Next time please use the issue channel mentioned above :)

The Range property in **Chat.Formatter.Range** must be a double, that means a number with a '.' like 2.5 or 2.0, not a whole number 1, 2, 3, ...
