### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by Sikatsu** [kangarko/ChatControl-Pro#26]
I'm receiving this error and my server crashes too. Not sure if it's the reason of the crash, but it's still an error I'd like not to see. ^^

`[15:53:10] [Async Chat Thread - #0/WARN]: java.lang.RuntimeException: Essentials API 
[15:53:10] [Async Chat Thread - #0/WARN]: is called before Essentials is loaded.
[15:53:10] [Async Chat Thread - #0/WARN]: 	at com.earth2me.essentials.api.Economy.getUserByName(Economy.java:62)
[15:53:10] [Async Chat Thread - #0/WARN]: 	at com.earth2me.essentials.api.Economy.getMoneyExact(Economy.java:85)
[15:53:10] [Async Chat Thread - #0/WARN]: 	at com.earth2me.essentials.api.Economy.getMoney(Economy.java:81)
[15:53:10] [Async Chat Thread - #0/WARN]: 	at net.milkbowl.vault.economy.plugins.Economy_Essentials.getBalance(Economy_Essentials.java:78)
[15:53:10] [Async Chat Thread - #0/WARN]: 	at net.milkbowl.vault.economy.AbstractEconomy.getBalance(AbstractEconomy.java:20)
[15:53:10] [Async Chat Thread - #0/WARN]: 	at com.extendedclip.papi.expansion.vault.VaultEcoHook.getBalance(VaultEcoHook.java:112)
[15:53:10] [Async Chat Thread - #0/WARN]: 	at com.extendedclip.papi.expansion.vault.VaultEcoHook.onPlaceholderRequest(VaultEcoHook.java:60)
[15:53:10] [Async Chat Thread - #0/WARN]: 	at com.extendedclip.papi.expansion.vault.VaultExpansion.onPlaceholderRequest(VaultExpansion.java:85)
[15:53:10] [Async Chat Thread - #0/WARN]: 	at me.clip.placeholderapi.PlaceholderAPI.setBracketPlaceholders(PlaceholderAPI.java:291)
[15:53:10] [Async Chat Thread - #0/WARN]: 	at me.kangarko.chatcontrol.COm7.const(SourceFile:569)
[15:53:10] [Async Chat Thread - #0/WARN]: 	at me.kangarko.chatcontrol.cOM6.const(SourceFile:219)
[15:53:10] [Async Chat Thread - #0/WARN]: 	at me.kangarko.chatcontrol.cOM5.const(SourceFile:143)
[15:53:10] [Async Chat Thread - #0/WARN]: 	at me.kangarko.chatcontrol.cOM5.const(SourceFile:129)
[15:53:10] [Async Chat Thread - #0/WARN]: 	at me.kangarko.chatcontrol.cOM5.const(SourceFile:122)
[15:53:10] [Async Chat Thread - #0/WARN]: 	at me.kangarko.chatcontrol.Prn.native(SourceFile:304)
[15:53:10] [Async Chat Thread - #0/WARN]: 	at me.kangarko.chatcontrol.prn.const(SourceFile:345)
[15:53:10] [Async Chat Thread - #0/WARN]: 	at me.kangarko.chatcontrol.pRN.const(SourceFile:48)
[15:53:10] [Async Chat Thread - #0/WARN]: 	at me.kangarko.chatcontrol.aux.const(SourceFile:82)
[15:53:10] [Async Chat Thread - #0/WARN]: 	at me.kangarko.chatcontrol.aux.execute(SourceFile:45)
[15:53:10] [Async Chat Thread - #0/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[15:53:10] [Async Chat Thread - #0/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
[15:53:10] [Async Chat Thread - #0/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484)
[15:53:10] [Async Chat Thread - #0/WARN]: 	at net.minecraft.server.v1_9_R1.PlayerConnection.chat(PlayerConnection.java:1272)
[15:53:10] [Async Chat Thread - #0/WARN]: 	at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1210)
[15:53:10] [Async Chat Thread - #0/WARN]: 	at net.minecraft.server.v1_9_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:39)
[15:53:10] [Async Chat Thread - #0/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[15:53:10] [Async Chat Thread - #0/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[15:53:10] [Async Chat Thread - #0/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[15:53:10] [Async Chat Thread - #0/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[15:53:10] [Async Chat Thread - #0/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[15:53:10] [Async Chat Thread - #0/INFO]: [ChatControl] *----------------------------------------------*
[15:53:10] [Async Chat Thread - #0/INFO]: [ChatControl]  PlaceholderAPI failed to replace variables!
[15:53:10] [Async Chat Thread - #0/INFO]: [ChatControl]  Player: Jorian03
[15:53:10] [Async Chat Thread - #0/INFO]: [ChatControl]  Message: *-----* Jorian03 *-----*
[15:53:10] [Async Chat Thread - #0/INFO]: [ChatControl] Speelt sinds: {player_first_join_date}
[15:53:10] [Async Chat Thread - #0/INFO]: [ChatControl] Totale speeltijd: {statistic_time_played}
[15:53:10] [Async Chat Thread - #0/INFO]: [ChatControl] Totale votes: {voteroulette_votes_lifetime}
[15:53:10] [Async Chat Thread - #0/INFO]: [ChatControl] Aantal keer dood: {statistic_deaths}
[15:53:10] [Async Chat Thread - #0/INFO]: [ChatControl] Saldo: {vault_eco_balance_fixed}
[15:53:10] [Async Chat Thread - #0/INFO]: [ChatControl]  Error: RuntimeException: Essentials API is called before Essentials is loaded.
[15:53:10] [Async Chat Thread - #0/INFO]: [ChatControl] *----------------------------------------------*`

**Comment by kangarko** [comment]
The error is hard to read, please repost on pastebin and ensure you have latest PlaceholderAPI.

**Comment by Sikatsu** [comment]
Pastebin: http://pastebin.com/aR7erqvt

I'm for sure using the latest placeholderAPI.

**Comment by kangarko** [comment]
This error comes from PlaceholderAPI, please contact its developer first.

**Comment by Sikatsu** [comment]
Hmm, I didn't see the error anymore, maybe it has been fixed with a PlaceholderAPI update in the meanwhile. If not, I'll make sure to contact the developer. ^^

**Comment by kangarko** [comment]
Fixed by third party.
