### ISSUE TITLE
Volanie nastaveni pred ich nacitanim

### ISSUE THREAD

**Issue by MC-SHD1** [kangarko/ChatControl-Pro#265]
[14:32:40 INFO]: [ChatControl] Enabling ChatControl v7.3.19
[14:32:40 INFO]:  _____ _           _    _____            _             _  +
[14:32:40 INFO]:  / ____| |         | |  / ____|          | |           | |
[14:32:40 INFO]: | |    | |__   __ _| |_| |     ___  _ __ | |_ _ __ ___ | |
[14:32:40 INFO]: | |    | '_ \ / _` | __| |    / _ \| '_ \| __| '__/ _ \| |
[14:32:40 INFO]: | |____| | | | (_| | |_| |___| (_) | | | | |_| | | (_) | |
[14:32:40 INFO]:  \_____|_| |_|\__,_|\__|\_____\___/|_| |_|\__|_|  \___/|_|
[14:32:40 INFO]:
[14:32:40 WARN]: java.lang.IllegalArgumentException: [FATAL/REPORT ME] Volanie nastaveni pred ich nacitanim!
[14:32:40 WARN]:        at org.apache.commons.lang.Validate.isTrue(Validate.java:136)
[14:32:40 WARN]:        at me.kangarko.chatcontrol.ChatControl.throw(SourceFile:529)
[14:32:40 WARN]:        at me.kangarko.chatcontrol.ChatControl.strictfp(SourceFile:478)
[14:32:40 WARN]:        at me.kangarko.chatcontrol.  .....CoN.onEnable(SourceFile:81)
[14:32:40 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271)
[14:32:40 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316)
[14:32:40 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407)
[14:32:40 WARN]:        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:378)
[14:32:40 WARN]:        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:328)
[14:32:40 WARN]:        at net.minecraft.server.v1_11_R1.MinecraftServer.t(MinecraftServer.java:437)
[14:32:40 WARN]:        at net.minecraft.server.v1_11_R1.MinecraftServer.l(MinecraftServer.java:398)
[14:32:40 WARN]:        at net.minecraft.server.v1_11_R1.MinecraftServer.a(MinecraftServer.java:336)
[14:32:40 WARN]:        at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:276)
[14:32:40 WARN]:        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:603)
[14:32:40 WARN]:        at java.lang.Thread.run(Thread.java:745)
[14:32:40 INFO]:   _   _                       _
[14:32:40 INFO]:   | | | | ___   ___  _ __  ___| |
[14:32:40 INFO]:   | |_| |/ _ \ / _ \| '_ \/ __| |
[14:32:40 INFO]:   |  _  | (_) | (_) | |_) \__ \_|
[14:32:40 INFO]:   |_| |_|\___/ \___/| .__/|___(_)
[14:32:40 INFO]:                     |_|
[14:32:40 INFO]: !-----------------------------------------------------!
[14:32:40 INFO]:  Error loading ChatControl v7.3.19, plugin is disabled!
[14:32:40 INFO]:  Running on 1.11.2-R0.1-SNAPSHOT (v1_11_R1) & Java 1.8.0_101
[14:32:40 INFO]: !-----------------------------------------------------!
[14:32:40 INFO]:  Error: [FATAL/REPORT ME] Volanie nastaveni pred ich nacitanim!
[14:32:40 INFO]: !-----------------------------------------------------!

I didn't use plugman and didn't use reload command either.
I'm sure this is a clean server start.
It's the newest version.
And my server version is PaperSpigot-1.11.2
java version is Java 1.8.0_101

**Comment by kangarko** [comment]
Hey, I don't mean to be rude but I have to ask: Have you purchased the plugin? Because there are several piracy checks and if someone attempts to crack the jar this is one of the result(s).

**Comment by kangarko** [comment]
You may try the version 7.4.0, as there have been somechanges in that.

**Comment by kangarko** [comment]
Closing, if still having issues please post below.

**Comment by MC-SHD1** [comment]
Thank you. I've solved the problem
