### ISSUE TITLE
issue on my server....

### ISSUE THREAD

**Issue by Jerlag01** [kangarko/ChatControl-Pro#268]
I'm having following error:

[14:29:57 INFO]: [ChatControl] Enabling ChatControl v7.4.3
[14:29:57 INFO]:  _____ _           _    _____            _             _  +
[14:29:57 INFO]:  / ____| |         | |  / ____|          | |           | |
[14:29:57 INFO]: | |    | |__   __ _| |_| |     ___  _ __ | |_ _ __ ___ | |
[14:29:57 INFO]: | |    | '_ \ / _` | __| |    / _ \| '_ \| __| '__/ _ \| |
[14:29:57 INFO]: | |____| | | | (_| | |_| |___| (_) | | | | |_| | | (_) | |
[14:29:57 INFO]:  \_____|_| |_|\__,_|\__|\_____\___/|_| |_|\__|_|  \___/|_|
[14:29:57 INFO]:
[14:29:57 INFO]: *-----------------------------------------------*
[14:29:57 INFO]:  There was a fatal problem with this version. We apologies.
[14:29:57 INFO]: If you have purchased it, please contact the author!
[14:29:57 INFO]: If not, well, too bad! (I am sad :()
[14:29:57 INFO]:  Plugin is now disabled.
[14:29:57 INFO]: *-----------------------------------------------*
[14:29:57 INFO]: [ChatControl] Disabling ChatControl v7.4.3
[14:29:57 INFO]: Plugin might not shut down property. Got NullPointerException: null
[14:29:57 INFO]: Configuration loads..
[14:29:57 INFO]: Created default file: settings.yml
[14:29:57 INFO]: Created default file: javascript.txt
[14:29:57 INFO]: Created default file: chat.yml
[14:29:57 INFO]: Created default file: messages.yml
[14:29:57 INFO]:
[14:29:57 INFO]: Checking compatible plugins..
[14:29:57 INFO]: Found:
[14:29:57 INFO]:
[14:29:57 INFO]: Rules loads now..
[14:29:58 INFO]: Created default file: handlers.yml
[14:29:58 INFO]: Created default file: rules.txt
[14:29:58 INFO]: Created default file: packets.txt
[14:29:58 INFO]: Created default file: chat.txt
[14:29:58 INFO]: Created default file: commands.txt
[14:29:58 INFO]: Created default file: sign.txt
[14:29:58 INFO]: Created default file: books.txt
[14:29:58 INFO]: Created default file: items.txt
[14:29:58 INFO]: 43 global, 15 chat, 4 command, 2 packet and one book rule(s) found
[14:29:58 INFO]:
[14:29:58 INFO]: Listening starts..
[14:29:58 INFO]: Chat & rules are watched with normal priority
[14:29:58 WARN]: org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register class org.bukkit.event.player.AsyncPlayerChatEvent while not enabled
[14:29:58 WARN]:        at org.bukkit.plugin.SimplePluginManager.registerEvent(SimplePluginManager.java:556)
[14:29:58 WARN]:        at me.kangarko.chatcontrol.  .....coM6.const(SourceFile:254)
[14:29:58 WARN]:        at me.kangarko.chatcontrol.ChatControl.const(SourceFile:98)
[14:29:58 WARN]:        at me.kangarko.chatcontrol.  .....coM6.onEnable(SourceFile:73)
[14:29:58 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[14:29:58 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
[14:29:58 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[14:29:58 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357)
[14:29:58 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317)
[14:29:58 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414)
[14:29:58 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378)
[14:29:58 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333)
[14:29:58 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263)
[14:29:58 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525)
[14:29:58 WARN]:        at java.lang.Thread.run(Unknown Source)
[14:29:58 INFO]:   _   _                       _
[14:29:58 INFO]:   | | | | ___   ___  _ __  ___| |
[14:29:58 INFO]:   | |_| |/ _ \ / _ \| '_ \/ __| |
[14:29:58 INFO]:   |  _  | (_) | (_) | |_) \__ \_|
[14:29:58 INFO]:   |_| |_|\___/ \___/| .__/|___(_)
[14:29:58 INFO]:                     |_|
[14:29:58 INFO]: !-----------------------------------------------------!
[14:29:58 INFO]:  Error loading ChatControl v7.4.3, plugin is disabled!
[14:29:58 INFO]:  Running on 1.8.8-R0.1-SNAPSHOT (v1_8_R3) & Java 1.8.0_131
[14:29:58 INFO]: !-----------------------------------------------------!
[14:29:58 INFO]:  Error: Plugin attempted to register class org.bukkit.event.player.AsyncPlayerChatEvent while not enabled
[14:29:58 INFO]: !-----------------------------------------------------!

**Comment by kangarko** [comment]
Have you purchased the plugin?

**Comment by Jerlag01** [comment]
Yes i purchased. Spigot account: FlandersCraft

Op 19 jun. 2017 18:45 schreef "kangarko" <notifications@github.com>:

**Comment by kangarko** [comment]
I am very sorry, but you appears on blacklist for leaking ChatControl in the past. Thus you no longer have access to the plugin.

**Comment by Jerlag01** [comment]
I never leaked the plugin myself..... so I don't know how and when but i'm
sure I never leaked it....

2017-06-20 12:12 GMT+02:00 kangarko <notifications@github.com>:

**Comment by kangarko** [comment]
It should work now, can you test?

**Comment by Jerlag01** [comment]
Yeah thank you. I changed my password just in case.

Op 20 jun. 2017 22:13 schreef "kangarko" <notifications@github.com>:
