### ISSUE TITLE
NPE

### ISSUE THREAD

**Issue by EvilOlaf** [kangarko/ChatControl-Pro#274]
```
[13:40:05] [Server thread/INFO]: *-----------------------------------------------*
[13:40:05] [Server thread/INFO]: Reloading plugin ChatControl v7.4.7
[13:40:05] [Server thread/INFO]: *-----------------------------------------------*
[13:40:05] [Server thread/INFO]: Configuration loads..
[13:40:05] [Jobs-BufferedPaymentThread/ERROR]: [ChatControl] Unhandled exception occured in onPacketSending(PacketEvent) for ChatControl
java.lang.NullPointerException: [REPORT ME] Rules map doesnt have rules type: PACKET
        at java.util.Objects.requireNonNull(Objects.java:228) ~[?:1.8.0_131]
        at me.kangarko.chatcontrol.  .....lPT7.const(SourceFile:291) ~[ChatControl.jar:?]
        at me.kangarko.chatcontrol.  .....lPT7.const(SourceFile:636) ~[ChatControl.jar:?]
        at me.kangarko.chatcontrol.  .....lPt7$2.onPacketSending(SourceFile:74) ~[ChatControl.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) [ProtocolLib-4.2.1-b354.jar:4.2.1]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) [ProtocolLib-4.2.1-b354.jar:4.2.1]
        at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:608) [ProtocolLib-4.2.1-b354.jar:4.2.1]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:584) [ProtocolLib-4.2.1-b354.jar:4.2.1]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:309) [ProtocolLib-4.2.1-b354.jar:4.2.1]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:269) [ProtocolLib-4.2.1-b354.jar:4.2.1]
        at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:396) [ProtocolLib-4.2.1-b354.jar:4.2.1]
        at com.comphenix.protocol.injector.netty.ChannelInjector.access$500(ChannelInjector.java:77) [ProtocolLib-4.2.1-b354.jar:4.2.1]
        at com.comphenix.protocol.injector.netty.ChannelInjector$5.handleScheduled(ChannelInjector.java:362) [ProtocolLib-4.2.1-b354.jar:4.2.1]
        at com.comphenix.protocol.injector.netty.ChannelInjector$5.onMessageScheduled(ChannelInjector.java:330) [ProtocolLib-4.2.1-b354.jar:4.2.1]
        at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) [ProtocolLib-4.2.1-b354.jar:4.2.1]
        at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) [ProtocolLib-4.2.1-b354.jar:4.2.1]
        at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:192) [spigot.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.NetworkManager.handle(NetworkManager.java:141) [spigot.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.PlayerConnection.sendPacket(PlayerConnection.java:907) [spigot.jar:git-Spigot-21fe707-e1ebe52]
        at sun.reflect.GeneratedMethodAccessor390.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
        at com.gamingmesh.jobs.stuff.ActionBar.send(ActionBar.java:113) [Jobs3.9.4.jar:?]
        at com.gamingmesh.jobs.stuff.ActionBar.ShowActionBar(ActionBar.java:86) [Jobs3.9.4.jar:?]
        at com.gamingmesh.jobs.economy.BufferedEconomy.payAll(BufferedEconomy.java:196) [Jobs3.9.4.jar:?]
        at com.gamingmesh.jobs.tasks.BufferedPaymentThread.run(BufferedPaymentThread.java:55) [Jobs3.9.4.jar:?]
[13:40:05] [Server thread/INFO]: 112 global, 28 chat, 17 command, 2 packet and one book rule(s) found
[13:40:05] [Server thread/INFO]:
[13:40:05] [Server thread/INFO]: [ChatControl] Configuration reloaded successfully.
[13:40:05] [Jobs-BufferedPaymentThread/ERROR]: Parameters:
  net.minecraft.server.v1_8_R3.PacketPlayOutChat@33f90654[
    a=TextComponent{text='§a§aYou got: §e2,34 money §62,34 points §70,99 exp', siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}
    components=<null>
    b=2
  ]


```

It seems like the message CHC is "worried" about comes from JobsReborn plugin.
As I could not reproduce this my guess is the very same time the configuration has been reloaded Jobs issued a Actionbar message to a player and for some reason CHC did not like that.

Spigot 1.8.8 @ CHC 7.4.7
JobsReborn 3.9.4 if interesting to know

**Comment by kangarko** [comment]
Does it happen once or each time you reload? From a quick look I find no obvious errors but it seems like a concurrency issue, somehow in the middle of reloading the other plugin interferes.

**Comment by EvilOlaf** [comment]
That was a one time occurrence.

**Comment by kangarko** [comment]
Congratulations for finding the 0.01% pain-in-the ass error, haha!

I'll silence it in the next version :)

**Comment by EvilOlaf** [comment]
It was a pleasure for me ^^
