### ISSUE TITLE
can you help me?

### ISSUE THREAD

**Issue by shenrne** [kangarko/ChatControl-Pro#282]
[12:25:27] [Server thread/INFO]: [ChatControl] Enabling ChatControl v7.4.10
[12:25:27] [Server thread/INFO]: [0;36;1m _____ _           _    _____            _             _  [0;35;1m+[m
[12:25:27] [Server thread/INFO]: [0;36;1m / ____| |         | |  / ____|          | |           | |[m
[12:25:27] [Server thread/INFO]: [0;36;1m| |    | |__   __ _| |_| |     ___  _ __ | |_ _ __ ___ | |[m
[12:25:27] [Server thread/INFO]: [0;36;1m| |    | '_ \ / _` | __| |    / _ \| '_ \| __| '__/ _ \| |[m
[12:25:27] [Server thread/INFO]: [0;36;22m| |____| | | | (_| | |_| |___| (_) | | | | |_| | | (_) | |[m
[12:25:27] [Server thread/INFO]: [0;36;22m \_____|_| |_|\__,_|\__|\_____\___/|_| |_|\__|_|  \___/|_|[m
[12:25:27] [Server thread/INFO]:  [m
[12:25:27] [Server thread/WARN]: java.lang.IllegalArgumentException: [FATAL/REPORT ME] Volanie nastaveni pred ich nacitanim!
[12:25:27] [Server thread/WARN]: 	at org.apache.commons.lang.Validate.isTrue(Validate.java:136)
[12:25:27] [Server thread/WARN]: 	at me.kangarko.chatcontrol.ChatControl.throw(SourceFile:529)
[12:25:27] [Server thread/WARN]: 	at me.kangarko.chatcontrol.ChatControl.strictfp(SourceFile:476)
[12:25:27] [Server thread/WARN]: 	at me.kangarko.chatcontrol.  .....coM6.onEnable(SourceFile:83)
[12:25:27] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271)
[12:25:27] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
[12:25:27] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[12:25:27] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:376)
[12:25:27] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:326)
[12:25:27] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.t(MinecraftServer.java:421)
[12:25:27] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.l(MinecraftServer.java:382)
[12:25:27] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.a(MinecraftServer.java:337)
[12:25:27] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:272)
[12:25:27] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:544)
[12:25:27] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[12:25:27] [Server thread/INFO]: [0;31;1m  _   _                       _ [m
[12:25:27] [Server thread/INFO]: [0;31;1m  | | | | ___   ___  _ __  ___| |[m
[12:25:27] [Server thread/INFO]: [0;31;1m  | |_| |/ _ \ / _ \| '_ \/ __| |[m
[12:25:27] [Server thread/INFO]: [0;31;1m  |  _  | (_) | (_) | |_) \__ \_|[m
[12:25:27] [Server thread/INFO]: [0;31;22m  |_| |_|\___/ \___/| .__/|___(_)[m
[12:25:27] [Server thread/INFO]: [0;31;22m                    |_|          [m
[12:25:27] [Server thread/INFO]: [0;31;22m!-----------------------------------------------------![m
[12:25:27] [Server thread/INFO]:  [0;31;1mError loading ChatControl v7.4.10, plugin is disabled![m
[12:25:27] [Server thread/INFO]:  [0;31;1mRunning on 1.11.2-R0.1-SNAPSHOT (v1_11_R1) & Java 1.8.0_131[m
[12:25:27] [Server thread/INFO]: [0;31;22m!-----------------------------------------------------![m
[12:25:27] [Server thread/INFO]:  [0;31;1mError: [FATAL/REPORT ME] Volanie nastaveni pred ich nacitanim![m
[12:25:27] [Server thread/INFO]: [0;31;22m!-----------------------------------------------------![m
[12:25:27] [Server thread/INFO]: [ChatControl] Disabling ChatControl v7.4.10

**Comment by kangarko** [comment]
You're posting in the wrong channel & this has already been addressed and is awaiting a fix.

**Comment by kangarko** [comment]
Reference: https://github.com/kangarko/ChatControl-Pro/issues/270
