### ISSUE TITLE
Can't change anything inside the rules section.

### ISSUE THREAD

**Issue by Rodrogamby** [kangarko/ChatControl-Pro#285]
Everytime I try to change something inside the rules section, I get this error, and the plugin breaks, please I need this to get fixed, I've just purchased the plugin and I'm already getting a bad experience. I had to get to Lite ChatControl again to protect the chat.
This is the error I get: 
[09:32:39] [Server thread/INFO]: Rodro issued server command: /chc reload
[09:32:39] [Server thread/INFO]: *-----------------------------------------------*[m
[09:32:39] [Server thread/INFO]: Reloading plugin ChatControl v7.4.10[m
[09:32:39] [Server thread/INFO]: *-----------------------------------------------*[m
[09:32:39] [Server thread/INFO]: [0;36;22mConfiguration loads[0;30;1m..[m
[09:32:39] [Server thread/INFO]: [ChatControl debug] Loaded 7 format(s), as follow:[m
[09:32:39] [Server thread/INFO]: [ChatControl debug] 
[mFormat {
[m  Name: 'Private_Message_Receiver'
[m  Parts: <<
[m    Everything {
[m      Message: '[0;37;22m✉ [0;33;22mde {sender}: [0;37;1m{message}'
[m      Hover Event: SHOW_TEXT with values: 
[m        -      [0;30;1m~ [0;36;22mMensaje privado [0;30;1m~     
[m        - [0;30;1m[3mRecibido {timestamp}
[m        - [0;36;22mRemitente: [0;37;1m{sender}
[m        - 
[m        - [0;37;22mClic para responder.
[m      Click Event: SUGGEST_COMMAND with value: /r 
[m    } >>
[m}[m
[09:32:39] [Server thread/INFO]: [ChatControl debug] 
[mFormat {
[m  Name: 'Example_Format'
[m  Parts: <<
[m    Staff {
[m      Message: '[0;33;22m[[0;32;1m+] '
[m      Hover Event: SHOW_TEXT with values: 
[m        - [0;33;22mAdministrador de Castle-Elevel
[m        - [0;33;22mDesde el [0;32;1m21/Jul/2012
[m    }
[m    Prefix {
[m      Message: '{pl_prefix}'
[m      Hover Event: SHOW_TEXT with values: 
[m        - [0;30;1m*-----* [0;37;1m{player} [0;30;1m*-----*
[m        - [0;37;22mPrefijo[0;30;1m: [0;37;22m{pl_prefix}
[m        - [0;37;22mGrupo[0;30;1m: [0;36;1m{pl_group}
[m    }
[m    Player {
[m      Message: '{player}:'
[m      Hover Event: SHOW_TEXT with values: 
[m        - [0;37;22mMensaje enviado: [0;36;1m{timestamp}
[m        - [0;37;22mClic para mandar un IM
[m      Click Event: SUGGEST_COMMAND with value: /tell {player} 
[m    }
[m    Suffix {
[m      Message: '{pl_suffix} '
[m    }
[m    Message {
[m      Message: '{message}'
[m    } >>
[m}[m
[09:32:39] [Server thread/INFO]: [ChatControl debug] 
[mFormat {
[m  Name: 'Admin_Chat'
[m  Parts: <<
[m    Bracket_Start {
[m      Message: '[0;30;1m[[0;31;1mA-Chat '
[m    }
[m    Player {
[m      Message: '{player}'
[m    }
[m    Bracket_End {
[m      Message: '[0;30;1m] [0;32;22m'
[m    }
[m    Message {
[m      Message: '{message}'
[m    } >>
[m}[m
[09:32:39] [Server thread/INFO]: [ChatControl debug] 
[mFormat {
[m  Name: 'Bungee_Chat'
[m  Parts: <<
[m    Bracket {
[m      Message: '[0;30;1m[[0;37;1mG[0;30;1m] '
[m    }
[m    Player {
[m      Message: '{player} [0;37;22m>[0;37;1m '
[m    }
[m    Message {
[m      Message: '{message}'
[m    } >>
[m}[m
[09:32:39] [Server thread/INFO]: [ChatControl debug] 
[mFormat {
[m  Name: 'Private_Message_Sender'
[m  Parts: <<
[m    Everything {
[m      Message: '[0;37;22m✉ [0;32;22menviado!'
[m      Hover Event: SHOW_TEXT with values: 
[m        -      [0;30;1m~ [0;36;22mMensaje privado [0;30;1m~     
[m        - [0;30;1m[3mEnviado {timestamp}
[m        - [0;36;22mDestinatario: [0;37;1m{receiver}
[m        - [0;36;22mContenido: [0;37;1m{message}
[m      Click Event: SUGGEST_COMMAND with value: /tell {player} 
[m    } >>
[m}[m
[09:32:39] [Server thread/INFO]: [ChatControl debug] 
[mFormat {
[m  Name: 'Spy_Chat'
[m  Parts: <<
[m    Everything {
[m      Message: '[0;30;1mSPY: [{world}[0;30;1m][0;37;1m {pl_prefix}{player}:{pl_suffix} {message}'
[m    } >>
[m}[m
[09:32:39] [Server thread/INFO]: [ChatControl debug] 
[mFormat {
[m  Name: 'Global_Chat'
[m  Parts: <<
[m    Everything {
[m      Message: '[0;37;22m[GLOBAL] {pl_prefix}{player}:{pl_suffix} {message}'
[m    } >>
[m}[m
[09:32:39] [Server thread/INFO]: [ChatControl debug] [0;37;1mMessages for: global[m
[09:32:39] [Server thread/INFO]: [ChatControl debug]  - [0;33;22mPsst, [0;32;1m{player}[0;33;22m, ya usaste [0;32;1m/Vote[0;33;22m?[m
[09:32:39] [Server thread/INFO]: [ChatControl debug]  - [0;33;22mAntes de jugar, no olvides leer las reglas en [0;32;1m/rules[m
[09:32:39] [Server thread/INFO]: [ChatControl debug]  - [0;33;22mSi ves que alguien hace algo indebido, reportalo! Usa [0;32;1m/report[0;33;22m[m
[09:32:39] [Server thread/INFO]: [ChatControl debug]  - [0;33;22mYa visitaste el foro? [0;36;1m> [0;32;1mHttp://Foros.Castle-Elevel.Com[m
[09:32:39] [Server thread/INFO]: [0;37;22m*-----------------------------------------------*[m
[09:32:39] [Server thread/INFO]:  [0;31;1m[0;31;1mError reading rules/commands.txt[m
[09:32:39] [Server thread/INFO]:  [0;31;1m[0;31;1mCheck for syntax errors.[m
[09:32:39] [Server thread/INFO]:  [0;31;1mError: Cannot define operator when nothing is being created! File: 'rules/commands.txt' Line 0: '﻿# -------------------------------------------------------------------------------' Previous: 'null'[m
[09:32:39] [Server thread/INFO]: [0;37;22m*-----------------------------------------------*[m
[09:32:39] [Server thread/WARN]: java.lang.NullPointerException: Cannot define operator when nothing is being created! File: 'rules/commands.txt' Line 0: '﻿# -------------------------------------------------------------------------------' Previous: 'null'
[09:32:39] [Server thread/WARN]: 	at java.util.Objects.requireNonNull(Objects.java:228)
[09:32:39] [Server thread/WARN]: 	at me.kangarko.chatcontrol.  .....LPt7.native(SourceFile:86)
[09:32:39] [Server thread/WARN]: 	at me.kangarko.chatcontrol.  .....LPt7.const(SourceFile:46)
[09:32:39] [Server thread/WARN]: 	at me.kangarko.chatcontrol.  .....lPT7.const(SourceFile:215)
[09:32:39] [Server thread/WARN]: 	at me.kangarko.chatcontrol.  .....lPT7.const(SourceFile:73)
[09:32:39] [Server thread/WARN]: 	at me.kangarko.chatcontrol.ChatControl.strictfp(SourceFile:222)
[09:32:39] [Server thread/WARN]: 	at me.kangarko.chatcontrol.  .....coM6.volatile(SourceFile:171)
[09:32:39] [Server thread/WARN]: 	at me.kangarko.chatcontrol.  .....cOm2.const(SourceFile:425)
[09:32:39] [Server thread/WARN]: 	at me.kangarko.chatcontrol.  .....LPt8.onCommand(SourceFile:52)
[09:32:39] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[09:32:39] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[09:32:39] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641)
[09:32:39] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162)
[09:32:39] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997)
[09:32:39] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
[09:32:39] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
[09:32:39] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[09:32:39] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[09:32:39] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[09:32:39] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[09:32:39] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715)
[09:32:39] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[09:32:39] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[09:32:39] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[09:32:39] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[09:32:40] [Server thread/INFO]: [ChatControl debug] [0;30;1m[[0;36;1mCastle-Elevel[0;30;1m]  [0;33;22mSi ves que alguien hace algo indebido, reportalo! Usa [0;32;1m/report[0;33;22m[m
[09:35:40] [Server thread/INFO]: [ChatControl debug] [0;30;1m[[0;36;1mCastle-Elevel[0;30;1m]  [0;33;22mAntes de jugar, no olvides leer las reglas en [0;32;1m/rules[m

---------
I stopped the server here.

**Comment by EvilOlaf** [comment]
What do you use for editing? Looks like an encoding issue.

**Comment by Rodrogamby** [comment]
Thanks for your reply, I was editing it on UTF-8-BOM

**Comment by kangarko** [comment]
It's an encoding issue. Please do not use Multicraft editor when editing, only your own editor on your computer operating system.

Here's a good article:
https://github.com/kangarko/ChatControl-Pro/wiki/Use-Right-Encoding

You can try other encodings as well until you find one that works on your system.
