### ISSUE TITLE
COM9: Unexpected: % error.

### ISSUE THREAD

**Issue by andris155** [kangarko/ChatControl-Pro#309]
```
22:08:48] [Server thread/INFO]: HELLCAT issued server command: /ignore
[22:08:49] [Async Chat Thread - #26/ERROR]: Could not pass event AsyncPlayerChatEvent to ChatControl v7.4.17
me.kangarko.chatcontrol.  .....COM9: Unexpected: %
	at me.kangarko.chatcontrol.  .....COm2$super.strictfp(SourceFile:184) ~[?:?]
	at me.kangarko.chatcontrol.  .....COm2$super.private(SourceFile:143) ~[?:?]
	at me.kangarko.chatcontrol.  .....COm2$super.native(SourceFile:125) ~[?:?]
	at me.kangarko.chatcontrol.  .....COm2$super.strictfp(SourceFile:173) ~[?:?]
	at me.kangarko.chatcontrol.  .....COm2$super.private(SourceFile:153) ~[?:?]
	at me.kangarko.chatcontrol.  .....COm2$super.native(SourceFile:125) ~[?:?]
	at me.kangarko.chatcontrol.  .....COm2$super.const(SourceFile:110) ~[?:?]
	at me.kangarko.chatcontrol.  .....COm2.const(SourceFile:197) ~[?:?]
	at me.kangarko.chatcontrol.  .....Lpt1.const(SourceFile:260) ~[?:?]
	at me.kangarko.chatcontrol.  .....Lpt1.const(SourceFile:50) ~[?:?]
	at me.kangarko.chatcontrol.  .....Lpt1.const(SourceFile:27) ~[?:?]
	at me.kangarko.chatcontrol.  .....COM2.execute(SourceFile:22) ~[?:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[patched_1.12.jar:git-Paper-1169]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.jar:git-Paper-1169]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:514) [patched_1.12.jar:git-Paper-1169]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:496) [patched_1.12.jar:git-Paper-1169]
	at net.minecraft.server.v1_12_R1.PlayerConnection.chat(PlayerConnection.java:1339) [patched_1.12.jar:git-Paper-1169]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1254) [patched_1.12.jar:git-Paper-1169]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:39) [patched_1.12.jar:git-Paper-1169]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_144]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_144]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
[22:08:49] [Async Chat Thread - #26/INFO]: [Elit]MerciGT: NNASH
[22:08:50] [Async Chat Thread - #26/ERROR]: Could not pass event AsyncPlayerChatEvent to ChatControl v7.4.17
me.kangarko.chatcontrol.  .....COM9: Unexpected: %
	at me.kangarko.chatcontrol.  .....COm2$super.strictfp(SourceFile:184) ~[?:?]
	at me.kangarko.chatcontrol.  .....COm2$super.private(SourceFile:143) ~[?:?]
	at me.kangarko.chatcontrol.  .....COm2$super.native(SourceFile:125) ~[?:?]
	at me.kangarko.chatcontrol.  .....COm2$super.strictfp(SourceFile:173) ~[?:?]
	at me.kangarko.chatcontrol.  .....COm2$super.private(SourceFile:153) ~[?:?]
	at me.kangarko.chatcontrol.  .....COm2$super.native(SourceFile:125) ~[?:?]
	at me.kangarko.chatcontrol.  .....COm2$super.const(SourceFile:110) ~[?:?]
	at me.kangarko.chatcontrol.  .....COm2.const(SourceFile:197) ~[?:?]
	at me.kangarko.chatcontrol.  .....Lpt1.const(SourceFile:260) ~[?:?]
	at me.kangarko.chatcontrol.  .....Lpt1.const(SourceFile:50) ~[?:?]
	at me.kangarko.chatcontrol.  .....Lpt1.const(SourceFile:27) ~[?:?]
	at me.kangarko.chatcontrol.  .....COM2.execute(SourceFile:22) ~[?:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[patched_1.12.jar:git-Paper-1169]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.jar:git-Paper-1169]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:514) [patched_1.12.jar:git-Paper-1169]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:496) [patched_1.12.jar:git-Paper-1169]
	at net.minecraft.server.v1_12_R1.PlayerConnection.chat(PlayerConnection.java:1339) [patched_1.12.jar:git-Paper-1169]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1254) [patched_1.12.jar:git-Paper-1169]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:39) [patched_1.12.jar:git-Paper-1169]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_144]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_144]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
```

**Comment by andris155** [comment]
Sorry. Config error. Fixed. :D
