### ISSUE TITLE
Every time

### ISSUE THREAD

**Issue by kubasek03** [kangarko/ChatControl-Pro#312]
Hello, today after restarting my server he showed me this error

erver thread/INFO]: _____ _ _ _____ _ _ +
[19:52:27] [Server thread/INFO]: / ____| | | | / ____| | | | |
[19:52:27] [Server thread/INFO]: | | | |__ __ _| |_| | ___ _ __ | |_ _ __ ___ | |
[19:52:27] [Server thread/INFO]: | | | '_ \ / _` | __| | / _ \| '_ \| __| '__/ _ \| |
[19:52:27] [Server thread/INFO]: | |____| | | | (_| | |_| |___| (_) | | | | |_| | | (_) | |
[19:52:27] [Server thread/INFO]: \_____|_| |_|\__,_|\__|\_____\___/|_| |_|\__|_| \___/|_|
[19:52:27] [Server thread/INFO]: 
[19:52:27] [Server thread/INFO]: *-----------------------------------------------*
[19:52:27] [Server thread/INFO]: There was a fatal problem with this version. We apologies.
[19:52:27] [Server thread/INFO]: If you have purchased it, please contact the author!
[19:52:27] [Server thread/INFO]: If not, well, too bad! (I am sad :()
[19:52:27] [Server thread/INFO]: Plugin is now disabled.
[19:52:27] [Server thread/INFO]: *-----------------------------------------------*
[19:52:27] [Server thread/INFO]: [ChatControl] Disabling ChatControl v7.3.14
[19:52:27] [Server thread/INFO]: Plugin might not shut down property. Got NullPointerException: null
[19:52:27] [Server thread/INFO]: Configuration loads..
[19:52:28] [Server thread/WARN]: org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
[19:52:28] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.validate(CraftScheduler.java:413)
[19:52:28] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:148)
[19:52:28] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.scheduleAsyncRepeatingTask(CraftScheduler.java:144)
[19:52:28] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.scheduleAsyncDelayedTask(CraftScheduler.java:118)
[19:52:28] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.scheduleAsyncDelayedTask(CraftScheduler.java:101)
[19:52:28] [Server thread/WARN]: at me.kangarko.chatcontrol. ......PRn.transient(SourceFile:323)
[19:52:28] [Server thread/WARN]: at me.kangarko.chatcontrol. ......LPT5.protected(SourceFile:150)
[19:52:28] [Server thread/WARN]: at me.kangarko.chatcontrol. ......lpT2.onEnable(SourceFile:69)
[19:52:28] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271)
[19:52:28] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316)
[19:52:28] [Server thread/WARN]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407)
[19:52:28] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:378)
[19:52:28] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:328)
[19:52:28] [Server thread/WARN]: at net.minecraft.server.v1_11_R1.MinecraftServer.t(MinecraftServer.java:438)
[19:52:28] [Server thread/WARN]: at net.minecraft.server.v1_11_R1.MinecraftServer.l(MinecraftServer.java:399)
[19:52:28] [Server thread/WARN]: at net.minecraft.server.v1_11_R1.MinecraftServer.a(MinecraftServer.java:337)
[19:52:28] [Server thread/WARN]: at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:276)
[19:52:28] [Server thread/WARN]: at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:612)
[19:52:28] [Server thread/WARN]: at java.lang.Thread.run(Thread.java:748)
[19:52:28] [Server thread/INFO]: _ _ _ 
[19:52:28] [Server thread/INFO]: | | | | ___ ___ _ __ ___| |
[19:52:28] [Server thread/INFO]: | |_| |/ _ \ / _ \| '_ \/ __| |
[19:52:28] [Server thread/INFO]: | _ | (_) | (_) | |_) \__ \_|
[19:52:28] [Server thread/INFO]: |_| |_|\___/ \___/| .__/|___(_)
[19:52:28] [Server thread/INFO]: |_| 
[19:52:28] [Server thread/INFO]: !-----------------------------------------------------!
[19:52:28] [Server thread/INFO]: Error loading ChatControl v7.3.14, plugin is disabled!
[19:52:28] [Server thread/INFO]: Running on 1.11.2-R0.1-SNAPSHOT (v1_11_R1) & Java 1.8.0_144
[19:52:28] [Server thread/INFO]: !-----------------------------------------------------!
[19:52:28] [Server thread/INFO]: Error: Plugin attempted to register task while disabled
[19:52:28] [Server thread/INFO]: !-----------------------------------------------------!

**Comment by Squirzy** [comment]
Receiving same error: https://pastebin.com/LVwhNBsV

**Comment by kangarko** [comment]
Plase update to the latest version.

If the problem persists, contact me on SpigotMC and include your paypal address from which you have paid.
