### ISSUE TITLE
Eror

### ISSUE THREAD

**Issue by FreeKillGR** [kangarko/ChatControl-Pro#313]
i'm getting this on a new server with no other plugins just chat control and protocollib

[22:13:22 INFO]:  _____ _           _    _____            _             _  +
[22:13:22 INFO]:  / ____| |         | |  / ____|          | |           | |
[22:13:22 INFO]: | |    | |__   __ _| |_| |     ___  _ __ | |_ _ __ ___ | |
[22:13:22 INFO]: | |    | '_ \ / _` | __| |    / _ \| '_ \| __| '__/ _ \| |
[22:13:22 INFO]: | |____| | | | (_| | |_| |___| (_) | | | | |_| | | (_) | |
[22:13:22 INFO]:  \_____|_| |_|\__,_|\__|\_____\___/|_| |_|\__|_|  \___/|_|
[22:13:22 INFO]:  
[22:13:22 INFO]: Configuration loads..
[22:13:22 INFO]:  
[22:13:22 INFO]: Checking compatible plugins..
[22:13:22 INFO]: Found: ProtocolLib
[22:13:22 INFO]:  
[22:13:22 INFO]: Rules loads now..
[22:13:22 INFO]: 43 global, 15 chat, 4 command, 2 packet and one sign rule(s) found
[22:13:22 INFO]:  
[22:13:22 INFO]: Listening starts..
[22:13:22 INFO]: Chat & rules are watched with normal priority
[22:13:22 WARN]: java.lang.ExceptionInInitializerError
[22:13:22 WARN]: 	at com.comphenix.protocol.injector.netty.InjectionFactory.fromPlayer(InjectionFactory.java:93)
[22:13:22 WARN]: 	at com.comphenix.protocol.injector.netty.ProtocolInjector$4.injectPlayer(ProtocolInjector.java:373)
[22:13:22 WARN]: 	at com.comphenix.protocol.injector.PacketFilterManager.initializePlayers(PacketFilterManager.java:946)
[22:13:22 WARN]: 	at com.comphenix.protocol.injector.PacketFilterManager.incrementPhases(PacketFilterManager.java:462)
[22:13:22 WARN]: 	at com.comphenix.protocol.injector.PacketFilterManager.addPacketListener(PacketFilterManager.java:405)
[22:13:22 WARN]: 	at me.kangarko.chatcontrol.  .....Com6.const(SourceFile:817)
[22:13:22 WARN]: 	at me.kangarko.chatcontrol.  .....com5.const(SourceFile:417)
[22:13:22 WARN]: 	at me.kangarko.chatcontrol.  .....lPt7.const(SourceFile:31)
[22:13:22 WARN]: 	at me.kangarko.chatcontrol.ChatControl.const(SourceFile:119)
[22:13:22 WARN]: 	at me.kangarko.chatcontrol.  .....lPt1.onEnable(SourceFile:102)
[22:13:22 WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292)
[22:13:22 WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
[22:13:22 WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[22:13:22 WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugin(CraftServer.java:373)
[22:13:22 WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugins(CraftServer.java:323)
[22:13:22 WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.reload(CraftServer.java:747)
[22:13:22 WARN]: 	at org.bukkit.Bukkit.reload(Bukkit.java:539)
[22:13:22 WARN]: 	at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:25)
[22:13:22 WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[22:13:22 WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:647)
[22:13:22 WARN]: 	at net.minecraft.server.v1_10_R1.PlayerConnection.handleCommand(PlayerConnection.java:1358)
[22:13:22 WARN]: 	at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1193)
[22:13:22 WARN]: 	at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[22:13:22 WARN]: 	at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
[22:13:22 WARN]: 	at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[22:13:22 WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[22:13:22 WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[22:13:22 WARN]: 	at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45)
[22:13:22 WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:732)
[22:13:22 WARN]: 	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400)
[22:13:22 WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668)
[22:13:22 WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567)
[22:13:22 WARN]: 	at java.lang.Thread.run(Thread.java:748)
[22:13:22 WARN]: Caused by: java.lang.IllegalArgumentException: 'PROTOCOL' is already in use
[22:13:22 WARN]: 	at io.netty.util.UniqueName.<init>(UniqueName.java:53)
[22:13:22 WARN]: 	at io.netty.util.AttributeKey.<init>(AttributeKey.java:47)
[22:13:22 WARN]: 	at io.netty.util.AttributeKey.valueOf(AttributeKey.java:39)
[22:13:22 WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector.<clinit>(ChannelInjector.java:95)
[22:13:22 WARN]: 	... 33 more
[22:13:22 INFO]:   _   _                       _ 
[22:13:22 INFO]:   | | | | ___   ___  _ __  ___| |
[22:13:22 INFO]:   | |_| |/ _ \ / _ \| '_ \/ __| |
[22:13:22 INFO]:   |  _  | (_) | (_) | |_) \__ \_|
[22:13:22 INFO]:   |_| |_|\___/ \___/| .__/|___(_)
[22:13:22 INFO]:                     |_|          
[22:13:22 INFO]: !-----------------------------------------------------!
[22:13:22 INFO]:  Error loading ChatControl v7.4.20, plugin is disabled!
[22:13:22 INFO]:  Running on 1.10.2-R0.1-SNAPSHOT (v1_10_R1) & Java 1.8.0_131
[22:13:22 INFO]: !-----------------------------------------------------!
[22:13:22 INFO]:  Error: 'PROTOCOL' is already in use
[22:13:22 INFO]: !-----------------------------------------------------!
[22:13:22 INFO]: [ChatControl] Disabling ChatControl v7.4.20
[22:13:22 INFO]: Server permissions file permissions.yml is empty, ignoring it

**Comment by kubasek03** [comment]
same

**Comment by kangarko** [comment]
Hey,

please contact me on SpigotMC privately regarding this error.
