### ISSUE TITLE
ChatControl wont load

### ISSUE THREAD

**Issue by FanaticNinja** [kangarko/ChatControl-Pro#315]
[16:05:10] [Server thread/INFO]: [ChatControl] Enabling ChatControl v7.4.20
[16:05:11] [Server thread/INFO]:  _____ _           _    _____            _             _  +
[16:05:11] [Server thread/INFO]:  / ____| |         | |  / ____|          | |           | |
[16:05:11] [Server thread/INFO]: | |    | |__   __ _| |_| |     ___  _ __ | |_ _ __ ___ | |
[16:05:11] [Server thread/INFO]: | |    | '_ \ / _` | __| |    / _ \| '_ \| __| '__/ _ \| |
[16:05:11] [Server thread/INFO]: | |____| | | | (_| | |_| |___| (_) | | | | |_| | | (_) | |
[16:05:11] [Server thread/INFO]:  \_____|_| |_|\__,_|\__|\_____\___/|_| |_|\__|_|  \___/|_|
[16:05:11] [Server thread/INFO]:  
[16:05:11] [Server thread/INFO]: *-----------------------------------------------*
[16:05:11] [Server thread/INFO]:  There was a fatal problem with this version. We apologies.
[16:05:11] [Server thread/INFO]: If you have purchased it, please contact the author!
[16:05:11] [Server thread/INFO]: If not, well, too bad! (I am sad :()
[16:05:11] [Server thread/INFO]:  Plugin is now disabled.
[16:05:11] [Server thread/INFO]: *-----------------------------------------------*
[16:05:11] [Server thread/INFO]: [ChatControl] Disabling ChatControl v7.4.20

[16:05:11] [Server thread/INFO]: Rules loads now..
[16:05:11] [Server thread/INFO]: 43 global, 15 chat, 4 command, 2 packet and one sign rule(s) found
[16:05:11] [Server thread/INFO]:  
[16:05:11] [Server thread/INFO]: Listening starts..
[16:05:11] [Server thread/INFO]: Chat & rules are watched with normal priority
[16:05:11] [Server thread/WARN]: org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register class org.bukkit.event.player.AsyncPlayerChatEvent while not enabled
[16:05:11] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.registerEvent(SimplePluginManager.java:553)
[16:05:11] [Server thread/WARN]: 	at me.kangarko.chatcontrol.  .....lPt1.const(SourceFile:349)
[16:05:11] [Server thread/WARN]: 	at me.kangarko.chatcontrol.ChatControl.const(SourceFile:95)
[16:05:11] [Server thread/WARN]: 	at me.kangarko.chatcontrol.  .....lPt1.onEnable(SourceFile:102)
[16:05:11] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[16:05:11] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
[16:05:11] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402)
[16:05:11] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:378)
[16:05:11] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:327)
[16:05:11] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:421)
[16:05:11] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:382)
[16:05:11] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:337)
[16:05:11] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272)
[16:05:11] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:544)
[16:05:11] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[16:05:11] [Server thread/INFO]:   _   _                       _ 
[16:05:11] [Server thread/INFO]:   | | | | ___   ___  _ __  ___| |
[16:05:11] [Server thread/INFO]:   | |_| |/ _ \ / _ \| '_ \/ __| |
[16:05:11] [Server thread/INFO]:   |  _  | (_) | (_) | |_) \__ \_|
[16:05:11] [Server thread/INFO]:   |_| |_|\___/ \___/| .__/|___(_)
[16:05:11] [Server thread/INFO]:                     |_|          
[16:05:11] [Server thread/INFO]: !-----------------------------------------------------!
[16:05:11] [Server thread/INFO]:  Error loading ChatControl v7.4.20, plugin is disabled!
[16:05:11] [Server thread/INFO]:  Running on 1.12-R0.1-SNAPSHOT (v1_12_R1) & Java 1.8.0_131
[16:05:11] [Server thread/INFO]: !-----------------------------------------------------!
[16:05:11] [Server thread/INFO]:  Error: Plugin attempted to register class org.bukkit.event.player.AsyncPlayerChatEvent while not enabled
[16:05:11] [Server thread/INFO]: !-----------------------------------------------------!

I've purchased the plugin a month back-ish.. Not really sure whats going on.
Spigot account: FanaticNinja

I saw an older post about similar to my issue. Saying something about leaking the plugin? Which i have not done, and would never do. (considering I dev my own plugins).

**Comment by Espantonius** [comment]
I have the same problem.

**Comment by kangarko** [comment]
@FanaticNinja I have fixed it for you, thank you for letting me know.

@Espantonius please PM me on Spigot.

**Comment by FanaticNinja** [comment]
@kangarko Thankyou! I am curious though, what can I avoid or do to stop this from happening again?

Ill change my spigot password asap. (its a little concerning that this happened in the first place)

Could it be that i was developing/configuring my server on my home machine before moving it up to the server environment? (different IP addresses)

**Comment by UberMC** [comment]
kangarko please fix my account as well.
My account is behind two factor authentication.

**Comment by kangarko** [comment]
## EXPLANATION
* If your user ID on Spigot matches known ID's of users that leaked the plugin, or ID's used by users on leak sites, the plugin is disabled. I believe you and not claim you have leaked it because some of the ID's are the same on both Spigot and the leak sites, especially if you have registered on Spigot 3+ years ago.

@UberMC, thank you for letting me know. It should now be fixed.

**Comment by Plumeex** [comment]
Hi @kangarko I'm facing the same issue.
[Here's my Spigot account](https://www.spigotmc.org/members/plumeex.548/) (jan 2013).

Can you help me with this? I can provide additional details if needed.
Thanks a lot!

**Comment by UberMC** [comment]
Hi my servers aren't loading chatcontrol again.
