### ISSUE TITLE
cauldron latest not working with the latest chatcontrol pro

### ISSUE THREAD

**Issue by jacky3362** [kangarko/ChatControl-Pro#332]
`[00:23:56 ERROR]: Could not load 'plugins\ChatControl.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: Cannot find main class `me.kangarko.chatcontrol.ChatControl'
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:191) ~[PluginClassLoader.class:KCauldron-1.7.10-2.1403.1.54]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:145) ~[JavaPluginLoader.class:KCauldron-1.7.10-2.1403.1.54]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:334) ~[SimplePluginManager.class:KCauldron-1.7.10-2.1403.1.54]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:256) [SimplePluginManager.class:KCauldron-1.7.10-2.1403.1.54]
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugins(CraftServer.java:320) [CraftServer.class:KCauldron-1.7.10-2.1403.1.54]
        at net.minecraft.world.storage.SaveHandler.initBukkitData(SaveHandler.java:461) [ayq.class:?]
        at net.minecraft.world.storage.SaveHandler.func_75757_d(SaveHandler.java:174) [ayq.class:?]
        at net.minecraft.world.World.<init>(World.java:349) [ahb.class:?]
        at net.minecraft.world.WorldServer.<init>(WorldServer.java:153) [mt.class:?]
        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:356) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:335) [lt.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:620) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
Caused by: java.lang.ClassNotFoundException: Failed to remap class me.kangarko.chatcontrol.ChatControl
        at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:488) ~[PluginClassLoader.class:KCauldron-1.7.10-2.1403.1.54]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:409) ~[PluginClassLoader.class:KCauldron-1.7.10-2.1403.1.54]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:211) ~[PluginClassLoader.class:KCauldron-1.7.10-2.1403.1.54]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_144]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_144]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_144]
        at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_144]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:189) ~[PluginClassLoader.class:KCauldron-1.7.10-2.1403.1.54]
        ... 12 more
Caused by: java.lang.NoClassDefFoundError: me/kangarko/chatcontrol/  /////lPt1
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_144]
        at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_144]
        at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_144]
        at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:476) ~[PluginClassLoader.class:KCauldron-1.7.10-2.1403.1.54]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:409) ~[PluginClassLoader.class:KCauldron-1.7.10-2.1403.1.54]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:211) ~[PluginClassLoader.class:KCauldron-1.7.10-2.1403.1.54]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_144]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_144]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_144]
        at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_144]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:189) ~[PluginClassLoader.class:KCauldron-1.7.10-2.1403.1.54]
        ... 12 more
Caused by: java.lang.ClassNotFoundException: Failed to remap class me.kangarko.chatcontrol.  .....lPt1
        at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:488) ~[PluginClassLoader.class:KCauldron-1.7.10-2.1403.1.54]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:409) ~[PluginClassLoader.class:KCauldron-1.7.10-2.1403.1.54]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:211) ~[PluginClassLoader.class:KCauldron-1.7.10-2.1403.1.54]`

**Comment by kangarko** [comment]
Hey,

that's really weird, and I have no experience with KCauldron. It seems like a major incompatibility though.

I am leaving this open but with a little hope on fix since I honestly I don't know what's causing this.

Also, the upcoming version has updated its compatibility, please test it with it, when it's out.

**Comment by jacky3362** [comment]
when i run the java 7 7.0.30 it works but when i run the java 8 version the latest it dosn't it might be the problem

**Comment by kangarko** [comment]
Feel free to use 7.0.30 for the time being until it's fixed :)

**Comment by jacky3362** [comment]
it works :D
