### ISSUE TITLE
ChatControl unhandling exception when a player join

### ISSUE THREAD

**Issue by NotAHackedCookie** [kangarko/ChatControl-Pro#338]
Hello, I get this error when a player joins

[17:43:35 ERROR]: [ChatControl] Unhandled exception number 128 occured in onPacketSending(PacketEvent) for ChatControl
java.lang.NoClassDefFoundError: Could not initialize class com.comphenix.protocol.wrappers.WrappedChatComponent
        at com.comphenix.protocol.wrappers.BukkitConverters$6.getSpecificValue(BukkitConverters.java:475) ~[ProtocolLib-4.2.1-20170309.155517-9.jar:4.2.1-SNAPSHOT-b350]
        at com.comphenix.protocol.wrappers.BukkitConverters$6.getSpecificValue(BukkitConverters.java:467) ~[ProtocolLib-4.2.1-20170309.155517-9.jar:4.2.1-SNAPSHOT-b350]
        at com.comphenix.protocol.wrappers.BukkitConverters$IgnoreNullConverter.getSpecific(BukkitConverters.java:148) ~[ProtocolLib-4.2.1-20170309.155517-9.jar:4.2.1-SNAPSHOT-b350]
        at com.comphenix.protocol.reflect.StructureModifier.readInternal(StructureModifier.java:230) ~[ProtocolLib-4.2.1-20170309.155517-9.jar:4.2.1-SNAPSHOT-b350]
        at com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:198) ~[ProtocolLib-4.2.1-20170309.155517-9.jar:4.2.1-SNAPSHOT-b350]
        at kangarko.chatcontrol.hooks.ProtocolLibHook$2.onPacketSending(HookManager.java:453) ~[ChatControl.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) [ProtocolLib-4.2.1-20170309.155517-9.jar:4.2.1-SNAPSHOT-b350]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) [ProtocolLib-4.2.1-20170309.155517-9.jar:4.2.1-SNAPSHOT-b350]
        at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:608) [ProtocolLib-4.2.1-20170309.155517-9.jar:4.2.1-SNAPSHOT-b350]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:584) [ProtocolLib-4.2.1-20170309.155517-9.jar:4.2.1-SNAPSHOT-b350]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:309) [ProtocolLib-4.2.1-20170309.155517-9.jar:4.2.1-SNAPSHOT-b350]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:269) [ProtocolLib-4.2.1-20170309.155517-9.jar:4.2.1-SNAPSHOT-b350]
        at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:396) [ProtocolLib-4.2.1-20170309.155517-9.jar:4.2.1-SNAPSHOT-b350]
        at com.comphenix.protocol.injector.netty.ChannelInjector.access$500(ChannelInjector.java:77) [ProtocolLib-4.2.1-20170309.155517-9.jar:4.2.1-SNAPSHOT-b350]
        at com.comphenix.protocol.injector.netty.ChannelInjector$5.handleScheduled(ChannelInjector.java:362) [ProtocolLib-4.2.1-20170309.155517-9.jar:4.2.1-SNAPSHOT-b350]
        at com.comphenix.protocol.injector.netty.ChannelInjector$5.onMessageScheduled(ChannelInjector.java:330) [ProtocolLib-4.2.1-20170309.155517-9.jar:4.2.1-SNAPSHOT-b350]
        at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) [ProtocolLib-4.2.1-20170309.155517-9.jar:4.2.1-SNAPSHOT-b350]
        at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) [ProtocolLib-4.2.1-20170309.155517-9.jar:4.2.1-SNAPSHOT-b350]
        at net.minecraft.server.v1_8_R1.NetworkManager.a(NetworkManager.java:140) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
        at net.minecraft.server.v1_8_R1.NetworkManager.handle(NetworkManager.java:101) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
        at net.minecraft.server.v1_8_R1.PlayerConnection.sendPacket(PlayerConnection.java:868) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
        at org.bukkit.craftbukkit.v1_8_R1.entity.CraftPlayer.sendRawMessage(CraftPlayer.java:150) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
        at org.bukkit.craftbukkit.v1_8_R1.entity.CraftPlayer.sendMessage(CraftPlayer.java:157) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
        at com.earth2me.essentials.CommandSource.sendMessage(CommandSource.java:36) [EssentialsX-2.0.1.jar:?]
        at com.earth2me.essentials.textreader.TextPager.showPage(TextPager.java:86) [EssentialsX-2.0.1.jar:?]
        at com.earth2me.essentials.EssentialsPlayerListener$1DelayJoinTask.run(EssentialsPlayerListener.java:268) [EssentialsX-2.0.1.jar:?]
        at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:71) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
        at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
        at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:709) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
        at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
        at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]

What can I do?

**Comment by EvilOlaf** [comment]
Maybe Protocollib is outdated. Grab a more current build from Jenkins 
http://ci.shadowvolt.com/job/ProtocolLib/

**Comment by kangarko** [comment]
Update your ProtocoLlib.

Thanks for quick support Olaf!
