### ISSUE TITLE
ChatControl Unhandled exception occurs when a player joins

### ISSUE THREAD

**Issue by NotAHackedCookie** [kangarko/ChatControl-Pro#339]
Hello, when a player joins the server it gives me this error. I have the latest version of protocollib and my server is running 1.8. What can I do?

[22:27:25 ERROR]: [ChatControl] Unhandled exception occured in onPacketSending(PacketEvent) for ChatControl
java.lang.NoClassDefFoundError: Could not initialize class com.comphenix.protocol.wrappers.WrappedChatComponent
        at com.comphenix.protocol.wrappers.BukkitConverters$6.getSpecificValue(BukkitConverters.java:469) ~[ProtocolLib.jar:4.3.0]
        at com.comphenix.protocol.wrappers.BukkitConverters$6.getSpecificValue(BukkitConverters.java:461) ~[ProtocolLib.jar:4.3.0]
        at com.comphenix.protocol.wrappers.BukkitConverters$IgnoreNullConverter.getSpecific(BukkitConverters.java:142) ~[ProtocolLib.jar:4.3.0]
        at com.comphenix.protocol.reflect.StructureModifier.readInternal(StructureModifier.java:230) ~[ProtocolLib.jar:4.3.0]
        at com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:198) ~[ProtocolLib.jar:4.3.0]
        at kangarko.chatcontrol.hooks.ProtocolLibHook$2.onPacketSending(HookManager.java:453) ~[ChatControl.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) [ProtocolLib.jar:4.3.0]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) [ProtocolLib.jar:4.3.0]
        at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:588) [ProtocolLib.jar:4.3.0]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:564) [ProtocolLib.jar:4.3.0]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:338) [ProtocolLib.jar:4.3.0]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:298) [ProtocolLib.jar:4.3.0]
        at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:386) [ProtocolLib.jar:4.3.0]
        at com.comphenix.protocol.injector.netty.ChannelInjector.access$500(ChannelInjector.java:77) [ProtocolLib.jar:4.3.0]
        at com.comphenix.protocol.injector.netty.ChannelInjector$5.handleScheduled(ChannelInjector.java:352) [ProtocolLib.jar:4.3.0]
        at com.comphenix.protocol.injector.netty.ChannelInjector$5.onMessageScheduled(ChannelInjector.java:320) [ProtocolLib.jar:4.3.0]
        at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) [ProtocolLib.jar:4.3.0]
        at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) [ProtocolLib.jar:4.3.0]
        at net.minecraft.server.v1_8_R1.NetworkManager.a(NetworkManager.java:140) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
        at net.minecraft.server.v1_8_R1.NetworkManager.handle(NetworkManager.java:101) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
        at net.minecraft.server.v1_8_R1.PlayerConnection.sendPacket(PlayerConnection.java:868) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
        at org.bukkit.craftbukkit.v1_8_R1.entity.CraftPlayer.sendRawMessage(CraftPlayer.java:150) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
        at org.bukkit.craftbukkit.v1_8_R1.entity.CraftPlayer.sendMessage(CraftPlayer.java:157) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
        at com.earth2me.essentials.User.sendMessage(User.java:772) [EssentialsX-2.0.1.jar:?]
        at com.earth2me.essentials.EssentialsPlayerListener$1DelayJoinTask.run(EssentialsPlayerListener.java:275) [EssentialsX-2.0.1.jar:?]
        at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:71) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
        at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
        at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:709) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
        at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
        at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537) [spigot-1.8.jar:git-Spigot-550ebac-7019900]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
[22:27:25 ERROR]: Parameters:
  net.minecraft.server.v1_8_R1.PacketPlayOutChat@6e0bd2e8[
    a=TextComponent{text='', siblings=[TextComponent{text='You have no new mail.', siblings=[], style=Style{hasParent=true, color=πa, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}
    components=<null>
    b=1
  ]

[22:27:25 INFO]: handlePos()
[22:27:25 INFO]: handlePos()
[22:27:25 INFO]: handlePos()
[22:27:25 INFO]: handlePos()
[22:27:25 INFO]: handlePos()

**Comment by kangarko** [comment]
Please update your ProtocolLib to latest development version.
