### ISSUE TITLE
error on player join

### ISSUE THREAD

**Issue by FrankHeijden** [kangarko/ChatControl-Pro#345]
```
09.09 11:19:17 [Server] WARN java.lang.NullPointerException: def
09.09 11:19:17 [Server] WARN at me.kangarko.chatcontrol.null.COm3.const(SourceFile:117)
09.09 11:19:17 [Server] WARN at me.kangarko.chatcontrol.null.COm3.const(SourceFile:103)
09.09 11:19:17 [Server] WARN at me.kangarko.chatcontrol.null.COm3.const(SourceFile:75)
09.09 11:19:17 [Server] WARN at me.kangarko.chatcontrol.null.Con.onJoin(SourceFile:112)
09.09 11:19:17 [Server] WARN at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
09.09 11:19:17 [Server] WARN at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
09.09 11:19:17 [Server] WARN at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
09.09 11:19:17 [Server] WARN at java.lang.reflect.Method.invoke(Method.java:498)
09.09 11:19:17 [Server] WARN at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
09.09 11:19:17 [Server] WARN at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
09.09 11:19:17 [Server] WARN at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499)
09.09 11:19:17 [Server] WARN at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484)
09.09 11:19:17 [Server] WARN at net.minecraft.server.v1_12_R1.PlayerList.onPlayerJoin(PlayerList.java:346)
09.09 11:19:17 [Server] WARN at net.minecraft.server.v1_12_R1.PlayerList.a(PlayerList.java:166)
09.09 11:19:17 [Server] WARN at net.minecraft.server.v1_12_R1.LoginListener.b(LoginListener.java:159)
09.09 11:19:17 [Server] WARN at net.minecraft.server.v1_12_R1.LoginListener.e(LoginListener.java:57)
09.09 11:19:17 [Server] WARN at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:233)
09.09 11:19:17 [Server] WARN at net.minecraft.server.v1_12_R1.ServerConnection.c(ServerConnection.java:140)
09.09 11:19:17 [Server] WARN at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:845)
09.09 11:19:17 [Server] WARN at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
09.09 11:19:17 [Server] WARN at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
09.09 11:19:17 [Server] WARN at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
09.09 11:19:17 [Server] WARN at java.lang.Thread.run(Thread.java:748)
```

When joining, tested with ChatControl Pro `7.5.0-beta` and spigot `CraftBukkit version git-Spigot-da42974-876d22c (MC: 1.12.1) (Implementing API version 1.12.1-R0.1-SNAPSHOT)`

**Comment by xion87** [comment]
Same on 1.8.9
is a little different

> [13:17:19] [Server thread/INFO]: [0;37;1m[0;35;22m[KitPvP] [0;37;22m[0;37;1m[0;37;1m[0;37;1m[0;37;1m[0;36;22mSTAFF[0;36;1m▐[0;36;22m [0;31;1m[21m(!) [0;33;1mPvPEu > Ping:107 Tps:19.97 > Heuristic[m
[13:17:50] [Thread-120/INFO]: UUID of player PvPEu is a907688e-189f-329d-a4ae-825350677399
[13:17:50] [Server thread/INFO]: PvPEu[/151.66.1.183:35890] logged in with entity id 6947 at ([world]-553.5, 169.0, -2097.5)
[13:17:50] [pool-29-thread-1/INFO]: Creazione configurazione vuota: /home/pp-test_riy5mgf/public/plugins/Essentials/userdata/a907688e-189f-329d-a4ae-825350677399.yml
[13:17:51] [Thread-127/INFO]: UUID of player TheSniper99 is 1cd51c78-a7d0-3939-9a4a-af7aac093119
[13:17:51] [Server thread/WARN]: java.lang.NullPointerException: def
[13:17:51] [Server thread/WARN]: 	at me.kangarko.chatcontrol.null.COm3.const(SourceFile:117)
[13:17:51] [Server thread/WARN]: 	at me.kangarko.chatcontrol.null.COm3.const(SourceFile:103)
[13:17:51] [Server thread/WARN]: 	at me.kangarko.chatcontrol.null.COm3.const(SourceFile:75)
[13:17:51] [Server thread/WARN]: 	at me.kangarko.chatcontrol.null.Con.onJoin(SourceFile:112)
[13:17:51] [Server thread/WARN]: 	at sun.reflect.GeneratedMethodAccessor285.invoke(Unknown Source)
[13:17:51] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[13:17:51] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[13:17:51] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300)
[13:17:51] [Server thread/WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78)
[13:17:51] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[13:17:51] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517)
[13:17:51] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502)
[13:17:51] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerList.onPlayerJoin(PlayerList.java:314)
[13:17:51] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerList.a(PlayerList.java:173)
[13:17:51] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.LoginListener.b(LoginListener.java:144)
[13:17:51] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.LoginListener.c(LoginListener.java:54)
[13:17:51] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:231)
[13:17:51] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.ServerConnection.c(ServerConnection.java:148)
[13:17:51] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:875)
[13:17:51] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378)
[13:17:51] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713)
[13:17:51] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616)
[13:17:51] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[13:17:51] [Server thread/INFO]: TheSniper99[/151.38.114.208:34122] logged in with entity id 6948 at ([world]-542.5250093643286, 158.0, -2105.7048611599325)
[13:17:55] [Server thread/INFO]: TheSniper99 issued server command: /check pvpeu 2
[13:17:55] [Server thread/INFO]: TheSniper99 [1cd51c78-a7d0-3939-9a4a-af7aac093119]: /check pvpeu 2

**Comment by kangarko** [comment]
@xion87 my eyes hurt reading this, please use pastebin.com for uploading stack traces with proper formatting.

I have fixed this error and it will be covered in the next release.
