### ISSUE TITLE
Regex replace error thing goin on (chat.txt vs rules.txt)

### ISSUE THREAD

**Issue by mrcoffee1026** [kangarko/ChatControl-Pro#358]
Ok so, this error comes and goes?  Not really sure why.  Coming from one or another ruleset depending on where it's put or what's enabled, the error is pretty much the same "undefined index" of some sort or another having to do with repeated characters... either in rules/rules.txt or rules/chat.txt.  The example in chat.txt showed the error first when I uncommented it:
```
# Example of limiting repeating characters to four repeats maximum.
#match (.)(?=([a-z])\1{4})
#then replace

```
When this resulted in an error every time there was a match and a replacement of 'nothing', thereby making things like 'yaaaaaaaaaaaay!' beome 'yy!', something had to be done immediately so I tried deactivating that rule (i have no idea what's wrong with it), and using the alternates available in rules.txt like this one:
```
# Restrict three characters to max. two repeats
# example: lollollol to lollol
match (....)(?=\1\1+)
#ignore event sign
then replace

```
I altered this to have extra .'s since I don't want it kicking in till there's like 4 in a row or something.  The "ignore event sign"... by the say the text at the top of the file list the event as being called "SIGNS".  When I put this in, the plugin effectively crashed and I had to restart the server.  When I traded that for "Sign",  well... sometimes this works sometimes it doesn't.  Seems from time to time I get an error when people "decorate" their signs with things like "-=-=-=-=-=-=-=-".  The plugin attempts to change the sign text... but can't, because the sign already exists.  I attempted to just ignore signs for that reason but now I'm getting the same undefined index error the first regex was throwing over half the time.  This rule worked for a while except for the errors with sign creation, since I got rid of those it hasn't worked since.  No idea why... the rule itself has not changed.  It seems to me the entire regex thing is not working as intended.  Here is the big ugly error I took out of the server log though I find this to be less than informative.

```
[22:44:48 INFO]: *--------- Rule match (chat) for CoffeeMug1026 --------- ID UNSET
[22:44:48 INFO]: MATCH: (....)(?=\1\1+)
[22:44:48 INFO]: CATCH: yaaaaaaaaaaaaaaaaay?
[22:44:48 ERROR]: Could not pass event AsyncPlayerChatEvent to ChatControl v7.5.1-BETA
java.lang.StringIndexOutOfBoundsException: String index out of range: 9
        at java.lang.String.substring(String.java:1963) ~[?:1.8.0_131]
        at me.kangarko.chatcontrol.null.Com3.const(SourceFile:724) ~[ChatControl.jar:?]
        at me.kangarko.chatcontrol.null.Com3.const(SourceFile:718) ~[ChatControl.jar:?]
        at me.kangarko.chatcontrol.null.Com3.const(SourceFile:422) ~[ChatControl.jar:?]
        at me.kangarko.chatcontrol.null.Com3.const(SourceFile:281) ~[ChatControl.jar:?]
        at me.kangarko.chatcontrol.null.Lpt2.const(SourceFile:182) ~[ChatControl.jar:?]
        at me.kangarko.chatcontrol.null.Lpt2.const(SourceFile:48) ~[ChatControl.jar:?]
        at me.kangarko.chatcontrol.null.Lpt2.const(SourceFile:30) ~[ChatControl.jar:?]
        at me.kangarko.chatcontrol.null.nUL.execute(SourceFile:26) ~[ChatControl.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.1-R0.1-SNAPSHOT.jar:git-Spigot-da42974-876d22c]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [spigot-1.12.1-R0.1-SNAPSHOT.jar:git-Spigot-da42974-876d22c]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:481) [spigot-1.12.1-R0.1-SNAPSHOT.jar:git-Spigot-da42974-876d22c]
        at net.minecraft.server.v1_12_R1.PlayerConnection.chat(PlayerConnection.java:1308) [spigot-1.12.1-R0.1-SNAPSHOT.jar:git-Spigot-da42974-876d22c]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1246) [spigot-1.12.1-R0.1-SNAPSHOT.jar:git-Spigot-da42974-876d22c]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:39) [spigot-1.12.1-R0.1-SNAPSHOT.jar:git-Spigot-da42974-876d22c]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_131]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
[22:44:48 INFO]: [Turtle] CoffeeMug1026: yaaaaaaaaaaaaaaaaay?
`
```
```

**Comment by kangarko** [comment]
Hey, sorry for the delay, please allow additional 24h to solve this.

**Comment by mrcoffee1026** [comment]
I am not entirely confident this issue exists anymore.  I just put your new build on and tried the same things... sign noise along with repeated items and didn't come up with any "out of index" errors.  The signs... do not auto-correct.  In the console I get the message that the text was caught and replaced... but since it was a sign (and therefore protected by other plugins like griefprotection and coreprotect) no alterations are made to the sign itself.  I've therefore reimplemented the rules.txt version of the rule I wanted... and just have it ignoring signs anyway since it can't make a change to them.

Before this update someone discovered some odd thing going on with the replacements when maybe "/" was included in the text and/or multiple curses/profanities... which seems to have also resolved itself with this update.  Don't know what you did, but it seems to have done the trick?

Thanks much.

**Comment by kangarko** [comment]
> Signs problem.
I will add an option to change the priority of the signs listener. You can play with it to allow ChatControl to act as last.

> Before this update...
Do you know which version are you talking about?

The next update will revert the dynamic swear replace of *** to match the word's length, which will also fix that issue. I will bring the feature back once I solve this completely.

> Issues resolved itself...
Since the next update reverts some mechanisms, it is possible they come back. Please keep me posted.

Closing this for now, but please let me know below if anything else arises in the next version :)

**Comment by mrcoffee1026** [comment]
Version 7.5.3 was *this* update I was referring to, I just loaded it... seemed to have resolved the regex error thing I was getting before, but - then again - it did only happen kind of sporadically anyway.  If your next update makes it like it was prior to this... I've been keeping up with updates as they've been available, but the last one I had (when this issue existed was one of the BETA ones, I believe the 7.5.0.

**Comment by kangarko** [comment]
I see. The error is sporadic due to odd style the rules are handled (due to the dynamic replacement feature).
