### ISSUE TITLE
Cauldron got broke again after 7.5.0beta+ update 7.4.24 works fine

### ISSUE THREAD

**Issue by jacky3362** [kangarko/ChatControl-Pro#394]
Cauldron got broke again after 7.5.0beta+ update 7.4.24 works fine
More Information: 
Could not find class: net.minecraft.server.v1_7_R4.EntityPlayer
lpt4Report / Could not find class: net.minecraft.server.v1_7_R4.EntityPlayer
	 at me.kangarko.chatcontrol.null.lPt2.private(SourceFile:169)
	 at me.kangarko.chatcontrol.null.lPt2.const(SourceFile:94)
	 at me.kangarko.chatcontrol.null.lPt2.<clinit>(SourceFile:41)
	 at me.kangarko.chatcontrol.null.COm6.const(SourceFile:206)
	 at me.kangarko.chatcontrol.null.COM8.strictfp(SourceFile:208)
	 at me.kangarko.chatcontrol.null.lpT1.const(SourceFile:33)
	 at me.kangarko.chatcontrol.null.lpT1$COM4.init(SourceFile:681)
	 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	 at java.lang.reflect.Method.invoke(Method.java:498)
	 at me.kangarko.chatcontrol.null.COM8.const(SourceFile:97)
	 at me.kangarko.chatcontrol.null.COM8.strictfp(SourceFile:74)
	 at me.kangarko.chatcontrol.null.COM8$1.const(SourceFile:29)
	 at me.kangarko.chatcontrol.null.COm6.native(SourceFile:120)
	 at me.kangarko.chatcontrol.null.COM8.boolean(SourceFile:128)
	 at me.kangarko.chatcontrol.null.lpT1.const(SourceFile:40)
	 at me.kangarko.chatcontrol.null.COM8.const(SourceFile:55)
	 at me.kangarko.chatcontrol.null.COM6.onEnable(SourceFile:123)
	 at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316)
	 at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368)
	 at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410)
	 at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:415)
	 at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:349)
----------------------------------------------------------------------------------------------

------------------------------------[ 27.09.2017 14:46:59 ]-----------------------------------
ChatControl 7.5.10 encountered a lpt4
Running 1.7.10-R0.1-SNAPSHOT and Java 1.8.0_141
Plugins: BungeeChatAPI v1.0.1, LuckPerms v3.4.16, WorldEdit v6.1.8-SNAPSHOT;cd4729f, Lockette v1.8.36, Essentials v2.0.1-b530, EssentialsSpawn v2.0.1-b530, EssentialsChat v2.0.1-b530, WorldGuard v6.2.1;84bc322, ChatControl v7.5.10, GriefPrevention v16.7.1
----------------------------------------------------------------------------------------------

More Information: 
ScriptEngine not found. Variables require Java 8 or newer
lpt4Report / ScriptEngine not found. Variables require Java 8 or newer
	 at me.kangarko.chatcontrol.null.aux.const(SourceFile:18)
	 at me.kangarko.chatcontrol.null.auX.<clinit>(SourceFile:30)
	 at me.kangarko.chatcontrol.null.lPT1$throw.const(SourceFile:111)
	 at me.kangarko.chatcontrol.null.lPT1$throw.const(SourceFile:104)
	 at me.kangarko.chatcontrol.null.lPT1.private(SourceFile:41)
	 at me.kangarko.chatcontrol.null.lPT1.native(SourceFile:37)
	 at me.kangarko.chatcontrol.null.COM6.onEnable(SourceFile:132)
	 at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316)
	 at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368)
	 at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410)
	 at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:415)
	 at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:349)
----------------------------------------------------------------------------------------------

**Comment by kangarko** [comment]
Thanks, will fix tonight :)
