### ISSUE TITLE
Random error when player joins

### ISSUE THREAD

**Issue by x1p** [kangarko/ChatControl-Pro#396]
29.09 23:11:09 [Server] WARN java.lang.ClassCastException: java.lang.Long cannot be cast to java.lang.String
29.09 23:11:09 [Server] WARN at me.kangarko.chatcontrol.null.AUx.private(SourceFile:94)
29.09 23:11:09 [Server] WARN at java.util.HashMap.forEach(HashMap.java:1288)
29.09 23:11:09 [Server] WARN at me.kangarko.chatcontrol.null.AUx.const(SourceFile:125)
29.09 23:11:09 [Server] WARN at me.kangarko.chatcontrol.null.AUx.const(SourceFile:94)
29.09 23:11:09 [Server] WARN at me.kangarko.chatcontrol.null.lPt3.onJoin(SourceFile:113)
29.09 23:11:09 [Server] WARN at sun.reflect.GeneratedMethodAccessor516.invoke(Unknown Source) 29.09 23:11:09 [Server] WARN at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
29.09 23:11:09 [Server] WARN at java.lang.reflect.Method.invoke(Method.java:498)
29.09 23:11:09 [Server] WARN at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
29.09 23:11:09 [Server] WARN at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
29.09 23:11:09 [Server] WARN at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499)
29.09 23:11:09 [Server] WARN at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484)
29.09 23:11:09 [Server] WARN at net.minecraft.server.v1_12_R1.PlayerList.onPlayerJoin(PlayerList.java:346)
29.09 23:11:09 [Server] WARN at net.minecraft.server.v1_12_R1.PlayerList.a(PlayerList.java:166) 29.09 23:11:09 [Server] WARN at net.minecraft.server.v1_12_R1.LoginListener.b(LoginListener.java:159)
29.09 23:11:09 [Server] WARN at net.minecraft.server.v1_12_R1.LoginListener.e(LoginListener.java:57)
29.09 23:11:09 [Server] WARN at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:233)
29.09 23:11:09 [Server] WARN at net.minecraft.server.v1_12_R1.ServerConnection.c(ServerConnection.java:140) 
9.09 23:11:09 [Server] WARN at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:842)
29.09 23:11:09 [Server] WARN at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405)
29.09 23:11:09 [Server] WARN at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678)
29.09 23:11:09 [Server] WARN at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576)
29.09 23:11:09 [Server] WARN at java.lang.Thread.run(Thread.java:745)

**Comment by malonnnn** [comment]
Could you please post a full server boot log?

**Comment by x1p** [comment]
Not for now because of the competition, but I can tell that the server uses MySQL Player Data Bridge.

**Comment by x1p** [comment]
Another example: (player data censored like this <<UUID>> )

[11:23:09] [User Authenticator #14/INFO]: UUID of player <<PLAYERNAME>> is <<UUID>>
[11:23:09] [Server thread/WARN]: java.lang.ClassCastException: java.lang.Long cannot be cast to java.lang.String
[11:23:09] [Server thread/WARN]: 	at me.kangarko.chatcontrol.null.AUx.private(SourceFile:94)
[11:23:09] [Server thread/WARN]: 	at java.util.HashMap.forEach(HashMap.java:1288)
[11:23:09] [Server thread/WARN]: 	at me.kangarko.chatcontrol.null.AUx.const(SourceFile:125)
[11:23:09] [Server thread/WARN]: 	at me.kangarko.chatcontrol.null.AUx.const(SourceFile:94)
[11:23:09] [Server thread/WARN]: 	at me.kangarko.chatcontrol.null.lPt3.onJoin(SourceFile:113)
[11:23:09] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[11:23:09] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[11:23:09] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[11:23:09] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[11:23:09] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
[11:23:09] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[11:23:09] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499)
[11:23:09] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484)
[11:23:09] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerList.onPlayerJoin(PlayerList.java:342)
[11:23:09] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerList.a(PlayerList.java:162)
[11:23:09] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.LoginListener.b(LoginListener.java:159)
[11:23:09] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.LoginListener.e(LoginListener.java:57)
[11:23:09] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:233)
[11:23:09] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.ServerConnection.c(ServerConnection.java:140)
[11:23:09] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:842)
[11:23:09] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405)
[11:23:09] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678)
[11:23:09] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576)
[11:23:09] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[11:23:09] [Server thread/INFO]: <<PLAYER>>[/IPADDRESS:51010] logged in with entity id 39474 at ([world]2312.3903676495734, 70.0, 4401.796874122501)

So everyone can see it happens at the very beginning of joining. The MySQL Player Data Bridge has probably nothing to do with it. It happens also on servers without MySQL Player Data Bridge, so normal essentials.

**Comment by kangarko** [comment]
Will fix, thank you for reporting.
