### ISSUE TITLE
Error on chat: `UnknownFormatConversionException: Conversion = 'p'`

### ISSUE THREAD

**Issue by totokaka** [kangarko/ChatControl-Pro#40]
Hi, I just bought the plugin, but it doesn't seem to work properly for me.

I am running spigot version `git-Spigot-e6f93f4-d884ab3 (MC: 1.9.2)` on OpenJDK version `1.8.0_91`, with version `6.9.0` of the plugin.

Whenever I chat from the game, this error shows in the console:
```
[10:09:00 ERROR]: Could not pass event AsyncPlayerChatEvent to ChatControl v6.9.0
java.util.UnknownFormatConversionException: Conversion = 'p'
        at org.bukkit.event.player.AsyncPlayerChatEvent.setFormat(AsyncPlayerChatEvent.java:100) ~[spigot-1.9.2.jar:git-Spigot-e6f93f4-d884ab3]
        at me.kangarko.chatcontrol.aux.const(SourceFile:70) ~[?:?]
        at me.kangarko.chatcontrol.aux.execute(SourceFile:45) ~[?:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.9.2.jar:git-Spigot-e6f93f4-d884ab3]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.9.2.jar:git-Spigot-e6f93f4-d884ab3]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot-1.9.2.jar:git-Spigot-e6f93f4-d884ab3]
        at net.minecraft.server.v1_9_R1.PlayerConnection.chat(PlayerConnection.java:1272) [spigot-1.9.2.jar:git-Spigot-e6f93f4-d884ab3]
        at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1210) [spigot-1.9.2.jar:git-Spigot-e6f93f4-d884ab3]
        at net.minecraft.server.v1_9_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:39) [spigot-1.9.2.jar:git-Spigot-e6f93f4-d884ab3]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_91]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_91]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_91]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_91]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
```
And the chat message is not formatted.

**Comment by EvilOlaf** [comment]
Did you upgrade from free?

**Comment by totokaka** [comment]
Yes, I did



*------totokaka*
*email:* mail@totokaka.io

2016-05-07 16:14 GMT+02:00 Very Evil Olaf <notifications@github.com>:

**Comment by EvilOlaf** [comment]
Then you probably need to convert your files into the new variable system. You find both the information why this did not happen automatically as well as instructions how to do that here:
https://www.spigotmc.org/threads/chatcontrol-pro-paid.82298/page-44#post-1323816

**Comment by kangarko** [comment]
Upgrade your variables.
