### ISSUE TITLE
Integration with LuckPerms and AuthMe

### ISSUE THREAD

**Issue by renzotom** [kangarko/ChatControl-Pro#404]
Hello, I have one BIG problem. New players can't register, beacuse password didn't match (but they match).

I tested it and I found mistake, it is between LuckPerms and ChatControl integration, and it brokes AuthMe registration.

So...

AuthMe + LuckPerms - works
AuthMe + ChatControl - works
AuthMe + LuckPerms + ChatControl - didn't work

**Comment by kangarko** [comment]
How exactly this doesn't work? What happens with the password, how it is changed by ChatControl?

**Comment by renzotom** [comment]
When I use ChatControl and LuckPerms combination, it says, Password didn't match.... Please, contact me on Discord or on Spigot for better soluting.

**Comment by kangarko** [comment]
If ChatControl + AuthMe works, and adding LuckPerms breaks it, then it's LuckPerms' fault, I am sorry.

Is there anything in the console from ChatControl about matching a rule when the password didn't match message appears?

**Comment by renzotom** [comment]
But,  it is also opposite, when I add ChatControl to LuckPerms, it breaks also.... IDK if mistake is here or in LP, but maybe here, beacuse when player has OP, it works. If you wanna, you can test it yourself on my server, to see it.

**Comment by renzotom** [comment]
`
>[2K [13:48:47 INFO]: UUID of player Tester is f3d28cb0-7225-3cb1-baeb-2dadd2be89ae 
>[2K [13:48:48 INFO]: [Bank] Unable to load f3d28cb0-7225-3cb1-baeb-2dadd2be89ae from SQL, locked 
>[2K [13:48:48 INFO]: [ChatAPI] Added channel for f3d28cb0-7225-3cb1-baeb-2dadd2be89ae[ChatControl debug] [data.db] Set Players.Tester.Ignoring_PM' --> 'null' 
>[2K [13:48:48 INFO]: [ChatControl debug] [data.db] Set Players.Tester.Spying' --> 'null' 
>[2K [13:48:48 INFO]: [ChatControl debug] [data.db] Set Players.Tester.Chat_Mode' --> 'null' 
>[2K [13:48:48 INFO]: [ChatControl debug] [data.db] Set Players.Tester.Points' --> 'null' 
>[2K [13:48:48 INFO]: [ChatControl debug] [data.db] Set Players.Tester.Ignored_Sets' --> 'null' 
>[2K [13:48:48 INFO]: [ChatControl debug] [data.db] Set Players.Tester.Channels' --> 'null' 
>[2K [13:48:48 INFO]: [Mail] Unable to load f3d28cb0-7225-3cb1-baeb-2dadd2be89ae from MySQL, locked[ChatControl debug] [data.db] Set Players.Tester.Ignored_Players' --> 'null' 
>[2K [13:48:48 INFO]: Tester[/46.173.197.19:58886] logged in with entity id 4344 at ([world]-198.7091712524031, 86.0, 259.97466244472446) 
>[2K [13:48:48 INFO]: [AuthMe] [DEBUG] Player `Tester` has groups `default` 
>[2K [13:49:18 INFO]: Tester lost connection: §cCas pro prihlaseni vyprsel! 
>[2K [13:49:18 ERROR]: Could not pass event PlayerQuitEvent to Mail v2.1l 
org.bukkit.event.EventException: null 
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[server.jar:git-Spigot-7754231-362ed32] 
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-Spigot-7754231-362ed32] 
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [server.jar:git-Spigot-7754231-362ed32] 
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [server.jar:git-Spigot-7754231-362ed32] 
at net.minecraft.server.v1_12_R1.PlayerList.disconnect(PlayerList.java:399) [server.jar:git-Spigot-7754231-362ed32] 
at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1102) [server.jar:git-Spigot-7754231-362ed32] 
at net.minecraft.server.v1_12_R1.PlayerConnection.disconnect(PlayerConnection.java:260) [server.jar:git-Spigot-7754231-362ed32] 
at org.bukkit.craftbukkit.v1_12_R1.entity.CraftPlayer.kickPlayer(CraftPlayer.java:221) [server.jar:git-Spigot-7754231-362ed32] 
at fr.xephi.authme.task.TimeoutTask.run(TimeoutTask.java:31) [AuthMe-5.4-SNAPSHOT%20(3).jar:?] 
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) [server.jar:git-Spigot-7754231-362ed32] 
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [server.jar:git-Spigot-7754231-362ed32] 
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [server.jar:git-Spigot-7754231-362ed32] 
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [server.jar:git-Spigot-7754231-362ed32] 
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [server.jar:git-Spigot-7754231-362ed32] 
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [server.jar:git-Spigot-7754231-362ed32] 
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144] 
Caused by: java.lang.NullPointerException 
at me.dablakbandit.mail.player.PlayerManager.remove(PlayerManager.java:98) ~[Mail.jar:?] 
at me.dablakbandit.mail.player.PlayerManager.onPlayerQuit(PlayerManager.java:122) ~[Mail.jar:?] 
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_144] 
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_144] 
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_144]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_144] 
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[server.jar:git-Spigot-7754231-362ed32] 
... 15 more 
>[2K [13:49:18 INFO]: Tester left the game 
>[2K [13:49:18 INFO]: [ChatAPI] Removed channel for f3d28cb0-7225-3cb1-baeb-2dadd2be89ae[Mail] Unable to save f3d28cb0-7225-3cb1-baeb-2dadd2be89ae to MySQL, locked 
>[2K [13:49:18 WARN]: handleDisconnection() called twice 
>[2K [13:49:18 INFO]: [AuthMe] [DEBUG] Restored LimboPlayer stats for `tester` 
>[2K [13:49:18 INFO]: [AuthMe] [DEBUG] No LimboPlayer found for `tester` - cannot restore 
>[2K [13:49:18 INFO]: [Bank] Unable to save f3d28cb0-7225-3cb1-baeb-2dadd2be89ae to SQL, locked/loading 
`

**Comment by renzotom** [comment]
I am found, where is problem....  When I have set that in settings.yml.
`
    Handle_As_Chat:
    - me
    - msg
    - r
    - pm
    - broadcast
`
It blocks register, beacuse there is R. But I wanna use that for reply, no register :D . But, why it said "Password didn't match", when there was that error?

**Comment by kangarko** [comment]
Hey,

that problem for Handle as Chat will be corrected in the next release, where only /r will be matched, no /register.

**Comment by renzotom** [comment]
Thanks.
