### ISSUE TITLE
java 9 support:

### ISSUE THREAD

**Issue by arturek1666** [kangarko/ChatControl-Pro#407]
Hi, my host updated java to 9 and now a lot of plugins don't work anymore i try to say to them to downgrade but i had negative response. When you do going to be able to update?

[10:27:45] [Server thread/ERROR]: Could not load 'plugins/ChatControl-7.5.12.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: sun/misc/BASE64Decoder
    at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[patched_1.12.2.jar:git-Paper-1233]
    at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:328) ~[patched_1.12.2.jar:git-Paper-1233]
    at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [patched_1.12.2.jar:git-Paper-1233]
    at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:309) [patched_1.12.2.jar:git-Paper-1233]
    at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:225) [patched_1.12.2.jar:git-Paper-1233]
    at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) [patched_1.12.2.jar:git-Paper-1233]
    at java.lang.Thread.run(Thread.java:844) [?:?]
Caused by: java.lang.NoClassDefFoundError: sun/misc/BASE64Decoder
    at me.kangarko.chatcontrol.null.Com2.<clinit>(SourceFile:13) ~[?:?]
    at me.kangarko.chatcontrol.null.pRn.const(SourceFile:17) ~[?:?]
    at me.kangarko.chatcontrol.null.com8.const(SourceFile:40) ~[?:?]
    at me.kangarko.chatcontrol.null.COM6.<clinit>(SourceFile:91) ~[?:?]
    at java.lang.Class.forName0(Native Method) ~[?:?]
    at java.lang.Class.forName(Class.java:375) ~[?:?]
    at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:68) ~[patched_1.12.2.jar:git-Paper-1233]
    at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:127) ~[patched_1.12.2.jar:git-Paper-1233]
    ... 6 more
Caused by: java.lang.ClassNotFoundException: sun.misc.BASE64Decoder
    at java.net.URLClassLoader.findClass(URLClassLoader.java:466) ~[?:?]
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:105) ~[patched_1.12.2.jar:git-Paper-1233]
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:90) ~[patched_1.12.2.jar:git-Paper-1233]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:563) ~[?:?]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:496) ~[?:?]
    at me.kangarko.chatcontrol.null.Com2.<clinit>(SourceFile:13) ~[?:?]
    at me.kangarko.chatcontrol.null.pRn.const(SourceFile:17) ~[?:?]
    at me.kangarko.chatcontrol.null.com8.const(SourceFile:40) ~[?:?]
    at me.kangarko.chatcontrol.null.COM6.<clinit>(SourceFile:91) ~[?:?]
    at java.lang.Class.forName0(Native Method) ~[?:?]
    at java.lang.Class.forName(Class.java:375) ~[?:?]
    at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:68) ~[patched_1.12.2.jar:git-Paper-1233]
    at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:127) ~[patched_1.12.2.jar:git-Paper-1233]
    ... 6 more

**Comment by kangarko** [comment]
Many plugins are using classes that were changed (here it's the sun.misc package that's missing).

Can you verify that you're on Oracle Java, or OpenJDK or anything else?

**Comment by arturek1666** [comment]
Not really as i am not a host so can't really say with one it is

**Comment by malonnnn** [comment]
@arturek1666 

maybe if you post a full server boot up log, we can find something in there

**Comment by kangarko** [comment]
Please ask your hosting provider for that. ChatControl uses Oracle Java (Sun Java), any other distribution will break. Luckily 99% servers use that distribution so it's never been a problem.

**Comment by arturek1666** [comment]
Ok, i informed him, I will inform you when i will get the information needed.

**Comment by arturek1666** [comment]
haha i am hosting server on not big host and looks like he doesn't know xD. He will check when he will be available as currently he is not at home till Thursday ahh

**Comment by arturek1666** [comment]
but i think it's oracle as when he had java 8 server was working fine. Just after update broke.

**Comment by kangarko** [comment]
I have added support for Java 9 to the latest version and fixed the missing classes. A new release will be available shortly. Please let me know if any issues arise (I have tested it on a virtual machine with JDK9).
