### ISSUE TITLE
NullPointerException; RuntimeException - enum 'EventPriority' does not contain 'MON?TOR'! Available values: LOWEST, LOW, NORMAL, HIGH, HIGHEST, MONITOR

### ISSUE THREAD

**Issue by mibby** [kangarko/ChatControl-Pro#423]
```
[02:25:26] [Server thread/INFO]: [ChatControl] Enabling ChatControl v7.5.16
[02:25:27] [Server thread/INFO]:   _____ _           _    _____            _             _  +
[02:25:27] [Server thread/INFO]:  / ____| |         | |  / ____|          | |           | |
[02:25:27] [Server thread/INFO]: | |    | |__   __ _| |_| |     ___  _ __ | |_ _ __ ___ | |
[02:25:27] [Server thread/INFO]: | |    | '_ \ / _` | __| |    / _ \| '_ \| __| '__/ _ \| |
[02:25:27] [Server thread/INFO]: | |____| | | | (_| | |_| |___| (_) | | | | |_| | | (_) | |
[02:25:27] [Server thread/INFO]:  \_____|_| |_|\__,_|\__|\_____\___/|_| |_|\__|_|  \___/|_|
[02:25:27] [Server thread/INFO]: 
[02:25:27] [Server thread/INFO]: *-----------------------------------------------*
[02:25:27] [Server thread/INFO]:  The enum 'EventPriority' does not contain 'MON?TOR'! Available values: LOWEST, LOW, NORMAL, HIGH, HIGHEST, MONITOR
[02:25:27] [Server thread/INFO]:  Plugin is now disabled.
[02:25:27] [Server thread/INFO]: *-----------------------------------------------*
[02:25:27] [Server thread/INFO]: [ChatControl] Disabling ChatControl v7.5.16
[02:25:27] [Server thread/INFO]: Plugin might not shut down property. Got NullPointerException: null
[02:25:27] [Server thread/INFO]: java.lang.RuntimeException
[02:25:27] [Server thread/INFO]:     at me.kangarko.chatcontrol.null.pRn.const(SourceFile:67)
[02:25:27] [Server thread/INFO]:     at me.kangarko.chatcontrol.null.lpt1.onEnable(SourceFile:125)
[02:25:27] [Server thread/INFO]:     at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[02:25:27] [Server thread/INFO]:     at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316)
[02:25:27] [Server thread/INFO]:     at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404)
[02:25:27] [Server thread/INFO]:     at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:386)
[02:25:27] [Server thread/INFO]:     at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:335)
[02:25:27] [Server thread/INFO]:     at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442)
[02:25:27] [Server thread/INFO]:     at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403)
[02:25:27] [Server thread/INFO]:     at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341)
[02:25:27] [Server thread/INFO]:     at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:292)
[02:25:27] [Server thread/INFO]:     at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616)
[02:25:27] [Server thread/INFO]:     at java.lang.Thread.run(Unknown Source)
[02:25:27] [Server thread/INFO]:   _   _                       _
[02:25:27] [Server thread/INFO]:   | | | | ___   ___  _ __  ___| |
[02:25:27] [Server thread/INFO]:   | |_| |/ _ \ / _ \| '_ \/ __| |
[02:25:27] [Server thread/INFO]:   |  _  | (_) | (_) | |_) \__ \_|
[02:25:27] [Server thread/INFO]:   |_| |_|\___/ \___/| .__/|___(_)
[02:25:27] [Server thread/INFO]:                     |_|         
[02:25:27] [Server thread/INFO]: !-----------------------------------------------------!
[02:25:27] [Server thread/INFO]:  Error loading ChatControl v7.5.16, plugin is disabled!
[02:25:27] [Server thread/INFO]:  Running on 1.12.2-R0.1-SNAPSHOT (v1_12_R1) & Java 1.8.0_144
[02:25:27] [Server thread/INFO]: !-----------------------------------------------------!
[02:25:27] [Server thread/INFO]:  Error: Unable to get the error message, search above.
[02:25:27] [Server thread/INFO]: !-----------------------------------------------------!
```

**Comment by mibby** [comment]
Fixed in re-upload.
