### ISSUE TITLE
Could not pass incoming plugin message to ChatControl

### ISSUE THREAD

**Issue by mibby** [kangarko/ChatControl-Pro#429]
```
[02:48:06] [Server thread/WARN]: Could not pass incoming plugin message to ChatControl v7.5.16
me.kangarko.chatcontrol.null.lpt4: Report / Data count != valid values count in TELL_PLAYER! Data: 1 vs 2
	at me.kangarko.chatcontrol.null.lPT8.const(SourceFile:28) ~[ChatControl-7.5.16.jar:?]
	at me.kangarko.chatcontrol.null.cOM7.const(SourceFile:45) ~[ChatControl-7.5.16.jar:?]
	at me.kangarko.chatcontrol.null.cOM7.const(SourceFile:26) ~[ChatControl-7.5.16.jar:?]
	at me.kangarko.chatcontrol.null.super.const(SourceFile:129) ~[ChatControl-7.5.16.jar:?]
	at me.kangarko.chatcontrol.null.coM1.onPluginMessageReceived(SourceFile:27) ~[ChatControl-7.5.16.jar:?]
	at org.bukkit.plugin.messaging.StandardMessenger.dispatchIncomingMessage(StandardMessenger.java:427) ~[patched_1.12.2.jar:git-Paper-1244]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:2664) ~[patched_1.12.2.jar:git-Paper-1244]
	at net.minecraft.server.v1_12_R1.PacketPlayInCustomPayload.a(SourceFile:58) ~[patched_1.12.2.jar:git-Paper-1244]
	at net.minecraft.server.v1_12_R1.PacketPlayInCustomPayload.a(SourceFile:8) ~[patched_1.12.2.jar:git-Paper-1244]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.2.jar:git-Paper-1244]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_144]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_144]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [patched_1.12.2.jar:git-Paper-1244]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:843) [patched_1.12.2.jar:git-Paper-1244]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426) [patched_1.12.2.jar:git-Paper-1244]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.2.jar:git-Paper-1244]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1244]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
```

**Comment by kangarko** [comment]
Thank you for reporting.

I have resolved that.
