### ISSUE TITLE
Could not pass event AsyncPlayerChatEvent to ChatControl

### ISSUE THREAD

**Issue by mibby** [kangarko/ChatControl-Pro#435]
```
[03:31:58] [Async Chat Thread - #0/ERROR]: Could not pass event AsyncPlayerChatEvent to ChatControl v7.6.0
java.lang.RuntimeException: Unknown type of data: CraftPlayer{name=mibby} (CraftPlayer)
	at me.kangarko.chatcontrol.final..\... .pRN.const(SourceFile:74) ~[ChatControl-7.6.0.jar:?]
	at me.kangarko.chatcontrol.final..\... .pRN.const(SourceFile:26) ~[ChatControl-7.6.0.jar:?]
	at me.kangarko.chatcontrol.final..\... .aB.native(SourceFile:99) ~[ChatControl-7.6.0.jar:?]
	at me.kangarko.chatcontrol.final..\... .aB.const(SourceFile:40) ~[ChatControl-7.6.0.jar:?]
	at me.kangarko.chatcontrol.final..\... .ar.const(SourceFile:288) ~[ChatControl-7.6.0.jar:?]
	at me.kangarko.chatcontrol.final..\... .ar.const(SourceFile:68) ~[ChatControl-7.6.0.jar:?]
	at me.kangarko.chatcontrol.final..\... .ar.const(SourceFile:31) ~[ChatControl-7.6.0.jar:?]
	at me.kangarko.chatcontrol.final..\... .Com7.execute(SourceFile:26) ~[ChatControl-7.6.0.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[patched_1.12.2.jar:git-Paper-1244]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1244]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:514) [patched_1.12.2.jar:git-Paper-1244]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:496) [patched_1.12.2.jar:git-Paper-1244]
	at net.minecraft.server.v1_12_R1.PlayerConnection.chat(PlayerConnection.java:1381) [patched_1.12.2.jar:git-Paper-1244]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1296) [patched_1.12.2.jar:git-Paper-1244]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:39) [patched_1.12.2.jar:git-Paper-1244]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_144]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_144]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
```

**Comment by kangarko** [comment]
Confirmed, fixed.
