### ISSUE TITLE
Java 9 compatibility - ClassFormatError: Illegal class name

### ISSUE THREAD

**Issue by mibby** [kangarko/ChatControl-Pro#446]
```
[00:32:56] [Server thread/ERROR]: Could not load 'plugins/ChatControl-7.6.6.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.ClassFormatError: Illegal class name "me/kangarko/chatcontrol/final//\/// /LpT5" in class file me/kangarko/chatcontrol/ChatControl
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[patched_1.12.2.jar:git-Paper-1244]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:328) ~[patched_1.12.2.jar:git-Paper-1244]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [patched_1.12.2.jar:git-Paper-1244]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:309) [patched_1.12.2.jar:git-Paper-1244]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:225) [patched_1.12.2.jar:git-Paper-1244]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) [patched_1.12.2.jar:git-Paper-1244]
	at java.lang.Thread.run(Thread.java:844) [?:?]
Caused by: java.lang.ClassFormatError: Illegal class name "me/kangarko/chatcontrol/final//\/// /LpT5" in class file me/kangarko/chatcontrol/ChatControl
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1007) ~[?:?]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174) ~[?:?]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:545) ~[?:?]
	at java.net.URLClassLoader.access$100(URLClassLoader.java:83) ~[?:?]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:453) ~[?:?]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:447) ~[?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:446) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:105) ~[patched_1.12.2.jar:git-Paper-1244]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:90) ~[patched_1.12.2.jar:git-Paper-1244]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:563) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:496) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:375) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:68) ~[patched_1.12.2.jar:git-Paper-1244]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:127) ~[patched_1.12.2.jar:git-Paper-1244]
	... 6 more
```

**Comment by leNicDev** [comment]
I can confirm that error. I'm using the latest version of Java 9 and Paper 1.12.2.

**Comment by kangarko** [comment]
Confirmed, will be fixed.
