### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by mibby** [kangarko/ChatControl-Pro#460]
ChatControlPro v7.6.7

```
[14:01:32] [Server thread/INFO]: player issued server command: /chc ach test
[14:01:32] [Server thread/WARN]: java.lang.NullPointerException
[14:01:32] [Server thread/WARN]: 	at me.kangarko.chatcontrol.final. .COM7.native(SourceFile:452)
[14:01:32] [Server thread/WARN]: 	at me.kangarko.chatcontrol.final. .COM7.strictfp(SourceFile:419)
[14:01:32] [Server thread/WARN]: 	at me.kangarko.chatcontrol.final. .ax.native(SourceFile:305)
[14:01:32] [Server thread/WARN]: 	at me.kangarko.chatcontrol.final. .void.const(SourceFile:248)
[14:01:32] [Server thread/WARN]: 	at me.kangarko.chatcontrol.final. .nUL.onCommand(SourceFile:54)
[14:01:32] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[14:01:32] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151)
[14:01:32] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:676)
[14:01:32] [Server thread/WARN]: 	at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:590)
[14:01:32] [Server thread/WARN]: 	at org.bukkit.command.FormattedCommandAlias.execute(FormattedCommandAlias.java:41)
[14:01:32] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151)
[14:01:32] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:676)
[14:01:32] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1466)
[14:01:32] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1271)
[14:01:32] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[14:01:32] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)
[14:01:32] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14)
[14:01:32] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[14:01:32] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[14:01:32] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[14:01:32] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:843)
[14:01:32] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426)
[14:01:32] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767)
[14:01:32] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665)
[14:01:32] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by mibby** [comment]
@kangarko Another related error.

```
[14:01:46] [Async Chat Thread - #51/ERROR]: Could not pass event AsyncPlayerChatEvent to ChatControl v7.6.7
java.lang.NullPointerException: null
	at me.kangarko.chatcontrol.final. .COM7.native(SourceFile:452) ~[ChatControl-7.6.7.jar:?]
	at me.kangarko.chatcontrol.final. .COM7.private(SourceFile:412) ~[ChatControl-7.6.7.jar:?]
	at me.kangarko.chatcontrol.final. .ax.const(SourceFile:291) ~[ChatControl-7.6.7.jar:?]
	at me.kangarko.chatcontrol.final. .ax.const(SourceFile:68) ~[ChatControl-7.6.7.jar:?]
	at me.kangarko.chatcontrol.final. .ax.const(SourceFile:31) ~[ChatControl-7.6.7.jar:?]
	at me.kangarko.chatcontrol.final. .lPt6.execute(SourceFile:26) ~[ChatControl-7.6.7.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[patched_1.12.2.jar:git-Paper-1248]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1248]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:514) [patched_1.12.2.jar:git-Paper-1248]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:496) [patched_1.12.2.jar:git-Paper-1248]
	at net.minecraft.server.v1_12_R1.PlayerConnection.chat(PlayerConnection.java:1381) [patched_1.12.2.jar:git-Paper-1248]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1296) [patched_1.12.2.jar:git-Paper-1248]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:39) [patched_1.12.2.jar:git-Paper-1248]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_152]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_152]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_152]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_152]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
```

**Comment by kangarko** [comment]
Hey,

I apology for the issues. Please contact me privately on Spigot regarding this. For now, this is solved by simply reloading the plugin or restarting the server. It should not normally happen again, hence I need your personal assistance. P.S.: I have adjusted that mechanism in the next version.
