### ISSUE TITLE
ChatControl v7.6.8 - error v7.6.6 - works perfectly (Pro)

### ISSUE THREAD

**Issue by andris155** [kangarko/ChatControl-Pro#466]
Paper 1.12.2
```
[15:32:51] [Async Chat Thread - #0/ERROR]: Could not pass event AsyncPlayerChatEvent to ChatControl v7.6.8
java.lang.NullPointerException: null
	at me.kangarko.chatcontrol.final. .COM7.native(SourceFile:452) ~[?:?]
	at me.kangarko.chatcontrol.final. .COM7.strictfp(SourceFile:419) ~[?:?]
	at me.kangarko.chatcontrol.final. .bk.const(SourceFile:148) ~[?:?]
	at me.kangarko.chatcontrol.final. .aO.const(SourceFile:768) ~[?:?]
	at me.kangarko.chatcontrol.final. .aO.const(SourceFile:334) ~[?:?]
	at me.kangarko.chatcontrol.final. .aO.const(SourceFile:287) ~[?:?]
	at me.kangarko.chatcontrol.final. .ax.const(SourceFile:183) ~[?:?]
	at me.kangarko.chatcontrol.final. .ax.const(SourceFile:49) ~[?:?]
	at me.kangarko.chatcontrol.final. .ax.const(SourceFile:31) ~[?:?]
	at me.kangarko.chatcontrol.final. .lPt6.execute(SourceFile:26) ~[?:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[patched_1.12.2.jar:git-Paper-1248]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1248]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:514) [patched_1.12.2.jar:git-Paper-1248]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:496) [patched_1.12.2.jar:git-Paper-1248]
	at net.minecraft.server.v1_12_R1.PlayerConnection.chat(PlayerConnection.java:1381) [patched_1.12.2.jar:git-Paper-1248]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1296) [patched_1.12.2.jar:git-Paper-1248]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:39) [patched_1.12.2.jar:git-Paper-1248]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_151]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_151]
```

**Comment by kangarko** [comment]
Hey, I apology, this should be solved in the upcoming version ;)

Have a great day/evening!
