### ISSUE TITLE
thermos 1.7.10

### ISSUE THREAD

**Issue by jacky3362** [kangarko/ChatControl-Pro#471]
ChatControl 7.6.8 encountered a COm7
Running 1.7.10-R0.1-SNAPSHOT and Java 1.8.0_144
Plugins: LuckPerms v3.4.1, WorldEdit v5.6.3, AdminFun v2.3.0, Skript v2.2-SNAPSHOT, OpenInv v3.0.3, Essentials vPre2.14.1.3, Custom_Wishes v1.0, GroupManager vPre2.14.1.3 FINAL (Phoenix), AgarthaLib vMysthoria, BungeeChatAPI v1.0.1, ClearLag v2.9.7, BukkitCompat vR22A, SkQuery v3.21.4, EndlessEnchant v1.4, ProtocolLib v4.2.1, WorldGuard v6.1, MyItems vMysthoria, Vault v1.6.1, EssentialsSpawn vPre2.14.1.3, GriefPrevention v9.1, MassiveCore v2.7.4, EnjinMinecraftPlugin v2.7.7, RPGItems v3.5.134, ChestShop v3.8.12, HolographicDisplays v1.8.8, CommandSpy v1.4, Factions v2.7.1, FactionsPets v1.13.2, ChatControl v7.6.8
----------------------------------------------------------------------------------------------

More Information: 
ScriptEngine not found. Variables require Java 8 or newer
COm7Report / ScriptEngine not found. Variables require Java 8 or newer
	 at me.kangarko.chatcontrol.final. .lpt3.const(SourceFile:18)
	 at me.kangarko.chatcontrol.final. .Com4.<clinit>(SourceFile:30)
	 at me.kangarko.chatcontrol.final. .LPt7$super.const(SourceFile:103)
	 at me.kangarko.chatcontrol.final. .LPt7$super.const(SourceFile:96)
	 at me.kangarko.chatcontrol.final. .LPt7.strictfp(SourceFile:40)
	 at me.kangarko.chatcontrol.final. .LPt7.native(SourceFile:36)
	 at me.kangarko.chatcontrol.final. .LpT5.onEnable(SourceFile:157)
	 at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316)
	 at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368)
	 at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410)
	 at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:438)
	 at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:372)
----------------------------------------------------------------------------------------------

**Comment by jacky3362** [comment]
this is cauldron btw

**Comment by kangarko** [comment]
Hey and thank you for using Issues Tracker!

ChatControl uses 'Nashorn' addon in Java 8 for the javascript Variables. It may be that your Java bundle does not have it - there are Oracle Java, Sun Java and possibly also other distributions. I am sorry, but it appears that your distribution does not support that feature, and thus you need to set 'Variables.Custom_Enabled' to false in settings.yml.

Also, please install [BungeeChatAPI ](https://www.spigotmc.org/resources/bungeechatapi.38379/) library for 1.7.10.

**Comment by jacky3362** [comment]
it's already set to false and still the same error

**Comment by kangarko** [comment]
Do you know what java distribution you're on ? You can ask your hosting provider.

**Comment by jacky3362** [comment]
it's on my pc and it's jre-8u151-windows-x64.exe

**Comment by kangarko** [comment]
Hello,

coming back from doing a testing, I was able to reproduce this behaviour. Thermos replaces some fundamental parts of the Minecraft server and libraries we use, so ChatControl cannot function.

I am extremely sorry for this, but unfortunately there's little I can do because I cannot ship those libraries myself. If you have purchased ChatControl under 7 days, PM me on Spigot and I will refund you.
