### ISSUE TITLE
1.7.10 cauldron i think you can fix it tho

### ISSUE THREAD

**Issue by jacky3362** [kangarko/ChatControl-Pro#515]
`[02:44:53 INFO]: Created default file: settings.yml
[02:44:53 INFO]: org.bukkit.configuration.InvalidConfigurationException: unaccep
table character '?' (0xFFFD) special characters are not allowed
[02:44:53 INFO]: in "<string>", position 28766
[02:44:53 INFO]:        at org.bukkit.configuration.file.YamlConfiguration.loadF
romString(YamlConfiguration.java:57)
[02:44:53 INFO]:        at org.bukkit.configuration.file.FileConfiguration.load(
FileConfiguration.java:226)
[02:44:53 INFO]:        at org.bukkit.configuration.file.FileConfiguration.load(
FileConfiguration.java:169)
[02:44:53 INFO]:        at me.kangarko.chatcontrol.final. .COM2.native(SourceFil
e:119)
[02:44:53 INFO]:        at me.kangarko.chatcontrol.final. .lPt5.native(SourceFil
e:129)
[02:44:53 INFO]:        at me.kangarko.chatcontrol.final. .bj.native(SourceFile:
40)
[02:44:53 INFO]:        at me.kangarko.chatcontrol.final. .lPt5.const(SourceFile
:56)
[02:44:53 INFO]:        at me.kangarko.chatcontrol.final. .Lpt2.onEnable(SourceF
ile:138)
[02:44:53 INFO]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlug
in.java:316)
[02:44:53 INFO]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(
JavaPluginLoader.java:368)
[02:44:53 INFO]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(Si
mplePluginManager.java:410)
[02:44:53 INFO]:        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin
(CraftServer.java:438)
[02:44:53 INFO]:        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlug
ins(CraftServer.java:372)
[02:44:53 INFO]:        at net.minecraft.server.MinecraftServer.func_71243_i(Min
ecraftServer.java:519)
[02:44:53 INFO]:        at net.minecraft.server.MinecraftServer.func_71222_d(Min
ecraftServer.java:493)
[02:44:53 INFO]:        at net.minecraft.server.MinecraftServer.func_71247_a(Min
ecraftServer.java:453)
[02:44:53 INFO]:        at net.minecraft.server.dedicated.DedicatedServer.func_7
1197_b(DedicatedServer.java:337)
[02:44:53 INFO]:        at net.minecraft.server.MinecraftServer.run(MinecraftSer
ver.java:643)
[02:44:53 INFO]:        at java.lang.Thread.run(Unknown Source)
[02:44:53 INFO]: unacceptable character '?' (0xFFFD) special characters are not
allowed
[02:44:53 INFO]: in "<string>", position 28766
[02:44:53 INFO]:        at org.yaml.snakeyaml.reader.StreamReader.checkPrintable
(StreamReader.java:70)
[02:44:53 INFO]:        at org.yaml.snakeyaml.reader.StreamReader.<init>(StreamR
eader.java:50)
[02:44:53 INFO]:        at org.yaml.snakeyaml.Yaml.load(Yaml.java:399)
[02:44:53 INFO]:        at org.bukkit.configuration.file.YamlConfiguration.loadF
romString(YamlConfiguration.java:55)
[02:44:53 INFO]:        at org.bukkit.configuration.file.FileConfiguration.load(
FileConfiguration.java:226)
[02:44:53 INFO]:        at org.bukkit.configuration.file.FileConfiguration.load(
FileConfiguration.java:169)
[02:44:53 INFO]:        at me.kangarko.chatcontrol.final. .COM2.native(SourceFil
e:119)
[02:44:53 INFO]:        at me.kangarko.chatcontrol.final. .lPt5.native(SourceFil
e:129)
[02:44:53 INFO]:        at me.kangarko.chatcontrol.final. .bj.native(SourceFile:
40)
[02:44:53 INFO]:        at me.kangarko.chatcontrol.final. .lPt5.const(SourceFile
:56)
[02:44:53 INFO]:        at me.kangarko.chatcontrol.final. .Lpt2.onEnable(SourceF
ile:138)
[02:44:53 INFO]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlug
in.java:316)
[02:44:53 INFO]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(
JavaPluginLoader.java:368)
[02:44:53 INFO]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(Si
mplePluginManager.java:410)
[02:44:53 INFO]:        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin
(CraftServer.java:438)
[02:44:53 INFO]:        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlug
ins(CraftServer.java:372)
[02:44:53 INFO]:        at net.minecraft.server.MinecraftServer.func_71243_i(Min
ecraftServer.java:519)
[02:44:53 INFO]:        at net.minecraft.server.MinecraftServer.func_71222_d(Min
ecraftServer.java:493)
[02:44:53 INFO]:        at net.minecraft.server.MinecraftServer.func_71247_a(Min
ecraftServer.java:453)
[02:44:53 INFO]:        at net.minecraft.server.dedicated.DedicatedServer.func_7
1197_b(DedicatedServer.java:337)
[02:44:53 INFO]:        at net.minecraft.server.MinecraftServer.run(MinecraftSer
ver.java:643)
[02:44:53 INFO]:        at java.lang.Thread.run(Unknown Source)
[02:44:53 INFO]:   _   _                       _
[02:44:53 INFO]:   | | | | ___   ___  _ __  ___| |
[02:44:53 INFO]:   | |_| |/ _ \ / _ \| '_ \/ __| |
[02:44:53 INFO]:   |  _  | (_) | (_) | |_) \__ \_|
[02:44:53 INFO]:   |_| |_|\___/ \___/| .__/|___(_)
[02:44:53 INFO]:                     |_|
[02:44:53 INFO]: !-----------------------------------------------------!
[02:44:53 INFO]:  Error loading ChatControl v7.6.18, plugin is disabled!
[02:44:53 INFO]:  Running on 1.7.10-R0.1-SNAPSHOT (v1_7_R4) & Java 1.8.0_151
[02:44:53 INFO]: !-----------------------------------------------------!
[02:44:53 INFO]:  Seems like your config is not a valid YAML.
[02:44:53 INFO]:  Use online services like
[02:44:53 INFO]:  http://yaml-online-parser.appspot.com/
[02:44:53 INFO]:  to check for syntax errors!
[02:44:53 INFO]:  Error: special characters are not allowed
[02:44:53 INFO]: !-----------------------------------------------------!
[02:44:53 INFO]: [ChatControl] Disabling ChatControl v7.6.18
[02:44:53 INFO]: Plugin might not shut down property. Got NullPointerException:
null`

**Comment by kangarko** [comment]
Hello,

I think it looks like an encoding issue, you can read more about it below and try to change to UTF or ANSI encoding:

https://github.com/kangarko/ChatControl-Pro/wiki/Use-Right-Encoding

**Comment by jacky3362** [comment]
i am allways getting that error without touching the file also i allways regenerate and gets that error without editing the file ....

**Comment by jacky3362** [comment]
btw converting to utf8 and or without bom and ANSI did not work

**Comment by jacky3362** [comment]
@kangarko hey you there? it didnt work converting them to utf and ansi

**Comment by kangarko** [comment]
Sorry I have not been able to reproduce that:

![a](https://i.imgur.com/heeNyRV.png)

Does it work when you delete ChatControl folder completely? What is your system language?

**Comment by jacky3362** [comment]
my system lang is eng and it dosn't work when i delete it aswell

**Comment by jacky3362** [comment]
ok it was  system unicode i fixed it but i am getting this now
`[22:55:08 INFO]: Created default file: javascript.txt
[22:55:08 INFO]: Created default file: channels.yml
[22:55:08 INFO]: Created default file: data.db
[22:55:09 INFO]: Created default file: formatting.yml
[22:55:09 INFO]: Created default file: messages.yml
[22:55:20 INFO]: ChatControl 7.6.19 encountered a lPT6! Please check your error.
log and report this issue with the information in that file.
[22:55:20 INFO]: Server permissions file permissions.yml is empty, ignoring it
[22:55:20 INFO]: Done (43.946s)! For help, type "help" or "?"
[22:55:20 INFO]: Registered command forge with permission node net.minecraftforg
e.server.command.ForgeCommand
[22:55:22 INFO]: Hey, you don't have a server icon! Try out one of Thermos' Icon
 Generators at https://github.com/CyberdyneCC/ThermosIconGenerators !
c[22:55:22 INFO]: [Thermos] Refusing to lock affinity, disabled in cauldron.yml`
and on error.log file this is what i am getting
`
------------------------------------[ 08.12.2017 22:55:20 ]-----------------------------------
ChatControl 7.6.19 encountered a lPT6
Running 1.7.10-R0.1-SNAPSHOT and Java 1.8.0_151
Plugins: BungeeChatAPI v1.0.1, ChatControl v7.6.19
----------------------------------------------------------------------------------------------

More Information: 
ScriptEngine not found. Detected: scala.tools.nsc.interpreter.IMain$Factory@7c1f0381
lPT6Report / ScriptEngine not found. Detected: scala.tools.nsc.interpreter.IMain$Factory@7c1f0381
	 at me.kangarko.chatcontrol.final. .com8.const(SourceFile:20)
	 at me.kangarko.chatcontrol.final. .lpT7.<clinit>(SourceFile:33)
	 at me.kangarko.chatcontrol.final. .coM1$super.const(SourceFile:117)
	 at me.kangarko.chatcontrol.final. .coM1$super.const(SourceFile:110)
	 at me.kangarko.chatcontrol.final. .coM1.strictfp(SourceFile:51)
	 at me.kangarko.chatcontrol.final. .coM1.native(SourceFile:47)
	 at me.kangarko.chatcontrol.final. .Lpt2.onEnable(SourceFile:157)
	 at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316)
	 at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368)
	 at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410)
	 at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:438)
	 at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:372)
----------------------------------------------------------------------------------------------

`

**Comment by kangarko** [comment]
Hey,

your Cauldron version does not contain the script language that ChatControl uses to function. This is a major incompatibility that I unfortunately cannot fix. Try to reach out for an alternative release from such as https://yivesmirror.com/downloads/cauldron or https://sourceforge.net/projects/cauldron-unofficial/files/1.7.10/, but I cannot give you a warranty.
