### ISSUE TITLE
UltimateSurvivalGames signs error (?)

### ISSUE THREAD

**Issue by andris155** [kangarko/ChatControl-Pro#521]
```
------------------------------------[ 05.12.2017 20:44:23 ]-----------------------------------
ChatControl 7.6.17 encountered a lpT5
Running 1.12.2-R0.1-SNAPSHOT and Java 1.8.0_151
Plugins: redclockdetector v23, Vehicles v8.6, PlugMan v2.1.4, PlayerWarp v[v1.1 release], NametagEdit v4.1.7, MineMarket-Universal v2.94, EntityDetection v1.0 (build #12), Murder v10.1, ViaVersion v1.3.0, Stats v1.0.0, ViaBackwards v2.3.1, JukeBox v1.0, CoreProtect v2.14.2, LuckPerms v4.0.18, MineMarketAPI v1.0, OpenInv v3.3.2, CreativeNbtControl v1.9, XrayInformer v3.6.0, NoSpawnerChange v1.7, Heads v1.13.1, WorldBorder v1.8.7, Votifier v2.3.5, ProtocolLib v4.3.0, OpenTerrainGenerator v1.12 v7, VotingPlugin v5.11, FastAsyncWorldEdit v17.10.16-7a4b7be-936-17.0.19, SignEdit v1.7.0, TimeIsMoney v1.9.6.1, ConditionalCommands v1.4, Lottery v1.1.1, Kredites v1.0.0, mcMMO v1.5.09-SNAPSHOT, CS-CoreLib v1.5.16, Vault v1.6.1, FastAsyncVoxelSniper v17.10.16-7a4b7be-936-17.0.19, AuctionHouse v3.3, VoxelSniper v5.172.0-SNAPSHOT, MyCommand v5.3.4, WorldEdit v6.1.8-SNAPSHOT;cd4729f, Essentials v2.0.1-bSNAPSHOT, CompatNoCheatPlus v6.6.4-RC-sMD5NET-b88, GameBox v1.5.11, SafeTrade v1.0.15, Battleship v2.3.3, NoCheatPlus v3.15.2-SNAPSHOT-sMD5NET-b1113, GemCrush v2.3.1, EssentialsChat v2.0.1-bSNAPSHOT, Sudoku v1.1.1, PartyChatSpy v1.2, CookieClicker v1.1.1, PlotSquared v17.10.23-097159d-1924, WorldGuard v6.2.2-SNAPSHOT;1710-95b88ea, Minesweeper v2.3.1, WhacAMole v1.0.2, Slimefun v${project.version}, LockettePro v2.9.0, myZone v1.1.170, EssentialsGeoIP v2.0.1-bSNAPSHOT, RandomTeleport v1.7.4 (build #20), ConnectFour v1.2.1, PvPManager v3.7.5, EssentialsSpawn v2.0.1-bSNAPSHOT, WorldGuardExtraFlags v2.14.2, TitleManager v2.0.9, ExtraGear v1.1.1, RestrictedCreative v1.12.2, 2048 v1.3.1, The Multiverse-Core Plugin, Shopkeepers v1.83, SlimefunLuckyBlocks v1.1, ExoticGarden v1.6.3, CraftBook v3.9-SNAPSHOT-jenkins-CraftBook-191, ChestShop v3.8.13-SNAPSHOT (build #40), ElectricSpawners v1.0, MobArena v0.99, SkinsRestorer v13.1.4, Multiverse-NetherPortals v2.5.0-SNAPSHOT-b714, LimitedCreative v2.3-SNAPSHOT-256f165622, AreaShop v2.4.0, ChatControl v7.6.17, SurvivalGames vBeta 1.9.5, Paintball v1.3.9, MyPet v2.3.7
----------------------------------------------------------------------------------------------

More Information: 
Format '[Sign: SurvivalGames [-459, 4, 1815]] Ad_Info' doesn't exist in formatting.yml! Available: Private_Message_Receiver, Admin_Chat, Chat, Bungee_Chat, Private_Message_Sender, Spy_Chat, Ad_Info, Global_Chat
lpT5Report / Format '[Sign: SurvivalGames [-459, 4, 1815]] Ad_Info' doesn't exist in formatting.yml! Available: Private_Message_Receiver, Admin_Chat, Chat, Bungee_Chat, Private_Message_Sender, Spy_Chat, Ad_Info, Global_Chat
	 at me.kangarko.chatcontrol.final. .com8.const(SourceFile:20)
	 at me.kangarko.chatcontrol.final. .aM$throw.const(SourceFile:131)
	 at me.kangarko.chatcontrol.final. .aM.const(SourceFile:41)
	 at me.kangarko.chatcontrol.final. .aL.const(SourceFile:114)
	 at me.kangarko.chatcontrol.final. .aS.const(SourceFile:527)
	 at me.kangarko.chatcontrol.final. .aS.const(SourceFile:445)
	 at me.kangarko.chatcontrol.final. .aS.const(SourceFile:282)
	 at me.kangarko.chatcontrol.final. .aF.const(SourceFile:62)
	 at me.kangarko.chatcontrol.final. .aF.const(SourceFile:20)
	 at me.kangarko.chatcontrol.final. .Lpt1.execute(SourceFile:26)
	 at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74)
	 at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
	 at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:515)
	 at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:500)
----------------------------------------------------------------------------------------------
```

**Comment by kangarko** [comment]
Something's wrong with your format, you have:

'[Sign: SurvivalGames [-459, 4, 1815]] Ad_Info'

while it is only supposed to be

'Ad_Info'

Please correct this in formatting.yml.
