### ISSUE TITLE
Console error (Key 'xxxxx' is already in the map)

### ISSUE THREAD

**Issue by PatoTheBest** [kangarko/ChatControl-Pro#541]
Hello!

We are getting these errors (happens once in an hour, give or take).

```
[19:34:14] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to ChatControl v7.6.26
org.bukkit.event.EventException: null
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.12.2.jar:git-Paper-1269]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.2.jar:git-Paper-1269]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1269]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:515) [patched_1.12.2.jar:git-Paper-1269]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:500) [patched_1.12.2.jar:git-Paper-1269]
	at net.minecraft.server.v1_12_R1.PlayerList.onPlayerJoin(PlayerList.java:370) [patched_1.12.2.jar:git-Paper-1269]
	at net.minecraft.server.v1_12_R1.PlayerList.a(PlayerList.java:183) [patched_1.12.2.jar:git-Paper-1269]
	at protocolsupport.zplatform.impl.spigot.network.handler.SpigotLoginListenerPlay.joinGame(SpigotLoginListenerPlay.java:124) [ProtocolSupport.jar:?]
	at protocolsupport.protocol.packet.handler.AbstractLoginListenerPlay.tryJoin(AbstractLoginListenerPlay.java:131) [ProtocolSupport.jar:?]
	at protocolsupport.protocol.packet.handler.AbstractLoginListenerPlay.tick(AbstractLoginListenerPlay.java:93) [ProtocolSupport.jar:?]
	at protocolsupport.zplatform.impl.spigot.network.handler.SpigotLoginListenerPlay.e(SpigotLoginListenerPlay.java:70) [ProtocolSupport.jar:?]
	at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:254) [patched_1.12.2.jar:git-Paper-1269]
	at net.minecraft.server.v1_12_R1.ServerConnection.c(ServerConnection.java:150) [patched_1.12.2.jar:git-Paper-1269]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:940) [patched_1.12.2.jar:git-Paper-1269]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426) [patched_1.12.2.jar:git-Paper-1269]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.2.jar:git-Paper-1269]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1269]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: me.kangarko.chatcontrol.final. .lPT6: Report / Key 'Fletchp' is already in the map --> 'me.kangarko.chatcontrol.final. .bm@73049c12'
	at me.kangarko.chatcontrol.final. .com8.const(SourceFile:30) ~[ChatControlPro.jar:?]
	at me.kangarko.chatcontrol.final. .H.const(SourceFile:103) ~[ChatControlPro.jar:?]
	at me.kangarko.chatcontrol.ChatControl.const(SourceFile:506) ~[ChatControlPro.jar:?]
	at me.kangarko.chatcontrol.ChatControl.const(SourceFile:497) ~[ChatControlPro.jar:?]
	at me.kangarko.chatcontrol.final. .aF.onJoin(SourceFile:92) ~[ChatControlPro.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor169.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1269]
	... 17 more
```

And related

```
[19:54:22] [Async Chat Thread - #83/INFO]: [ChatControl] ChatControl 7.6.26 encountered a lPT6! Please check your error.log and report this issue with the information in that file.
[19:54:22] [Async Chat Thread - #83/ERROR]: Could not pass event AsyncPlayerChatEvent to ChatControl v7.6.26
me.kangarko.chatcontrol.final. .lPT6: Report / Key 'killuaYT' is already in the map --> 'me.kangarko.chatcontrol.final. .bm@b4c12b9'
	at me.kangarko.chatcontrol.final. .com8.const(SourceFile:30) ~[?:?]
	at me.kangarko.chatcontrol.final. .H.const(SourceFile:103) ~[?:?]
	at me.kangarko.chatcontrol.ChatControl.const(SourceFile:506) ~[?:?]
	at me.kangarko.chatcontrol.ChatControl.const(SourceFile:497) ~[?:?]
	at me.kangarko.chatcontrol.final. .aE.const(SourceFile:21) ~[?:?]
	at java.util.Collection.removeIf(Collection.java:414) ~[?:1.8.0_131]
	at me.kangarko.chatcontrol.final. .aE.const(SourceFile:21) ~[?:?]
	at me.kangarko.chatcontrol.final. .aE.const(SourceFile:10) ~[?:?]
	at me.kangarko.chatcontrol.final. .LPT6.execute(SourceFile:26) ~[?:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[patched_1.12.2.jar:git-Paper-1269]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1269]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:515) [patched_1.12.2.jar:git-Paper-1269]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:497) [patched_1.12.2.jar:git-Paper-1269]
	at net.minecraft.server.v1_12_R1.PlayerConnection.chat(PlayerConnection.java:1386) [patched_1.12.2.jar:git-Paper-1269]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1301) [patched_1.12.2.jar:git-Paper-1269]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:39) [patched_1.12.2.jar:git-Paper-1269]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
```

error.log

```
------------------------------------[ 22.12.2017 19:54:22 ]-----------------------------------
ChatControl 7.6.26 encountered a lPT6
Running 1.12.2-R0.1-SNAPSHOT and Java 1.8.0_131
Plugins: LuckPerms v4.0.49, Hub v1.0, ProtocolLib v4.4.0-SNAPSHOT-b389, ProtocolSupport v4.28, WorldEdit v6.1.8-SNAPSHOT;cd4729f, Essentials v2.0.1-b550, ChatControl v7.6.26, WorldGuard v6.2.2-SNAPSHOT;1709-f76259d
----------------------------------------------------------------------------------------------

More Information: 
Key 'killuaYT' is already in the map --> 'me.kangarko.chatcontrol.final. .bm@b4c12b9'
lPT6Report / Key 'killuaYT' is already in the map --> 'me.kangarko.chatcontrol.final. .bm@b4c12b9'
	 at me.kangarko.chatcontrol.final. .com8.const(SourceFile:30)
	 at me.kangarko.chatcontrol.final. .H.const(SourceFile:103)
	 at me.kangarko.chatcontrol.ChatControl.const(SourceFile:506)
	 at me.kangarko.chatcontrol.ChatControl.const(SourceFile:497)
	 at me.kangarko.chatcontrol.final. .aE.const(SourceFile:21)
	 at java.util.Collection.removeIf(Collection.java:414)
	 at me.kangarko.chatcontrol.final. .aE.const(SourceFile:21)
	 at me.kangarko.chatcontrol.final. .aE.const(SourceFile:10)
	 at me.kangarko.chatcontrol.final. .LPT6.execute(SourceFile:26)
	 at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74)
	 at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
	 at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:515)
	 at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:497)
----------------------------------------------------------------------------------------------
```

**Comment by kangarko** [comment]
Should be fixed now, please test using the next version.
