### ISSUE TITLE
IllegalArgumentException when using /tell

### ISSUE THREAD

**Issue by TufanMeric** [kangarko/ChatControl-Pro#543]
I just downloaded the plugin and didn't edit anything (except Private_Messages:Enabled: true), when i use /tell command i get this error

Error log:

```
------------------------------------[ 27.12.2017 13:28:09 ]-----------------------------------
ChatControl 7.6.26 encountered a IllegalArgumentException
Running 1.12-R0.1-SNAPSHOT and Java 1.8.0_151
Plugins: Skript v2.2-dev32c, Websend v2.5.7, ClearLag v2.9.7, MVdWPlaceholderAPI v2.3.1, PlayerStats v0.1, PermissionsEx v1.23.4, FeatherBoard v4.0.5, SpigotBlankPlugin v1.0, ViaVersion v1.3.0, Vault v1.6.1, BungeeTabListPlus v2.8.2, Essentials v2.0.1-b550, ProtocolLib v4.3.0, Citizens v2.0.22-SNAPSHOT (build 1487), FastAsyncWorldEdit v17.12.26-1cb4cb3-951-18.0.8, EssentialsProtect v2.0.1-b550, BossShop v2.7.5, EssentialsSpawn v2.0.1-b550, WorldEdit v6.1.7;dd00bb1, PlotSquared v3.5.0-SNAPSHOT-95f8aaa, The Multiverse-Core Plugin, WorldGuard v6.2.1;84bc322, Shopkeepers v1.83, MythicMobs v4.3.2-SNAPSHOT, Quests v3.1.6-b203, MineResetLite v0.4.7, AuthMe v5.4.0-b1877, HolographicDisplays v2.2.6, LiteBans v2.2.6, LegacyFactions v1.4.7, ChatControl v7.6.26
----------------------------------------------------------------------------------------------

More Information: 
Malformed JSON when sending message to tufanmeric
JSON: {"extra":[{"extra":[{"extra":[{"color":"gray","text":"? "},{"color":"gold","text":"from CONSOLE: "},{"color":"white","text":"a"}],"clickEvent":{"action":"suggest_command","value":"/r "},"hoverEvent":{"action":"show_text","value":[{"text":"     ~ Private Message ~     \nReceived 27.12.2017 13:28:09\nSender: CONSOLE\n\nClick for a reply."}]},"text":""}],"text":""}],"text":""}
IllegalArgumentExceptionNo enum constant net.md_5.bungee.api.ChatColor.WHİTE
	 at java.lang.Enum.valueOf(Unknown Source)
	 at net.md_5.bungee.api.ChatColor.valueOf(ChatColor.java:11)
	 at net.md_5.bungee.chat.BaseComponentSerializer.deserialize(BaseComponentSerializer.java:22)
	 at net.md_5.bungee.chat.TextComponentSerializer.deserialize(TextComponentSerializer.java:24)
	 at net.md_5.bungee.chat.TextComponentSerializer.deserialize(TextComponentSerializer.java:16)
	 at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
	 at com.google.gson.Gson.fromJson(Gson.java:887)
	 at com.google.gson.Gson.fromJson(Gson.java:952)
	 at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162)
	 at net.md_5.bungee.chat.ComponentSerializer.deserialize(ComponentSerializer.java:68)
	 at net.md_5.bungee.chat.ComponentSerializer.deserialize(ComponentSerializer.java:18)
	 at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
	 at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
	 at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72)
	 at com.google.gson.Gson.fromJson(Gson.java:887)
	 at com.google.gson.Gson.fromJson(Gson.java:952)
	 at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162)
	 at net.md_5.bungee.chat.BaseComponentSerializer.deserialize(BaseComponentSerializer.java:50)
	 at net.md_5.bungee.chat.TextComponentSerializer.deserialize(TextComponentSerializer.java:24)
	 at net.md_5.bungee.chat.TextComponentSerializer.deserialize(TextComponentSerializer.java:16)
	 at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
	 at com.google.gson.Gson.fromJson(Gson.java:887)
	 at com.google.gson.Gson.fromJson(Gson.java:952)
	 at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162)
	 at net.md_5.bungee.chat.ComponentSerializer.deserialize(ComponentSerializer.java:68)
	 at net.md_5.bungee.chat.ComponentSerializer.deserialize(ComponentSerializer.java:18)
	 at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
	 at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
	 at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72)
	 at com.google.gson.Gson.fromJson(Gson.java:887)
	 at com.google.gson.Gson.fromJson(Gson.java:952)
	 at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162)
	 at net.md_5.bungee.chat.BaseComponentSerializer.deserialize(BaseComponentSerializer.java:50)
	 at net.md_5.bungee.chat.TextComponentSerializer.deserialize(TextComponentSerializer.java:24)
	 at net.md_5.bungee.chat.TextComponentSerializer.deserialize(TextComponentSerializer.java:16)
	 at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
	 at com.google.gson.Gson.fromJson(Gson.java:887)
	 at com.google.gson.Gson.fromJson(Gson.java:952)
	 at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162)
	 at net.md_5.bungee.chat.ComponentSerializer.deserialize(ComponentSerializer.java:68)
	 at net.md_5.bungee.chat.ComponentSerializer.deserialize(ComponentSerializer.java:18)
	 at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
	 at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
	 at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72)
	 at com.google.gson.Gson.fromJson(Gson.java:887)
	 at com.google.gson.Gson.fromJson(Gson.java:952)
	 at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162)
	 at net.md_5.bungee.chat.BaseComponentSerializer.deserialize(BaseComponentSerializer.java:50)
	 at net.md_5.bungee.chat.TextComponentSerializer.deserialize(TextComponentSerializer.java:24)
	 at net.md_5.bungee.chat.TextComponentSerializer.deserialize(TextComponentSerializer.java:16)
	 at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
	 at com.google.gson.Gson.fromJson(Gson.java:887)
	 at com.google.gson.Gson.fromJson(Gson.java:952)
	 at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162)
	 at net.md_5.bungee.chat.ComponentSerializer.deserialize(ComponentSerializer.java:68)
	 at net.md_5.bungee.chat.ComponentSerializer.deserialize(ComponentSerializer.java:18)
	 at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
	 at com.google.gson.Gson.fromJson(Gson.java:887)
	 at com.google.gson.Gson.fromJson(Gson.java:852)
	 at com.google.gson.Gson.fromJson(Gson.java:801)
	 at com.google.gson.Gson.fromJson(Gson.java:773)
	 at net.md_5.bungee.chat.ComponentSerializer.parse(ComponentSerializer.java:38)
	 at me.kangarko.chatcontrol.final. .b.const(SourceFile:384)
	 at me.kangarko.chatcontrol.final. .cOm2.const(SourceFile:98)
	 at me.kangarko.chatcontrol.final. .LPt7.onCommand(SourceFile:53)
	 at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
	 at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
	 at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:641)
	 at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchServerCommand(CraftServer.java:627)
----------------------------------------------------------------------------------------------
```

**Comment by kangarko** [comment]
Please install BungeeChatAPI: https://www.spigotmc.org/resources/bungeechatapi.38379

**Comment by TufanMeric** [comment]
I tried using a clean paperspigot 1.12.2 setup and installed bungeechatapi but i still get the same error.

**Comment by kangarko** [comment]
I am sorry, but it seems that you have typed the letter i from your language  "WHİTE" and not "WHITE" (see the difference?) Please go through your formatting.yml and try to correct that. If unsure, you can just post me the file.

**Comment by TufanMeric** [comment]
Here's my formatting.yml: https://hastebin.com/ifihibaqoz.coffeescript
I didn't edit anything but group formats, i also tried default configurations with private messaging enabled but the same error occurs.

**Comment by TufanMeric** [comment]
I also get warnings on start/reload, chc tries to use 'ı' instead of 'i', which may be related to this issue.

> [18:54:59 INFO]: [Warning]: The death cause 'Entıty_Attack' is missing from your messages.yml. Ignoring..
> [18:54:59 INFO]: [Warning]: The death cause 'Projectıle' is missing from your messages.yml. Ignoring..
> [18:54:59 INFO]: [Warning]: The death cause 'Suffocatıon' is missing from your messages.yml. Ignoring..
> [18:54:59 INFO]: [Warning]: The death cause 'Fıre' is missing from your messages.yml. Ignoring..
> [18:54:59 INFO]: [Warning]: The death cause 'Fıre_Tıck' is missing from your messages.yml. Ignoring..
> [18:54:59 INFO]: [Warning]: The death cause 'Drownıng' is missing from your messages.yml. Ignoring..
> [18:54:59 INFO]: [Warning]: The death cause 'Block_Explosıon' is missing from your messages.yml. Ignoring..
> [18:54:59 INFO]: [Warning]: The death cause 'Entıty_Explosıon' is missing from your messages.yml. Ignoring..
> [18:54:59 INFO]: [Warning]: The death cause 'Voıd' is missing from your messages.yml. Ignoring..
> [18:54:59 INFO]: [Warning]: The death cause 'Lıghtnıng' is missing from your messages.yml. Ignoring..
> [18:54:59 INFO]: [Warning]: The death cause 'Suıcıde' is missing from your messages.yml. Ignoring..
> [18:54:59 INFO]: [Warning]: The death cause 'Starvatıon' is missing from your messages.yml. Ignoring..
> [18:54:59 INFO]: [Warning]: The death cause 'Magıc' is missing from your messages.yml. Ignoring..
> [18:54:59 INFO]: [Warning]: The death cause 'Wıther' is missing from your messages.yml. Ignoring..
> [18:54:59 INFO]: [Warning]: The death cause 'Fallıng_Block' is missing from your messages.yml. Ignoring..
> [18:54:59 INFO]: [Warning]: The death cause 'Crammıng' is missing from your messages.yml. Ignoring..

**Comment by kangarko** [comment]
Hey, it's caused by the letter I and possible others as well if you used them. You must only use ASCII English alphabet everyone except for the messages. So that would be Cramming instead of Crammıng, etc.

**Comment by TufanMeric** [comment]
The problem is that i didn't change anything. In config, crammıng is cramming but plugin tries to use crammıng instead of cramming. I just put the jar on plugins folder and these warnings came up. It also happens on FAWE (http://prntscr.com/hye7yg), i think my os language somehow causing the error.

**Comment by kangarko** [comment]
Yes, I am very sorry, this is coming from your OS and there is nothing I can do about it. You can try using Notepad++ or googling and asking out people from Turkey, perhaps they had a similar problem elsewhere and solved it.

**Comment by TufanMeric** [comment]
It's not about my IDE, i already use npp. There is nothing i can do about it. **Everything in chatcontrol folder is generated by plugin itself**, i didn't edit anything. It's not about me or plugin configuration, **the plugin tries to get WHİTE instead of WHITE**, Entıty instead of Entity. I'm not a java expert but i guess obfuscating the code causes the problem, it converts letters into something else (like hex or ascii values), they probably have the same values as İ, ı and my os traits them as in turkish q keyboard.

So i can't do anything to solve it, it's up to plugin itself.

**Comment by kangarko** [comment]
Try to re-download the plugin, remove ChatControl/ folder entirely and let it re-generate again.

If this won't help, try to use Notepad++ to open files, and use "Search and Replace" function to replace that letter to _I_ manually.

**Comment by TufanMeric** [comment]
I don't think you understand the problem.
As you can see, messages.xml is generated by the plugin: https://hastebin.com/ziyosunaqo.coffeescript
I get these warnings with this configuration, everything is fine and there's no ı, İ etc.

Config file doesn't matter, even if i change "i" to "ı", it will only hide warnings. I am unable to use the /tell command because the plugin tries to use ı,İ instead of i,I.

It is not about me or the files, its about plugin itself. I don't know how to explain better but the plugin tries to use these characters, configurations are just fine.

**Comment by kangarko** [comment]
I understand. The error remains and it is not coming from the files but from the internal methods. From that fact, if you look at the stack trace, ChatControl is among the last ones and the method that causes the error is at the top. 

That makes me believe it is related to a Spigot issue, and ChatControl is only un-hiding it because we use methods from Spigot. Make sure you have latest Spigot, or eventually try PaperSpigot (https://ci.destroystokyo.com/job/PaperSpigot/) instead. If that doesn't help, I am afraid you will have to make a JIRA issue for Spigot itself at https://hub.spigotmc.org/jira/secure/Dashboard.jspa

**Comment by TufanMeric** [comment]
Okay, i've created an issue on spigot but i still don't think it's about spigot because it only happens in chatcontrol and fawe. I hope i can make it work in an ENG vds.
