### ISSUE TITLE
Packet Error

### ISSUE THREAD

**Issue by x1p** [kangarko/ChatControl-Pro#560]
[12:17:24] [Craft Scheduler Thread - 553/ERROR]: [ChatControl] Unhandled exception occured in onPacketSending(PacketEvent) for ChatControl
java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.fastRemove(ArrayList.java:546) ~[?:1.8.0_131]
	at java.util.ArrayList.remove(ArrayList.java:529) ~[?:1.8.0_131]
	at me.kangarko.chatcontrol.hooks.class$3.onPacketSending(SourceFile:174) ~[ChatControl-7.6.28.jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) [ProtocolLib-4.3.0.jar:4.3.0]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) [ProtocolLib-4.3.0.jar:4.3.0]
	at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:588) [ProtocolLib-4.3.0.jar:4.3.0]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:564) [ProtocolLib-4.3.0.jar:4.3.0]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:338) [ProtocolLib-4.3.0.jar:4.3.0]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:298) [ProtocolLib-4.3.0.jar:4.3.0]
	at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:386) [ProtocolLib-4.3.0.jar:4.3.0]
	at com.comphenix.protocol.injector.netty.ChannelInjector.access$500(ChannelInjector.java:77) [ProtocolLib-4.3.0.jar:4.3.0]
	at com.comphenix.protocol.injector.netty.ChannelInjector$5.handleScheduled(ChannelInjector.java:352) [ProtocolLib-4.3.0.jar:4.3.0]
	at com.comphenix.protocol.injector.netty.ChannelInjector$5.onMessageScheduled(ChannelInjector.java:320) [ProtocolLib-4.3.0.jar:4.3.0]
	at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) [ProtocolLib-4.3.0.jar:4.3.0]
	at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) [ProtocolLib-4.3.0.jar:4.3.0]
	at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:194) [spigot-SuSE-1.12.2.jar:git-Spigot-549c1fa-8c37e2e]
	at net.minecraft.server.v1_12_R1.NetworkManager.sendPacket(NetworkManager.java:143) [spigot-SuSE-1.12.2.jar:git-Spigot-549c1fa-8c37e2e]
	at net.minecraft.server.v1_12_R1.PlayerConnection.sendPacket(PlayerConnection.java:1138) [spigot-SuSE-1.12.2.jar:git-Spigot-549c1fa-8c37e2e]
	at org.bukkit.craftbukkit.v1_12_R1.entity.CraftPlayer.sendRawMessage(CraftPlayer.java:157) [spigot-SuSE-1.12.2.jar:git-Spigot-549c1fa-8c37e2e]
	at org.bukkit.craftbukkit.v1_12_R1.entity.CraftPlayer.sendMessage(CraftPlayer.java:164) [spigot-SuSE-1.12.2.jar:git-Spigot-549c1fa-8c37e2e]
	at com.plotsquared.bukkit.object.BukkitPlayer.sendMessage(BukkitPlayer.java:115) [PlotSquared-Bukkit-%23543.jar:?]
	at com.intellectualcrafters.plot.util.MainUtil$2.run(MainUtil.java:643) [PlotSquared-Bukkit-%23543.jar:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) [spigot-SuSE-1.12.2.jar:git-Spigot-549c1fa-8c37e2e]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-SuSE-1.12.2.jar:git-Spigot-549c1fa-8c37e2e]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
[12:17:24] [Craft Scheduler Thread - 553/ERROR]: Parameters: 
  net.minecraft.server.v1_12_R1.PacketPlayOutChat@170907e1[
    a=TextComponent{text='', siblings=[TextComponent{text='[', siblings=[], style=Style{hasParent=true, color=§6, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}, TextComponent{text='CP', siblings=[], style=Style{hasParent=true, color=§e, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}, TextComponent{text='] ', siblings=[], style=Style{hasParent=true, color=§6, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}, TextComponent{text='You are lacking the permission node: ', siblings=[], style=Style{hasParent=true, color=§7, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}, TextComponent{text='plots.admin.interact.other', siblings=[], style=Style{hasParent=true, color=§6, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=ClickEvent{action=OPEN_URL, value='http://plots.admin.interact.other'}, hoverEvent=null, insertion=null}}], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}
    components=<null>
    b=SYSTEM
  ]

**Comment by x1p** [comment]
I suspect it has something to do with the rewriting of a message into a message with colors.
How must a rewrite message be formatted?
then rewrite &fUnknown command. Type "/help" for help.

**Comment by kangarko** [comment]
Thanks, fixed. Just a minor internal concurrency error.
