### ISSUE TITLE
Private Message JSON  NoSuchMethodError

### ISSUE THREAD

**Issue by Kingdingbat** [kangarko/ChatControl-Pro#562]
When a player sends a private message to another, this error comes up in the log.
I'll have to double check later today, but I think that the PM does not show up in the chat window. I'm not sure if that is correct. It does show up in the Achievement popup.
```
----------------------------------[ 09.01.2018 03:33:33 ]-----------------------------------
ChatControl 7.6.28 encountered a NoSuchMethodError
Running CraftBukkit 1.12.2-R0.1-SNAPSHOT and Java 1.8.0_151
Plugins: dynmap v2.5-Dev201706100405, WorldEdit v6.1.8-SNAPSHOT;cd4729f, BetterBeds v0.6.1-SNAPSHOT (build #4), BungeeChatAPI v1.0.1, PermissionsEx v1.23.4, TreeAssist v5.11.50, WorldBorder v1.8.7, WorldInfo v0.1 Alpha, Vault v1.6.6-b${env.TRAVIS_BUILD_NUMBER}, The Multiverse-Core Plugin, ProtocolLib v4.3.0, DiscordSRV v16.0, Essentials v2.0.1-b569, EssentialsChat v2.0.1-b569, EmojiChat v1.6, ChatControl v7.6.28, CraftBook v3.9-SNAPSHOT-jenkins-CraftBook-201, PerWorldInventory v1.11.1, Multiverse-Portals v2.5.0-b751
----------------------------------------------------------------------------------------------

More Information: 
Error printing JSON message, sending as plain.
Error: %error
NoSuchMethodError org.bukkit.entity.Player.spigot()Lorg/bukkit/entity/Player$Spigot;
	 at me.kangarko.chatcontrol.final. .a.const(SourceFile:1066)
	 at me.kangarko.chatcontrol.final. .a.const(SourceFile:1051)
	 at me.kangarko.chatcontrol.final. .c.const(SourceFile:392)
	 at me.kangarko.chatcontrol.final. .c.const(SourceFile:384)
	 at me.kangarko.chatcontrol.final. .nul.const(SourceFile:79)
	 at me.kangarko.chatcontrol.final. .LPt7.onCommand(SourceFile:53)
	 at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
	 at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:140)
	 at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:629)
---------------------------------------------------------------------------------------------
  
```

**Comment by kangarko** [comment]
I am sorry, ChatControl requires Spigot for 1.12, not CraftBukkit. Or download PaperSpigot.

**Comment by Kingdingbat** [comment]
Your plugin requirements section does not state that Spigot is required. You should fix that if you're going to use that as an excuse to not fix bugs.
