### ISSUE TITLE
NullPointerException on start-up.

### ISSUE THREAD

**Issue by mibby** [kangarko/ChatControl-Pro#563]
ChatControl v7.6.29
Paper dev 1298 (Spigot 1.12.2)

@kangarko Saw this error on start-up when restarting one of my servers. Occurs on every restart / start-up.
```
[16:45:46] [Server thread/INFO]: [ChatControl] Enabling ChatControl v7.6.29
[16:45:46] [Server thread/INFO]:   _____ _           _    _____            _             _  +
[16:45:46] [Server thread/INFO]:  / ____| |         | |  / ____|          | |           | |
[16:45:46] [Server thread/INFO]: | |    | |__   __ _| |_| |     ___  _ __ | |_ _ __ ___ | |
[16:45:46] [Server thread/INFO]: | |    | '_ \ / _` | __| |    / _ \| '_ \| __| '__/ _ \| |
[16:45:46] [Server thread/INFO]: | |____| | | | (_| | |_| |___| (_) | | | | |_| | | (_) | |
[16:45:46] [Server thread/INFO]:  \_____|_| |_|\__,_|\__|\_____\___/|_| |_|\__|_|  \___/|_|
[16:45:46] [Server thread/INFO]:  
[16:45:47] [Server thread/INFO]: Configuration loads..
[16:45:47] [Server thread/INFO]:  
[16:45:47] [Server thread/INFO]: Checking compatible plugins..
[16:45:47] [Server thread/INFO]: Rules loads now..
[16:45:47] [Server thread/INFO]: Listening starts..
[16:45:47] [Server thread/INFO]:  
[16:45:47] [Server thread/INFO]: BungeeCords enabled. See www.spigotmc.org/resources/13079
[16:45:47] [Server thread/INFO]: java.lang.NullPointerException
[16:45:47] [Server thread/INFO]: 	at me.kangarko.chatcontrol.final. .bm.const(SourceFile:33)
[16:45:47] [Server thread/INFO]: 	at me.kangarko.chatcontrol.ChatControl.native(SourceFile:158)
[16:45:47] [Server thread/INFO]: 	at me.kangarko.chatcontrol.final. .Lpt2.reloadWeak(SourceFile:240)
[16:45:47] [Server thread/INFO]: 	at me.kangarko.chatcontrol.final. .lpT7.const(SourceFile:78)
[16:45:47] [Server thread/INFO]: 	at me.kangarko.chatcontrol.final. .lpT7.const(SourceFile:74)
[16:45:47] [Server thread/INFO]: 	at me.kangarko.chatcontrol.final. .coM1$super.const(SourceFile:169)
[16:45:47] [Server thread/INFO]: 	at me.kangarko.chatcontrol.final. .coM1$super.const(SourceFile:162)
[16:45:47] [Server thread/INFO]: 	at me.kangarko.chatcontrol.final. .coM1.protected(SourceFile:60)
[16:45:47] [Server thread/INFO]: 	at me.kangarko.chatcontrol.final. .coM1.native(SourceFile:56)
[16:45:47] [Server thread/INFO]: 	at me.kangarko.chatcontrol.final. .Lpt2.onEnable(SourceFile:188)
[16:45:47] [Server thread/INFO]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[16:45:47] [Server thread/INFO]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316)
[16:45:47] [Server thread/INFO]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[16:45:47] [Server thread/INFO]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:383)
[16:45:47] [Server thread/INFO]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:332)
[16:45:47] [Server thread/INFO]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442)
[16:45:47] [Server thread/INFO]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403)
[16:45:47] [Server thread/INFO]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341)
[16:45:47] [Server thread/INFO]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:292)
[16:45:47] [Server thread/INFO]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616)
[16:45:47] [Server thread/INFO]: 	at java.lang.Thread.run(Thread.java:748)
[16:45:47] [Server thread/INFO]:   _   _                       _ 
[16:45:47] [Server thread/INFO]:   | | | | ___   ___  _ __  ___| |
[16:45:47] [Server thread/INFO]:   | |_| |/ _ \ / _ \| '_ \/ __| |
[16:45:47] [Server thread/INFO]:   |  _  | (_) | (_) | |_) \__ \_|
[16:45:47] [Server thread/INFO]:   |_| |_|\___/ \___/| .__/|___(_)
[16:45:47] [Server thread/INFO]:                     |_|          
[16:45:47] [Server thread/INFO]: !-----------------------------------------------------!
[16:45:47] [Server thread/INFO]:  Error loading ChatControl v7.6.29, plugin is disabled!
[16:45:47] [Server thread/INFO]:  Running on 1.12.2-R0.1-SNAPSHOT (v1_12_R1) & Java 1.8.0_152
[16:45:47] [Server thread/INFO]: !-----------------------------------------------------!
[16:45:47] [Server thread/INFO]:  Error: Unable to get the error message, search above.
[16:45:47] [Server thread/INFO]: !-----------------------------------------------------!
```
  

---

On my main server, it seems to start-up fine. Perhaps it breaks on the BungeeCord check?
```
[16:41:22] [Server thread/INFO]: [ChatControl] Enabling ChatControl v7.6.29
[16:41:23] [Server thread/INFO]:   _____ _           _    _____            _             _  +
[16:41:23] [Server thread/INFO]:  / ____| |         | |  / ____|          | |           | |
[16:41:23] [Server thread/INFO]: | |    | |__   __ _| |_| |     ___  _ __ | |_ _ __ ___ | |
[16:41:23] [Server thread/INFO]: | |    | '_ \ / _` | __| |    / _ \| '_ \| __| '__/ _ \| |
[16:41:23] [Server thread/INFO]: | |____| | | | (_| | |_| |___| (_) | | | | |_| | | (_) | |
[16:41:23] [Server thread/INFO]:  \_____|_| |_|\__,_|\__|\_____\___/|_| |_|\__|_|  \___/|_|
[16:41:23] [Server thread/INFO]:  
[16:41:23] [Server thread/INFO]: Configuration loads..
[16:41:23] [Server thread/INFO]:  
[16:41:23] [Server thread/INFO]: Checking compatible plugins..
[16:41:23] [Server thread/INFO]: Rules loads now..
[16:41:23] [Server thread/INFO]: Listening starts..
[16:41:23] [Server thread/INFO]:  
[16:41:23] [Server thread/INFO]: BungeeCords enabled. See www.spigotmc.org/resources/13079
[16:41:23] [Server thread/INFO]:  
[16:41:23] [Server thread/INFO]: Fire in the hole! (took 243 ms)
[16:41:23] [Server thread/INFO]: ______________________________________________________________
[16:41:23] [Server thread/INFO]:  
```

**Comment by kangarko** [comment]
I apology. This was an error related to empty data.db. Please test on the next version.
