### ISSUE TITLE
Issue on startup

### ISSUE THREAD

**Issue by Venlious** [kangarko/ChatControl-Pro#565]
Before I start, I should mention I did attempt to receive support on your Discord and FrankHeijden was kind enough to run a few tests with me. He was unable to reproduce the issue, but we did try a few things to see if we could get it working again.

The plugin suddenly stopped working after an automatic scheduled server restart and threw errors in the console on start-up. Attempting to fix it with yet another restart resulted in nothing good. Attempting to clear all configs and do a fresh install did no good. Attempting to start just the plugin with a fresh install and no other plugins did no good.

https://pastebin.com/jbU9LTvk
https://pastebin.com/U7GsuPdM

I should mention that my test server had a much earlier version of ChatControl running (7.4.7) which coincidentally did happen to work, but is of course many features and bugfixes behind. I am currently running this on my server as backup.

**Comment by braceyourself07** [comment]
I am having the exact same problem after an automated 24h server restart. Interestingly it is only doing it on one dedicated server so I'm guessing it has something to do with the server environment, however all of my dedis are set up the same way.

**Comment by Venlious** [comment]
If it helps, I'd like to add that my server is also running on a dedicated server.

**Comment by andris155** [comment]
Same problem.

**Comment by andris155** [comment]
```
[14:53:06] [Server thread/INFO]: Starting minecraft server version 1.12.2
[14:53:06] [Server thread/INFO]: Loading properties
[14:53:06] [Server thread/INFO]: Default game type: SURVIVAL
[14:53:06] [Server thread/INFO]: This server is running Paper version git-Paper-1293 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
[14:53:06] [Server thread/INFO]: Server Ping Player Sample Count: 12
[14:53:06] [Server thread/INFO]: Using 4 threads for Netty based IO
[14:53:06] [Server thread/INFO]: Debug logging is disabled
[14:53:06] [Server thread/INFO]: Generating keypair
[14:53:06] [Server thread/INFO]: Starting Minecraft server on 127.0.0.1:26535
[14:53:06] [Server thread/INFO]: Using epoll channel type
[14:53:06] [Server thread/INFO]: Set PluginClassLoader as parallel capable
[14:53:07] [Server thread/ERROR]: Could not load 'plugins/ChatControl.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.ClassFormatError: Illegal UTF8 string in constant pool in class file me/kangarko/chatcontrol/ChatControl
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[patched_1.12.2.jar:git-Paper-1293]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[patched_1.12.2.jar:git-Paper-1293]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [patched_1.12.2.jar:git-Paper-1293]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:306) [patched_1.12.2.jar:git-Paper-1293]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:225) [patched_1.12.2.jar:git-Paper-1293]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) [patched_1.12.2.jar:git-Paper-1293]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: java.lang.ClassFormatError: Illegal UTF8 string in constant pool in class file me/kangarko/chatcontrol/ChatControl
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_151]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763) ~[?:1.8.0_151]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_151]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:146) ~[patched_1.12.2.jar:git-Paper-1293]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:104) ~[patched_1.12.2.jar:git-Paper-1293]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_151]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_151]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_151]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_151]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:82) ~[patched_1.12.2.jar:git-Paper-1293]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:127) ~[patched_1.12.2.jar:git-Paper-1293]
	... 6 more
```

**Comment by kangarko** [comment]
@Venlious 
@braceyourself07 
@andris155 

This issue is unrelated to your server set-up, but may happen in a few scenarios:
- a leaked version of the product appears to share some of the verification data plugin is bound with,
- you re-distributed the plugin or used too many different computers so a antileak protection was triggered,
- your IP address appeared in a public spam database,
- some unspecific issue (?)

First of all, I apology for the inconvenience. To ensure you that the plugin is safe to run I will mention that we do not require internet access, at all, and no personal data is used to check for piracy.

Either way, please send me a private message on Spigot, so I can see and verify your username and fix it quickly.
