### ISSUE TITLE
Updated spigot.jar and chc

### ISSUE THREAD

**Issue by DeusNinja** [kangarko/ChatControl-Pro#605]
I do not use the channel features and just saw this pop up in my console, am I improperly going about not using the channels?

[20:20:54 INFO]: [ChatControl] *-----------------------------------------------*
[20:20:54 INFO]: [ChatControl]  Failed to load Channels from MySQL
[20:20:54 INFO]: [ChatControl] *-----------------------------------------------*
[20:20:54 INFO]: [ChatControl]  Failed to load Channels from MySQL
[20:20:54 INFO]: [ChatControl] *-----------------------------------------------*
[20:20:54 INFO]: [ChatControl] *-----------------------------------------------*
[20:20:54 INFO]: [ChatControl] ChatControl 7.7.0-BETA encountered a ArrayIndexOutOfBoundsException! Please check your error.log and report this issue with the information in that file.
[20:20:54 INFO]: [ChatControl] ChatControl 7.7.0-BETA encountered a ArrayIndexOutOfBoundsException! Please check your error.log and report this issue with the information in that file.
[20:20:54 WARN]: java.lang.RuntimeException: java.lang.ArrayIndexOutOfBoundsException: 137
[20:20:54 WARN]:        at me.kangarko.chatcontrol.final. .LPT8.native(SourceFile:548)
[20:20:54 WARN]:        at me.kangarko.chatcontrol.final. .aT.const(SourceFile:164)
[20:20:54 WARN]:        at me.kangarko.chatcontrol.final. .aT.const(SourceFile:127)
[20:20:54 WARN]:        at me.kangarko.chatcontrol.final. .aT.const(SourceFile:90)
[20:20:54 WARN]:        at me.kangarko.chatcontrol.final. .aJ.const(SourceFile:97)
[20:20:54 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71)
[20:20:54 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[20:20:54 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[20:20:54 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[20:20:54 WARN]:        at java.lang.Thread.run(Thread.java:748)
[20:20:54 WARN]: Caused by: java.lang.ArrayIndexOutOfBoundsException: 137
[20:20:54 WARN]:        at com.mysql.jdbc.Buffer.readFieldLength(Buffer.java:285)
[20:20:54 WARN]:        at com.mysql.jdbc.BufferRow.isNull(BufferRow.java:607)
[20:20:54 WARN]:        at com.mysql.jdbc.ResultSetImpl.getStringInternal(ResultSetImpl.java:5227)
[20:20:54 WARN]:        at com.mysql.jdbc.ResultSetImpl.getString(ResultSetImpl.java:5138)
[20:20:54 WARN]:        at com.mysql.jdbc.ResultSetImpl.getString(ResultSetImpl.java:5177)
[20:20:54 WARN]:        at me.kangarko.chatcontrol.final. .aT.const(SourceFile:153)
[20:20:54 WARN]:        ... 8 more
[20:20:54 WARN]: java.lang.RuntimeException: java.lang.ArrayIndexOutOfBoundsException: 137
[20:20:54 WARN]:        at me.kangarko.chatcontrol.final. .LPT8.native(SourceFile:548)
[20:20:54 WARN]:        at me.kangarko.chatcontrol.final. .aT.const(SourceFile:164)
[20:20:54 WARN]:        at me.kangarko.chatcontrol.final. .aT.const(SourceFile:127)
[20:20:54 WARN]:        at me.kangarko.chatcontrol.final. .aT.const(SourceFile:90)
[20:20:54 WARN]:        at me.kangarko.chatcontrol.final. .aJ.const(SourceFile:97)
[20:20:54 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71)
[20:20:54 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[20:20:54 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[20:20:54 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[20:20:54 WARN]:        at java.lang.Thread.run(Thread.java:748)
[20:20:54 WARN]: Caused by: java.lang.ArrayIndexOutOfBoundsException: 137
[20:20:54 WARN]:        at com.mysql.jdbc.Buffer.readFieldLength(Buffer.java:285)
[20:20:54 WARN]:        at com.mysql.jdbc.BufferRow.isNull(BufferRow.java:607)
[20:20:54 WARN]:        at com.mysql.jdbc.ResultSetImpl.getStringInternal(ResultSetImpl.java:5227)
[20:20:54 WARN]:        at com.mysql.jdbc.ResultSetImpl.getString(ResultSetImpl.java:5138)
[20:20:54 WARN]:        at com.mysql.jdbc.ResultSetImpl.getString(ResultSetImpl.java:5177)
[20:20:54 WARN]:        at me.kangarko.chatcontrol.final. .aT.const(SourceFile:153)
[20:20:54 WARN]:        ... 8 more

**Comment by DeusNinja** [comment]
7.7.0-BETA beta version
with  version 1.12.2-R0.1-SNAPSHOT of spigot

**Comment by kangarko** [comment]
It seems there is a problem with your MySQL database instead. You can try deleting ChatControl's table (player's information such as their saved channels, ignore, spy will be reset).

**Comment by DeusNinja** [comment]
Currently those features are not in use, I use a different plugin for command spy and it handles all of our social commands. If I clear the entire mysql database for chc will there be any negative effects other than every players options with chc being reset to default?

**Comment by kangarko** [comment]
The following information will be removed: players' history and preferences of: channel, warning points, ignored players in /ignore, ignored rules sets /chc ignore, /togglepm preference, /spy mode and chat mode - from /chc ach|g switch command. Those are not critical and yes, may be removed.

**Comment by kangarko** [comment]
Closing, assuming fixed.
