### ISSUE TITLE
error thrown on message from discord with LuckPerms 4.1.1

### ISSUE THREAD

**Issue by StrangerFive** [kangarko/ChatControl-Pro#609]
Not sure if the problem's with LuckPerms 4.1.1 or DiscordSRV 16.0 or ChatControl-Pro 7.6.34, but getting the below error a lot after upgrading LuckPerms to 4.1.1. Backed it down to LP 4.0.74 and it goes away.

Let me know if I should open an issue with someone else instead.  Thanks.

[16:49:11] [JDA MainWS-ReadThread/INFO]: [DiscordSRV] Chat: [Discord | Co-owner] Ian012345 > and...
[16:49:22] [JDA MainWS-ReadThread/ERROR]: [DiscordSRV] DiscordSRV API Listener me.kangarko.chatcontrol.hooks.DiscordHookListener threw an error:
java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor101.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at github.scarsz.discordsrv.api.ApiManager.callEvent(ApiManager.java:105)
	at github.scarsz.discordsrv.listeners.DiscordChatListener.onGuildMessageReceived(DiscordChatListener.java:101)
	at github.scarsz.discordsrv.dependencies.jda.core.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:372)
	at github.scarsz.discordsrv.dependencies.jda.core.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:84)
	at github.scarsz.discordsrv.dependencies.jda.core.handle.MessageCreateHandler.handleDefaultMessage(MessageCreateHandler.java:96)
	at github.scarsz.discordsrv.dependencies.jda.core.handle.MessageCreateHandler.handleInternally(MessageCreateHandler.java:49)
	at github.scarsz.discordsrv.dependencies.jda.core.handle.SocketHandler.handle(SocketHandler.java:37)
	at github.scarsz.discordsrv.dependencies.jda.core.requests.WebSocketClient.handleEvent(WebSocketClient.java:968)
	at github.scarsz.discordsrv.dependencies.jda.core.requests.WebSocketClient.onTextMessage(WebSocketClient.java:661)
	at com.neovisionaries.ws.client.ListenerManager.callOnTextMessage(ListenerManager.java:352)
	at com.neovisionaries.ws.client.ReadingThread.callOnTextMessage(ReadingThread.java:260)
	at com.neovisionaries.ws.client.ReadingThread.callOnTextMessage(ReadingThread.java:238)
	at com.neovisionaries.ws.client.ReadingThread.handleTextFrame(ReadingThread.java:963)
	at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:746)
	at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108)
	at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64)
	at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45)
Caused by: java.lang.NullPointerException: uuid
	at java.util.Objects.requireNonNull(Objects.java:228)
	at me.lucko.luckperms.bukkit.vault.VaultPermissionHook.hasPermission(VaultPermissionHook.java:120)
	at me.lucko.luckperms.bukkit.vault.AbstractVaultPermission.has(AbstractVaultPermission.java:132)
	at me.kangarko.chatcontrol.final. .lpT5.const(SourceFile:1064)
	at me.kangarko.chatcontrol.final. .com9.const(SourceFile:460)
	at me.kangarko.chatcontrol.final. .LpT5.hasPermission(SourceFile:42)
	at me.kangarko.chatcontrol.final. .lPt7.const(SourceFile:403)
	at me.kangarko.chatcontrol.final. .aE.const(SourceFile:164)
	at me.kangarko.chatcontrol.final. .aN.const(SourceFile:117)
	at me.kangarko.chatcontrol.final. .aN.const(SourceFile:107)
	at me.kangarko.chatcontrol.final. .throw.sendDiscordMessage(SourceFile:295)
	at me.kangarko.chatcontrol.hooks.DiscordHookListener.discordMessageReceived(SourceFile:61)
	... 20 more

**Comment by kangarko** [comment]
According to these lines, the bug is in LuckPerms. Please report it to that developer.

````
Caused by: java.lang.NullPointerException: uuid
	at java.util.Objects.requireNonNull(Objects.java:228)
	at me.lucko.luckperms.bukkit.vault.VaultPermissionHook.hasPermission(VaultPermissionHook.java:120)
	at me.lucko.luckperms.bukkit.vault.AbstractVaultPermission.has(AbstractVaultPermission.java:132)
````

**Comment by kangarko** [comment]
Correction: I attempted to include a workaround in ChatControl. You should still report it to devs of LuckPerms but also update your CHC version and re-check.

**Comment by StrangerFive** [comment]
Yeah, your workaround didn't work.  Still happening with cc pro 7.7.3.  Filed issue with LP @ https://github.com/lucko/LuckPerms/issues/806
