### ISSUE TITLE
error on first join after server restart

### ISSUE THREAD

**Issue by kikelkik** [kangarko/ChatControl-Pro#616]
When a player joins the server the first time after a server restart, the plugin throws the following error:

`[13:15:34] [User Authenticator #1/INFO]: UUID of player kikelkik is 9a67a540-fbdb-4814-a7f5-e1835a055d1a
[13:15:35] [Server thread/ERROR]: Could not pass event PlayerLoginEvent to ChatControl v7.7.3
org.bukkit.event.EventException: null
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.12.2.jar:git-Paper-1329]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.2.jar:git-Paper-1329]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1329]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:515) [patched_1.12.2.jar:git-Paper-1329]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:500) [patched_1.12.2.jar:git-Paper-1329]
	at net.minecraft.server.v1_12_R1.PlayerList.attemptLogin(PlayerList.java:565) [patched_1.12.2.jar:git-Paper-1329]
	at net.minecraft.server.v1_12_R1.LoginListener.b(LoginListener.java:149) [patched_1.12.2.jar:git-Paper-1329]
	at net.minecraft.server.v1_12_R1.LoginListener.e(LoginListener.java:65) [patched_1.12.2.jar:git-Paper-1329]
	at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:254) [patched_1.12.2.jar:git-Paper-1329]
	at net.minecraft.server.v1_12_R1.ServerConnection.c(ServerConnection.java:150) [patched_1.12.2.jar:git-Paper-1329]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:941) [patched_1.12.2.jar:git-Paper-1329]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426) [patched_1.12.2.jar:git-Paper-1329]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.2.jar:git-Paper-1329]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1329]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
Caused by: java.lang.NullPointerException: uuid
	at java.util.Objects.requireNonNull(Unknown Source) ~[?:1.8.0_131]
	at me.lucko.luckperms.bukkit.vault.VaultPermissionHook.hasPermission(VaultPermissionHook.java:120) ~[LuckPerms.jar:?]
	at me.lucko.luckperms.bukkit.vault.AbstractVaultPermission.has(AbstractVaultPermission.java:132) ~[LuckPerms.jar:?]
	at me.kangarko.chatcontrol.final. .lPT7.const(SourceFile:1065) ~[ChatControl.jar:?]
	at me.kangarko.chatcontrol.final. .lPt6.const(SourceFile:447) ~[ChatControl.jar:?]
	at me.kangarko.chatcontrol.final. .LPT8.const(SourceFile:400) ~[ChatControl.jar:?]
	at me.kangarko.chatcontrol.super.native(SourceFile:204) ~[ChatControl.jar:?]
	at me.kangarko.chatcontrol.super.strictfp(SourceFile:131) ~[ChatControl.jar:?]
	at me.kangarko.chatcontrol.super.const(SourceFile:104) ~[ChatControl.jar:?]
	at me.kangarko.chatcontrol.ChatControl.const(SourceFile:497) ~[ChatControl.jar:?]
	at me.kangarko.chatcontrol.ChatControl.const(SourceFile:485) ~[ChatControl.jar:?]
	at me.kangarko.chatcontrol.final. .aJ.onPreLogin(SourceFile:66) ~[ChatControl.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor273.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1329]
	... 14 more `

If the player logs in the second time, everything's fine.

**Comment by kangarko** [comment]
Thanks, fixed.
