### ISSUE TITLE
Error PaperSpigot

### ISSUE THREAD

**Issue by TopCZE** [kangarko/ChatControl-Pro#651]
Could not pass event AsyncPlayerChatEvent to ChatControl v7.8.1
java.lang.NullPointerException: null
at me.kangarko.chatcontrol.final. .CoM3.native(SourceFile:484) ~[ChatControl-7.8.1.jar:?]
at me.kangarko.chatcontrol.final. .CoM3.strictfp(SourceFile:451) ~[ChatControl-7.8.1.jar:?]
at me.kangarko.chatcontrol.final. .bF.native(SourceFile:242) ~[ChatControl-7.8.1.jar:?]
at me.kangarko.chatcontrol.final. .bm.const(SourceFile:762) ~[ChatControl-7.8.1.jar:?]
at me.kangarko.chatcontrol.final. .bm.const(SourceFile:335) ~[ChatControl-7.8.1.jar:?]
at me.kangarko.chatcontrol.final. .bm.const(SourceFile:286) ~[ChatControl-7.8.1.jar:?]
at me.kangarko.chatcontrol.final. .bb.const(SourceFile:196) ~[ChatControl-7.8.1.jar:?]
at me.kangarko.chatcontrol.final. .bb.const(SourceFile:48) ~[ChatControl-7.8.1.jar:?]
at me.kangarko.chatcontrol.final. .bb.const(SourceFile:30) ~[ChatControl-7.8.1.jar:?]
at me.kangarko.chatcontrol.final. .lpt1.execute(SourceFile:26) ~[ChatControl-7.8.1.jar:?]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[minecraft_server.jar:git-Paper-1353]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[minecraft_server.jar:git-Paper-1353]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:515) [minecraft_server.jar:git-Paper-1353]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:497) [minecraft_server.jar:git-Paper-1353]
at net.minecraft.server.v1_12_R1.PlayerConnection.chat(PlayerConnection.java:1387) [minecraft_server.jar:git-Paper-1353]
at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1302) [minecraft_server.jar:git-Paper-1353]
at net.minecraft.server.v1_12_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:39) [minecraft_server.jar:git-Paper-1353]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_112]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_112]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_112]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_112]

FakeLeave command:

[14:26:00 WARN]: java.lang.NullPointerException
[14:26:00 WARN]: at me.kangarko.chatcontrol.final. .CoM3.native(SourceFile:484)
[14:26:00 WARN]: at me.kangarko.chatcontrol.final. .CoM3.volatile(SourceFile:466)
[14:26:00 WARN]: at me.kangarko.chatcontrol.final. .CoM3.const(SourceFile:247)
[14:26:00 WARN]: at me.kangarko.chatcontrol.final. .CoM3.strictfp(SourceFile:238)
[14:26:00 WARN]: at me.kangarko.chatcontrol.final. .CoM3.const(SourceFile:234)
[14:26:00 WARN]: at me.kangarko.chatcontrol.final. .case.const(SourceFile:167)
[14:26:00 WARN]: at me.kangarko.chatcontrol.final. .auX.onCommand(SourceFile:57)
[14:26:00 WARN]: at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[14:26:00 WARN]: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151)
[14:26:00 WARN]: at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:677)
[14:26:00 WARN]: at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1472)
[14:26:00 WARN]: at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1277)
[14:26:00 WARN]: at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[14:26:00 WARN]: at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)
[14:26:00 WARN]: at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14)
[14:26:00 WARN]: at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[14:26:00 WARN]: at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[14:26:00 WARN]: at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[14:26:00 WARN]: at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:843)
[14:26:00 WARN]: at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426)
[14:26:00 WARN]: at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767)
[14:26:00 WARN]: at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665)
[14:26:00 WARN]: at java.lang.Thread.run(Thread.java:745)

**Comment by kangarko** [comment]
Please contact me on Spigot.
