### ISSUE TITLE
Build 7.8.2 does not parse the YML that worked in 7.8.1

### ISSUE THREAD

**Issue by malonnnn** [kangarko/ChatControl-Pro#659]
Edit: rolling back to 7.8.1 fixes the issue

I get the following error:

```
1036 [17:56:38] [Server thread/INFO]: [ChatControl] Enabling ChatControl v7.8.2
1037 [17:56:38] [Server thread/INFO]:   _____ _           _    _____            _             _  +
1038 [17:56:38] [Server thread/INFO]:  / ____| |         | |  / ____|          | |           | |
1039 [17:56:38] [Server thread/INFO]: | |    | |__   __ _| |_| |     ___  _ __ | |_ _ __ ___ | |
1040 [17:56:38] [Server thread/INFO]: | |    | '_ \ / _` | __| |    / _ \| '_ \| __| '__/ _ \| |
1041 [17:56:38] [Server thread/INFO]: | |____| | | | (_| | |_| |___| (_) | | | | |_| | | (_) | |
1042 [17:56:38] [Server thread/INFO]:  \_____|_| |_|\__,_|\__|\_____\___/|_| |_|\__|_|  \___/|_|
1043 [17:56:38] [Server thread/INFO]:
1044 [17:56:39] [Server thread/INFO]: ChatControl 7.8.2 encountered a com9! Please check your error.log and report this issue with the information in that file.
1045 [17:56:39] [Server thread/INFO]: *-----------------------------------------------*
1046 [17:56:39] [Server thread/INFO]:  Error loading configuration in channels.yml!
1047 [17:56:39] [Server thread/INFO]:  Problematic section: null
1048 [17:56:39] [Server thread/INFO]:  Problem: me.kangarko.chatcontrol.final. .com9: Report / Null int[] field 'a'  in ag
1049 [17:56:39] [Server thread/INFO]:  Plugin is now disabled.
1050 [17:56:39] [Server thread/INFO]: *-----------------------------------------------*
1051 [17:56:39] [Server thread/INFO]: [ChatControl] Disabling ChatControl v7.8.2
1052 [17:56:39] [Server thread/INFO]: me.kangarko.chatcontrol.final. .com9: Report / Null int[] field 'a'  in ag
1053 [17:56:39] [Server thread/INFO]:        at me.kangarko.chatcontrol.final. .lpt7.const(SourceFile:20)
1054 [17:56:39] [Server thread/INFO]:        at me.kangarko.chatcontrol.final. .ag.native(SourceFile:152)
1055 [17:56:39] [Server thread/INFO]:        at me.kangarko.chatcontrol.final. .ag.const(SourceFile:138)
1056 [17:56:39] [Server thread/INFO]:        at me.kangarko.chatcontrol.final. .ag.strictfp(SourceFile:85)
1057 [17:56:39] [Server thread/INFO]:        at me.kangarko.chatcontrol.final. .ag$1.const(SourceFile:37)
1058 [17:56:39] [Server thread/INFO]:        at me.kangarko.chatcontrol.final. .af.native(SourceFile:128)
1059 [17:56:39] [Server thread/INFO]:        at me.kangarko.chatcontrol.final. .ag.native(SourceFile:165)
1060 [17:56:39] [Server thread/INFO]:        at me.kangarko.chatcontrol.final. .by.native(SourceFile:68)
1061 [17:56:39] [Server thread/INFO]:        at me.kangarko.chatcontrol.final. .ag.const(SourceFile:63)
1062 [17:56:39] [Server thread/INFO]:        at me.kangarko.chatcontrol.final. .coM4.onEnable(SourceFile:164)
1063 [17:56:39] [Server thread/INFO]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
1064 [17:56:39] [Server thread/INFO]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316)
1065 [17:56:39] [Server thread/INFO]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
1066 [17:56:39] [Server thread/INFO]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:387)
1067 [17:56:39] [Server thread/INFO]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:336)
1068 [17:56:39] [Server thread/INFO]:        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442)
1069 [17:56:39] [Server thread/INFO]:        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403)
1070 [17:56:39] [Server thread/INFO]:        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341)
1071 [17:56:39] [Server thread/INFO]:        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:292)
1072 [17:56:39] [Server thread/INFO]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616)
1073 [17:56:39] [Server thread/INFO]:        at java.lang.Thread.run(Thread.java:748)
1074 [17:56:39] [Server thread/INFO]:   _   _                       _
1075 [17:56:39] [Server thread/INFO]:   | | | | ___   ___  _ __  ___| |
1076 [17:56:39] [Server thread/INFO]:   | |_| |/ _ \ / _ \| '_ \/ __| |
1077 [17:56:39] [Server thread/INFO]:   |  _  | (_) | (_) | |_) \__ \_|
1078 [17:56:39] [Server thread/INFO]:   |_| |_|\___/ \___/| .__/|___(_)
1079 [17:56:39] [Server thread/INFO]:                     |_|
1080 [17:56:39] [Server thread/INFO]: !-----------------------------------------------------!
1081 [17:56:39] [Server thread/INFO]:  Error loading ChatControl v7.8.2, plugin is disabled!
1082 [17:56:39] [Server thread/INFO]:  Running on 1.12.2-R0.1-SNAPSHOT (v1_12_R1) & Java 1.8.0_161
1083 [17:56:39] [Server thread/INFO]: !-----------------------------------------------------!
1084 [17:56:39] [Server thread/INFO]:  Error: Report / Null int[] field 'a'  in ag
1085 [17:56:39] [Server thread/INFO]: !-----------------------------------------------------!

```

My Configs
https://github.com/malonnnn/ServerConfig2/tree/master/ChatControl

**Comment by kangarko** [comment]
Please see https://github.com/kangarko/ChatControl-Pro/issues/662. Thank you.

**Comment by malonnnn** [comment]
but but mine was posted first :P

lol jk thanks for the fix
