### ISSUE TITLE
Error with Build 7.8.2

### ISSUE THREAD

**Issue by Qinak** [kangarko/ChatControl-Pro#660]
Updated to latest and got this error when earlier version worked fine.

```
------------------------------------[ 22.03.2018 03:38:59 ]-----------------------------------
ChatControl 7.8.2 encountered a com9
Running CraftBukkit 1.12.2-R0.1-SNAPSHOT and Java 1.8.0_91
Plugins: ProtocolLib v4.4.0-SNAPSHOT-b390, ChatControl v7.8.2
----------------------------------------------------------------------------------------------

More Information: 
Null int[] field 'a'  in ag
com9 Report / Null int[] field 'a'  in ag
	 at me.kangarko.chatcontrol.final. .lpt7.const(SourceFile:20)
	 at me.kangarko.chatcontrol.final. .ag.native(SourceFile:152)
	 at me.kangarko.chatcontrol.final. .ag.const(SourceFile:138)
	 at me.kangarko.chatcontrol.final. .ag.strictfp(SourceFile:85)
	 at me.kangarko.chatcontrol.final. .ag$1.const(SourceFile:37)
	 at me.kangarko.chatcontrol.final. .af.native(SourceFile:128)
	 at me.kangarko.chatcontrol.final. .ag.native(SourceFile:165)
	 at me.kangarko.chatcontrol.final. .by.native(SourceFile:68)
	 at me.kangarko.chatcontrol.final. .ag.const(SourceFile:63)
	 at me.kangarko.chatcontrol.final. .coM4.onEnable(SourceFile:164)
	 at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
	 at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
	 at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403)
	 at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381)
	 at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330)
----------------------------------------------------------------------------------------------
```

**Comment by kangarko** [comment]
Please see https://github.com/kangarko/ChatControl-Pro/issues/662. Thank you.
