### ISSUE TITLE
Loading plugin shows this error. was told to show.

### ISSUE THREAD

**Issue by WalkingPixel1** [kangarko/ChatControl-Pro#665]
More Information: 
Null int[] field 'a'  in ag
com9 Report / Null int[] field 'a'  in ag
	 at me.kangarko.chatcontrol.final. .lpt7.const(SourceFile:20)
	 at me.kangarko.chatcontrol.final. .ag.native(SourceFile:152)
	 at me.kangarko.chatcontrol.final. .ag.const(SourceFile:138)
	 at me.kangarko.chatcontrol.final. .ag.strictfp(SourceFile:85)
	 at me.kangarko.chatcontrol.final. .ag$1.const(SourceFile:37)
	 at me.kangarko.chatcontrol.final. .af.native(SourceFile:128)
	 at me.kangarko.chatcontrol.final. .ag.native(SourceFile:165)
	 at me.kangarko.chatcontrol.final. .by.native(SourceFile:68)
	 at me.kangarko.chatcontrol.final. .ag.const(SourceFile:63)
	 at me.kangarko.chatcontrol.final. .coM4.onEnable(SourceFile:164)
	 at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
	 at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
	 at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403)
	 at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:366)
	 at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:318)
	 at com.rylinaux.plugman.util.PluginUtil.reload(PluginUtil.java:380)
	 at com.rylinaux.plugman.command.ReloadCommand.execute(ReloadCommand.java:122)
	 at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95)
	 at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
	 at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
	 at gyurix.commands.CustomCommandMap.dispatch(CustomCommandMap.java:89)
	 at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:651)

**Comment by malonnnn** [comment]
Update to the lastest build, you're on the 2nd lastest
