### ISSUE TITLE
Yet another error in BungeeControlBridge

### ISSUE THREAD

**Issue by x1p** [kangarko/ChatControl-Pro#672]
BungeeControlBridge version 2.2

21:58:57 [WARNING] Exception encountered when loading plugin: BungeeControlBridge
java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Double
	at me.kangarko.chatbungee.Config.getDouble(Config.java:133)
	at me.kangarko.chatbungee.Config.loadConfig(Config.java:54)
	at me.kangarko.chatbungee.BungeeBridge.onEnable(BungeeBridge.java:35)
	at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:227)
	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:277)
	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:56)
	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)

Same error as in version 2.1

**Comment by AmazedMender16** [comment]
I believe this error comes from setting 

# Set any value from 0.0 to 1.0 (match in percent, equals to 0% to 100%) or 0 to disable.
pm-partial-match: 0

That in your config.yml 
change it to

# Set any value from 0.0 to 1.0 (match in percent, equals to 0% to 100%) or 0 to disable.
pm-partial-match: 0.0

**Comment by x1p** [comment]
Well who would have thought that :-)

Thank you for the tip. I'll try asap.

**Comment by kangarko** [comment]
Thanks @AmazedMender16 for the help, it was that. I will silence it in the next version, for now use a whole number like 0.0.
