### ISSUE TITLE
error each discord->mc message with 7.8.7 and discord 1.16.1

### ISSUE THREAD

**Issue by StrangerFive** [kangarko/ChatControl-Pro#698]
Every message sent from discord to minecraft spams an error to the console.  Message still comes thru to player chat window.  I even turned off sound notify in chc settings.yml, and it didn't help.

From error.log...

> ------------------------------------[ 19.04.2018 00:13:31 ]-----------------------------------
ChatControl 7.8.7 encountered a lPt6
Running CraftBukkit 1.12.2-R0.1-SNAPSHOT and Java 1.8.0_152
Plugins: CoreProtect v2.14.2, LuckPerms v4.1.25, PluginConstructorAPI v1.0.31, PlaceholderAPI v2.8.5, WorldBorder v1.8.7, PandaWire v1.0.3-SNAPSHOT, BannerBoard v1.9.9, The Multiverse-Core Plugin, ProtocolLib v4.3.0, LibsDisguises v9.5.1, FastAsyncWorldEdit v18.04.13-049aff4-1063-19.4.26, VoidGenerator v1.2.0, SerializationAPI v4.0.1, Vault v1.6.10, BetterDrops v2.9.3, WorldEdit v6.1.9-SNAPSHOT;3735-ca660f1, CrazyEnchantments v1.7.9.3.7, HeadDatabase v4.3.1, WorldGuard v6.2.2-SNAPSHOT;1713-d2c52f7, DiscordSRV v1.16.1, MythicMobs v4.4.0-SNAPSHOT, AdminAnything v1.7.3, Residence v4.7.8.1, AddLight v4.2.0, PlayerVaults v3.6.3-NBT-vk-2.1.2, VillageDefense v3.2.0, QualityArmory v1.1.77, MythicMobsExtension v1.239, ChatControl v7.8.7, Jobs v4.5.3, CMI v7.6.10.0, AdvancedMobArena v4.0.3, SelectionVisualizer v1.9.10.0
----------------------------------------------------------------------------------------------

> More Information: 
Sender cannot be null in sound notify!
lPt6 Report / Sender cannot be null in sound notify!
	 at me.kangarko.chatcontrol.final. .lpt7.const(SourceFile:20)
	 at me.kangarko.chatcontrol.final. .bH.const(SourceFile:41)
	 at me.kangarko.chatcontrol.final. .super.processDiscordMessage(SourceFile:302)
	 at me.kangarko.chatcontrol.final. .lpt4.const(SourceFile:67)
	 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	 at java.lang.reflect.Method.invoke(Method.java:498)
	 at github.scarsz.discordsrv.api.ApiManager.callEvent(ApiManager.java:105)
	 at github.scarsz.discordsrv.listeners.DiscordChatListener.onGuildMessageReceived(DiscordChatListener.java:103)
	 at github.scarsz.discordsrv.dependencies.jda.core.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:373)
	 at github.scarsz.discordsrv.dependencies.jda.core.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:84)
	 at github.scarsz.discordsrv.dependencies.jda.core.handle.MessageCreateHandler.handleInternally(MessageCreateHandler.java:90)
	 at github.scarsz.discordsrv.dependencies.jda.core.handle.SocketHandler.handle(SocketHandler.java:37)
	 at github.scarsz.discordsrv.dependencies.jda.core.requests.WebSocketClient.onDispatch(WebSocketClient.java:1051)
	 at github.scarsz.discordsrv.dependencies.jda.core.requests.WebSocketClient.onEvent(WebSocketClient.java:911)
	 at github.scarsz.discordsrv.dependencies.jda.core.requests.WebSocketClient.handleEvent(WebSocketClient.java:890)
	 at github.scarsz.discordsrv.dependencies.jda.core.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:1089)
	 at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:368)
	 at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:270)
	 at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:990)
	 at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:749)
	 at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108)
	 at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64)
	 at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45)
----------------------------------------------------------------------------------------------

**Comment by StrangerFive** [comment]
meh, don't bother. I'm about done with cc pro anyway.
