### ISSUE TITLE
Small error PlayerCommandPreprocessEvent

### ISSUE THREAD

**Issue by x1p** [kangarko/ChatControl-Pro#701]
Came across this error. Might be because I changed the command limit value and did a reload. Thought you like to know. Probably gone tomorrow after a fresh restart. (Otherwise I will let it know.)

[23:01:17] [Server thread/ERROR]: Could not pass event PlayerCommandPreprocessEvent to ChatControl v7.8.7
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[Spigot-1.12.2.jar:"349591d"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[Spigot-1.12.2.jar:"349591d"]
etc etc...

**Comment by kangarko** [comment]
I am sorry but the err stack is incomplete. Please also don't rely on reload and if you get errors only report them if they appear after a clean start.
