### ISSUE TITLE
[v7.8.10] Could not pass event AsyncPlayerChatEvent

### ISSUE THREAD

**Issue by x1p** [kangarko/ChatControl-Pro#724]
I'm pretty sure my rule is correct. Its been functional quite a while. This time the advertisement was not blocked.
Got this error
java.lang.NullPointerException: null
	at me.kangarko.chatcontrol.final. .bi.const(SourceFile:54) ~[?:?]
	at me.kangarko.chatcontrol.final. .bi.const(SourceFile:38) ~[?:?]
	at me.kangarko.chatcontrol.final. .bi.const(SourceFile:34) ~[?:?]
	at me.kangarko.chatcontrol.final. .bl.const(SourceFile:527) ~[?:?]
	at me.kangarko.chatcontrol.final. .bl.const(SourceFile:444) ~[?:?]
	at me.kangarko.chatcontrol.final. .bl.const(SourceFile:281) ~[?:?]
	at me.kangarko.chatcontrol.final. .ba.const(SourceFile:214) ~[?:?]
	at me.kangarko.chatcontrol.final. .ba.const(SourceFile:51) ~[?:?]
	at me.kangarko.chatcontrol.final. .ba.const(SourceFile:33) ~[?:?]
	at me.kangarko.chatcontrol.final. .coM5.execute(SourceFile:26) ~[?:?]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-SuSE-1.12.jar:git-Spigot-596221b-9a1fc1e]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [spigot-SuSE-1.12.jar:git-Spigot-596221b-9a1fc1e]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:481) [spigot-SuSE-1.12.jar:git-Spigot-596221b-9a1fc1e]
	at net.minecraft.server.v1_12_R1.PlayerConnection.chat(PlayerConnection.java:1307) [spigot-SuSE-1.12.jar:git-Spigot-596221b-9a1fc1e]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1245) [spigot-SuSE-1.12.jar:git-Spigot-596221b-9a1fc1e]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:39) [spigot-SuSE-1.12.jar:git-Spigot-596221b-9a1fc1e]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_161]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_161]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]

**Comment by kangarko** [comment]
Thanks, that'll be fixed.

**Comment by x1p** [comment]
then this issue can be closed
