### ISSUE TITLE
TypeError: Cannot read property "getHandle" from undefined

### ISSUE THREAD

**Issue by mrcoffee1026** [kangarko/ChatControl-Pro#730]
[18:28:43] [Async Chat Thread - #76/ERROR]: Could not pass event AsyncPlayerChatEvent to ChatControl v7.8.11
java.lang.RuntimeException: <eval>:1 TypeError: Cannot read property "getHandle" from undefined
	at me.kangarko.chatcontrol.final. .lPt2.native(SourceFile:586) ~[ChatControl-7.8.11.jar:?]
	at me.kangarko.chatcontrol.final. .LPT1.const(SourceFile:217) ~[ChatControl-7.8.11.jar:?]
	at me.kangarko.chatcontrol.final. .LPT1.const(SourceFile:184) ~[ChatControl-7.8.11.jar:?]
	at me.kangarko.chatcontrol.final. .lpt7.const(SourceFile:130) ~[ChatControl-7.8.11.jar:?]
	at me.kangarko.chatcontrol.final. .lpt7.const(SourceFile:126) ~[ChatControl-7.8.11.jar:?]
	at me.kangarko.chatcontrol.final. .lpt7.const(SourceFile:119) ~[ChatControl-7.8.11.jar:?]
	at me.kangarko.chatcontrol.final. .nul.native(SourceFile:380) ~[ChatControl-7.8.11.jar:?]
	at me.kangarko.chatcontrol.final. .NUl.const(SourceFile:425) ~[ChatControl-7.8.11.jar:?]
	at me.kangarko.chatcontrol.final. .CON.const(SourceFile:92) ~[ChatControl-7.8.11.jar:?]
	at me.kangarko.chatcontrol.final. .CON.const(SourceFile:40) ~[ChatControl-7.8.11.jar:?]
	at me.kangarko.chatcontrol.final. .bd.const(SourceFile:93) ~[ChatControl-7.8.11.jar:?]
	at me.kangarko.chatcontrol.final. .bd.const(SourceFile:56) ~[ChatControl-7.8.11.jar:?]
	at me.kangarko.chatcontrol.final. .bd.const(SourceFile:29) ~[ChatControl-7.8.11.jar:?]
	at me.kangarko.chatcontrol.final. .coM5.execute(SourceFile:26) ~[ChatControl-7.8.11.jar:?]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-2086bb0-61ca7d9]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-2086bb0-61ca7d9]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:482) [spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-2086bb0-61ca7d9]
	at net.minecraft.server.v1_12_R1.PlayerConnection.chat(PlayerConnection.java:1319) [spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-2086bb0-61ca7d9]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1257) [spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-2086bb0-61ca7d9]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:39) [spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-2086bb0-61ca7d9]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_162]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_162]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_162]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_162]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]
Caused by: jdk.nashorn.internal.runtime.ECMAException: TypeError: Cannot read property "getHandle" from undefined
	at jdk.nashorn.internal.runtime.ECMAErrors.error(ECMAErrors.java:57) ~[nashorn.jar:?]
	at jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:213) ~[nashorn.jar:?]
	at jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:185) ~[nashorn.jar:?]
	at jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:172) ~[nashorn.jar:?]
	at jdk.nashorn.internal.runtime.Undefined.get(Undefined.java:157) ~[nashorn.jar:?]
	at jdk.nashorn.internal.scripts.Script$7$\^eval\_.:program(<eval>:1) ~[?:?]
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:637) ~```
[nashorn.jar:?]
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494) ~[nashorn.jar:?]
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393) ~[nashorn.jar:?]
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:449) ~[nashorn.jar:?]
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:406) ~[nashorn.jar:?]
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:402) ~[nashorn.jar:?]
	at jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:155) ~[nashorn.jar:?]
	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264) ~[?:1.8.0_162]
	at me.kangarko.chatcontrol.final. .COM5.const(SourceFile:77) ~[ChatControl-7.8.11.jar:?]
	at me.kangarko.chatcontrol.final. .COM5.const(SourceFile:73) ~[ChatControl-7.8.11.jar:?]
	at me.kangarko.chatcontrol.final. .Com3.const(SourceFile:393) ~[ChatControl-7.8.11.jar:?]
	at me.kangarko.chatcontrol.final. .LPT1.const(SourceFile:214) ~[ChatControl-7.8.11.jar:?]
	... 23 more
[18:28:43] [Async Chat Thread - #76/INFO]: <OreoTeh_Woof> it didn't work[m

```

**Comment by mrcoffee1026** [comment]
also from like 3 builds ago chatcontrol seems to be lagging everything, although I'm not sure if that's what's doing it... but every time it does like a regex catch i'm lag spiking severely.

**Comment by kangarko** [comment]
Are you using a custom javascript variable? When does it happen exactly, or random?

Also, meanwhile I try to fix that, try to set Variables.Custom_Enabled to false.

**Comment by kangarko** [comment]
Please don't fix it this way, this is a rather nasty workaround. I have included stricter error checks upstream in the plugin, so next time you will get an error like "Cast cannot be null for custom variables" or any please open a new issue so I can push a proper fix ;)
