### ISSUE TITLE
NullPointerException: null

### ISSUE THREAD

**Issue by mibby** [kangarko/ChatControl-Pro#734]
ChatControl v7.8.10

Noticed this error in my logs.
```
[09:48:57] [Async Chat Thread - #5/ERROR]: Could not pass event AsyncPlayerChatEvent to ChatControl v7.8.10
java.lang.NullPointerException: null
	at me.kangarko.chatcontrol.final. .bi.const(SourceFile:54) ~[ChatControl-7.8.10.jar:?]
	at me.kangarko.chatcontrol.final. .bi.const(SourceFile:38) ~[ChatControl-7.8.10.jar:?]
	at me.kangarko.chatcontrol.final. .bi.const(SourceFile:34) ~[ChatControl-7.8.10.jar:?]
	at me.kangarko.chatcontrol.final. .bl.const(SourceFile:527) ~[ChatControl-7.8.10.jar:?]
	at me.kangarko.chatcontrol.final. .bl.const(SourceFile:444) ~[ChatControl-7.8.10.jar:?]
	at me.kangarko.chatcontrol.final. .bl.const(SourceFile:286) ~[ChatControl-7.8.10.jar:?]
	at me.kangarko.chatcontrol.final. .ba.const(SourceFile:214) ~[ChatControl-7.8.10.jar:?]
	at me.kangarko.chatcontrol.final. .ba.const(SourceFile:51) ~[ChatControl-7.8.10.jar:?]
	at me.kangarko.chatcontrol.final. .ba.const(SourceFile:33) ~[ChatControl-7.8.10.jar:?]
	at me.kangarko.chatcontrol.final. .coM5.execute(SourceFile:26) ~[ChatControl-7.8.10.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[patched_1.12.2.jar:git-Paper-1413]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1413]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:515) [patched_1.12.2.jar:git-Paper-1413]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:497) [patched_1.12.2.jar:git-Paper-1413]
	at net.minecraft.server.v1_12_R1.PlayerConnection.chat(PlayerConnection.java:1387) [patched_1.12.2.jar:git-Paper-1413]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1302) [patched_1.12.2.jar:git-Paper-1413]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:39) [patched_1.12.2.jar:git-Paper-1413]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_172]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_172]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_172]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_172]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_172]
```

**Comment by kangarko** [comment]
Please update to 7.8.11.
