### ISSUE TITLE
error on startup for latest beta

### ISSUE THREAD

**Issue by mrcoffee1026** [kangarko/ChatControl-Pro#747]
7.8.18-BETA

Maybe only because they logged in like right while the server was booting up tho, I'm not sure:

```
[18:11:03] [User Authenticator #1/INFO]: [0;37;22m[21m[[0;36;1mLuck[0;36;22mPerms[0;37;22m[21m] [0;31;1m[WARN] Processing login for mc_diamondmaniac took 20867ms.[m
[18:11:03] [User Authenticator #2/INFO]: [0;37;22m[21m[[0;36;1mLuck[0;36;22mPerms[0;37;22m[21m] [0;31;1m[WARN] Processing login for Kiwiunnie took 18127ms.[m
[18:11:03] [User Authenticator #2/INFO]: UUID of player Kiwiunnie is e93e8d65-edd5-460e-8be8-274578eef951
[18:11:03] [User Authenticator #1/INFO]: UUID of player mc_diamondmaniac is 223f4074-8872-4a82-afec-0d0ac41ef59d
[18:11:04] [Craft Scheduler Thread - 21/WARN]: [ChatControl] Plugin ChatControl v7.8.13-BETA generated an exception while executing task 159
java.lang.ArrayIndexOutOfBoundsException: 14
	at sun.util.calendar.BaseCalendar.getCalendarDateFromFixedDate(BaseCalendar.java:453) ~[?:?]
	at java.util.GregorianCalendar.computeFields(GregorianCalendar.java:2393) ~[?:?]
	at java.util.GregorianCalendar.computeFields(GregorianCalendar.java:2308) ~[?:?]
	at java.util.Calendar.complete(Calendar.java:2270) ~[?:?]
	at java.util.Calendar.get(Calendar.java:1826) ~[?:?]
	at java.text.SimpleDateFormat.subFormat(SimpleDateFormat.java:1119) ~[?:?]
	at java.text.SimpleDateFormat.format(SimpleDateFormat.java:966) ~[?:?]
	at java.text.SimpleDateFormat.format(SimpleDateFormat.java:936) ~[?:?]
	at java.text.DateFormat.format(DateFormat.java:345) ~[?:?]
	at net.minecraft.server.v1_12_R1.UserCache$BanEntrySerializer.a(UserCache.java:300) ~[spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-2086bb0-d0a3620]
	at net.minecraft.server.v1_12_R1.UserCache$BanEntrySerializer.serialize(UserCache.java:346) ~[spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-2086bb0-d0a3620]
	at net.minecraft.server.v1_12_R1.UserCache$BanEntrySerializer.serialize(UserCache.java:1) ~[spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-2086bb0-d0a3620]
	at com.google.gson.internal.bind.TreeTypeAdapter.write(TreeTypeAdapter.java:81) ~[spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-2086bb0-d0a3620]
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69) ~[spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-2086bb0-d0a3620]
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:97) ~[spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-2086bb0-d0a3620]
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:61) ~[spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-2086bb0-d0a3620]
	at com.google.gson.Gson.toJson(Gson.java:669) ~[spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-2086bb0-d0a3620]
	at com.google.gson.Gson.toJson(Gson.java:648) ~[spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-2086bb0-d0a3620]
	at com.google.gson.Gson.toJson(Gson.java:603) ~[spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-2086bb0-d0a3620]
	at com.google.gson.Gson.toJson(Gson.java:583) ~[spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-2086bb0-d0a3620]
	at net.minecraft.server.v1_12_R1.UserCache.c(UserCache.java:232) ~[spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-2086bb0-d0a3620]
	at net.minecraft.server.v1_12_R1.UserCache.getProfile(UserCache.java:165) ~[spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-2086bb0-d0a3620]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.getOfflinePlayer(CraftServer.java:1302) ~[spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-2086bb0-d0a3620]
	at org.bukkit.Bukkit.getOfflinePlayer(Bukkit.java:714) ~[spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-2086bb0-d0a3620]
	at me.kangarko.chatcontrol.final. .lpT5.transient(SourceFile:135) ~[ChatControl-7.8.13-BETA.jar:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-2086bb0-d0a3620]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-2086bb0-d0a3620]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1158) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:632) [?:?]
	at java.lang.Thread.run(Thread.java:804) [?:?]
[18:11:04] [Server thread/INFO]: mc_diamondmaniac[/166.181.86.24:32088] logged in with entity id 2906 at ([world]3228.445212995938, 74.375, -2306.997414133297)
[18:11:04] [Server thread/INFO]: Kiwiunnie[/76.20.97.64:54039] logged in with entity id 2909 at ([world]4539.3646797101555, 69.0625, -12073.648209391382)
[18:11:05] [Server thread/INFO]: mc_diamondmaniac [0;34;1mhas joined [0;37;1m[21mCommunity Brew[m[0;34;1m![m
[18:11:05] [Server thread/INFO]: Kiwiunnie [0;34;1mhas joined [0;37;1m[21mCommunity Brew[m[0;34;1m![m
[18:11:05] [Craft Scheduler Thread - 6/INFO]: [BossShopPro] Successfully hooked into Points plugin PlayerPoints.
```

**Comment by kangarko** [comment]
Do you use late-bind ?

Does it always happen or just when players initialized joining while the server was loading?

**Comment by mrcoffee1026** [comment]
i think it's just with a fast join, I didn't see it before this time and I don't think it's shown up since then.

**Comment by mrcoffee1026** [comment]
no it's not a plugin allowing a fast join, I just mean when a user is joining while the server is still doing things during startup, this happened.  Some plugins take longer than others to "finish" and things were still going on after those joins.

**Comment by kangarko** [comment]
Do you have late-bind in spigot or paper enabled?

**Comment by mrcoffee1026** [comment]
I run spigot and it doesn't seem to have that option?

**Comment by x1p** [comment]
Spigot.yml says:

> late-bind
> 
> Default: false
> Type: Boolean
> Description: This delays players from entering the server until all plugins are loaded. Please note, it is advised to test this before putting it into practice as there may be problems with some plugins.

So if I'm right, this must be enabled to delay the joining. But according to kangarko words above, he seems to have preference for disabling. I wonder what "problems" might pup up if enabled.

**Comment by mrcoffee1026** [comment]
I don't know my config file doesn't have the option, so without it specified it should be false.

**Comment by kangarko** [comment]
I always test with this option disabled, because that is what 80-90% of people use anyways. Never had issues with calendar or date being out of sync.

From further investigation I found that the error came from Bukkit getting an offline player's last login when we clear data.db. This is done async and so it may be the cause of the problem. I made it sync in the next version.

**Comment by mrcoffee1026** [comment]
ok... and I haven't actually seen it again past that first time so it may be a really rare thing, even.  Anyway, I'll keep my chc updated and see if it shows up again at any point.
