### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by Yuliansky** [kangarko/ChatControl-Pro#749]
------------------------------------[ 20.05.2018 17:46:30 ]-----------------------------------
ChatControl 7.8.12 encountered a com4
Running CraftBukkit 1.8.8-R0.1-SNAPSHOT and Java 1.8.0_91
Plugins: CustomHelpMessage v1.4, PremiumHub v4.1.0, SkinsRestorer v13.3, WorldEdit v6.1.8-SNAPSHOT;cd4729f, PlaceholderAPI v2.8.7, PermissionsEx v1.23.4, PlugMan v1.8.1, ViaVersion v1.3.0, Vault v1.5.6-b49, EasyBackup v2.6.0, ProtocolLib v4.4.0-SNAPSHOT-b390, WorldGuard v6.1, AAC v3.3.14, Citizens v2.0.16-SNAPSHOT (build 1267), DiscordSRV v1.16.1, AuthMe v5.5.0-SNAPSHOT-b2041, ChatControl v7.8.12, CommandDoesNotExist v2.6.2, ConditionalCommands v1.4, AuthMeBridge v1.6.2, CommandNPC v1.9.1, HolographicDisplays v2.2.6, LiteBans v2.2.14, LeaderHeads v3.1.8.1
----------------------------------------------------------------------------------------------

More Information: 
File plugins\ChatControl\data.db already loaded!
com4 Report / File plugins\ChatControl\data.db already loaded!
	 at me.kangarko.chatcontrol.final. .CoM5.const(SourceFile:30)
	 at me.kangarko.chatcontrol.final. .aj.native(SourceFile:39)
	 at me.kangarko.chatcontrol.final. .aj.<init>(SourceFile:88)
	 at me.kangarko.chatcontrol.final. .aj.<init>(SourceFile:67)
	 at me.kangarko.chatcontrol.final. .CoM3.native(SourceFile:24)
	 at me.kangarko.chatcontrol.final. .lpT5.<init>(SourceFile:27)
	 at me.kangarko.chatcontrol.final. .lpT5.<clinit>(SourceFile:22)
	 at me.kangarko.chatcontrol.ChatControl.private(SourceFile:199)
	 at me.kangarko.chatcontrol.final. .cOm8.onDisable(SourceFile:402)
	 at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:323)
	 at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:364)
	 at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:424)
	 at me.kangarko.chatcontrol.final. .lPt2.const(SourceFile:544)
	 at me.kangarko.chatcontrol.final. .af.strictfp(SourceFile:113)
	 at me.kangarko.chatcontrol.final. .af$1.const(SourceFile:37)
	 at me.kangarko.chatcontrol.final. .ae.native(SourceFile:128)
	 at me.kangarko.chatcontrol.final. .af.native(SourceFile:166)
	 at me.kangarko.chatcontrol.final. .bx.native(SourceFile:68)
	 at me.kangarko.chatcontrol.final. .af.const(SourceFile:63)
	 at me.kangarko.chatcontrol.final. .cOm8.onEnable(SourceFile:174)
	 at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
	 at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
	 at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
	 at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357)
	 at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317)
----------------------------------------------------------------------------------------------

**Comment by kangarko** [comment]
If you use PlugMan or reload, don't please.

Otherwise, update to the latest beta version.
