### ISSUE TITLE
Long cannot be cast to org.json.simple.JSONObject

### ISSUE THREAD

**Issue by mibby** [kangarko/ChatControl-Pro#751]
Paper dev 1424 (Spigot 1.12.2)
ChatControl v7.8.14

Noticed this error in my console log after restarting my server.
```
[05:15:31] [Craft Scheduler Thread - 14/WARN]: java.lang.ClassCastException: java.base/java.lang.Long cannot be cast to org.json.simple.JSONObject
[05:15:31] [Craft Scheduler Thread - 14/WARN]: 	at me.kangarko.chatcontrol.final. .bj.const(SourceFile:128)
[05:15:31] [Craft Scheduler Thread - 14/WARN]: 	at me.kangarko.chatcontrol.final. .bj.const(SourceFile:102)
[05:15:31] [Craft Scheduler Thread - 14/WARN]: 	at me.kangarko.chatcontrol.final. .be.const(SourceFile:128)
[05:15:31] [Craft Scheduler Thread - 14/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:63)
[05:15:31] [Craft Scheduler Thread - 14/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[05:15:31] [Craft Scheduler Thread - 14/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[05:15:31] [Craft Scheduler Thread - 14/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
[05:15:31] [Craft Scheduler Thread - 14/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[05:15:31] [Craft Scheduler Thread - 14/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:844)
[05:15:31] [Craft Scheduler Thread - 34/WARN]: java.lang.ClassCastException: java.base/java.lang.Long cannot be cast to org.json.simple.JSONObject
[05:15:31] [Craft Scheduler Thread - 34/WARN]: 	at me.kangarko.chatcontrol.final. .bj.const(SourceFile:128)
[05:15:31] [Craft Scheduler Thread - 34/WARN]: 	at me.kangarko.chatcontrol.final. .bj.const(SourceFile:102)
[05:15:31] [Craft Scheduler Thread - 34/WARN]: 	at me.kangarko.chatcontrol.final. .be.const(SourceFile:128)
[05:15:31] [Craft Scheduler Thread - 34/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:63)
[05:15:31] [Craft Scheduler Thread - 34/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[05:15:31] [Craft Scheduler Thread - 34/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[05:15:31] [Craft Scheduler Thread - 34/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
[05:15:31] [Craft Scheduler Thread - 34/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[05:15:31] [Craft Scheduler Thread - 34/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:844)
```

**Comment by kangarko** [comment]
I advise to clear your ChatControl table in your MySQL database, especially the Ignored_Sets column as it contains a 0 instead of a JSONObject that we store the data as.

Also, the next version will ignore such values and not produce this.

**Comment by mibby** [comment]
Will do. Thanks for the fix!
