### ISSUE TITLE
CHC v 7.8.15 error when players joins/leaves

### ISSUE THREAD

**Issue by x1p** [kangarko/ChatControl-Pro#752]
Came across this error when testing the new CHC 7.8.15
This error appears after each player joining/disconnecting.

`
[08:44:39] [Server thread/INFO]: Player54321 lost connection: Disconnected
[08:44:39] [Craft Scheduler Thread - 3/WARN]: java.sql.SQLException: Operation not allowed after ResultSet closed
[08:44:39] [Craft Scheduler Thread - 3/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
[08:44:39] [Craft Scheduler Thread - 3/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
[08:44:39] [Craft Scheduler Thread - 3/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
[08:44:39] [Craft Scheduler Thread - 3/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
[08:44:39] [Craft Scheduler Thread - 3/WARN]: 	at com.mysql.jdbc.ResultSetImpl.checkClosed(ResultSetImpl.java:743)
[08:44:39] [Craft Scheduler Thread - 3/WARN]: 	at com.mysql.jdbc.ResultSetImpl.next(ResultSetImpl.java:6288)
[08:44:39] [Craft Scheduler Thread - 3/WARN]: 	at me.kangarko.chatcontrol.final. .bh.const(SourceFile:268)
[08:44:39] [Craft Scheduler Thread - 3/WARN]: 	at me.kangarko.chatcontrol.final. .bh.const(SourceFile:211)
[08:44:39] [Craft Scheduler Thread - 3/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76)
[08:44:39] [Craft Scheduler Thread - 3/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[08:44:39] [Craft Scheduler Thread - 3/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[08:44:39] [Craft Scheduler Thread - 3/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[08:44:39] [Craft Scheduler Thread - 3/WARN]: 	at java.lang.Thread.run(Thread.java:748)
`

**Comment by kangarko** [comment]
Confirmed, will be patched asap in the next version.
