### ISSUE TITLE
Operation not allowed after ResultSet closed

### ISSUE THREAD

**Issue by mibby** [kangarko/ChatControl-Pro#755]
ChatControl v7.8.15
Paper dev 1427 (Spigot 1.12.2)

SQL enabled with a new table created of this update.
```
[02:05:10] [Craft Scheduler Thread - 19/INFO]: Async with thread: Craft Scheduler Thread - 19
[02:05:10] [Craft Scheduler Thread - 36/WARN]: java.sql.SQLException: Operation not allowed after ResultSet closed
[02:05:10] [Craft Scheduler Thread - 36/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
[02:05:10] [Craft Scheduler Thread - 36/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
[02:05:10] [Craft Scheduler Thread - 36/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
[02:05:10] [Craft Scheduler Thread - 36/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
[02:05:10] [Craft Scheduler Thread - 36/WARN]: 	at com.mysql.jdbc.ResultSetImpl.checkClosed(ResultSetImpl.java:743)
[02:05:10] [Craft Scheduler Thread - 36/WARN]: 	at com.mysql.jdbc.ResultSetImpl.next(ResultSetImpl.java:6288)
[02:05:10] [Craft Scheduler Thread - 36/WARN]: 	at me.kangarko.chatcontrol.final. .bh.const(SourceFile:83)
[02:05:10] [Craft Scheduler Thread - 36/WARN]: 	at me.kangarko.chatcontrol.final. .bc.const(SourceFile:128)
[02:05:10] [Craft Scheduler Thread - 36/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:63)
[02:05:10] [Craft Scheduler Thread - 36/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[02:05:10] [Craft Scheduler Thread - 36/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[02:05:10] [Craft Scheduler Thread - 36/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
[02:05:10] [Craft Scheduler Thread - 36/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[02:05:10] [Craft Scheduler Thread - 36/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:844)
```

**Comment by kangarko** [comment]
Thanks, fixed.
