### ISSUE TITLE
error on logon and logoff...

### ISSUE THREAD

**Issue by clipartinc** [kangarko/ChatControl-Pro#775]
[04:06:03 INFO]: [ChatControl] ChatControl 7.8.22 encountered a EOFException! Please check your error.log and report this issue with the information in that file.
[04:06:03 WARN]: [ChatControl] Plugin ChatControl v7.8.22 generated an exception while executing task 2443
java.lang.RuntimeException: java.io.EOFException: Can not read response from server. Expected to read 4 bytes, read 0 bytes before connection was unexpectedly lost.
        at me.kangarko.chatcontrol.final. .LPT3.native(SourceFile:587) ~[ChatControl-7.8.22.jar:?]
        at me.kangarko.chatcontrol.final. .bg.const(SourceFile:251) ~[ChatControl-7.8.22.jar:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot-1.12.2.jar:git-Spigot-2086bb0-8cc5a7e]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-1.12.2.jar:git-Spigot-2086bb0-8cc5a7e]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_171]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_171]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.io.EOFException: Can not read response from server. Expected to read 4 bytes, read 0 bytes before connection was unexpectedly lost.
        at com.mysql.jdbc.MysqlIO.readFully(MysqlIO.java:3011) ~[spigot-1.12.2.jar:git-Spigot-2086bb0-8cc5a7e]
        at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3469) ~[spigot-1.12.2.jar:git-Spigot-2086bb0-8cc5a7e]
        at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3459) ~[spigot-1.12.2.jar:git-Spigot-2086bb0-8cc5a7e]
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3900) ~[spigot-1.12.2.jar:git-Spigot-2086bb0-8cc5a7e]
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527) ~[spigot-1.12.2.jar:git-Spigot-2086bb0-8cc5a7e]
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680) ~[spigot-1.12.2.jar:git-Spigot-2086bb0-8cc5a7e]
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2484) ~[spigot-1.12.2.jar:git-Spigot-2086bb0-8cc5a7e]
        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858) ~[spigot-1.12.2.jar:git-Spigot-2086bb0-8cc5a7e]
        at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2079) ~[spigot-1.12.2.jar:git-Spigot-2086bb0-8cc5a7e]
        at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2013) ~[spigot-1.12.2.jar:git-Spigot-2086bb0-8cc5a7e]
        at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5104) ~[spigot-1.12.2.jar:git-Spigot-2086bb0-8cc5a7e]
        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1998) ~[spigot-1.12.2.jar:git-Spigot-2086bb0-8cc5a7e]
        at me.kangarko.chatcontrol.final. .bg.const(SourceFile:248) ~[ChatControl-7.8.22.jar:?]
        ... 5 more

**Comment by kangarko** [comment]
Hello,

there is a problem with your MySQL connection. I would send this error to your hosting provider instead. Thank you.
