### ISSUE TITLE
 Could not pass event AsyncPlayerChatEvent to ChatControl v7.8.26

### ISSUE THREAD

**Issue by x1p** [kangarko/ChatControl-Pro#779]
swear is caught, but comes in chat anyway

[10:25:38] [Async Chat Thread - #10/ERROR]: Could not pass event AsyncPlayerChatEvent to ChatControl v7.8.26
java.lang.ArrayIndexOutOfBoundsException: 0
	at me.kangarko.chatcontrol.final. .com8.private(SourceFile:57) ~[?:?]
	at me.kangarko.chatcontrol.final. .aS.const(SourceFile:310) ~[?:?]
	at me.kangarko.chatcontrol.final. .aS.const(SourceFile:52) ~[?:?]
	at me.kangarko.chatcontrol.final. .aS.const(SourceFile:34) ~[?:?]
	at me.kangarko.chatcontrol.final. .nUL.execute(SourceFile:26) ~[?:?]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[custom-Spigot-1.12.2.jar:git-custom-"2ff68af"]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [custom-Spigot-1.12.2.jar:git-custom-"2ff68af"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:482) [custom-Spigot-1.12.2.jar:git-custom-"2ff68af"]
	at net.minecraft.server.v1_12_R1.PlayerConnection.chat(PlayerConnection.java:1352) [custom-Spigot-1.12.2.jar:git-custom-"2ff68af"]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1267) [custom-Spigot-1.12.2.jar:git-custom-"2ff68af"]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:39) [custom-Spigot-1.12.2.jar:git-custom-"2ff68af"]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_161]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_161]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]

No errors on startup

**Comment by kangarko** [comment]
Thanks, will be patched.
