### ISSUE TITLE
ChatControl - Broadcaster (messages.yml)

### ISSUE THREAD

**Issue by donpiano** [kangarko/ChatControl-Pro#80]
Have been having major problems with the broadcaster not working. I try so many different formats of my text, and it still generates current error below.

I couildn't figure it out, because when I delete the file and regenerate it, things work fine. Then, finally, i tried MODE from 2 til 0

I had not tried 0 before, since I wanted 2 - but on 2, it generates the error below.

[20:22:16] [Server thread/INFO]: ChatControl Configuration loads..
[20:22:16] [Server thread/INFO]: ChatControl 70 global, 15 chat, 4 command, 2 packet and one sign rule(s) found
[20:22:16] [Server thread/INFO]: ChatControl  
[20:22:17] [Server thread/WARN]: [ChatControl] Task #1055630 for ChatControl v7.0.3 generated an exception
java.lang.NullPointerException
	at me.kangarko.chatcontrol.ChatControl$2.run(SourceFile:313) ~[?:?]
	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-5391d73-287ef78]
	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-5391d73-287ef78]
	at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:741) [spigot.jar:git-Spigot-5391d73-287ef78]
	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot.jar:git-Spigot-5391d73-287ef78]
	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:672) [spigot.jar:git-Spigot-5391d73-287ef78]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:571) [spigot.jar:git-Spigot-5391d73-287ef78]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]

**Comment by locke-d** [comment]
Looks like you're having same issues as I am, issue #72

**Comment by kangarko** [comment]
Please update to 7.0.5
