### ISSUE TITLE
Random error while trying to send messages

### ISSUE THREAD

**Issue by Leomelonseeds** [kangarko/ChatControl-Pro#807]
Sometimes when players try to send messages this error happens:

[14:00:16 INFO]: [ChatControl] ChatControl 7.8.28 encountered a NullPointerException! Please check your error.log and report this issue with the information in that file.
[14:00:16 INFO]: java.lang.NullPointerException
[14:00:16 INFO]:        at me.kangarko.chatcontrol.final. .coM1.const(SourceFile:199)
[14:00:16 INFO]:        at me.kangarko.chatcontrol.final. .lPt8.const(SourceFile:130)
[14:00:16 INFO]:        at me.kangarko.chatcontrol.final. .lPt8.const(SourceFile:126)
[14:00:16 INFO]:        at me.kangarko.chatcontrol.final. .lPt8.const(SourceFile:119)
[14:00:16 INFO]:        at me.kangarko.chatcontrol.final. .bb.native(SourceFile:380)
[14:00:16 INFO]:        at me.kangarko.chatcontrol.final. .ba.const(SourceFile:425)
[14:00:16 INFO]:        at me.kangarko.chatcontrol.final. .bf.const(SourceFile:92)
[14:00:16 INFO]:        at me.kangarko.chatcontrol.final. .bf.const(SourceFile:40)
[14:00:16 INFO]:        at me.kangarko.chatcontrol.final. .protected.sendMessage(SourceFile:214)
[14:00:16 INFO]:        at me.kangarko.chatcontrol.final. .protected.sendMessage(SourceFile:172)
[14:00:16 INFO]:        at me.kangarko.chatcontrol.final. .protected.sendMessage(SourceFile:167)
[14:00:16 INFO]:        at me.kangarko.chatcontrol.final. .aR.const(SourceFile:59)
[14:00:16 INFO]:        at me.kangarko.chatcontrol.final. .aR.const(SourceFile:17)
[14:00:16 INFO]:        at me.kangarko.chatcontrol.final. .nUL.execute(SourceFile:26)
[14:00:16 INFO]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74)
[14:00:16 INFO]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[14:00:16 INFO]:        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:527)
[14:00:16 INFO]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:509)
[14:00:16 INFO]: [ChatControl] *-----------------------------------------------*
[14:00:16 INFO]: [ChatControl]  Error sending channel message for allijac!
[14:00:16 INFO]: [ChatControl]  Channel: global
[14:00:16 INFO]: [ChatControl]  Message: also when i would kill mobs it would ban me
[14:00:16 INFO]: [ChatControl]  Error: NullPointerException
[14:00:16 INFO]: [ChatControl] *-----------------------------------------------*

I am using ChatControlPro 7.8.28

Thanks in advance for your help :D

**Comment by ArtelGG** [comment]
Post the `error.log` file like it says in the stacktrace.

**Comment by Leomelonseeds** [comment]
Here it is. I don't think there is much extra information though...

------------------------------------[ 04.07.2018 14:06:37 ]-----------------------------------
ChatControl 7.8.28 encountered a NullPointerException
Running Paper 1.12.2-R0.1-SNAPSHOT and Java 1.8.0_171
Plugins: PlaceholderAPI v2.9.1, Boss v1.6.3, NametagEdit v4.2.0, GeneralLib v0.1.4, OldCombatMechanics v1.6.5, TitleAPI v1.7.5, DeluxeTags v1.7.1, SuperTrails v9.6.7, AutoRestart v1.0, EpicWorldGenerator v7.2.30, ClearAll v1.0, EpicNetherGenerator v1.0.6, LuckPerms v4.2.17, LeakParkour v2.4, AdvancedBan v2.1.5-RELEASE, WorldBorder v1.8.6, BuycraftX v10.6.2, Votifier v2.3.5, ProtocolLib v4.3.0, VotingPlugin v5.13.1, FastAsyncWorldEdit v18.05.01-0331836-1097-19.7.2, PocketGames v3.1.3, React v6.567, BedrockBreaker v1.0-Release, ConditionalCommands v1.4, mcMMO v1.5.10-SNAPSHOT, Vault v1.5.6-b49, DailyRewards v1.3.1, ProtocolSupport v4.28, CrazyCrates v1.8.1, EpicRename v3.3.1, HolographicDisplays v2.2.6, PlayerVaults v4.0.5, TreeFeller v2.4-RELEASE, WorldEdit v6.1.7;dd00bb1, TryMe v5.5.1, Essentials v2.15.0.1, CommandSigns v1.6.3, Citizens v2.0.22-SNAPSHOT (build 1541), DiscordSRV v1.16.3, AdvancedAchievements v5.8.2, ProtocolSupportStuff v1.0.2, WorldGuard v6.2.1;84bc322, CommandNPC v1.9.1, CombatLogX v7.2.0.0, EssentialsSpawn v2.15.0.1, TitleManager v2.0.9, RandomCoords v0.6.2-RELEASE, CompatNoCheatPlus v6.6.5-RC-sMD5NET-b90, ChatControl v7.8.28, Kingdoms v14.2.17, SilkSpawners v5.0.2, NoCheatPlus v3.16.1-SNAPSHOT-sMD5NET-b1148, GUIShop v6.3.7, BossShopPro v1.9.5, CrazyEnchantments v1.7.9.3.8, PlayerShops v1.2.2
----------------------------------------------------------------------------------------------

More Information: 
Error sending channel message for Leomelonseeds!
Channel: global
Message: yea
Error: %error
NullPointerException (Unknown cause)
	 at me.kangarko.chatcontrol.final. .coM1.const(SourceFile:199)
	 at me.kangarko.chatcontrol.final. .lPt8.const(SourceFile:130)
	 at me.kangarko.chatcontrol.final. .lPt8.const(SourceFile:126)
	 at me.kangarko.chatcontrol.final. .lPt8.const(SourceFile:119)
	 at me.kangarko.chatcontrol.final. .bb.native(SourceFile:380)
	 at me.kangarko.chatcontrol.final. .bf.const(SourceFile:81)
	 at me.kangarko.chatcontrol.final. .bf.const(SourceFile:40)
	 at me.kangarko.chatcontrol.final. .protected.sendMessage(SourceFile:214)
	 at me.kangarko.chatcontrol.final. .protected.sendMessage(SourceFile:172)
	 at me.kangarko.chatcontrol.final. .protected.sendMessage(SourceFile:167)
	 at me.kangarko.chatcontrol.final. .aR.const(SourceFile:59)
	 at me.kangarko.chatcontrol.final. .aR.const(SourceFile:17)
	 at me.kangarko.chatcontrol.final. .nUL.execute(SourceFile:26)
	 at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74)
	 at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
	 at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:527)
	 at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:509)
----------------------------------------------------------------------------------------------

**Comment by kangarko** [comment]
Thanks, fixed in the next release.
