### ISSUE TITLE
Chat Control Pro, error when tested advertising

### ISSUE THREAD

**Issue by AndGK** [kangarko/ChatControl-Pro#81]
So i added "vk.com/cactuscraft" to white list in the advertising, but sometimes when i type "vk.com" it self or sometimes even on any other url's, this error occurs:

`[22:27:10] [Async Chat Thread - #0/INFO]: [0;31;22m[[0;34;1mVIP[0;31;22m] [0;34;1mTester: cactuscraft.ru[m
[22:27:16] [Async Chat Thread - #0/ERROR]: Could not pass event AsyncPlayerChatEvent to ChatControl v7.0.4
java.lang.NullPointerException: Warning set spam does not exists!
	at java.util.Objects.requireNonNull(Unknown Source) ~[?:1.8.0_91]
	at nul.final...\\....if.lPt1.const(SourceFile:120) ~[?:?]
	at nul.final...\\....if.cOM8.const(SourceFile:156) ~[?:?]
	at nul.final...\\....if.cOM8.execute(SourceFile:44) ~[?:?]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-90f61bc-83a9dbd]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-90f61bc-83a9dbd]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot.jar:git-Spigot-90f61bc-83a9dbd]
	at net.minecraft.server.v1_10_R1.PlayerConnection.chat(PlayerConnection.java:1273) [spigot.jar:git-Spigot-90f61bc-83a9dbd]
	at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1211) [spigot.jar:git-Spigot-90f61bc-83a9dbd]
	at net.minecraft.server.v1_10_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:39) [spigot.jar:git-Spigot-90f61bc-83a9dbd]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_91]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_91]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_91]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_91]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]
[22:27:16] [Async Chat Thread - #0/INFO]: [0;31;22m[[0;34;1mVIP[0;31;22m] [0;34;1mTester: vk.com[m`

**Comment by locke-d** [comment]
have you enabled points in your settings.yml?

**Comment by AndGK** [comment]
@locke-d yes, they are enabled.

**Comment by EvilOlaf** [comment]
Can you show us your whole advertisment rule?

**Comment by kangarko** [comment]
Some place in your plugin you use the warning set named 'spam', but you haven't configured it. Remember, you must assign at least one key to the section, otherwise i'll be ignored:

>   # To punish player in different ways for doing specific thing, you can create multiple warning sets.
>   Warn_Sets:
> 
>     spam:
>       6:
>         - "warn &cPlease do not act like spammer."
>       10:
>         - "warn &cPlease do not spam, otherwise you will be banned."
>       12:
>         - "kick {player} &cSpamming the chat (last warning)"
>       26:
>         - "tempban {player} 10m autoban for chat spam" # This requires compatible third party plugin installed

**Comment by kangarko** [comment]
Closing. Let me know if you have any more inquiries.
