### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ZoneTriplu** [kangarko/ChatControl-Pro#826]
[16:48:56] [Server thread/ERROR]: [ChatControl] Unhandled exception occured in onPacketSending(PacketEvent) for ChatControl
java.lang.UnsupportedOperationException: The method hasPermission is not supported for temporary players.
	at com.comphenix.protocol.injector.server.TemporaryPlayerFactory$1.intercept(TemporaryPlayerFactory.java:144) ~[ProtocolLib.jar:4.3.0]
	at com.comphenix.protocol.injector.server.InjectorContainer$$EnhancerByCGLIB$$692d51cd.hasPermission(<generated>) ~[?:?]
	at me.kangarko.chatcontrol.final. .lpT1.const(SourceFile:428) ~[ChatControl.jar:?]
	at me.kangarko.chatcontrol.final. .LpT1$3.onPacketSending(SourceFile:125) ~[ChatControl.jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) [ProtocolLib.jar:4.3.0]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) [ProtocolLib.jar:4.3.0]
	at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:588) [ProtocolLib.jar:4.3.0]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:564) [ProtocolLib.jar:4.3.0]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:338) [ProtocolLib.jar:4.3.0]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:298) [ProtocolLib.jar:4.3.0]
	at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:386) [ProtocolLib.jar:4.3.0]
	at com.comphenix.protocol.injector.netty.ChannelInjector.access$500(ChannelInjector.java:77) [ProtocolLib.jar:4.3.0]
	at com.comphenix.protocol.injector.netty.ChannelInjector$5.handleScheduled(ChannelInjector.java:352) [ProtocolLib.jar:4.3.0]
	at com.comphenix.protocol.injector.netty.ChannelInjector$5.onMessageScheduled(ChannelInjector.java:320) [ProtocolLib.jar:4.3.0]
	at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) [ProtocolLib.jar:4.3.0]
	at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) [ProtocolLib.jar:4.3.0]
	at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:194) [spigot.jar:git-Spigot-642f6d2-6103339]
	at net.minecraft.server.v1_12_R1.NetworkManager.sendPacket(NetworkManager.java:143) [spigot.jar:git-Spigot-642f6d2-6103339]
	at net.minecraft.server.v1_12_R1.PlayerConnection.sendPacket(PlayerConnection.java:1138) [spigot.jar:git-Spigot-642f6d2-6103339]
	at org.bukkit.craftbukkit.v1_12_R1.entity.CraftPlayer.sendRawMessage(CraftPlayer.java:148) [spigot.jar:git-Spigot-642f6d2-6103339]
	at org.bukkit.craftbukkit.v1_12_R1.entity.CraftPlayer.sendMessage(CraftPlayer.java:155) [spigot.jar:git-Spigot-642f6d2-6103339]
	at me.xtomyserrax.StaffFacilities.Listeners.WelcomebackListeners.onPlayerJoin(WelcomebackListeners.java:28) [StaffFacilities.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_171]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) [spigot.jar:git-Spigot-642f6d2-6103339]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot.jar:git-Spigot-642f6d2-6103339]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot.jar:git-Spigot-642f6d2-6103339]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot.jar:git-Spigot-642f6d2-6103339]
	at net.minecraft.server.v1_12_R1.PlayerList.onPlayerJoin(PlayerList.java:346) [spigot.jar:git-Spigot-642f6d2-6103339]
	at net.minecraft.server.v1_12_R1.PlayerList.a(PlayerList.java:166) [spigot.jar:git-Spigot-642f6d2-6103339]
	at net.minecraft.server.v1_12_R1.LoginListener.b(LoginListener.java:159) [spigot.jar:git-Spigot-642f6d2-6103339]
	at net.minecraft.server.v1_12_R1.LoginListener.e(LoginListener.java:57) [spigot.jar:git-Spigot-642f6d2-6103339]
	at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:233) [spigot.jar:git-Spigot-642f6d2-6103339]
	at net.minecraft.server.v1_12_R1.ServerConnection.c(ServerConnection.java:140) [spigot.jar:git-Spigot-642f6d2-6103339]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:845) [spigot.jar:git-Spigot-642f6d2-6103339]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot.jar:git-Spigot-642f6d2-6103339]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot.jar:git-Spigot-642f6d2-6103339]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot.jar:git-Spigot-642f6d2-6103339]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
[16:48:56] [Server thread/ERROR]: Parameters: 
  net.minecraft.server.v1_12_R1.PacketPlayOutChat@1160572e[
    a=TextComponent{text='', siblings=[TextComponent{text='Welcome back ', siblings=[], style=Style{hasParent=true, color=§5, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}, TextComponent{text='ChucklesM8', siblings=[], style=Style{hasParent=true, color=§d, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}, TextComponent{text='!', siblings=[], style=Style{hasParent=true, color=§5, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}
    components=<null>
    b=SYSTEM
  ]

**Comment by kangarko** [comment]
What are your plugins please? When does it happen?

**Comment by kangarko** [comment]
Update: I found that it's most likely caused by an outdated ProtocolLib. Please update it to the very latest version.
