### ISSUE TITLE
Tried using /msg (player) hi or /tell (player) = unhandled error occurred ingame

### ISSUE THREAD

**Issue by axemwa** [kangarko/ChatControl-Pro#834]
It's as the title says also this WARN appears in console

[12:03:03 WARN]: java.lang.IllegalArgumentException: key
[12:03:03 WARN]:        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
[12:03:03 WARN]:        at org.bukkit.NamespacedKey.<init>(NamespacedKey.java:72)
[12:03:03 WARN]:        at me.kangarko.chatcontrol.final. .f.<init>(SourceFile:1110)
[12:03:03 WARN]:        at me.kangarko.chatcontrol.final. .i.native(SourceFile:863)
[12:03:03 WARN]:        at me.kangarko.chatcontrol.final. .bC.const(SourceFile:151)
[12:03:03 WARN]:        at me.kangarko.chatcontrol.final. .AUX.const(SourceFile:102)
[12:03:03 WARN]:        at me.kangarko.chatcontrol.final. .LPT4.onCommand(SourceFile:59)
[12:03:03 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[12:03:03 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151)
[12:03:03 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:685)
[12:03:03 WARN]:        at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1473)
[12:03:03 WARN]:        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1278)
[12:03:03 WARN]:        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[12:03:03 WARN]:        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)
[12:03:03 WARN]:        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14)
[12:03:03 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[12:03:03 WARN]:        at java.util.concurrent.FutureTask.run(Unknown Source)
[12:03:03 WARN]:        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[12:03:03 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:849)
[12:03:03 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:427)
[12:03:03 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:773)
[12:03:03 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665)
[12:03:03 WARN]:        at java.lang.Thread.run(Unknown Source)

**Comment by axemwa** [comment]
Also /r doesn't seem to work it says you have no one to reply to when attempting to reply to a message

**Comment by TheIntelloBox** [comment]
Me too. ;)

**Comment by axemwa** [comment]
You too for the WARN or for the /r not working?

**Comment by TheIntelloBox** [comment]
Yep. ;) And the /msg player doesn't work, there is an error. x)

**Comment by axemwa** [comment]
Yeah I had that too

**Comment by kangarko** [comment]
Please test using 7.9.2 rev.2 version.

**Comment by axemwa** [comment]
Still getting WARNs in console and unhandled errors ingame when trying to send a /msg message (the message does go through though with the errors) here's the WARN below. Players also can't use /r to reply to the sent message

**Comment by axemwa** [comment]
beep

**Comment by kangarko** [comment]
Solved in the second revision of the latest update.

**Comment by axemwa** [comment]
Awesome great work there :)
