### ISSUE TITLE
1.13 Support

### ISSUE THREAD

**Issue by gerardvanschip** [kangarko/ChatControl-Pro#844]
Seems the error is due to calling the old style sound name. Tried to change it to the new name but 

entity.firework.launch   ---->    entity.firework_rocket.launch

Shame the plugin won't load for such a simple error.

`
[02:56:05] [Server thread/INFO]: [ChatControl] Enabling ChatControl v7.9.3
[02:56:06] [Server thread/INFO]:   _____ _           _    _____            _             _  +
[02:56:06] [Server thread/INFO]:  / ____| |         | |  / ____|          | |           | |
[02:56:06] [Server thread/INFO]: | |    | |__   __ _| |_| |     ___  _ __ | |_ _ __ ___ | |
[02:56:06] [Server thread/INFO]: | |    | '_ \ / _` | __| |    / _ \| '_ \| __| '__/ _ \| |
[02:56:06] [Server thread/INFO]: | |____| | | | (_| | |_| |___| (_) | | | | |_| | | (_) | |
[02:56:06] [Server thread/INFO]:  \_____|_| |_|\__,_|\__|\_____\___/|_| |_|\__|_|  \___/|_|
[02:56:06] [Server thread/INFO]:  
[02:56:07] [Server thread/INFO]: *-----------------------------------------------*
[02:56:07] [Server thread/INFO]:  Your Minecraft version v1_13
[02:56:07] [Server thread/INFO]:  has not yet been officialy tested
[02:56:07] [Server thread/INFO]:  on this plugin. It should work, but
[02:56:07] [Server thread/INFO]:  please proceed with caution.
[02:56:07] [Server thread/INFO]: *-----------------------------------------------*
[02:56:07] [Server thread/INFO]: Created default file: settings.yml
[02:56:07] [Server thread/INFO]: ChatControl 7.9.3 encountered a IllegalArgumentException! Please check your error.log and report this issue with the information in that file.
[02:56:07] [Server thread/INFO]: *-----------------------------------------------*
[02:56:07] [Server thread/INFO]:  Error loading configuration in settings.yml!
[02:56:07] [Server thread/INFO]:  Problematic section: Motd
[02:56:07] [Server thread/INFO]:  Problem: me.kangarko.chatcontrol.final. .coM7: Report / java.lang.IllegalArgumentException: No enum constant org.bukkit.Sound.ENTITY_FIREWORK_LAUNCH
[02:56:07] [Server thread/INFO]:  Plugin is now disabled.
[02:56:07] [Server thread/INFO]: *-----------------------------------------------*
[02:56:07] [Server thread/INFO]: [ChatControl] Disabling ChatControl v7.9.3
[02:56:07] [Server thread/INFO]: Created default file: data.db
[02:56:07] [Server thread/INFO]: me.kangarko.chatcontrol.final. .coM7: Report / java.lang.IllegalArgumentException: No enum constant org.bukkit.Sound.ENTITY_FIREWORK_LAUNCH
[02:56:07] [Server thread/INFO]: 	at me.kangarko.chatcontrol.final. .w.const(SourceFile:1251)
[02:56:07] [Server thread/INFO]: 	at me.kangarko.chatcontrol.final. .i.protected(SourceFile:601)
[02:56:07] [Server thread/INFO]: 	at me.kangarko.chatcontrol.api.lib.SoundHelper.<init>(SourceFile:27)
[02:56:07] [Server thread/INFO]: 	at me.kangarko.chatcontrol.final. .W.super(SourceFile:191)
[02:56:07] [Server thread/INFO]: 	at me.kangarko.chatcontrol.final. .X.while(SourceFile:270)
[02:56:07] [Server thread/INFO]: 	at me.kangarko.chatcontrol.final. .bA.cG(SourceFile:34)
[02:56:07] [Server thread/INFO]: 	at me.kangarko.chatcontrol.final. .bA$lPT5.init(SourceFile:832)
[02:56:07] [Server thread/INFO]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[02:56:07] [Server thread/INFO]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[02:56:07] [Server thread/INFO]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[02:56:07] [Server thread/INFO]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[02:56:07] [Server thread/INFO]: 	at me.kangarko.chatcontrol.final. .X.const(SourceFile:135)
[02:56:07] [Server thread/INFO]: 	at me.kangarko.chatcontrol.final. .X.strictfp(SourceFile:102)
[02:56:07] [Server thread/INFO]: 	at me.kangarko.chatcontrol.final. .X$1.const(SourceFile:37)
[02:56:07] [Server thread/INFO]: 	at me.kangarko.chatcontrol.final. .W.native(SourceFile:129)
[02:56:07] [Server thread/INFO]: 	at me.kangarko.chatcontrol.final. .X.native(SourceFile:166)
[02:56:07] [Server thread/INFO]: 	at me.kangarko.chatcontrol.final. .Z.native(SourceFile:24)
[02:56:07] [Server thread/INFO]: 	at me.kangarko.chatcontrol.final. .X.const(SourceFile:63)
[02:56:07] [Server thread/INFO]: 	at me.kangarko.chatcontrol.final. .pRn.onEnable(SourceFile:177)
[02:56:07] [Server thread/INFO]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[02:56:07] [Server thread/INFO]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:339)
[02:56:07] [Server thread/INFO]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403)
[02:56:07] [Server thread/INFO]: 	at org.bukkit.craftbukkit.v1_13_R1.CraftServer.enablePlugin(CraftServer.java:424)
[02:56:07] [Server thread/INFO]: 	at org.bukkit.craftbukkit.v1_13_R1.CraftServer.enablePlugins(CraftServer.java:338)
[02:56:07] [Server thread/INFO]: 	at net.minecraft.server.v1_13_R1.MinecraftServer.m(MinecraftServer.java:523)
[02:56:07] [Server thread/INFO]: 	at net.minecraft.server.v1_13_R1.MinecraftServer.g_(MinecraftServer.java:485)
[02:56:07] [Server thread/INFO]: 	at net.minecraft.server.v1_13_R1.MinecraftServer.a(MinecraftServer.java:384)
[02:56:07] [Server thread/INFO]: 	at net.minecraft.server.v1_13_R1.DedicatedServer.init(DedicatedServer.java:288)
[02:56:07] [Server thread/INFO]: 	at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:647)
[02:56:07] [Server thread/INFO]: 	at java.lang.Thread.run(Unknown Source)
[02:56:07] [Server thread/INFO]: java.lang.IllegalArgumentException: No enum constant org.bukkit.Sound.ENTITY_FIREWORK_LAUNCH
[02:56:07] [Server thread/INFO]: 	at java.lang.Enum.valueOf(Unknown Source)
[02:56:07] [Server thread/INFO]: 	at org.bukkit.Sound.valueOf(Sound.java:1)
[02:56:07] [Server thread/INFO]: 	at me.kangarko.chatcontrol.final. .w.const(SourceFile:1246)
[02:56:07] [Server thread/INFO]: 	at me.kangarko.chatcontrol.final. .i.protected(SourceFile:601)
[02:56:07] [Server thread/INFO]: 	at me.kangarko.chatcontrol.api.lib.SoundHelper.<init>(SourceFile:27)
[02:56:07] [Server thread/INFO]: 	at me.kangarko.chatcontrol.final. .W.super(SourceFile:191)
[02:56:07] [Server thread/INFO]: 	at me.kangarko.chatcontrol.final. .X.while(SourceFile:270)
[02:56:07] [Server thread/INFO]: 	at me.kangarko.chatcontrol.final. .bA.cG(SourceFile:34)
[02:56:07] [Server thread/INFO]: 	at me.kangarko.chatcontrol.final. .bA$lPT5.init(SourceFile:832)
[02:56:07] [Server thread/INFO]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[02:56:07] [Server thread/INFO]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[02:56:07] [Server thread/INFO]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[02:56:07] [Server thread/INFO]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[02:56:07] [Server thread/INFO]: 	at me.kangarko.chatcontrol.final. .X.const(SourceFile:135)
[02:56:07] [Server thread/INFO]: 	at me.kangarko.chatcontrol.final. .X.strictfp(SourceFile:102)
[02:56:07] [Server thread/INFO]: 	at me.kangarko.chatcontrol.final. .X$1.const(SourceFile:37)
[02:56:07] [Server thread/INFO]: 	at me.kangarko.chatcontrol.final. .W.native(SourceFile:129)
[02:56:07] [Server thread/INFO]: 	at me.kangarko.chatcontrol.final. .X.native(SourceFile:166)
[02:56:07] [Server thread/INFO]: 	at me.kangarko.chatcontrol.final. .Z.native(SourceFile:24)
[02:56:07] [Server thread/INFO]: 	at me.kangarko.chatcontrol.final. .X.const(SourceFile:63)
[02:56:07] [Server thread/INFO]: 	at me.kangarko.chatcontrol.final. .pRn.onEnable(SourceFile:177)
[02:56:07] [Server thread/INFO]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[02:56:07] [Server thread/INFO]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:339)
[02:56:07] [Server thread/INFO]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403)
[02:56:07] [Server thread/INFO]: 	at org.bukkit.craftbukkit.v1_13_R1.CraftServer.enablePlugin(CraftServer.java:424)
[02:56:07] [Server thread/INFO]: 	at org.bukkit.craftbukkit.v1_13_R1.CraftServer.enablePlugins(CraftServer.java:338)
[02:56:07] [Server thread/INFO]: 	at net.minecraft.server.v1_13_R1.MinecraftServer.m(MinecraftServer.java:523)
[02:56:07] [Server thread/INFO]: 	at net.minecraft.server.v1_13_R1.MinecraftServer.g_(MinecraftServer.java:485)
[02:56:07] [Server thread/INFO]: 	at net.minecraft.server.v1_13_R1.MinecraftServer.a(MinecraftServer.java:384)
[02:56:07] [Server thread/INFO]: 	at net.minecraft.server.v1_13_R1.DedicatedServer.init(DedicatedServer.java:288)
[02:56:07] [Server thread/INFO]: 	at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:647)
[02:56:07] [Server thread/INFO]: 	at java.lang.Thread.run(Unknown Source)
[02:56:07] [Server thread/INFO]:   _   _                       _ 
[02:56:07] [Server thread/INFO]:   | | | | ___   ___  _ __  ___| |
[02:56:07] [Server thread/INFO]:   | |_| |/ _ \ / _ \| '_ \/ __| |
[02:56:07] [Server thread/INFO]:   |  _  | (_) | (_) | |_) \__ \_|
[02:56:07] [Server thread/INFO]:   |_| |_|\___/ \___/| .__/|___(_)
[02:56:07] [Server thread/INFO]:                     |_|          
[02:56:07] [Server thread/INFO]: !-----------------------------------------------------!
[02:56:07] [Server thread/INFO]:  Error loading ChatControl v7.9.3, plugin is disabled!
[02:56:07] [Server thread/INFO]:  Running on 1.13-pre7-R0.1-SNAPSHOT (v1_13_R1) & Java 1.8.0_65
[02:56:07] [Server thread/INFO]: !-----------------------------------------------------!
[02:56:07] [Server thread/INFO]:  Error: No enum constant org.bukkit.Sound.ENTITY_FIREWORK_LAUNCH
[02:56:07] [Server thread/INFO]: !-----------------------------------------------------!
`

**Comment by kangarko** [comment]
Due to significant API changes, there are more fatal errors preventing all of my plugins from loading.

The plugins will be updated when stable 1.13 builds are ready (meaning critical fixes are in place). Generally I plan to push the compatibility update between 23-29.07.

**Comment by gerardvanschip** [comment]
Please let me know if your other plugins are updated as well, planning to buy all of them.

**Comment by kuohsuanlo** [comment]
Looking forward to see the 1.13 update. Especially ChatControlPro. :)

**Comment by JarlPenguin** [comment]
Is 1.13 support for ChatControl (not Pro) also in the works?

**Comment by kangarko** [comment]
1.13 is in preparation, stay in touch with my profile posts on Spigot for latest information.

**Comment by kangarko** [comment]
Please stop asking when the update will be done, this adds 0 time or resources to the process.

**Comment by TheIntelloBox** [comment]
That was just a question. :x

**Comment by kangarko** [comment]
Once it will arrive it will be announced as a new update.
