### ISSUE TITLE
problem using 1.12.2

### ISSUE THREAD

**Issue by dabou0** [kangarko/ChatControl-Pro#870]
[20:23:29 INFO]: UrGonnaDie issued server command: /tell gay sasa
[20:23:29 WARN]: java.lang.IllegalArgumentException: key
[20:23:29 WARN]:        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
[20:23:29 WARN]:        at org.bukkit.NamespacedKey.<init>(NamespacedKey.java:72)
[20:23:29 WARN]:        at me.kangarko.chatcontrol.final. .j.<init>(SourceFile:1114)
[20:23:29 WARN]:        at me.kangarko.chatcontrol.final. .m.native(SourceFile:864)
[20:23:29 WARN]:        at me.kangarko.chatcontrol.final. .bG.const(SourceFile:151)
[20:23:29 WARN]:        at me.kangarko.chatcontrol.final. .AUX.const(SourceFile:102)
[20:23:29 WARN]:        at me.kangarko.chatcontrol.final. .LPT4.onCommand(SourceFile:59)
[20:23:29 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[20:23:29 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[20:23:29 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648)
[20:23:29 WARN]:        at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1397)
[20:23:29 WARN]:        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1232)
[20:23:29 WARN]:        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[20:23:29 WARN]:        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
[20:23:29 WARN]:        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[20:23:29 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[20:23:29 WARN]:        at java.util.concurrent.FutureTask.run(Unknown Source)
[20:23:29 WARN]:        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[20:23:29 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748)
[20:23:29 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
[20:23:29 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[20:23:29 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
[20:23:29 WARN]:        at java.lang.Thread.run(Unknown Source)

i got this error when i private msg someone, im using 1.12.2 with allowing 1.8 clients to join

**Comment by dabou0** [comment]
my 1,.12 account name is ieatroadkills, and 1.8 is urgonnadie ,   i cant use tab-complete to ieatroadkills, bc if just changed it for gay, idk what happened, i msged him gay, and his name is now gay.

**Comment by kangarko** [comment]
Update ChatControl to latest release.
