### ISSUE TITLE
Private Messages Broken

### ISSUE THREAD

**Issue by Tyloonie** [kangarko/ChatControl-Pro#888]
Hello,

Not able to use /msg through ChatControl at all. No messages are ever sent. Also, trying to tab complete a name after /msg causes the following error:

`
------------------------------------[ 13.08.2018 14:49:40 ]-----------------------------------
ChatControl 7.9.10 encountered a com7
Running Paper 1.12.2-R0.1-SNAPSHOT and Java 1.8.0_181
Plugins: CoreProtect v2.14.2, LuckPerms v4.2.51, MinionsFree v2.5.4, PlaceholderAPI v2.9.1, SuperTrailsPro vv1.0.4, BuycraftX v10.6.2, Votifier v1.9, EasyBackup v2.8.0, ProtocolLib v4.4.0-SNAPSHOT-b403, AAC v3.4.2, MVdWPlaceholderAPI v2.5.1, FastAsyncWorldEdit v18.07.15-7cbb117-1154-20.3.4, FeatherBoard v4.9.0, Tab v6.3.0, Casino v1.0-SNAPSHOT, mcMMO v1.5.10, Vault v1.5.6-b49, ShardheavenCore v1.0.0, Essentials v2.15.0.17, FastAsyncVoxelSniper v18.07.15-7cbb117-1154-20.3.4, AnimatedNames v6.4.0, AACAdditionPro v4.0.3, LiteBans v2.2.10, Citizens v2.0.22-SNAPSHOT (build 1547), ASkyBlock v3.0.9.4, VoxelSniper v5.172.0-SNAPSHOT, CrazyAuctions v1.2.6, SuperbVote v0.5.2-1.12, PlayerVaults v4.0.5, EssentialsSpawn v2.15.0.17, WorldEdit v6.1.7;dd00bb1, The Multiverse-Core Plugin, WorldGuard v6.2.1;84bc322, CitizensCMD v2.1, StackMob v2.2.14, ChestShop v3.9.2 (build 86), ChatControl v7.9.10, HolographicDisplays v2.2.6, CrateReloaded 2.0.0-alpha7 by Will, SilkSpawners v5.0.2, BossShopPro v1.9.8, ProQuests v2.0.7, LeaderHeads v3.1.8.3
----------------------------------------------------------------------------------------------

More Information: 
Value 'Tyloonie' is already in the list!
com7 Report / Value 'Tyloonie' is already in the list!
	 at me.kangarko.chatcontrol.final. .lpt9.const(SourceFile:30)
	 at me.kangarko.chatcontrol.final. .N.strictfp(SourceFile:91)
	 at me.kangarko.chatcontrol.final. .LPt6.case(SourceFile:1568)
	 at me.kangarko.chatcontrol.final. .AUX.onTabComplete(SourceFile:128)
	 at org.bukkit.command.PluginCommand.tabComplete(PluginCommand.java:132)
	 at org.bukkit.command.Command.tabComplete(Command.java:90)
	 at org.bukkit.command.SimpleCommandMap.tabComplete(SimpleCommandMap.java:230)
	 at org.bukkit.craftbukkit.v1_12_R1.CraftServer.tabCompleteCommand(CraftServer.java:1698)
	 at org.bukkit.craftbukkit.v1_12_R1.CraftServer.tabComplete(CraftServer.java:1670)
----------------------------------------------------------------------------------------------

`

**Comment by SuperiorCodeMonkey** [comment]
Same thing happens to me but only if a player on the server has no nickname assigned.
Hope this helps with debugging
