### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by mibby** [kangarko/ChatControl-Pro#897]
ChatControlPro v7.9.13
Paper dev 1547 (Spigot 1.12.2)

Noticed this error at start-up with people connecting after a restart.
```
[09:00:53] [Craft Scheduler Thread - 26/WARN]: java.lang.NullPointerException
[09:00:53] [Craft Scheduler Thread - 26/WARN]: 	at me.kangarko.chatcontrol.final. .bh.const(SourceFile:138)
[09:00:53] [Craft Scheduler Thread - 26/WARN]: 	at me.kangarko.chatcontrol.final. .bh.const(SourceFile:103)
[09:00:53] [Craft Scheduler Thread - 26/WARN]: 	at me.kangarko.chatcontrol.final. .aX.const(SourceFile:132)
[09:00:53] [Craft Scheduler Thread - 26/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:63)
[09:00:53] [Craft Scheduler Thread - 26/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[09:00:53] [Craft Scheduler Thread - 26/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[09:00:53] [Craft Scheduler Thread - 26/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[09:00:53] [Craft Scheduler Thread - 26/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[09:00:53] [Craft Scheduler Thread - 26/WARN]: 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by kangarko** [comment]
This is related to some error while loading MySQL data that hid something else, I will uncover it in the next version. Please comment below with a new stack trace, if it happens. Thank you.
