### ISSUE TITLE
Unhandled chat mode null

### ISSUE THREAD

**Issue by mibby** [kangarko/ChatControl-Pro#899]
ChatControlPro v7.9.13
Paper dev 1550 (Spigot 1.12.2)

Checking the error.log file for ChatControl, noticed this error occurred 67 times in the last 2 days.

```
------------------------------------[ 19.08.2018 20:52:51 ]-----------------------------------
ChatControl 7.9.13 encountered a com7
Running Paper 1.12.2-R0.1-SNAPSHOT and Java 1.8.0_181
Plugins: stripped censored large list
----------------------------------------------------------------------------------------------

More Information: 
Unhandled chat mode null
com7 Report / Unhandled chat mode null
	 at me.kangarko.chatcontrol.final. .aT.const(SourceFile:86)
	 at me.kangarko.chatcontrol.final. .aT.const(SourceFile:35)
	 at me.kangarko.chatcontrol.final. .Com3.execute(SourceFile:26)
	 at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74)
	 at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
	 at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:527)
	 at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:509)
----------------------------------------------------------------------------------------------
```

**Comment by kangarko** [comment]
Thanks, fixed in the next release.
