### ISSUE TITLE
Error updating mysql data for player

### ISSUE THREAD

**Issue by mibby** [kangarko/ChatControl-Pro#900]
ChatControlPro v7.9.13
Paper dev 1550 (Spigot 1.12.2)

Checking the error.log file for ChatControl, noticed this error once.

```
------------------------------------[ 19.08.2018 21:13:53 ]-----------------------------------
ChatControl 7.9.13 encountered a NullPointerException
Running Paper 1.12.2-R0.1-SNAPSHOT and Java 1.8.0_181
Plugins: stripped censored large list
----------------------------------------------------------------------------------------------

More Information: 
Error updating mysql data for Bwusagi
NullPointerException (Unknown cause)
	 at me.kangarko.chatcontrol.final. .bh.const(SourceFile:246)
	 at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:63)
	 at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
	 at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
	 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	 at java.lang.Thread.run(Thread.java:748)
----------------------------------------------------------------------------------------------

```

**Comment by kangarko** [comment]
Probably similar to your previous error about chat mode, since now we are trying to save null value and that's the problem. Nvm, fixed, sorry about this.
