### ISSUE TITLE
Java 11 - javax.net.ssl.SSLException: No PSK available. Unable to resume.

### ISSUE THREAD

**Issue by mibby** [kangarko/ChatControl-Pro#946]
Java SE 11
Paper dev 366 (Spigot 1.13.1)
ChatControlPro v7.9.28

```
[00:32:23] [Craft Scheduler Thread - 34/WARN]: javax.net.ssl.SSLException: No PSK available. Unable to resume.
[00:32:23] [Craft Scheduler Thread - 34/WARN]: 	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:129)
[00:32:23] [Craft Scheduler Thread - 34/WARN]: 	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:117)
[00:32:23] [Craft Scheduler Thread - 34/WARN]: 	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:308)
[00:32:23] [Craft Scheduler Thread - 34/WARN]: 	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:264)
[00:32:23] [Craft Scheduler Thread - 34/WARN]: 	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:255)
[00:32:23] [Craft Scheduler Thread - 34/WARN]: 	at java.base/sun.security.ssl.ServerHello$T13ServerHelloConsumer.consume(ServerHello.java:1224)
[00:32:23] [Craft Scheduler Thread - 34/WARN]: 	at java.base/sun.security.ssl.ServerHello$ServerHelloConsumer.onServerHello(ServerHello.java:984)
[00:32:23] [Craft Scheduler Thread - 34/WARN]: 	at java.base/sun.security.ssl.ServerHello$ServerHelloConsumer.consume(ServerHello.java:872)
[00:32:23] [Craft Scheduler Thread - 34/WARN]: 	at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:392)
[00:32:23] [Craft Scheduler Thread - 34/WARN]: 	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:444)
[00:32:23] [Craft Scheduler Thread - 34/WARN]: 	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:421)
[00:32:23] [Craft Scheduler Thread - 34/WARN]: 	at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:178)
[00:32:23] [Craft Scheduler Thread - 34/WARN]: 	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:164)
[00:32:23] [Craft Scheduler Thread - 34/WARN]: 	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1152)
[00:32:23] [Craft Scheduler Thread - 34/WARN]: 	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1063)
[00:32:23] [Craft Scheduler Thread - 34/WARN]: 	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:402)
[00:32:23] [Craft Scheduler Thread - 34/WARN]: 	at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:567)
[00:32:23] [Craft Scheduler Thread - 34/WARN]: 	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
[00:32:23] [Craft Scheduler Thread - 34/WARN]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1581)
[00:32:23] [Craft Scheduler Thread - 34/WARN]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1509)
[00:32:23] [Craft Scheduler Thread - 34/WARN]: 	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:245)
[00:32:23] [Craft Scheduler Thread - 34/WARN]: 	at me.kangarko.chatcontrol.final. .aM.run(SourceFile:77)
[00:32:23] [Craft Scheduler Thread - 34/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:63)
[00:32:23] [Craft Scheduler Thread - 34/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[00:32:23] [Craft Scheduler Thread - 34/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[00:32:23] [Craft Scheduler Thread - 34/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[00:32:23] [Craft Scheduler Thread - 34/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[00:32:23] [Craft Scheduler Thread - 34/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by kangarko** [comment]
Should be fixed in the next release.

**Comment by mibby** [comment]
Thanks!
