### ISSUE TITLE
Error on load

### ISSUE THREAD

**Issue by Jerlag01** [kangarko/ChatControl-Pro#965]
error on load of plugin:

http://paste.flanderscraft.eu:83/witixowoho.shell

server verion: thermos 1.7.10

error.log from test server:
------------------------------------[ 22.10.2018 01:57:27 ]-----------------------------------
ChatControl 7.9.32 encountered a CoM4
Running Cauldron 1.7.10-R0.1-SNAPSHOT and Java 1.8.0_172
Plugins: PlugMan v2.1.5, MassiveCore v2.7.0, Factions v2.7.0, ChatControl v7.9.32
----------------------------------------------------------------------------------------------

More Information: 
ScriptEngine not found. Detected: scala.tools.nsc.interpreter.IMain$Factory@20f40e30
CoM4 Report / ScriptEngine not found. Detected: scala.tools.nsc.interpreter.IMain$Factory@20f40e30
	 at me.kangarko.chatcontrol.final. .Com6.const(SourceFile:22)
	 at me.kangarko.chatcontrol.final. .cOm7.<clinit>(SourceFile:32)
	 at me.kangarko.chatcontrol.final. .lpt3$protected.const(SourceFile:118)
	 at me.kangarko.chatcontrol.final. .lpt3.private(SourceFile:56)
	 at me.kangarko.chatcontrol.final. .lpt3.native(SourceFile:52)
	 at me.kangarko.chatcontrol.final. .lpt6.onEnable(SourceFile:238)
	 at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316)
	 at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368)
	 at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410)
	 at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:438)
	 at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:372)
----------------------------------------------------------------------------------------------

**Comment by kangarko** [comment]
Sorry but Thermos is not supported. Only Spigot or PaperSpigot are supported.

**Comment by Jerlag01** [comment]
i got the exact same errors on spigot though in #966

**Comment by kangarko** [comment]
Re-download and test now. If you get any , what error specifically ?

**Comment by Jerlag01** [comment]
------------------------------------[ 22.10.2018 21:57:12 ]-----------------------------------
ChatControl 7.9.32 encountered a CoM4
Running 1.7.10-R0.1-SNAPSHOT and Java 1.8.0_191
Plugins: ProtocolLib v3.7.0, ChatControl v7.9.32
----------------------------------------------------------------------------------------------

More Information: 
ScriptEngine not found. Detected: scala.tools.nsc.interpreter.IMain$Factory@270b2ef2
CoM4 Report / ScriptEngine not found. Detected: scala.tools.nsc.interpreter.IMain$Factory@270b2ef2
	 at me.kangarko.chatcontrol.final. .Com6.const(SourceFile:22)
	 at me.kangarko.chatcontrol.final. .cOm7.<clinit>(SourceFile:32)
	 at me.kangarko.chatcontrol.final. .lpt3$protected.const(SourceFile:118)
	 at me.kangarko.chatcontrol.final. .lpt3.private(SourceFile:56)
	 at me.kangarko.chatcontrol.final. .lpt3.native(SourceFile:52)
	 at me.kangarko.chatcontrol.final. .lpt6.onEnable(SourceFile:238)
	 at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316)
	 at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368)
	 at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410)
	 at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:438)
	 at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:372)
----------------------------------------------------------------------------------------------

**Comment by Jerlag01** [comment]
and in console it returns this when running on a spigot 1.7.10 server:
http://paste.flanderscraft.eu:83/ipesajesut.sql

**Comment by Jerlag01** [comment]
@kangarko still waiting here

**Comment by kangarko** [comment]
Sorry my email answer did not get through. Termos is not supported. For Spigot on 1.7.10 you have to install BungeeChatAPI (see my resources on Spigot)

**Comment by Jerlag01** [comment]
works fine on spigot now, thanks. is there any way or another plugin you know of that fix the required classes that the plugin needs on thermos?

**Comment by kangarko** [comment]
I have no idea, probably missing many classes or classes are renamed. These classes relate to the core minecraft server and cannot be shipped in an external library. Sorry about this.

**Comment by Jerlag01** [comment]
Ok, thanks for the support

Van: kangarko
Verzonden: donderdag 25 oktober 2018 11:57
Aan: kangarko/ChatControl-Pro
CC: Jerlag01; Author
Onderwerp: Re: [kangarko/ChatControl-Pro] Error on load (#965)

I have no idea, probably missing many classes or classes are renamed. These classes relate to the core minecraft server and cannot be shipped in an external library. Sorry about this.
