### ISSUE TITLE
Again the bug of latest release

### ISSUE THREAD

**Issue by xion87** [kangarko/ChatControl-Pro#970]
Since i am not loving that you forced all user to use latest release. I stopped to upgrade chatcontrol because everytime i found new bugs and stuff.
The new chatcontrol version allow people to spam server ip on hub where i enabled channel mode with bungee between all hubs. no errors. using 1.12.2 and chatcontrol 7.9.31

**Comment by kangarko** [comment]
It was only temporary, you can now use older releases as well, but at your own risk - these are not supported.

I alerted our developer about your issue.

**Comment by xion87** [comment]
You stopped to worked on it? :|

**Comment by kangarko** [comment]
Of course not :) Just having more people to work on it.

Post me your ChatControl folder as a ZIP from that hub.

**Comment by xion87** [comment]
Here: [ChatControl.zip](https://github.com/kangarko/ChatControl-Pro/files/2515277/ChatControl.zip)

**Comment by jascotty2** [comment]
This seems to be an issue with the way the rules for IP matching were written. 
Try changing your rules.txt for IP match (about line 69) to this:
`
match [0-9]{1,3}(\.|dot|\(dot\)|-|;|:|,|(\W|\d|_)*\s)+[0-9]{1,3}(\.|dot|\(dot\)|-|;|:|,|(\W|\d|_)*\s)+[0-9]{1,3}(\.|dot|\(dot\)|-|;|:|,|(\W|\d|_)*\s)+[0-9]{1,3}
id 1
before replace dot|\[|\]|\{|\}|\(|\) with .
before strip [\(\[\]\)]|\s*
handle as advertisement
`

**Comment by xion87** [comment]
now is spamming this
[16:50:37 INFO]: [hub] star22: huzuno
> [16:50:38 INFO]: [ChatControl] *-----------------------------------------------*
> [16:50:38 INFO]: [ChatControl] Malformed regex: '[([])]|\s*'
> [16:50:38 INFO]: [ChatControl] Use online services (like regex101.com) for fixing errors
> [16:50:38 INFO]: [ChatControl] *-----------------------------------------------*
> [16:50:38 INFO]: [ChatControl] ChatControl 7.9.31 encountered a PatternSyntaxException! Please check your error.log and report this issue with the information in that file.
> [16:50:38 ERROR]: Could not pass event AsyncPlayerChatEvent to ChatControl v7.9.31
java.util.regex.PatternSyntaxException: Unclosed character class near index 9
[([])]|\s*
^
at java.util.regex.Pattern.error(Pattern.java:1957) ~[?:1.8.0_171]
at java.util.regex.Pattern.clazz(Pattern.java:2550) ~[?:1.8.0_171]
at java.util.regex.Pattern.sequence(Pattern.java:2065) ~[?:1.8.0_171]
at java.util.regex.Pattern.expr(Pattern.java:1998) ~[?:1.8.0_171]
at java.util.regex.Pattern.compile(Pattern.java:1698) ~[?:1.8.0_171]
at java.util.regex.Pattern.<init>(Pattern.java:1351) ~[?:1.8.0_171]
at java.util.regex.Pattern.compile(Pattern.java:1054) ~[?:1.8.0_171]
at me.kangarko.chatcontrol.final. .COM9.void(SourceFile:649) ~[?:?]
at me.kangarko.chatcontrol.final. .COM9.volatile(SourceFile:640) ~[?:?]
at me.kangarko.chatcontrol.final. .bu.int(SourceFile:77) ~[?:?]
at me.kangarko.chatcontrol.final. .bo.const(SourceFile:322) ~[?:?]
at me.kangarko.chatcontrol.final. .bo.const(SourceFile:279) ~[?:?]
at me.kangarko.chatcontrol.final. .aW.const(SourceFile:271) ~[?:?]
at me.kangarko.chatcontrol.final. .aW.const(SourceFile:57) ~[?:?]
at me.kangarko.chatcontrol.final. .aW.const(SourceFile:39) ~[?:?]
at me.kangarko.chatcontrol.final. .coM2.execute(SourceFile:26) ~[?:?]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[patched_1.12.2.jar:git-Paper-1559]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1559]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.12.2.jar:git-Paper-1559]
at net.minecraft.server.v1_12_R1.PlayerConnection.chat(PlayerConnection.java:1391) ~[patched_1.12.2.jar:git-Paper-1559]
at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1306) ~[patched_1.12.2.jar:git-Paper-1559]
at net.minecraft.server.v1_12_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:39) ~[patched_1.12.2.jar:git-Paper-1559]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_171]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_171]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_171]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_171]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]

**Comment by xion87** [comment]
The issue is when i write "nuovo server al ip 1.1.1.1:12345 snipper giva banane" is not blocked by chatcontrol

**Comment by xion87** [comment]
Latest release still not fixed the issue
![image](https://user-images.githubusercontent.com/3611852/47552613-66f20100-d905-11e8-88f5-c7c1518f0857.png)

**Comment by jascotty2** [comment]
https://pastebin.com/j3MXiByc

**Comment by kangarko** [comment]
@xion87 please report your status ;)

**Comment by kangarko** [comment]
Closing due to regular maintenance, just comment below if still having issues.

**Comment by xion87** [comment]
i forgot to say that fixed the issue, sorry :)

**Comment by kangarko** [comment]
Awesome!
